### PR TITLE
luci-app-dnscrypt-proxy: small fixes & additions

### PR DESCRIPTION
**Pull request by dibdot**
* check/add for 'global' section to fix a possible issue with old
(non-default) dnscrypt-proxy config files
* a custom 'resolv-crypt.conf' can now be added in the new "Extra
options" section
* accept IPv4 and IPv6 address as local dnscrypt ip address

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by montvid** [comment]
Hi @dibdot , thanks for the commit - it works. I wanted to ask you to improve the custom 'resolv-crypt.conf' function to check if the file is present and write an output to the web console. Now after a push of the button no output is seen so there is no way to see in the web console if the button did anything. I checked the /etc/config/dhcp file and it was NOT changed by the push of the button to include 	option resolvfile '/etc/resolv-crypt.conf'. So the button does not work as intended.

**Comment by dibdot** [comment]
@montvid thanks for your input!
The file check is already implemented but at this stage the app didn't change any dnsmasq settings. Please stay tuned for the next update.

**Comment by dibdot** [comment]
@montvid see #1382 (not applied yet)

**Comment by montvid** [comment]
How can I test that - I am not good at code reading.

**Comment by dibdot** [comment]
copy the updated files manually from my source github repo to your router or simply wait until the changes has been applied.

**Comment by montvid** [comment]
Thanks for developing the luci plugin. I found that if I want to select a second server in the config I see:
First server:
config dnscrypt-proxy 'ns1'
Second server:
config dnscrypt-proxy
As per openwrt instructions the second server should be ns2 and so on:
config dnscrypt-proxy 'ns2'
Another one is using google dns for ntp requests. My suggestion as openwrt is an opensource project so we should use OpenNic dns services https://wiki.opennic.org/doku.php#anycast_tier_2_dns_resolvers
Thanks a lot again! I did not find any other problems while using the gui for months.

**Comment by dibdot** [comment]
That's no problem, during package startup the init script is iterating the configuration sections "dnscrypt-proxy" with the "config_foreach" procedure. You can just remove the (needless) naming.

Regarding google dns, I do not plan to change that - it's still the best default, I think.

**Comment by montvid** [comment]
I can remove the needless naming but is it created by your extension or there by default?

**Comment by dibdot** [comment]
It's the core package default config, see [here](https://github.com/openwrt/packages/blob/master/net/dnscrypt-proxy/files/dnscrypt-proxy.config)

**Comment by montvid** [comment]
So maybe it is a good idea to follow the default config naming "ns1","ns2" when creating the second server config with your extension. Just a suggestion.

**Pull request merged**
