### PR TITLE
luci-app-adblock: Fix visualizzation

### PR DESCRIPTION
**Pull request by Ansuel**
Fix wrong visualizzation of runtime information

### CODE REVIEW

**Comment by hnyman** [comment]
cc @dibdot

**Comment by dibdot** [comment]
@Ansuel What's wrong with a dummy section header without making a new section? Which type of visualization error will be fixed?
Thanks!

**Comment by Ansuel** [comment]
@dibdot This [](https://s2.postimg.org/jbc343luh/screenshot_5.png)

**Comment by dibdot** [comment]
@Ansuel OK, usually I only use bootstrap ... change looks good, just one change: please rename "dv" variable to "ds" cause it's a section variable - than it's OK from my point of view.

Thank you!

**Pull request closed without merging**
