### PR TITLE
luci-app-mosquitto: import new application

### PR DESCRIPTION
**Pull request by karlp**
Originally developed and maintained at https://github.com/remakeelectric/owrt_pub_feeds/tree/master/luci-app-mosquitto

Signed-off-by: Karl Palsson <karlp@etactica.com>

### CODE REVIEW

**Comment by karlp** [comment]
I've imported this ~as is from our original feed, but it's missing lots of translation.  I chose to leave that off for a second followup so I can get that in pieces.

**Comment by jow-** [comment]
Looks okay on a first glance - the Makefile should be converted to use the shared `luci.mk` which would make it much shorter. Is the ucitrack entry needed yet?

**Comment by karlp** [comment]
Honestly, I've not followed when luci_reload /ucitrack can go away.  This package worked without having to worry what branch it was on.  On current master, are you saying that it _shouldn't_ be required anymore, as long as the init script is setup properly?

**Comment by jow-** [comment]
Correct, if Mosquitto's init script is procd enabled, then you do not need the ucitrack business anymore.

**Comment by jow-** [comment]
It applies to both master and openwrt-18.06 but not to lede-17.01

**Comment by karlp** [comment]
wow, this ```# call BuildPackage - OpenWrt buildroot signature``` magic string in a comment was.... not very visible to work out why my package wasn't showing up :)

**Comment by karlp** [comment]
Ok, dropped ucitrack and confirmed no longer required, and moved to the luci.mk style.

**Comment by jow-** [comment]
merged, thanks!

**Pull request merged**
