### PR TITLE
luci-app-adblock: release 4.0.0

### PR DESCRIPTION
**Pull request by dibdot**
* complete rewrite, migrated to client side JS
* tested with mainline 19.07 and current master
* tested with latest Firefox & Chrome and all
  standard themes (not OpenWrt2020!)
  Pre-tested by many forum users, see here:
  https://forum.openwrt.org/t/adblock-4-pre-releases/57101
* sync translations

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by dibdot** [comment]
@hnyman what's the best strategy with the *.po files here (frequently updated by weblate). Should I remove the *.po files and just provide the current template in this PR?

**Comment by hnyman** [comment]
Probably you should run build/i18n-sync.pl so that it would cleanup/update strings and remove the old translation strings from all languages.  Then when the PR gets merged, weblate will then find the new strings and the old ones have disapperared.

Ps. and naturally get rid of that merge commit.

**Comment by hnyman** [comment]
Or merge the PR first and then run build/i18n-sync.pl  and commit the "sync translations" treewide.

**Comment by dibdot** [comment]
OK, thanks I'll take the first variant later on!

**Comment by hnyman** [comment]
You should probably rebase the feature branch on master first, before the i18n-sync, as you may get conflicts otherwise.  (Apparently the translation update that I merged earlier, causes conflict as your feature branch has branched off earlier.)

```
git checkout master
git pull
git checkout adblock4
git rebase master
(fix conflicts)
./build/i18n-sync.pl
```

**Pull request closed without merging**
