### PR TITLE
luci-app-ddns: update to version 2.2.0-1

### PR DESCRIPTION
**Pull request by chris5560**
- implement new option bind_interface
- fixes problems when updating status displays (i.e. showing Software update needed)
- new links to OpenWrt wiki
- new screen to set global settings
- implements global option use_curl

Signed-off-by: Christian Schoenebeck <<christian.schoenebeck@gmail.com>>

### CODE REVIEW

**Comment by hnyman** [comment]
Should this be checked in?  The "software update needed" error is boring, and this is supposed to fix that.
@jow-

**Comment by chris5560** [comment]
@jow - may I get merge permission to support you ? The update is really needed.

**Comment by thess** [comment]
@jow- @chris5560, I agree with hannu - please do this.

**Comment by chris5560** [comment]
@mmunz 
Manuel could you please merge this pull request ?
Jo-Phillipp is currently not responding. Many thanks.

**Comment by jow-** [comment]
Sorry, I overlooked this one and was afk for a while. Merged, thanks!

**Pull request merged**
