### PR TITLE
luci-app-bmx7: transfer from routing

### PR DESCRIPTION
**Pull request by aparcar**
The Makefile is minified as the LuCi build system does most of the job.

@p4u @rogerpueyo

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by p4u** [comment]
It was initially added an openwrt-routing because the maintainer (myself) got access to that repository. Now if it's transfer to luci, I will loose the ability to directly merge anything. It's not a drama, but will be less operational. Is there anyone with merge rights to this repository who would maintain this packet (and review the PR) ?

**Comment by dangowrt** [comment]
I've invited @p4u to the luci maintainers team, so he got commit access here to keep maintaining the luci-app-bmx7 package once moved.

**Comment by rogerpueyo** [comment]
@aparcar Thanks for your work.

It'd be nice for me also to be able to take care of the bmx6/7-related packages, if it's fine for you.

**Comment by p4u** [comment]
@dangowrt thanks. However @rogerpueyo is right now a better candidate that myself. So either you add us both or just add him.

**Comment by dangowrt** [comment]
@rogerpueyo I've invited you to the team as well.

**Comment by aparcar** [comment]
@rogerpueyo @p4u are you okay with a merge? If so I'd remove the package from routing.git

**Comment by rogerpueyo** [comment]
> @rogerpueyo @p4u are you okay with a merge? If so I'd remove the package from routing.git

Sure, go ahead!

**Pull request merged**
