### PR TITLE
luci-app-attendedsysupgrade: upgrade to version 2

### PR DESCRIPTION
**Pull request by aparcar**
Add required ubus acls from package rpcd-mod-attendedsysupgrade.

Signed-off-by: Paul Spooren <paul@spooren.de>

### CODE REVIEW

**Comment by FreifunkUFO** [comment]
i this we dont need it.
corresponding package rpcd-mod-attendedsysupgrade has that file already, and its better hosted there..
btw, the file there is almost the same, but with better ubus-description

https://github.com/openwrt/packages/blob/master/utils/rpcd-mod-attendedsysupgrade/files/attendedsysupgrade.acl

**Comment by aparcar** [comment]
@FreifunkUFO I thought of removing the acl-files from rpcd-mod-attendedsysupgrade to luci-app-attendedsysupgrade as a possible cli wouldn't need the acls afaik.

**Comment by FreifunkUFO** [comment]
i think the rpcd-acls belong to the rpcd-packet (as a config).

when using attendeedsysupgrade via CLI neither rpcd-alcs nor the rpcd-attended-sysupgrade is needed.

**Comment by aparcar** [comment]
@jow- do you have an opinion about that?

**Comment by jow-** [comment]
The ACL definitions belong with the package / program needing them in order to talk to ubus, so the LuCI application in this case.

**Comment by aparcar** [comment]
Please merge if there are no further doubts. After merging I'd create another PR to move it in lede-17.01

**Comment by aparcar** [comment]
@jow- if the postinst script looks good I'd merge this

**Comment by FreifunkUFO** [comment]
what about the nicer description inside the acl file? 
this is a bit better: https://github.com/openwrt/packages/blob/master/utils/rpcd-mod-attendedsysupgrade/files/attendedsysupgrade.acl

**Comment by aparcar** [comment]
@FreifunkUFO better now?

**Comment by aparcar** [comment]
screenshot app

**Comment by aparcar** [comment]
screenshot building

**Comment by aparcar** [comment]
screenshot success
Now the app waits until the rooter is rebooted and asks the user to reload.

**Comment by aparcar** [comment]
needs https://github.com/openwrt/packages/pull/5053 first

**Pull request merged**
