### PR TITLE
luci-theme-material: make 'Loading...' text translatable

### PR DESCRIPTION
**Pull request by sch-m**
Signed-off-by: Martin Schiller <ms@dev.tdt.de>

### CODE REVIEW

**Comment by jow-** [comment]
Merged, thanks!

**Comment by sch-m** [comment]
@jow- Thanks for merging this.
While I wanted to integrate the msgid "Loading..." into the base.po I noticed that a msgid "Loading" already exists there. I don't want to add more variants of the same text.

What do you think about changing the 
`<%:Loading...%>` into `<%:Loading%>...`
This allows us to reuse the msgid "Loading" and the "..." are still there (untranslated).

**Comment by jow-** [comment]
In principle okay, but I am not sure if the ellipsis is applicable like this to all languages (think Hebrew (rtl), Chinese etc...)

@yousong ?

**Comment by sch-m** [comment]
> In principle okay, but I am not sure if the ellipsis is applicable like this to all languages (think Hebrew (rtl), Chinese etc...)

Oh, good point. Alternatively, we could just eliminate the ellipsis.

**Comment by jow-** [comment]
Alternatively you maybe could use the `Loading data...` string.

**Comment by sch-m** [comment]
Sorry, can't find any `Loading data...`string. Where is it? :-)

**Comment by jow-** [comment]
Nvm, I was misremembering "Collecting data..."

**Comment by sch-m** [comment]
Ah, nice. Ok, so will change the text in luci-theme-material to `<%:Collecting data...%>`

**Comment by sch-m** [comment]
and send a new pr, ok?

**Comment by jow-** [comment]
yes, please

**Pull request merged**
