### PR TITLE
Use a shared widget for "logread" views

### PR DESCRIPTION
**Pull request by karlp**
Much help from jow!

This was developed and tested on 21.02, but applies clean on master, and is ~same there...

### CODE REVIEW

**Comment by karlp** [comment]
Build failure is in cryptdev and completely unrelated to this PR :|

**Comment by systemcrash** [comment]
Hi @karlp - is this still usable on current master?

**Comment by karlp** [comment]
I have absolutely no idea sorry, feel very welcome to take it and do as  you see fit.

**Comment by systemcrash** [comment]
Thanks @karlp - it's now implemented in master as @jow-'s suggestion of a `view`.

**Pull request closed without merging**
