### PR TITLE
luci-base: fix duid_to_mac reference in status.lua

### PR DESCRIPTION
**Pull request by dibdot**
* fix for openwrt/packages#9148

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by Ansuel** [comment]
didn't notice the second call... my bad.. sorry

**Comment by jow-** [comment]
@Ansuel - so you didn't runtime test your changes?

**Comment by jow-** [comment]
@dibdot - thanks!

**Comment by Ansuel** [comment]
@jow- i tested them but as i don't have ipv6 lease the error didn't show up.

**Pull request merged**
