### PR TITLE
Show LEDE Project/OpenWrt moniker based on the content of ver.distver…

### PR DESCRIPTION
**Pull request by stangri**
Show OpenWrt/LEDE Project moniker in luci-mod-admin-mini/full based on ver.distversion.
Show OpenWrt/LEDE Project URL in the theme footer based on ver.distversion.

### CODE REVIEW

**Comment by cshoredaniel** [comment]
@stangri Others will chime in obviously, but I'd prefer to see the string test moved info luci.util and return the translated string from there.  There are probably a number of other locations (e.g. apps) that use OpenWrt/LEDE.  Also for derivatives it'd useful to make changes in only one place.

**Comment by stangri** [comment]
@cshoredaniel I've considered the approach (not the actual implementation) you're referring to. While it might be neater to move the test/return of the proper tag somewhere else, but because the tags were in the middle of sentences, it would unnecessarily burden localization.

**Comment by cshoredaniel** [comment]
Ah, makes sense, then ACK by me.

**Comment by hnyman** [comment]
It is possible that Openwrt and LEDE codebases will merge in (near?) future (based on http://lists.infradead.org/pipermail/lede-adm/2016-December/000293.html ). So I would wait until there is more clarity about the final outcome.

I would actually prefer simplifying things. Instead of adding complexity of sniffing for distro, I would just delete the specific references from the theme footer and modify the other texts to avoid mentioning Openwrt/LEDE specifically. That approach would also serve derivative distros (like Gluon) rather easily.

... current configuration (requires a LEDE Project compatible firmware image)
.--> .. current configuration (requires a compatible firmware image)

 Please refer to the OpenWrt wiki for device...
-->  Please refer to the wiki for device...

And now have fun with your LEDE Project device
--> And now have fun with your device

Upload an OpenWrt image file to reflash the device
--> Upload a sysupgrade compatible image file to reflash the device

OpenWrt does not support a system upgrade on this platform
--> A system upgrade is not supported on this platform

**Comment by cshoredaniel** [comment]
That's a very good point.  It makes i18n easier too (and shares it).

**Comment by jow-** [comment]
I agree with @hnyman - let's make the strings distro-agnostic.

**Comment by hnyman** [comment]
My idea got support, so I will commit something along those lines.

**Comment by hnyman** [comment]
I pushed https://github.com/openwrt/luci/commit/73749fa048e2dbccb4e730b628ab062c98d51877 and https://github.com/openwrt/luci/commit/f7ec630913a4eadea0b9927881f62b095bc95563 (plus https://github.com/openwrt/luci/commit/e65f6512e7d6978eab01e4ee473dafa88320e9f8 )

**Comment by jow-** [comment]
Thanks @hnyman. Maybe we can try to fix the translation manually as these changes touch a number of essential strings.

**Comment by hnyman** [comment]
I considered the same, but have not yet done anything.

The European languages are rather easy as you can usually just remove the "openwrt" plus possibly a prepositioneven without understanding the language fully, but the Asian languages with the symbols will be more problematic and will likely need to be left .

Additionally, I think that the "-full" is more important than the rarely(?) used "-mini"

**Comment by jow-** [comment]
For the Asian languages we could simply replace OpenWrt with "OpenWrt/LEDE" and wait until someone eventually updates the translations. Its not perfect but better than having untrnaslated sections in the middle of the base package.

**Comment by hnyman** [comment]
I pushed https://github.com/openwrt/luci/commit/0fdee1ed9db38c2e324e83470765063b79d66013 to fix things. Roughly half of the languages had translated those strings.

In general, the languages miss quite many strings, as there not been much translation activity for the past 2-3 years.

**Comment by stangri** [comment]
Having worked on localization project in the past, I'd like to point out that there're cases/languages where "OpenWrt compatible" might/have to be translated literally as "compatible with the OpenWrt" and if you remove "OpenWrt" or even "the OpenWrt", you're still left with the broken translation. 
 
PS. I've asked for the feedback of what would preferred solution be for handling distro-specific texts in a previous PR, I wish it had been provided in time, so I wouldn't have wasted my time doing dynamic thing.

**Pull request closed without merging**
