### PR TITLE
luci-proto-ipv6: add new package for IPIP6(RFC2473) support

### PR DESCRIPTION
**Pull request by missing233**
Add Generic Packet Tunneling in IPv6 Specification (RFC 2473) support.
Japan NTT V6 Plus fixed IP
[openwrt:#14498](https://github.com/openwrt/openwrt/pull/14498)

### CODE REVIEW

**Comment by systemcrash** [comment]
Thanks for your contribution! Please provide a real email in your SOB.

**Comment by missing233** [comment]
> Thanks for your contribution! Please provide a real email in your SOB.

Thank you for reviewing my pull request. I have updated my real email address. Please let me know if there's anything else needed from my side.

**Comment by systemcrash** [comment]
You have some extra commits in there - they should not be. You may need to re-make a PR on a new branch. 

Review https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md

**Comment by missing233** [comment]
> You have some extra commits in there - they should not be. You may need to re-make a PR on a new branch.
> 
> Review https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md

Thank you. I will reopen a PR later to make these modifications.

**Pull request closed without merging**
