### PR TITLE
luci-app-ddns: Complete update of the Spanish language

### PR DESCRIPTION
**Pull request by castillofrancodamian**
luci-app-ddns: Update Spanish translation.

Complete updated of the Spanish language.

Signed-off-by: Franco Castillo <castillofrancodamian@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
The binary .mo file should not be included in the PR.

Otherwise it looks ok, as you have even remembered to sign-off the commit

**Comment by castillofrancodamian** [comment]
> The binary .mo file should not be included in the PR.
> 
> Otherwise it looks ok, as you have even remembered to sign-off the commit

Delete that .mo file?

**Comment by hnyman** [comment]
Delete that file in git, add the change, amend the commit, and force-push to update the PR

**Comment by hnyman** [comment]
Commits squashed together with `git rebase -i HEAD~2` and applied manually as 7f172e1a2

**Pull request closed without merging**
