### PR TITLE
luci-mod-status: extend DSL metrics

### PR DESCRIPTION
**Pull request by janh**
This restructures the DSL metrics to make them easier to read, and adds several additional metrics, making use of https://github.com/openwrt/openwrt/commit/b91d7d9d78ea12097de4c518c8cd2215ff286f7a.

### CODE REVIEW

**Comment by dhewg** [comment]
Nice, I still need to try this!

This looks all good at first glance, but that DSL status box is getting rather huge.

Maybe we can move some stuff elsewhere? Network/Interfaces/DSL might be too hidden though.
Or group stats by topic and make it child boxes, like the wifi networks are on the phy box? So they float/arrange themselves based on the browser window width, that'll make it at least shrink in height.

**Comment by jow-** [comment]
I'd say make a separate DSL status page and only keep the most relevant indicators (SNR & line status?) in the general overview page.

**Comment by janh** [comment]
I assume it would make sense to add the separate status page to `luci-mod-dsl` instead of this one then. Should I create a separate pull request for that once it is done?

**Comment by dhewg** [comment]
We could also integrate it into the dsl spectrum status and rename it accordingly.
Tested as-is, apart from the big box it works as described :)

**Comment by jow-** [comment]
I merged the change for now. Would be great if you could follow up with moving extended status info into a separate view and only keeping most important indicators on the main status screen.

**Pull request merged**
