### PR TITLE
luci-base: also take ip addresses from virtual sub-interfaces

### PR DESCRIPTION
**Pull request by sch-m**
This patch fixes the problem that no ip addresses are shown in the
interfaces overview for interfaces with protocol handlers like QMI
which spawn a virtual sub-interface (e.g. wwan_4) which handles
the actual IPv4 connectivity.

This partialy fixes FS#1304.

Signed-off-by: Martin Schiller <ms@dev.tdt.de>

### CODE REVIEW

**Comment by jow-** [comment]
Hm, I am not overly happy with that approach but lets see...
Can you provide a full `ubus call network.interface dump` output? Possibly with sensitive info redacted

**Comment by sch-m** [comment]
```
root@VR2020-LD:~# ubus call network.interface dump
{
        "interface": [
                {
                        "interface": "lan",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 13802,
                        "l3_device": "eth1.1",
                        "proto": "static",
                        "device": "eth1.1",
                        "updated": [
                                "addresses"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "192.168.0.50",
                                        "mask": 24
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "loopback",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 13802,
                        "l3_device": "lo",
                        "proto": "static",
                        "device": "lo",
                        "updated": [
                                "addresses"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "127.0.0.1",
                                        "mask": 8
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "tun",
                        "up": false,
                        "pending": false,
                        "available": false,
                        "autostart": true,
                        "dynamic": false,
                        "proto": "none",
                        "device": "tun0",
                        "data": {

                        }
                },
                {
                        "interface": "wan",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 13800,
                        "l3_device": "eth0",
                        "proto": "dhcp",
                        "device": "eth0",
                        "updated": [
                                "addresses",
                                "routes",
                                "data"
                        ],
                        "metric": 10,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "172.16.2.190",
                                        "mask": 24
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [
                                {
                                        "target": "0.0.0.0",
                                        "mask": 0,
                                        "nexthop": "172.16.2.254",
                                        "source": "172.16.2.190\/32"
                                }
                        ],
                        "dns-server": [
                                "172.16.2.254"
                        ],
                        "dns-search": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ]
                        },
                        "data": {
                                "leasetime": 43200
                        }
                },
                {
                        "interface": "wwan",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 13637,
                        "l3_device": "wwan0",
                        "proto": "multisim",
                        "updated": [
                                "data"
                        ],
                        "metric": 30,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [

                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ]
                        },
                        "data": {
                                "cid_4": "18",
                                "pdh_4": "1205704784"
                        }
                },
                {
                        "interface": "wwan_4",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": true,
                        "uptime": 13637,
                        "l3_device": "wwan0",
                        "proto": "dhcp",
                        "device": "wwan0",
                        "metric": 30,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "100.65.242.87",
                                        "mask": 28
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [
                                {
                                        "target": "0.0.0.0",
                                        "mask": 0,
                                        "nexthop": "100.65.242.81",
                                        "source": "100.65.242.87\/32"
                                }
                        ],
                        "dns-server": [
                                "139.7.30.126",
                                "139.7.30.125"
                        ],
                        "dns-search": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ]
                        },
                        "data": {
                                "hostname": "VR2020-LD",
                                "leasetime": 7200
                        }
                },
                {
                        "interface": "xdsl",
                        "up": false,
                        "pending": false,
                        "available": false,
                        "autostart": false,
                        "dynamic": false,
                        "proto": "pppoe",
                        "device": "dsl0",
                        "data": {

                        }
                }
        ]
}
```

**Comment by jow-** [comment]
Instead of assuming `xxx_4` and `xxx_6` referecnes we should probably discover subinterfaces by checking `"dynamic": true` and a matching `device` or `l3_device`.

**Comment by sch-m** [comment]
yes, you are right. That should be more flexible.

**Comment by jow-** [comment]
I am currently looking into patching netifd to expose the virtual-interface<=>parent relation in the ubus dumps

**Comment by jow-** [comment]
Can you provide me with the output of `ubus call network.device status` as well?

**Comment by sch-m** [comment]
```
root@VR2020-LD:~# ubus call network.device status
{
        "eth0": {
                "external": false,
                "present": true,
                "type": "Network device",
                "up": true,
                "carrier": true,
                "mtu": 1500,
                "mtu6": 1500,
                "macaddr": "00:01:49:01:d8:cb",
                "txqueuelen": 1000,
                "ipv6": true,
                "promisc": false,
                "rpfilter": 0,
                "acceptlocal": false,
                "igmpversion": 0,
                "mldversion": 0,
                "neigh4reachabletime": 30000,
                "neigh6reachabletime": 30000,
                "neigh4gcstaletime": 60,
                "neigh6gcstaletime": 60,
                "dadtransmits": 1,
                "multicast": true,
                "sendredirects": true,
                "statistics": {
                        "collisions": 0,
                        "rx_frame_errors": 0,
                        "tx_compressed": 0,
                        "multicast": 0,
                        "rx_length_errors": 0,
                        "tx_dropped": 0,
                        "rx_bytes": 2119158,
                        "rx_missed_errors": 0,
                        "tx_errors": 0,
                        "rx_compressed": 0,
                        "rx_over_errors": 0,
                        "tx_fifo_errors": 0,
                        "rx_crc_errors": 0,
                        "rx_packets": 22443,
                        "tx_heartbeat_errors": 0,
                        "rx_dropped": 18042,
                        "tx_aborted_errors": 0,
                        "tx_packets": 4411,
                        "rx_errors": 0,
                        "tx_bytes": 358896,
                        "tx_window_errors": 0,
                        "rx_fifo_errors": 0,
                        "tx_carrier_errors": 0
                }
        },
        "eth1": {
                "external": false,
                "present": true,
                "type": "Network device",
                "up": true,
                "carrier": true,
                "mtu": 1500,
                "mtu6": 1500,
                "macaddr": "00:01:49:01:d8:cc",
                "txqueuelen": 1000,
                "ipv6": true,
                "promisc": false,
                "rpfilter": 0,
                "acceptlocal": false,
                "igmpversion": 0,
                "mldversion": 0,
                "neigh4reachabletime": 30000,
                "neigh6reachabletime": 30000,
                "neigh4gcstaletime": 60,
                "neigh6gcstaletime": 60,
                "dadtransmits": 1,
                "multicast": true,
                "sendredirects": true,
                "statistics": {
                        "collisions": 0,
                        "rx_frame_errors": 0,
                        "tx_compressed": 0,
                        "multicast": 0,
                        "rx_length_errors": 0,
                        "tx_dropped": 0,
                        "rx_bytes": 9888284,
                        "rx_missed_errors": 0,
                        "tx_errors": 0,
                        "rx_compressed": 0,
                        "rx_over_errors": 0,
                        "tx_fifo_errors": 0,
                        "rx_crc_errors": 0,
                        "rx_packets": 85728,
                        "tx_heartbeat_errors": 0,
                        "rx_dropped": 6,
                        "tx_aborted_errors": 0,
                        "tx_packets": 70077,
                        "rx_errors": 0,
                        "tx_bytes": 16331624,
                        "tx_window_errors": 0,
                        "rx_fifo_errors": 0,
                        "tx_carrier_errors": 0
                }
        },
        "eth1.1": {
                "external": false,
                "present": true,
                "type": "VLAN",
                "up": true,
                "carrier": true,
                "mtu": 1500,
                "mtu6": 1500,
                "macaddr": "00:01:49:01:d8:cc",
                "txqueuelen": 1000,
                "ipv6": true,
                "promisc": false,
                "rpfilter": 0,
                "acceptlocal": false,
                "igmpversion": 0,
                "mldversion": 0,
                "neigh4reachabletime": 30000,
                "neigh6reachabletime": 30000,
                "neigh4gcstaletime": 60,
                "neigh6gcstaletime": 60,
                "dadtransmits": 1,
                "multicast": true,
                "sendredirects": true,
                "statistics": {
                        "collisions": 0,
                        "rx_frame_errors": 0,
                        "tx_compressed": 0,
                        "multicast": 18048,
                        "rx_length_errors": 0,
                        "tx_dropped": 0,
                        "rx_bytes": 7657977,
                        "rx_missed_errors": 0,
                        "tx_errors": 0,
                        "rx_compressed": 0,
                        "rx_over_errors": 0,
                        "tx_fifo_errors": 0,
                        "rx_crc_errors": 0,
                        "rx_packets": 85712,
                        "tx_heartbeat_errors": 0,
                        "rx_dropped": 18035,
                        "tx_aborted_errors": 0,
                        "tx_packets": 70049,
                        "rx_errors": 0,
                        "tx_bytes": 15767392,
                        "tx_window_errors": 0,
                        "rx_fifo_errors": 0,
                        "tx_carrier_errors": 0
                }
        },
        "lo": {
                "external": false,
                "present": true,
                "type": "Network device",
                "up": true,
                "carrier": true,
                "mtu": 65536,
                "mtu6": 65536,
                "macaddr": "00:00:00:00:00:00",
                "txqueuelen": 1,
                "ipv6": true,
                "promisc": false,
                "rpfilter": 0,
                "acceptlocal": false,
                "igmpversion": 0,
                "mldversion": 0,
                "neigh4reachabletime": 30000,
                "neigh6reachabletime": 30000,
                "neigh4gcstaletime": 60,
                "neigh6gcstaletime": 60,
                "dadtransmits": 1,
                "multicast": false,
                "sendredirects": true,
                "statistics": {
                        "collisions": 0,
                        "rx_frame_errors": 0,
                        "tx_compressed": 0,
                        "multicast": 0,
                        "rx_length_errors": 0,
                        "tx_dropped": 0,
                        "rx_bytes": 30009777,
                        "rx_missed_errors": 0,
                        "tx_errors": 0,
                        "rx_compressed": 0,
                        "rx_over_errors": 0,
                        "tx_fifo_errors": 0,
                        "rx_crc_errors": 0,
                        "rx_packets": 461476,
                        "tx_heartbeat_errors": 0,
                        "rx_dropped": 0,
                        "tx_aborted_errors": 0,
                        "tx_packets": 461476,
                        "rx_errors": 0,
                        "tx_bytes": 30009777,
                        "tx_window_errors": 0,
                        "rx_fifo_errors": 0,
                        "tx_carrier_errors": 0
                }
        },
        "wwan0": {
                "external": false,
                "present": true,
                "type": "Network device",
                "up": true,
                "carrier": true,
                "mtu": 1500,
                "mtu6": 1500,
                "macaddr": "de:ad:be:ef:00:00",
                "txqueuelen": 1000,
                "ipv6": true,
                "promisc": false,
                "rpfilter": 0,
                "acceptlocal": false,
                "igmpversion": 0,
                "mldversion": 0,
                "neigh4reachabletime": 30000,
                "neigh6reachabletime": 30000,
                "neigh4gcstaletime": 60,
                "neigh6gcstaletime": 60,
                "dadtransmits": 1,
                "multicast": true,
                "sendredirects": true,
                "statistics": {
                        "collisions": 0,
                        "rx_frame_errors": 0,
                        "tx_compressed": 0,
                        "multicast": 0,
                        "rx_length_errors": 0,
                        "tx_dropped": 0,
                        "rx_bytes": 19369,
                        "rx_missed_errors": 0,
                        "tx_errors": 0,
                        "rx_compressed": 0,
                        "rx_over_errors": 0,
                        "tx_fifo_errors": 0,
                        "rx_crc_errors": 0,
                        "rx_packets": 524,
                        "tx_heartbeat_errors": 0,
                        "rx_dropped": 0,
                        "tx_aborted_errors": 0,
                        "tx_packets": 526,
                        "rx_errors": 0,
                        "tx_bytes": 26904,
                        "tx_window_errors": 0,
                        "rx_fifo_errors": 0,
                        "tx_carrier_errors": 0
                }
        }
}

```

**Comment by AreYouLoco** [comment]
I cannot wait for this fix to go upstream :D

**Comment by sch-m** [comment]
This patch is now obsolete, because the sub-interfaces have been added to the interface overview in the meantime.

**Pull request closed without merging**
