### PR TITLE
luci-mod-status: add nftables status page

### PR DESCRIPTION
**Pull request by jow-**
The PR introduces an nftables status page similar to the existing one for iptables.

### CODE REVIEW

**Comment by hnyman** [comment]
Thanks Jow,
Seems to work ok with my simple (pretty default) firewall.

**Comment by hnyman** [comment]
@jow- 
I noticed a new branch.
Did you accidentally push an update of this PR's commit to a branch at the main site, instead of your own fork?

**Comment by bittin** [comment]
@jow- @hnyman noticed that now too, when i updated

**Comment by hnyman** [comment]
@jow- 
Any blockers for merging this?
The nftables status screen would help users a lot.

**Comment by hnyman** [comment]
@jow- 
I feel that we should merge this, as the snapshot users have been the last two weeks without a firewall status page.
The functionality may not be complete, yet, but to me it looks  good enough.

Any objections?

**Pull request merged**
