### PR TITLE
luci-mod-network: add warning with weak security wirless Encryption

### PR DESCRIPTION
**Pull request by Ansuel**
Add a warning if an user select a weak security wireless Encryption to
make him aware that he is using a vulnerable security mode.

Also demote WPA-PSK mixed mode to a weak security mode.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

----

This is the current design for this

image

### CODE REVIEW

**Comment by Ansuel** [comment]
@jow- what do you think?

**Comment by jow-** [comment]
I already demoted WPA-PSK to low security. I do not like the banner message.

**Comment by Ansuel** [comment]
Mhhh don't know a small message with low security is not enough to say that
you are actually using a vulnerable encryption

Il Mar 19 Lug 2022, 16:57 Jo-Philipp Wich ***@***.***> ha
scritto:

**Comment by jow-** [comment]
There's a billion potential settings to make your router insecure and we don't plaster warning banners for them everywhere.

**Comment by lynxthecat** [comment]
"A journey of a thousand miles begins with a single step"?

Also this is a setting that almost every user will actually set? 

Or this creep factor for lots of unwanted feedback like the paper clip in Microsoft Office.

**Comment by Ansuel** [comment]
Closing this as not accepted.

**Pull request closed without merging**
