### PR TITLE
luci-app-ddns: fix huge typo in luasrc/tools/ddns.lua

### PR DESCRIPTION
**Pull request by yangfl**
Signed-off-by: David Yang <mmyangfl@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
Thanks for fixing the typo in tyep-->type originating from #1819 

This might be needed to be backported to 18.06, too.

@Ansuel , you authored the original changes. Somehow the app has worked with that typo, so I wonder if there have been some later workarounds around the effects of the typo, that could now be removed?
Or has it just been partially broken?

**Comment by yangfl** [comment]
@hnyman It was partially broken, that is, no matter what packages you have installed, ddns app always complained about "Using specific DNS Server not supported" (in luasrc/model/cbi/ddns/hints.lua#140)

**Comment by jow-** [comment]
The change looks legit to me, will merge it.

**Comment by yangfl** [comment]
@jow- you might also want to merge #1865

**Pull request merged**
