### PR TITLE
Pull request app uhttpd

### PR DESCRIPTION
**Pull request by dfc-d**
This series of commits add a LuCI app for configuring uHTTPs UCI parameters as well as managing the Basic Auth authorization config in /etc/httpd.conf (or whatever is configured in uci config).

### CODE REVIEW

**Comment by dfc-d** [comment]
l2tp ipaddrport is actually wrong if ipv6 support is desired; the ipaddrport from 9b30357 regex is wrong for ipv6.

**Comment by jow-** [comment]
You're right. Will take care of it.

**Comment by dfc-d** [comment]
Ok, I'm made a number of fixes and improvements:

1) I've merged the safe file upload into the regular FileUpload widget with an option to use the unsafe (certificate removing) upload via self.unsafeupload
2) For the FileUpload widget I have added a secondary textbox that allows you to enter a path to a file already on the router instead of uploading a file.
3) For the uHTTPd application itself I have remove the whole business of non-UCI config file handling via UCI; I decided the better path to to UCI-ify the /etc/httpd.conf (or whatever file the user picks for name; can have different .conf per uhttpd instance so that will take some work).
4) I fixed the ipaddrport validator to handle ipv6
5) I added an ipv4only option to hostport (which is actually what l2tp uses) for l2tp and other protocols/applications that only support ipv4.
6) I have fixed a problem with the FileUpload widget (at least) (possibly the sysupgrade was affected as well) that was introduced the CSRF token being moved off of the URI.  Basically the http.formvalue call to parse the token triggers luci.http._parse_input *before* setfilehandler can be called by the load cbimap code (not sure if it is also before the setfilehandler for sysupgrade).  What I've done is added an mkstemp function to lib-nixio which calls mkstemp and immediately performs an unlink so that the (safe b/c mkstemp) temp file will be removed once the file is closed.  In the mimedecode function I store any 'file' fields in (different) temporary files which are kept open until luci.http.setfilehandler is called.  When setfilehandler is called I iterate through the file fields and copy the data from the temporary file to the filehandler callback (which behaves as before), and then close the temporary file (which causes unlink to complete).  Once setfilehandler has been called, the filehandler is used instead of temp files.

I also have a fallback option of copying the file fields to memory if the temp file fails.

**Comment by jow-** [comment]
Sysupgrade is not affected by this race as it does not use CBI maps and performs the `setfilehandler()` call in the controller action. It also uses an ordinary `call()` target instead of a `post()` one and invokes `test_post_security()` manually in order to avoid premature implicit HTTP message parsing (see [system controller](https://github.com/openwrt/luci/blob/master/modules/luci-mod-admin-full/luasrc/controller/admin/system.lua#L249))

**Comment by jow-** [comment]
Can you break out the validator changes and the FileUpload widget rework (without the changed setfilehandler handling) into separate PRs so that I can already merge those parts?

**Comment by dfc-d** [comment]
Do you want the setfilehandler change broken out as well?

Also any objections to merging the uhttpd app as it is, and I'll add the Basic Auth configuration stuff later (since that requires modification of uhttpd package in order to ucify that part of the config).

The only thing that wouldn't work with the uhttpd app would be the certificate upload and that is because of the race condition with setfilehandler, and I believe at the moment all use of FileUpload is broken until the setfilehandler is resolved.

**Comment by jow-** [comment]
Merged, thanks!

**Pull request merged**
