### PR TITLE
Backup: add firmware backup for mtdblock devices

### PR DESCRIPTION
**Pull request by rosysong**
This commit add the feature that allow user to backup the image of the flash. 

backup

### CODE REVIEW

**Comment by rosysong** [comment]
@hnyman @jow-

**Comment by hnyman** [comment]
How is that ipv6 related change related to the backup functionality that is the topic of this PR?

**Comment by rosysong** [comment]
@hnyman  sorry, will drop it.

**Comment by rwalli** [comment]
Hello!

First I’d like to say that this PR is really essential in luci:
It allows user to make a real backup of the system and to restore the whole device with all packages an config's.
A perfect long outstanding feature!

For me it works perfect, but maybe for new users the interface may be confusing.
It’s not clear how to restore the backups and how to deal with mtd-partitions.
If you want to restore u-boot or art partition it is very likely that you already have serial adapter and soldering iron lying around, which is not the everyday case.

I would suggest to remove other partitions than “firmware” or make it visible via “Expert Options”  -checkbox in the Configuration-section (if you lockup the bootloader  it can’t be restored within luci).

Further more it could be handy if the downloaded images have “Model” and “Hostname” in their filenames. 

Maybe it could look like this:

(“Keep settings” is a little bit confusing when restoring a backup-firmware but did no harm in my tests.)

screenshot 2018-09-02 12 16 49

**Comment by rosysong** [comment]
@rwalli  Having “Model” and “Hostname” in target file is a good suggestions. 

In addition, I think we really need the backup options for **u-boot** and **art** partitions, particularly for the developers who work on them. Though these features is not everyday case but it is useful and convenient once we need. Moreover, this can meet the different needs of people who use OpenWrt and luci. So I would prefer to **make it visible via “Expert Options” -checkbox** in the Configuration-section.

Thank you for your suggestions, @rwalli ! :-)

**Comment by hnyman** [comment]
The help texts should indicate more clearly that this is low-level technical functionality accessing flash partition directly, and is not meant for everyday config backup/restore. I am pretty sure that if the current version is merged, there will be people making config backups this way and then wondering how to restore them.

Should it be in a separate section??? (instead of backup)
Maybe after backup and restore. 

Terminology may be a bit confusing, as both this new text and the firmware flash text talk about "image". So, people may try using this mtdblock image for firmware flash...

**Comment by rosysong** [comment]
@hnyman @rwalli  Hi,  how about this ?

backupv3

**Comment by rosysong** [comment]
@hnyman This is the latest modification. I added a caution sentence saying that "this feature is for professionals!" at the description. Feel free to correct me if you think it is not properly. Thanks.

backupv4

**Comment by rosysong** [comment]
@hnyman @rwalli  I did not upload the code of the last screenshot, because I was not sure it seems OK.

Now I update my commit, and also fixed the issue (@hnyman) you mentioned. It won't miss the last 1024 bytes any longer. :-)

**Comment by hnyman** [comment]
Thanks. Looks good enough for me.
Seemed to work ok with my wrt3200acm, so let's merge it.

**Pull request merged**
