### PR TITLE
luci-mod-admin-full: add arp-scan to network diagnostic

### PR DESCRIPTION
**Pull request by aparcar**
This is a JavaScript rewrite of the PR#5152

It adds the ability to perform ARP scans if the tool `arp-scan` is
installed.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by aparcar** [comment]
image
image

**Comment by systemcrash** [comment]
Doesn't this create the requirement for the `/usr/bin/arp-scan` tool (not normally installed)?

**Comment by aparcar** [comment]
No, in case it is not installed it shows the message shown in the first picture

**Comment by systemcrash** [comment]
Commit e4bc192012b05078eb7675e42908e0dd9d04ee88 
https://github.com/openwrt/luci/blob/f974529c287a91e4cf477a5ce32f69d133e9feb5/modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js#L297

**Comment by aparcar** [comment]
image

CSS needs some fixing.

**Pull request merged**
