### PR TITLE
SVG favicon

### PR DESCRIPTION
**Pull request by stokito**
Replacement for #6717 

* Fix OpenWrt 2020 logo colors and background
* Use the SVG logo as a favicon
* Migrate all themes to the same logo

### CODE REVIEW

**Comment by stokito** [comment]
Needs for testing and feedback but generally it's should be ready to be merged. It will close #6716 and #6717

**Comment by systemcrash** [comment]
One thing #6717 does correctly is retain the png for those browsers that do not support them (safari...). 

https://caniuse.com/link-icon-svg

**Comment by systemcrash** [comment]
Looks mostly good. You retained the 180x180 png ya?

**Comment by stokito** [comment]
Yes, sorry, forgot to mention this: the original logo.png from the 2020 theme remains untouched. I was afraid to make a regression there.
For the theme the logo is also shown on the front page as a home logo.
Maybe there the 48px would be not enough.
But the material and the bootstrap will use the 48px version.

**Comment by stokito** [comment]
> For the theme the logo is also shown on the front page as a home logo.

Sorry, I was wrong, there is used the logo.svg, not png.
It should be safe to downscale that png too. It must be approved by the theme author.

**Comment by hnyman** [comment]
I tested with Firefox and Chrome, both bootstrap and openwrt2020 themes.
Looks ok to me.

Any objections, @jow-  ?

**Comment by stokito** [comment]
Thank you!

**Comment by jow-** [comment]
Looks quite ugly in dark mode:
grafik

I think the white curved bars at the top should be light blue, the circle should remain dark blue and the background should become transparent. This way it works well in both dark and light backgrounds.

**Comment by stokito** [comment]
According to [logo usage guidelines](https://openwrt.org/_media/docs/guide-graphic-designer/openwrt-logo-usage-guidelines.pdf) there are a few schemes:

1. White & Dark Blue that is used here
2. White & Blue that should look better on a dark background
3. White that also may be used in a dark mode.

The problem that I see is that here we have a dark theme of OS but the site itself may be in a light mode.

**Comment by stokito** [comment]
FYI: the SVG can be adopted to a dark mode by using internal styles https://rigtorp.se/notes/dark-mode-svg/

**Comment by jow-** [comment]
Here's a quick mockup of the changed color scheme:
grafik
grafik
grafik
grafik

**Pull request merged**
