### PR TITLE
luci-proto-ipv6: Add DHCPv6 norelease menu option

### PR DESCRIPTION
**Pull request by detobate**
Resubmitting #6764 without the change of default behaviour.

### CODE REVIEW

**Comment by systemcrash** [comment]
Merged, thanks :)

**Comment by try496** [comment]
Why is there no translation file?

**Comment by hnyman** [comment]
The possible translation strings get synced/populated in batch in random intervals

**Comment by hnyman** [comment]
>  build based on the latest 23.05 encountered a large number of dhcp content translation failures. I don’t know the reason.

Well, all translations are made by volunteers like you and me.
New strings are not automatically translated by some paid organisation, but require manual work. So, it may take a while after changes until you (or somebody else) does the translation and the new strings translations get merged (into main/master).  And then later they get backported into stable 23.05.

Feel free to contribute at https://hosted.weblate.org/projects/openwrt/

**Comment by try496** [comment]
Screenshot_2023-12-22-20-57-04-82

**Comment by try496** [comment]
IMG_20231222_210732
But this website cannot solve this problem

**Comment by systemcrash** [comment]
Correct. I added some new strings recently because the older ones were
ambiguous or did not explain clearly, and as such will require translating,
because the old ones were subtly wrong.

**Pull request merged**
