### PR TITLE
luci-app-pagekitec: add Japanese translation

### PR DESCRIPTION
**Pull request by musashino205**
Added Japanese translations.

Signed-off-by: INAGAKI Hiroshi <musashino.open@gmail.com>

- Question: Which of the tags ```<p/>``` and ```<br/>``` should I use as a newline?

### CODE REVIEW

**Comment by dibdot** [comment]
`<p/>` is not valid html, please use `</p>` instead. For newline I would use `<br />`.

**Comment by musashino205** [comment]
I see.
```<p/>``` tag used in original text merged in dcfc4569c483f4218cf41b26ef0f4dfed0441c55 , so I noticed it when I tried to translate and I was wondering if it was not right.
Should I also fix original text?

**Comment by dibdot** [comment]
Sorry, I didn't check that correctly. The paragraph tag used in this manner `(<p />`) serves as a double line break. It does not contain text. Unlike the `<br />` tag it cannot be used multiple times to generate more white space. Bottom line just leave it, it's OK.

**Comment by musashino205** [comment]
Well then, is it okay to keep ```<p/>```?

**Comment by dibdot** [comment]
Yep, ready to merge?

**Comment by musashino205** [comment]
Yes, OK!

**Comment by dibdot** [comment]
Thanks!

**Comment by musashino205** [comment]
Thanks :)

**Pull request merged**
