### PR TITLE
luci-proto-qmi is not displaying link informations 

### PR DESCRIPTION
**Pull request by bgiboudeau**
It would be great if we can have in the status section some details about the link status.
Something a bit like the Wifi status section, it's very helpfull to see quickly where do we stand with the radio interface.

Some informations from the command : uqmi -d "modem" --get-signal-info
- Link type : LTE, 3G, GPRS, ...

rssi / rsrq / rsrp & snr.

Some informations from the command : uqmi -d "modem" --get-serving-system
-registration
plmn_mcc
plmn_mnc
plmn_description
roaming
Thanks a lot
bgiboudeau

below the output of the two commands.
First command:  /sbin/uqmi -d /dev/cdc-wdm0 --get-signal-info

{
        "type": "lte",
        "rssi": -67,
        "rsrq": -10,
        "rsrp": -90,
        "snr": 250
}

Second command : uqmi -d /dev/cdc-wdm0 --get-serving-system

{
        "registration": "registered",
        "plmn_mcc": 208,
        "plmn_mnc": 15,
        "plmn_description": "Fy▒\u000c",
        "roaming": false
}

### CODE REVIEW

**Comment by feckert** [comment]
Please rebase your changes to the current master.

**Comment by feckert** [comment]
I think this is not a pullrequest.
@bgiboudeau please open an issue.

**Comment by feckert** [comment]
@bgiboudeau 
Please take a look at the difference between a pullrequest and an issue.
pullrequest: adds new code to the repository
issue: is for discussion

**Comment by bgiboudeau** [comment]
So I opened an issue 5 days ago.
This issue have been closed because it's a PR and that's true I'm asking new features. I made this mistake and sorry for that. As a reference the closed first issue that have been closed by @jow- . https://github.com/openwrt/luci/issues/3349

So I reopened today a "pullrequest" that you closed right away and asked me to reopen an issue.
     "I think this is not a pullrequest. @bgiboudeau please open an issue. feckert closed this 2 hours ago"

So to conclude do whatever you want with this pullrequest or issue. I just wanted to help.

**Comment by bgiboudeau** [comment]
> @bgiboudeau
> Please take a look at the difference between a pullrequest and an issue.
> pullrequest: adds new code to the repository
> issue: is for discussion
> 
> And this is a pullrequest Please also have a look at **this** website.
> Doesn't that look garbage to you, too?

So I closed everything, I let you decide between @jow- and you if it's a pullrequest or an issue and if you guys think the missing features are intresting. I'm done with the ping-pong between the two queues.

I also recommend to fully read the content of the request submited even if it's done by a new contributor.

Thx and have a nice day.

**Pull request closed without merging**
