### PR TITLE
luci-mod-network: permit WPS push-button on WPA3

### PR DESCRIPTION
**Pull request by Ansuel**
Currently WPS push-button is dropped when SAE or SAE-Mixed is selected. WPS is still supported in WPA3.

@jow- 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Please resync the translations when you change labels. At least update the english key strings so that other translations do not get lost.

**Comment by Ansuel** [comment]
@jow- should i manually update the already translated strings? (think it's bad that the translation got dropped)

**Comment by hnyman** [comment]
> should i manually update the already translated strings? (think it's bad that the translation got dropped)

Yes. I think that for many of the few translated languages it would be relatively easy to add WPA3 to the translated string.  

Dropping existing translations is always bad. Preventing that usually requires some manual work (or sed + manual work).

**Comment by feckert** [comment]
Please rebase your changes

**Comment by Ansuel** [comment]
@feckert can you give me some advice on how to easily change po files? for this?

**Comment by Ansuel** [comment]
@jow- i also updated this

**Comment by jow-** [comment]
Strictly speaking there's no `WPA3-PSK` - a better wording would be `WPA(2)-PSK/WPA3-SAE`

**Comment by Ansuel** [comment]
@jow- fixed

**Pull request merged**
