### PR TITLE
Pull request dnsmasq dnssec

### PR DESCRIPTION
**Pull request by dfc-d**
Add (conditional on dnsmasq-full) ability to set DNSSEC options.

### CODE REVIEW

**Comment by hnyman** [comment]
I merged this and then compiled Luci to test it, but to me it seems that the check for dnsmasq variant does not work. The DNSSEC options are visible although I do not have enabled dnssec in dnsmasq. 

If I change the test ``` if have_dnssec_support then ``` to ``` if have_dnssec_support == 1 then ```, then the DNSSEC section is properly hiddden.

Dit you test this with both variants? Does it work for you without modifications?

**Comment by dfc-d** [comment]
In 16-03-29 09:25 AM, Hannu Nyman wrote:
> I merged this and then compiled Luci to test it, but to me it seems that
> the check for dnsmasq variant does not work. The DNSSEC options are
> visible although I do not have enabled dnssec in dnsmasq.
>
> If I change the test |if have_dnssec_support then| to |if
> have_dnssec_support == 1 then|, then the DNSSEC section is properly hiddden.
>
> Dit you test this with both variants? Does it work for you without
> modifications?

Doh!  I didn't rebase with the fixes to the patch it depends on - it 
should be return false and return true instead of return 0 and return 1.

Regards,

Daniel

**Comment by dfc-d** [comment]
On 16-03-29 09:25 AM, Hannu Nyman wrote:
> I merged this and then compiled Luci to test it, but to me it seems that
> the check for dnsmasq variant does not work. The DNSSEC options are
> visible although I do not have enabled dnssec in dnsmasq.
>
> If I change the test |if have_dnssec_support then| to |if
> have_dnssec_support == 1 then|, then the DNSSEC section is properly hiddden.
>
> Dit you test this with both variants? Does it work for you without
> modifications?

Actually I'm not sure my solution of false/true is ideal since the 
original reason for numbers was that I used -1 to indicate we done know 
(because of lack of ldd - e.g. default uclibc++ or glibc if no ldd 
installed (not sure if that is allowed), 0 for lib not linked, and 1 for 
is linked.

I'm decided I didn't think the -1 case was actually relevant and in my 
fix I ditched the -1 (because needing to check for a number instead of 
true/false is less intuitive), but I'm not sure that's the right decision.

Do you think the tristate or boolean is the better way to go?

Regards,

Daniel

**Comment by dfc-d** [comment]
On 16-03-29 09:25 AM, Hannu Nyman wrote:
> I merged this and then compiled Luci to test it, but to me it seems that
> the check for dnsmasq variant does not work. The DNSSEC options are
> visible although I do not have enabled dnssec in dnsmasq.
>
> If I change the test |if have_dnssec_support then| to |if
> have_dnssec_support == 1 then|, then the DNSSEC section is properly hiddden.
>
> Dit you test this with both variants? Does it work for you without
> modifications?

Also for boolean option to you think "don't know" should be true or 
false.  I used true, but now that I think about it, false is probably safer.

Regards,

Daniel

**Comment by hnyman** [comment]
I would keep it simple: boolean, and false for absent library or failing test, true if the needed library is found.

**Comment by dfc-d** [comment]
Ok, I'll do up a patch and push once I've tested the cases (actually I 
cheat and just move ldd out of the way, rather than third build).

Regards,

Daniel

**Comment by hnyman** [comment]
Please don't forget fixing this.

**Comment by dfc-d** [comment]
I've tested the case of with dnssec linked and with no ldd (i.e. can't
tell, but haven't had a chance to test a non-dnssec binary to confirm
the no match case.

Regards,

Daniel

**Comment by hnyman** [comment]
> ...but haven't had a chance to test a non-dnssec binary to confirm the no match case.

I can test the non-dnssec manually on my router, if I can pick up the patch from a pull request.

**Comment by dfc-d** [comment]
On 16-04-07 01:53 AM, Hannu Nyman wrote:
>     ...but haven't had a chance to test a non-dnssec binary to confirm
>     the no match case.
> 
> I can test the non-dnssec manually on my router, if I can pick up the
> patch from a pull request.

Thanks for helping.  Pull request is here:
https://github.com/openwrt/luci/pull/698

I'm trying to be more rigorous than I have been, and not submitting not
thoroughly tested (in the exact incarnation pushed) requests / patches.

Regards,

Daniel

**Pull request merged**
