### PR TITLE
luci-app-dockerman: check for existing IPAM config

### LINKED ISSUE #6973: luci-app-dockerman: networks page error
After docker update from 24.0.7 to 25.0.3  the networks page on luci-app-dockerman get error.
https://github.com/openwrt/packages/pull/23482
## Steps to reproduce:

luci-app-dockerman --> networks

## Actual behavior:

docker-networks

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r25409-4adba64156'
DISTRIB_TARGET='bcm27xx/bcm2712'
DISTRIB_ARCH='aarch64_cortex-a76'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r25409-4adba64156'
DISTRIB_TAINTS=''
```

### PR DESCRIPTION
**Pull request by dannil**
Fixes #6973 

This was added in upstream with https://github.com/lisaac/luci-app-dockerman/commit/7292955a1b415bb60fa2e403bb3a437b4b7f7846 so should be fine for us to add it.

Networks tab works again after fix. I'm not entirely sure how to test this properly as I don't use Docker via LuCI myself so any test would be appreciated.

Screenshot_48

Ping @leobsky @Joee-D

- [X] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [X] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [X] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [X] Incremented :up: any `PKG_VERSION` in the Makefile
- [X] Tested on: (x86/generic, 23.05.2, Firefox) :white_check_mark:
- [X] \( Preferred ) Mention: @ the original code author for feedback @feckert (and @lisaac maybe?)
- [X] \( Preferred ) Screenshot or mp4 of changes:
- [X] \( Optional ) Closes: e.g. openwrt/luci#6973
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [X] Description: (describe the changes proposed in this PR)

### CODE REVIEW

**Comment by dannil** [comment]
Also, a thing to note; the change in https://github.com/openwrt/packages/pull/23482 was backported to the `23.05` branch with https://github.com/openwrt/packages/pull/23483 (which was what spawned this issue to begin with) so if this gets merged we will most likely need a cherry-pick.

**Review by systemcrash — APPROVED** [review]

**Comment by systemcrash** [comment]
Yeah, these look good. Anyone else?

**Comment by jow-** [comment]
LGTM as well. Too bad Lua has no optional chaining operator.

**Comment by jow-** [comment]
Merged, thanks!

**Pull request merged**
