### PR TITLE
luci-app-adblock query form: Fix enter key submitting form but not showing any results

### PR DESCRIPTION
**Pull request by stefansundin**
Right now you can hit the enter key while the input field is focused, and it submits the form, but no result is displayed. Even though a POST request is made, it doesn't seem to actually be querying the domain.

It might be nice to fix that too, so it would work for users that have JavaScript disabled. But I am not sure how to make that work, so if someone can provide help with that, that would be great.

Thanks!

### CODE REVIEW

**Comment by dibdot** [comment]
Thanks for your contribution!
Please remove the CONTRIBUTING.md change from this PR, its unrelated to adblock and should go in a separate PR.

Thanks!

**Comment by stefansundin** [comment]
Done. I cherry-picked that commit to this PR: https://github.com/openwrt/luci/pull/3708

**Comment by dibdot** [comment]
Thanks!

**Comment by dibdot** [comment]
cherry-picked to 19.07 as well.

**Comment by stefansundin** [comment]
@dibdot Just wanted to note that it may be desirable to fix the form submission as well? I just didn't know how to do that. Thanks.

**Comment by dibdot** [comment]
I don't really care, cause I've already migrated forthcoming adblock 4.0 to client side JS ...;-)

**Pull request merged**
