### PR TITLE
luci-app-ddns: add improvments

### PR DESCRIPTION
**Pull request by feckert**
* Update config view, so that the individual sections (info, global) are divided into different tabs. 
* Cleaned up source

@Ansuel could you please have a look if this breaks anything?
You did the intial checkin of this package in javascript.

### CODE REVIEW

**Comment by Ansuel** [comment]
Tested and looks good... Do you have any other suggestion to improve this mess? (a better start/restart for the ddns rules)

**Comment by feckert** [comment]
>  Do you have any other suggestion to improve this mess? (a better start/restart for the ddns rules)

From my point of view, this can certainly be improved. But I have to take a closer look at it again. After merging this P/R.

**Comment by feckert** [comment]
>  Do you have any other suggestion to improve this mess? (a better start/restart for the ddns rules)

@Ansuel I am in the process of refactoring the ddns-scripts package. So it might be that we have to rebuild the luci-app-ddns a bit. Would you be willing to test the changes in the ddns-scripts package when I am ready? I will open a P/R [WIP] in the next days.

**Comment by Ansuel** [comment]
Sure tag me when you open the pr... and thx a lot for the work

**Comment by feckert** [comment]
@Ansuel I pushed a  [P/R](https://github.com/openwrt/packages/pull/13402) in WIP for ddsn-scripts.
Can you have a look at it? And try it if this works for your setup and give me some feedback?

I have seen that when I outsource this to individual JSON files, the size of the installed package changes significantly. I don't see this as a problem, because I would improve other things that works against it. For example _maintainability_. It is also not always necessary to install all providers. Which is not possible now.

As it is, there are some hacks that are not easy to maintain and therefore not necessary if we outsource it to JSON.
Also the question is if we really need all providers.

**Pull request merged**
