### PR TITLE
samba4: fix the layout of textbox

### PR DESCRIPTION
**Pull request by selanf**
without this, only 50% of screen where used

### CODE REVIEW

**Comment by selanf** [comment]
Screenshot how it looks with this commit:
image

**Comment by selanf** [comment]
Is this the correct way to update this pr, will it be squashed? Or have i to recreate it?

**Comment by hnyman** [comment]
You should squash the branch, and then force push the branch and the PR gets updated.

**Comment by selanf** [comment]
Thx, "rebase" did not work, so i
```
git reset --soft HEAD~2
git commit
git push -f
```

**Comment by jow-** [comment]
Merged, thank you!

**Pull request merged**
