### PR TITLE
luci-app-mwan3: add syslog option and prefiil ipset rule dropdown

### PR DESCRIPTION
**Pull request by feckert**
- Add new syslog option
- Add prefilled ipset dropdwon on rule configuration

### CODE REVIEW

**Comment by monokoo** [comment]
What can  i do if i have no ipset list installed?  Prefilling the ipset selection maybe not a good chioce.

**Comment by feckert** [comment]
@monokoo thanks good hint I will update the code tomorrow

**Comment by feckert** [comment]
@monokoo I took a look at this and mwan3 has a dependency to ipset
https://github.com/openwrt/packages/blob/c25e0cbc5e72de86cd18832c8d1f51849e3aa290/net/mwan3/Makefile#L24
So this tool should be auto installed. Dependency tree is luci-app-mwan3 -> mwan3 -> ipset.
If no ipset is found or setup in the system
https://github.com/openwrt/luci/blob/d6ae36353b355600057fa81ffbf15a29acd6059e/applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua#L13
then you can add your own IPset in the dropdown under userdefined.

**Comment by monokoo** [comment]
> @monokoo I took a look at this and mwan3 has a dependency to ipset
> https://github.com/openwrt/packages/blob/c25e0cbc5e72de86cd18832c8d1f51849e3aa290/net/mwan3/Makefile#L24
> So this tool should be auto installed. Dependency tree is luci-app-mwan3 -> mwan3 -> ipset.
> If no ipset is found or setup in the system
> [luci/applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua](https://github.com/openwrt/luci/blob/d6ae36353b355600057fa81ffbf15a29acd6059e/applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua#L13)
> 
> Line 13 in [d6ae363](/openwrt/luci/commit/d6ae36353b355600057fa81ffbf15a29acd6059e)
> 
>  local ipsets = util.split(util.trim(util.exec("ipset -n -L 2>/dev/null | grep -v mwan3_ | sort")), "\n", nil, true) or {} 
> 
> then you can add your own IPset in the dropdown under userdefined.

thanks， I will try this.

**Comment by monokoo** [comment]
> @monokoo I took a look at this and mwan3 has a dependency to ipset
> https://github.com/openwrt/packages/blob/c25e0cbc5e72de86cd18832c8d1f51849e3aa290/net/mwan3/Makefile#L24
> So this tool should be auto installed. Dependency tree is luci-app-mwan3 -> mwan3 -> ipset.
> If no ipset is found or setup in the system
> [luci/applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua](https://github.com/openwrt/luci/blob/d6ae36353b355600057fa81ffbf15a29acd6059e/applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua#L13)
> 
> Line 13 in [d6ae363](/openwrt/luci/commit/d6ae36353b355600057fa81ffbf15a29acd6059e)
> 
>  local ipsets = util.split(util.trim(util.exec("ipset -n -L 2>/dev/null | grep -v mwan3_ | sort")), "\n", nil, true) or {} 
> 
> then you can add your own IPset in the dropdown under userdefined.

But i still have issue with configuring rule, like this: [](https://i.loli.net/2019/01/31/5c527eb280716.png)

I don't want to use any ipset list, just wana this to be blank. But no blank option.
Normally, there should be a "Please choose" option like others: [](https://i.loli.net/2019/01/31/5c527f9f68d97.png)

**Comment by feckert** [comment]
Got it.
Sorry my fault.
See follow up PR

**Pull request merged**
