### PR TITLE
luci-app-ddns: fix Event Network value source

### PR DESCRIPTION
**Pull request by findlayfeng**
Event Network value source should be NetworkSelect instead of DeviceSelect

- [x] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [x] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [x] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [x] Tested on: (arm/r5c, main, vivaldi) :white_check_mark:
- [x] \( Preferred ) Mention: Ansuel Smith <ansuelsmth@gmail.com>
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [ ] \( Optional ) Closes: e.g. openwrt/luci#issue-number
- [x] \( Optional ) Depends on: 
- [x] Description: The source of network events is the interface rather than the device

### CODE REVIEW

**Comment by McGiverGim** [comment]
I've one ddns entry associated to this "event" and it does not start after a reboot of the router. I need to start it manually. With this PR it seems to start. So it seems a good fix.

**Review by McGiverGim — APPROVED** [review]

**Comment by systemcrash** [comment]
Thanks for confirming. 

Maybe @findlayfeng you can see why the Reload log file button sometimes does not work. I don't see the button for my ipv4 check, but I do under the ipv6 check which is not in use.

**Comment by findlayfeng** [comment]
> I've one ddns entry associated to this "event" and it does not start after a reboot of the router. I need to start it manually. With this PR it seems to start. So it seems a good fix.

因为ddns的每一个脚本都会关联到某个事件，为了避免在引导阶段重复启动，ddns选择在引导时跳过所有的脚本，这个错误的下拉条让ddns脚本不能正确的关联到接口的网络事件，也就导致了这个脚本在引导时没有正确的启动，如果你足够细心的话还能发现接口在重启时并没有正确的触发对应的ddns脚本重载
Because each script of ddns will be associated with a certain event, in order to avoid repeated startup during the boot phase, ddns chooses to skip all scripts during boot. This wrong drop-down bar prevents the ddns script from correctly relating to the network events of the interface.  This results in the script not starting correctly during boot. If you are careful enough, you can also find that the interface does not correctly trigger the corresponding ddns script reload when restarting.

**Comment by McGiverGim** [comment]
@systemcrash I don't understand what is happening to you with the button of Reload log. I can't reproduce it. Maybe you can give a step by step instructions?

If not, I think this PR can be merged as is, the problem with the button can be fixed later.

**Comment by systemcrash** [comment]
I just realised @ansuel was not tagged initially.

**Comment by systemcrash** [comment]
> @systemcrash I don't understand what is happening to you with the button of Reload log. I can't reproduce it. Maybe you can give a step by step instructions?
> 
> If not, I think this PR can be merged as is, the problem with the button can be fixed later.

I have e.g. config
```

config ddns 'global'
	option ddns_dateformat '%F %R'
	option ddns_loglines '250'
	option upd_privateip '0'

config service 'myddns_ipv4'
	option interface 'wan'
	option ip_source 'network'
	option ip_network 'wan'
	option lookup_host 'xxx'
	option use_syslog '1'
	option force_interval '30'
	option force_unit 'days'
	option enabled '1'
	option check_unit 'hours'
	option use_https '1'
	option update_url 'https://.../?'

config service 'myddns_ipv6'
	option update_url 'http://[USERNAME]:[PASSWORD]@your.provider.net/nic/update?hostname=[DOMAIN]&myip=[IP]'
	option lookup_host 'yourhost.example.com'
	option domain 'yourhost.example.com'
	option username 'your_username'
	option password 'your_password'
	option use_ipv6 '1'
	option interface 'wan6'
	option ip_source 'network'
	option ip_network 'wan6'
```

Which looks respectively like:
Screenshot 2024-04-05 at 16 05 55
Screenshot 2024-04-05 at 16 06 00

**Comment by systemcrash** [comment]
Merged. Thanks @findlayfeng

**Comment by McGiverGim** [comment]
Adding your IPv4 config to my file reproduces the issue. I've other ddns with IPv4 that don't have this error, so is some data in your config. I will do more tests to see if I can fix it.

**Comment by systemcrash** [comment]
It's likely related to the '--custom--' profile.

**Comment by findlayfeng** [comment]
> > @systemcrash I don't understand what is happening to you with the button of Reload log. I can't reproduce it. Maybe you can give a step by step instructions?
> > 
> > If not, I think this PR can be merged as is, the problem with the button can be fixed later.
> 
> I have e.g. config
> ```
> 
> config ddns 'global'
> 	option ddns_dateformat '%F %R'
> 	option ddns_loglines '250'
> 	option upd_privateip '0'
> 
> config service 'myddns_ipv4'
> 	option interface 'wan'
> 	option ip_source 'network'
> 	option ip_network 'wan'
> 	option lookup_host 'xxx'
> 	option use_syslog '1'
> 	option force_interval '30'
> 	option force_unit 'days'
> 	option enabled '1'
> 	option check_unit 'hours'
> 	option use_https '1'
> 	option update_url 'https://.../?'
> 
> config service 'myddns_ipv6'
> 	option update_url 'http://[USERNAME]:[PASSWORD]@your.provider.net/nic/update?hostname=[DOMAIN]&myip=[IP]'
> 	option lookup_host 'yourhost.example.com'
> 	option domain 'yourhost.example.com'
> 	option username 'your_username'
> 	option password 'your_password'
> 	option use_ipv6 '1'
> 	option interface 'wan6'
> 	option ip_source 'network'
> 	option ip_network 'wan6'
> ```
> 
> Which looks respectively like:
> Screenshot 2024-04-05 at 16 05 55
> Screenshot 2024-04-05 at 16 06 00
> 
> 

重要的是 option use_syslog '1'
日志读取功能只是读取记录到文件的日志 use_syslog 需要配置为0

The important thing is that the Option USE_SYSLOG '1' log read function just reads the log recorded to the file USE_SYSLOG needs to be configured as 0

**Comment by McGiverGim** [comment]
The problem is with the option:
```
option use_ipv6 '0'
```
If you add it, all works, but if it's missing, like now, it hides the button (and the advanced tab).

**Pull request merged**
