### PR TITLE
luci-app-sshtunnel: servers: ProxyCommand option

### PR DESCRIPTION
**Pull request by stokito**
A leftover from #6772
Since the https://github.com/openwrt/packages/pull/22975 was merged we can now add the ProxyCommand to the Luci app.

cc @systemcrash

### CODE REVIEW

**Comment by stokito** [comment]
thank you

**Comment by hnyman** [comment]
There is now a weblate conflict.
Hopefully @systemcrash can fix it, as I am travelling without proper access...

**Comment by stokito** [comment]
I checked and my translation is better than from the WebLate. Also one key was changed (typo "serve" to "server"). So the WebLate changes needs to be discarded

**Comment by systemcrash** [comment]
> There is now a weblate conflict. Hopefully @systemcrash can fix it, as I am travelling without proper access...

Should be able to. Can you see where? I don't immediately see a conflict.

**Comment by stokito** [comment]
It looks like it's too complicated to fix the conflict in the WebLate
https://hosted.weblate.org/projects/openwrt/luciapplicationsdockerman/#alerts

Maybe I'll remove my changes? And later will translate from the WebLate.

**Comment by systemcrash** [comment]
I've reverted this commit via 23df9c2fbf2eafdb208b1461ba0d823d989819d7

**Comment by systemcrash** [comment]
OK, looks like we are back in business.

**Comment by stokito** [comment]
ok, and should I make a new PR without the po files?

**Comment by systemcrash** [comment]
That's certainly one way to do it.

**Pull request merged**
