### PR TITLE
luci-app-firewall: improve offload option

### PR DESCRIPTION
**Pull request by Ansuel**
This improve how offload option are displayed

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
I had that originally, but in my tests that caused trouble when you toggle the options on and off several times. Something went wrong in  config file.

Maybe Luci does not like duplicate typedsections.

**Comment by Ansuel** [comment]
@hnyman problem is that in that page all is based on the section of the firewall config file...

we should set a new section in the config file to create a separate section in the luci page... (and i think it should be that way, as flow offload is not so related to the general option of the firewall...)

**Comment by Ansuel** [comment]
ok i reworked this... now it does create the section if supported... I can't find where the offload option is loaded. Can you tell me where it's used? (so i can change it to reflect this pr?)

**Comment by jow-** [comment]
The proposed change does not really make sense. The offloading options are located in the firewall defaults section. Your change would create a new `config offload_option` section (and break the entire uci save / apply / revert workflow at the same time).

**Comment by Ansuel** [comment]
then there is no way to put this 2 option in another section?

**Comment by jow-** [comment]
Why?

**Comment by jow-** [comment]
If this change is for purely cosmetic reasons then consider adjusting the theme CSS instead.

**Comment by Ansuel** [comment]
flow_offloading_hw option depends on  flow_offloading

When flow_offloading is selected flow_offloading_hw should appear under flow_offloading but it does appear under drop_invalid option

if it's not possible i will go with css way


cattura
cattura2

**Pull request closed without merging**
