### PR TITLE
luci-app-firewall:  Full Italian Translation

### PR DESCRIPTION
**Pull request by Bubu83**
Full and correct ITALIAN translation of luci firewall.po

Signed-off-by: Alessio Casagrande <bubu83@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
@Bubu83 
Thanks for your input, but please follow the rules and sign-off the commits properly (in the commit message itself) with your real name.
When amending that sign-off, please also squash the commits together.
And please prepend the commit title with "luci-app-firewall: "

**Comment by Bubu83** [comment]
thanks for the reply, it's my first time doing this: can you help me with the squashing together thing, i can't see a button to do that.

**Comment by hnyman** [comment]
> can you help me with the squashing together thing, i can't see a button to do that.

You need to use git command line tools.
Short advice in https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md#advice-on-pull-requests

**Comment by Bubu83** [comment]
i'm trying but without succes, could you explain how to do that or just squash and approve all for me?

thanks

**Comment by Bubu83** [comment]
i think i did it. I was doing the process on the wrong branch.

**Comment by hnyman** [comment]
It is almost right, just one commit, but you should still edit it one more time, so that you can add the signed-off-by to the commit message itself. (This PR discussion does not get stored to git, but commit message does.)

simple "git commit --amend" on the branch would be enough to edit the message. And then force push the branch to get the change reflected on Github.

**Comment by Bubu83** [comment]
Hope this time is correct.
thanks

**Comment by hnyman** [comment]
Thanks ;-)

**Pull request merged**
