### PR TITLE
luci-app-bcp38: added bcp38 application

### PR DESCRIPTION
**Pull request by danrl**
This application was moved from the packages repository to luci.

Signed-off-by: Dan Luedtke <mail@danrl.com>

What I do not know how to implement best is this part:
````
define Package/luci-app-bcp38/postrm
#!/bin/sh
uci delete ucitrack.@bcp38[0]
uci commit
endef
````
What is the correct trigger in the LuCI build system for that?

This  PR depends on: https://github.com/openwrt/packages/pull/4013

### CODE REVIEW

**Comment by tohojo** [comment]
No objections to this move, but the postinst/prerm hooks need to be carried over (or equivalent functionality needs to be added); otherwise things will break...

**Comment by danrl** [comment]
I hope I covered the postinst correclty with the uci-defaults script.


It was this before:
````
define Package/luci-app-bcp38/postinst
 #!/bin/sh
 [ -x /etc/uci-defaults/luci-bcp38 ] && /etc/uci-defaults/luci-bcp38 || exit 0
 endef
````

And now is in `applications/luci-app-bcp38/root/etc/uci-defaults/60_luci-bcp38`

For the prerm I have to admit that I do not know how it is handled in the LuCI build system. Maybe @hnyman can give me a hint?

**Comment by tohojo** [comment]
Trouble is that the uci-defaults is not run until the next boot. And since this package is not likely to be installed as part of an image, without the postinst, what will happen is that people will install it, then go configure it, and it'll do... nothing...

**Comment by danrl** [comment]
Ok, that's bad. So this PR is not a candidate for merging until I figured out how to fix that. Thanks for the clarification!

**Comment by hnyman** [comment]
> Trouble is that the uci-defaults is not run until the next boot. 

To my knowledge the uci-defaults of a package is run nowadays at the opkg installation to a live router with both LEDE and Openwrt master (since April-May 2016):

LEDE master:
https://github.com/lede-project/source/commit/9b9c78e071469313566473984fb79f54c1881c10
https://github.com/lede-project/source/commit/7f6945829640e82dadf928c9e214470fa0c5a321

Openwrt master (practically same patch has been applied twice...):
https://github.com/openwrt/openwrt/commit/ca78fd16b547604eae6757241acacf30bbe2904f
https://github.com/openwrt/openwrt/commit/535a2648b20d1ee10cb444d590aebfd488d2c180

Additionally, packages **from the LuCI repo** have ran uci-defaults at opkg install due to postinst automatics in luci-mk (since 2014):
https://github.com/openwrt/luci/blob/master/luci.mk#L11
https://github.com/openwrt/luci/blob/master/luci.mk#L189

Ps.
bcp38 does not have prerm. (It has a rather non-essential postrm)
https://github.com/openwrt/packages/blob/master/net/luci-app-bcp38/Makefile#L51

**Comment by tohojo** [comment]
Ah, was not aware of that - that's awesome, we can probably lose the postinst then :)

And yeah the postrm (post, pre, who is really keeping track? ;)), it's not terribly important. Anyone knows what happens if the ucitrack entry is not removed? If it doesn't break things I'm fine with just going without it as well

**Comment by hnyman** [comment]
There was a typo in dependencies that I fixed with https://github.com/openwrt/luci/commit/c0303598d5420324fa8991bfca8f34d341ab4d44

**Pull request merged**
