### PR TITLE
add string

### PR DESCRIPTION
**Pull request by kuoruan**

### CODE REVIEW

**Comment by chris5560** [comment]
could you please sign-off your work

**Comment by kuoruan** [comment]
Add translate

**Comment by chris5560** [comment]
https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md
https://dev.openwrt.org/wiki/SubmittingPatches#a10.Signyourwork

**Comment by kuoruan** [comment]
Signed-off-by: Kuoruan <kuoruan@qq.com>

Like this?

**Comment by kuoruan** [comment]
I'm sorry but I don't know how to sign-off...

**Comment by hnyman** [comment]
You should squash the 13 commits into one. (Currently you ave several reverts, reverts of reverts etc. which make the changes confusing.)

And that commit should be signed-off. The signed-off line needs to be in the commit message of the commit itself and it should contain your real name, not just the gmail username.

From functional perspective, the basic translation corrections are probably ok, but I am not sure about the acceptability of adding the translation layer to the option value labels like WPA-PSK etc.

**Pull request closed without merging**
