### PR TITLE
luci-base: update Ukrainian translation

### PR DESCRIPTION
**Pull request by YuriPet**
Updating Ukrainian translation according the latest sync translation. Сorrections and additions.

Signed-off-by: Yurii <yuripet@gmail.com>

### CODE REVIEW

**Comment by feckert** [comment]
@YuriPet Could you please add in the future your real full name in den Signed-off-by line?

**Comment by YuriPet** [comment]
I would do it with pleasure, but I can not find a way to do it.

**Comment by jow-** [comment]
Do you use Git from the command line? If yes, try this within your clone of the LuCI repository:
`git config user.name "Your Real Name"`

**Comment by YuriPet** [comment]
No, unfortunately, I work with github.com only through the browser.

**Pull request merged**
