### PR TITLE
luci-app-dawn: Network Overview Rewrite with div tables

### PR DESCRIPTION
**Pull request by JonnyTischbein**
Based on the work of @PolynomialDivision I did a rewrite of the dawn network overview similar to https://github.com/openwrt/luci/pull/3927

Screenshot_2020-04-19_22-04-11-2

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Thank u very much for finishing my work! :D

I thought about changing Channel Utilization to just Utilization, so the boundaries are on the same height. I think it is getting clear what utilization means in the context.

**Comment by castillofrancodamian** [comment]
What is this App for?

**Comment by JonnyTischbein** [comment]
@castillofrancodamian as titled for DAWN

**Comment by PolynomialDivision** [comment]
> What is this App for?

Decentralized Controller for Radio Resource Managment (Client Steering, Load Balancing, etc. ...)
https://github.com/berlin-open-wireless-lab/DAWN

**Comment by castillofrancodamian** [comment]
> > What is this App for?
> 
> Decentralized Controller for Radio Resource Managment (Client Steering, Load Balancing, etc. ...)
> https://github.com/berlin-open-wireless-lab/DAWN

Excellent! 👌

**Comment by PolynomialDivision** [comment]
asdf

Looks much cleaner now! :D Thank u!

**Comment by PolynomialDivision** [comment]
I will test in another theme again.

**Comment by castillofrancodamian** [comment]
I hope to try it out sometime!

**Comment by castillofrancodamian** [comment]
It is missing that it is translatable for WebLate...

**Comment by PolynomialDivision** [comment]
looksnice
The second table is darker and changes in color?

**Comment by PolynomialDivision** [comment]
> I hope to try it out sometime!

Still under huge development... :P

**Comment by PolynomialDivision** [comment]
> It is missing that it is translatable for WebLate...

Is this important?

**Comment by PolynomialDivision** [comment]
But it looks very nice! I don't care if the color is changing. :)

**Comment by castillofrancodamian** [comment]
> > It is missing that it is translatable for WebLate...
> 
> Is this important?

And... yes, since almost all LuCI apps can be translated or are already translated in different languages.

**Comment by PolynomialDivision** [comment]
> > > It is missing that it is translatable for WebLate...
> > 
> > 
> > Is this important?
> 
> And... yes, since almost all LuCI apps can be translated or are already translated in different languages.

Ah okay. I will do that in future. I first have to read how to do it.

**Comment by PolynomialDivision** [comment]
Please merge.

**Comment by castillofrancodamian** [comment]
> > > > It is missing that it is translatable for WebLate...
> > > 
> > > 
> > > Is this important?
> > 
> > 
> > And... yes, since almost all LuCI apps can be translated or are already translated in different languages.
> 
> Ah okay. I will do that in future. I first have to read how to do it.

👍

**Pull request merged**
