### PR TITLE
luci-app-eventcat: add package.

### PR DESCRIPTION
**Pull request by mips171**
Eventcat is like Watchcat but written in Lua and can react to interface up/down events. Depends on https://github.com/openwrt/packages/pull/25088

Screenshot 2024-10-06 at 21 02 53

- [X] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [X] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [X] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [X] Incremented :up: any `PKG_VERSION` in the Makefile
- [X] Tested on: (architecture, openwrt version, browser) :white_check_mark:
- [X] \( Preferred ) Screenshot or mp4 of changes:
- [X] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo

### CODE REVIEW

**Comment by systemcrash** [comment]
So how does this materially differ from watchcat? It’s unlikely that any new lua additions will be accepted. Ucode seems to be the way forward.

**Comment by mips171** [comment]
>So how does this materially differ from watchcat?
Less code and easier to maintain. Due to quirks of shell's language, I had a lot of grief extending the original watchcat and would rather have an option done in a "real" programming language.

>Ucode seems to be the way forward.
That's unfortunate. I'm not interested in learning a DSL so might have to close this one. Whats the real problem that Ucode solves that couldn't have been solved with a library or improvements to the ubus interface? Making a language is really cool, but maintaining a language for the long term probably isn't a commitment to make lightly.

**Comment by mips171** [comment]
JS isn't exactly a language implementation that is known for being small, clean and consistent.  If going for a DSL I'd argue for at least mimicking a better language. Good luck have fun, I'm out.

**Comment by mips171** [comment]
Closing because it depends on Lua, which I thought was included in the base installation.

**Comment by systemcrash** [comment]
Oh, lua is included in base installs, but the idea of new apps and functionality is to avoid using any more lua (and move away from it entirely).

**Pull request closed without merging**
