### PR TITLE
luci-mod-admin-full: add factory reset for ubi partions

### PR DESCRIPTION
**Pull request by feckert**
- For ubi partitions there is no posibility to reset
  the system to factory config (factory reset)
- checking if an mtd ubi is available shows the factory reset button
- If button is pressed a jffs2reset with an reboot is performed
- Tested on an lantiq xrx200

- add Sleep before uhttpd stop, to deliver http content

Signed-off-by: Florian Eckert <Eckert.Florian@googlemail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Can you try to unify the code paths? The grep can likely check both variants with a `grep -E '"rootfs_data"|"ubi"' /proc/mtd` and I suppose jffs2reset applies to the JFFS2 case as well.

**Comment by feckert** [comment]
I only have an xrx200 and an geode running with the factory reset possibility.
So I only can test this.

Maybe it es better to make a switch case statement to check which reset we can do and start the desired factory reset. This would make the code understandable?

**Comment by hnyman** [comment]
I tested Jow's idea and below is my patch for the 15.05 branch which this PR is about.
(new functionality should be added to trunk first)

jffs2reset is the normal reset command also for squashfs+jffs2 combi, so if it works also for ubi. let's use it for both.

This works in 15.05.1 with a traditional squashfs + jffs2 combination.
Please test that it works with ubi.
```
--- /usr/lib/lua/luci/controller/admin/system.lua
+++ /usr/lib/lua/luci/controller/admin/system.lua
@@ -171,7 +171,7 @@
 	local fs  = require "nixio.fs"
 
 	local upgrade_avail = fs.access("/lib/upgrade/platform.sh")
-	local reset_avail   = os.execute([[grep '"rootfs_data"' /proc/mtd >/dev/null 2>&1]]) == 0
+	local reset_avail   = os.execute([[grep -E '"rootfs_data"|"ubi"' /proc/mtd >/dev/null 2>&1]]) == 0
 
 	local restore_cmd = "tar -xzC/ >/dev/null 2>&1"
 	local backup_cmd  = "sysupgrade --create-backup - 2>/dev/null"
@@ -287,7 +287,7 @@
 			msg   = luci.i18n.translate("The system is erasing the configuration partition now and will reboot itself when finished."),
 			addr  = "192.168.1.1"
 		})
-		fork_exec("killall dropbear uhttpd; sleep 1; mtd -r erase rootfs_data")
+		fork_exec("sleep 1; killall dropbear uhttpd; sleep 1; jffs2reset -y && reboot")
 	else
 		--
 		-- Overview
```

**Comment by hnyman** [comment]
I created also the patch for trunk
```
--- a/modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
+++ b/modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
@@ -190,7 +190,7 @@ local function supports_sysupgrade()
 end
 
 local function supports_reset()
-	return (os.execute([[grep -sq '"rootfs_data"' /proc/mtd]]) == 0)
+	return (os.execute([[grep -sqE '"rootfs_data"|"ubi"' /proc/mtd]]) == 0)
 end
 
 local function storage_size()
@@ -351,7 +351,7 @@ function action_reset()
 			addr  = "192.168.1.1"
 		})
 
-		fork_exec("killall dropbear uhttpd; sleep 1; mtd -r erase rootfs_data")
+		fork_exec("sleep 1; killall dropbear uhttpd; sleep 1; jffs2reset -y && reboot")
 		return
 	end
 
```
I have tested both CC15.05.1 and trunk versions in squashfs+jffs2 combo. It would be great to get confirmation that they work on ubi (I guess ubi+jffs2 ????).

**Comment by feckert** [comment]
Hello

I have tested it and it works with ubi.

Kind regards

Flo
Am 23.03.2016 3:15 nachm. schrieb "Hannu Nyman" <notifications@github.com>:

**Comment by hnyman** [comment]
Great.
I will then push my patch to trunk, and if no hiccups materialize, I will later push to to for-15.05

**Pull request closed without merging**
