### PR TITLE
luci-i18n-base: fix postinst script run failed

### LINKED ISSUE #7070: [bug report]an error is reported when installing the luci-i18n language pack
1. go to: Software
2. install luci-i18n-base-zh-cn

## Reason speculation
OpenWrt 23.05.3 changed postinst logic (https://lists.openwrt.org/pipermail/openwrt-devel/2023-November/041878.html)
This change causes /etc/uci-defaults/luci-i18n-base-zh-cn to be deleted before the postinst script is executed, causing an error to be reported when the postinst script is executed
postinst script reported
 ```//usr/lib/opkg/info/luci-i18n-base-zh-cn.postinst: .: line 2: can't open '/etc/uci-defaults/luci-i18n-base-zh-cn': No such file or directory```

image

## How to fix it
Check if the file exists before deleting it
(https://github.com/openwrt/luci/blob/master/luci.mk) line 344, Determine whether the file exists

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.3'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_TAINTS=''
```

### PR DESCRIPTION
**Pull request by unknown-o**
In OpenWRT 23.05.3, the package installation logic was changed, resulting in the uci-default/luci-i18n-base file being deleted in advance, resulting in an error during installation

Closes #7070

- [x] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [x] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [x] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [x] Tested on: (x86_64, openwrt 23.05.3, Chrome) :white_check_mark:
- [ ] \( Preferred ) Mention: @ the original code author for feedback
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [x] \( Optional ) Closes: e.g. openwrt/luci#issue-number
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [x] Description: (describe the changes proposed in this PR)

### CODE REVIEW

**Comment by hnyman** [comment]
@jow-   @unknown-o 

@unknown-o  :  You talk about fixing 23.05.3 in the commit title, but the PR tries to merge this into the development master branch. The change should first go into master and then later backported into 23.05. The reference to 23.05 should be dropped from commit.

Although the commit is wrong on that detail, you actually brought a real (different) issue into highlight:

Relevant commit that moved the postinst vs. uci-defaults run order, moving the LuCI postinst script to be run later:
* OpenWrt main/master: https://github.com/openwrt/openwrt/commit/b799dd3c705dfd95745cdd94b13d1cd2ad2367a6
* 23:05: https://github.com/openwrt/openwrt/commit/6b7c4739c407588865aaa0d6868cf6bfe216a987

@jow- 
Do we currently need the separate LuCI postinst that just runs the uci-defaults ?

OpenWrt master has since 2016 has run the uci defaults also in run-time installations: 
https://github.com/openwrt/openwrt/commit/9b9c78e071469313566473984fb79f54c1881c10

LuCI's current postinst code dates from earlier time, from 2015:
https://github.com/openwrt/luci/commit/1bb4822dca6113f73e3bc89e2acf15935e6f8e92

To me it looks like the separate uci-defaults handling in postinst in LuCI has been unnecessary since 2016.
That would mean that the whole postinst could be deleted.

https://github.com/openwrt/luci/blob/master/luci.mk#L344-L349

Should I just remove it?

**Comment by unknown-o** [comment]
> @jow- @unknown-o
> 
> @unknown-o : You talk about fixing 23.05.3 in the commit title, but the PR tries to merge this into the development master branch. The change should first go into master and then later backported into 23.05. The reference to 23.05 should be dropped from commit.
> 
> Although the commit is wrong on that detail, you actually brought a real (different) issue into highlight:
> 
> Relevant commit that moved the postinst vs. uci-defaults run order, moving the LuCI postinst script to be run later:
> 
> * OpenWrt main/master: [openwrt/openwrt@b799dd3](https://github.com/openwrt/openwrt/commit/b799dd3c705dfd95745cdd94b13d1cd2ad2367a6)
> * 23:05: [openwrt/openwrt@6b7c473](https://github.com/openwrt/openwrt/commit/6b7c4739c407588865aaa0d6868cf6bfe216a987)
> 
> @jow- Do we currently need the separate LuCI postinst that just runs the uci-defaults ?
> 
> OpenWrt master has since 2016 has run the uci defaults also in run-time installations: [openwrt/openwrt@9b9c78e](https://github.com/openwrt/openwrt/commit/9b9c78e071469313566473984fb79f54c1881c10)
> 
> LuCI's current postinst code dates from earlier time, from 2015: [1bb4822](https://github.com/openwrt/luci/commit/1bb4822dca6113f73e3bc89e2acf15935e6f8e92)
> 
> To me it looks like the separate uci-defaults handling in postinst in LuCI has been unnecessary since 2016. That would mean that the whole postinst could be deleted.
> 
> https://github.com/openwrt/luci/blob/master/luci.mk#L344-L349
> 
> Should I just remove it?

I think you can remove this script.
Although this error does not seem to affect the installation of the package, it is still a bit uncomfortable to see the error when installing the package

**Comment by jow-** [comment]
@hnyman - I think that postinstall logic can be dropped. Are you able to take care of it?

**Comment by hnyman** [comment]
I will remove it.

**Comment by unknown-o** [comment]
> I will remove it.

Should I close this PR and wait for your modify?

**Comment by hnyman** [comment]
You can just leave this open as a reminder for me. I will close it.

**Comment by unknown-o** [comment]
> You can just leave this open as a reminder for me. I will close it.

OK, thanks

**Comment by hnyman** [comment]
Fixed with fb776a6645

**Pull request closed without merging**
