### PR TITLE
luci-mod-system: add password strength info

### PR DESCRIPTION
**Pull request by feckert**
Add a password strength hint.

### CODE REVIEW

**Comment by cshoredaniel** [comment]
I like the password strength check idea - not sure how other projects implement, but I'm of two minds about whether I think this regex based approach helps or is too simplistic to provide genuinely useful feedback.

**Comment by cshoredaniel** [comment]
Also could this go in luci.util or such?  It'd be good to share this with luci-app-radicale2 for example (in progress) which has a password entry thingy.

**Comment by feckert** [comment]
A lot of them use external javascript libraries. I think this is not applicable for LuCI. Keep it simple.


> Also could this go in luci.util or such? It'd be good to share this with luci-app-radicale2 for example (in progress) which has a password entry thingy.

Yes I could to this.

**Comment by cshoredaniel** [comment]
I wonder if it could be called 'basic strength estimate' or some such to indicate that it's a fairly unsophisticated measure of strength.  Otherwise I like it.

**Comment by yifu1128** [comment]
你们来自加拿大吗？    我来自福建省

**Comment by feckert** [comment]
@yifu1128 ??
@jow- your assessment

**Comment by cshoredaniel** [comment]
@feckert You might be interested in looking at https://github.com/openwrt/luci/pull/2463 where I (ab)use the datatype validation system to do password + confirm logic.  Depending on what @jow- thinks of that approach it might be a way to do this as well.

**Comment by feckert** [comment]
@jow any comments from your side about this change?

**Comment by jow-** [comment]
NO, feel free to merge.

**Pull request merged**
