### PR TITLE
luci-app-statistics: support ReportNumCPU

### PR DESCRIPTION
**Pull request by mrjoel**
Signed-off-by: Joel Johnson <mrjoel@lixil.net>

### CODE REVIEW

**Comment by hnyman** [comment]
Number of CPUs should be static in a router, so I wonder about the usefulness of this (especially in the LuCI stats)

**Comment by mrjoel** [comment]
> Number of CPUs should be static in a router, so I wonder about the usefulness of this (especially in the LuCI stats)

Sure, it's definitely not interesting in isolation of a single router. It does end up being useful for me in a few different contexts though, including a) single collectd data repo maintained across multiple installs/configurations of virtual machines, b) similarly, shared data history across single "role" of router positions with circulating underlying hardware, and c) sending network reporting to a central log server in order to have a reminder and comparison basis for statistics across multiple hosts.

**Comment by systemcrash** [comment]
I see no harm in having this included. @jow- @hnyman ?

**Comment by systemcrash** [comment]
@mrjoel Could you rebase on current master please?

**Comment by systemcrash** [comment]
In my tests, I could not get this to do anything. Possibly as a result of what plugins area available in cpu.so. After install, the CPU graph is stuck at loading. Restarting collectd didn't seem to fix it, so it's a problem stuck in-between collectd and the GUI. 

Can you get this to work on current master @mrjoel ?

**Pull request closed without merging**
