### PR TITLE
[18.06] luci-app-https_dns_proxy: better handling of ports, update dhcp config

### PR DESCRIPTION
**Pull request by stangri**
Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by feckert** [comment]
I think the Makefile is missing.
And this is a new package / app in the LuCI feed.
@jow I thought only bug fixes should go into a stable branch?

**Comment by stangri** [comment]
@feckert you're right, the Makefile is missing. Should I resubmit (if the decision has been made to backport it to 18.06) or should I wait for @jow's decision on this?

**Comment by feckert** [comment]
I think we should do a cherry-pick from master to 18.06 because this is more traceable and we should wait on @jow´s decision if we should even do this. It is up to you to close this pullrequest or let them open for reminding.

**Comment by stangri** [comment]
Closing this, it's missing Makefile anyways. May reopen with blessing from @jow after these changes get merged to master/19.07.

**Pull request closed without merging**
