### PR TITLE
[URFC] luci-app-statistics: Add support for encrypted networking

### PR DESCRIPTION
**Pull request by dfc-d**
Add configuration for encrypted networking, when enabled.

Signed-off-by: Daniel Dickinson openwrt@daniel.thecshore.com

Note this has only been verified to not break the interface and hasn't been tested for actual configuration generation and is more a request for comments.

### CODE REVIEW

**Comment by hnyman** [comment]
This contains also the same library checking commit, so if/when you fix that 0/1 to false/true separately, you should remove the conflicting commit from this PR.

**Comment by dfc-d** [comment]
Yes, will do.

**Comment by dfc-d** [comment]
Marking as Untested Request For Comments as it was primarily for soliciting comments about the approach and still needs to be tested.

**Comment by dfc-d** [comment]
too far on back-burner and no one else interested

**Pull request closed without merging**
