### PR TITLE
Luci App Access Control

### PR DESCRIPTION
**Pull request by augustgermar**
Allows scheduled access based on mac address by time of day in the luci app.
Tested in openwrt 15.05 and trunk.

### CODE REVIEW

**Comment by hnyman** [comment]
Some technical comments:
* The PR seems to contain duplicates for three files. The same files are in two locations, right? I would guess that one location is correct and the other location is an unnecessary copy. E.g. also the config file is included two two times.
* You should squash the two commits into one
* The commit(s) need to be properly signed-off-by. Especially important, as the included copyright notice in the files is apparently not from you. Read https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md and https://dev.openwrt.org/wiki/SubmittingPatches#a10.Signyourwork

Ps. The original seems to be from https://github.com/k-szuster/luci-access-control

**Comment by augustgermar** [comment]
Thanks for your input. This is a fork of a previous version yes. I kept all copyright notices to the original author. The main difference being that the original required manual editing of the file 
 /openwrt/feeds/luci/contrib/package/luci-addons/Makefile

So I updated it so that it would install like any other package. 

Also I tested with DD and Trunk, the old version was for BB and CC. 

I see the error with the duplicate files , there is a folder for files to add this package as an overlay, this was for testing only. Good catch. I will delete them. 

I will also merge the commits into one. 

Should I close this pull request, then make the changes and re-submit, or should I continue to make changes under this PR?

Thank you!

**Comment by hnyman** [comment]
If you have the commits for this PR in a separate feature branch (as suggested in CONTRIBUTING.md ), you can simply edit/squash/rebase the commit in your local repo and then use "git push -f" to overwrite the original commits in the PR.

But also creating a brand new PR (and closing this one) is ok.

**Comment by augustgermar** [comment]
Cool thanks for the help. I am working on it right now. I will close this PR and submit a new one with (hopefully) all the proper changes.

**Pull request closed without merging**
