### PR TITLE
luci-theme-material: improve view

### PR DESCRIPTION
**Pull request by Ansuel**
This color the legend row of the index table, fix the progressbar that doesn't fill correctly and change color of the inner value of the bar. Fix some problem button with stock color. Improve cbi-select interface.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Thanks, I am in the middle of some larger reworks atm, will defer this PR until that is done.

**Comment by Ansuel** [comment]
will rebase with the changes when you are done.

**Comment by jow-** [comment]
Why are the changes to the template markup needed?

**Comment by Ansuel** [comment]
The first change just change the color to white if the progressbar is more than 65 % 

The second solve a problem with margin and the progress bar that with some screen goes offset...

cattura

**Comment by Ansuel** [comment]
Fixed other little things, can't understand the change of the button name in the interface overview page think we should add some id there and at the login page so that i can remove border only from that section.

**Comment by jow-** [comment]
Closing this as it does not apply anymore.

**Pull request closed without merging**
