### PR TITLE
luci_base: Update zh_CN base.po, translate fix

### PR DESCRIPTION
**Pull request by Cye3s**
Line 3021:
msgid "Switch protocol"
sould be:
msgstr "切换协议"

This "Switch protocol" means "Change one protocol to another protocol", not "protocol of switch deivce"(current version)

### CODE REVIEW

**Comment by yousong** [comment]
LGTM

**Comment by yousong** [comment]
Please update also the zh-tw translation and change the commit subject accordingly.

**Comment by Cye3s** [comment]
Sorry, zh_TW is different from zh_CN, the words used to describe something can still differ between cultures, so I can not do that.

**Comment by yousong** [comment]
In this specific case, it's doable.

```
➜  ~/git-repo/lede-project/luci git:(master) ag -A1 'switch protocol' modules/luci-base/po/zh-tw/base.po
2546:msgid "Really switch protocol?"
2547-msgstr "確定要更換協定?"
3012:msgid "Switch protocol"
3013-msgstr "交換器協定"
➜  ~/git-repo/lede-project/luci git:(master) ag -A1 'switch protocol' modules/luci-base/po/zh-cn/base.po
2549:msgid "Really switch protocol?"
2550-msgstr "确定要切换协议？"
3021:msgid "Switch protocol"
3022-msgstr "交换机协议"
```

**Comment by kuoruan** [comment]
我刚刚 pull request 了一条，没注意到这里 https://github.com/openwrt/luci/pull/1239，我看看能不能一起加上

**Comment by Cye3s** [comment]
@kuoruan 嗯，本来想只提个issue，后来想想还是开个pull更快，如果你加上了，我这个就关闭吧

**Pull request merged**
