### PR TITLE
[RFC] luci-app-opkg: add ipk upload feature

### PR DESCRIPTION
**Pull request by ysc3839**
Sometime people just want to upload and install a package using luci, however currently it's impossible without other tools (scp, WinSCP).
This pull request add this feature.

There are some minor issues I request for comments:
1. The confirm dialog reuses `handleManualInstall`, and shows `/tmp/upload.ipk` as filename. Should I make it shows it's real name?
image
2. Should confirm dialog shows checksums and size info?

@jow-

### CODE REVIEW

**Comment by jow-** [comment]
Showing the real (before upload) name would be better UX I think. I see you reused the upload code from flash.js - I think instead of copying it, we should move it to ui.js and use it from there.

**Comment by ysc3839** [comment]
Now it looks like this.
image

**Comment by ysc3839** [comment]
There's another issue, the uploaded file is not deleted after install. `handleOpkg` doesn't provide a "after install" callback.

**Comment by jow-** [comment]
The not deleted temp file is acceptable for now, but can you factor out the upload code into `ui.js` ? The rest looks fine to me

**Comment by ysc3839** [comment]
Ping @jow-

**Comment by jow-** [comment]
Merged with slight changes in c360cdd1f0b03ec208eaf1f8f85893aec50c7555

**Pull request closed without merging**
