### PR TITLE
luci-mod-admin-full: fix broken char translation of " and '

### PR DESCRIPTION
**Pull request by Ansuel**
Currently if a translated string contains " or ' they get replaced with &#34. We use the translate function to translate the string correctly and fix this problem.

@jow- think a refresh of translation is needed and also should be added \ in front of any ' or it will cause error

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Nack. Such issues need to be solved on the template level on a case-by case basis, not in the translations itself.

**Comment by Ansuel** [comment]
@jow- so tell me if i'm wrong...

It's not a display problem, the paraser actually translate " to &#34 and not the real char?

**Comment by jow-** [comment]
Your fix is almsot correct but the escaping of special characters should not happen in translations as these are context-free. The escaping needs to happen in code using these strings.

**Comment by jow-** [comment]
I added the two translations in e7866c7dccd72943bd985de32031002f37f9a777

**Pull request closed without merging**
