### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/openwrt/luci/) for OpenWrt/LuCI/modules/luci-base.

### CODE REVIEW

**Comment by feckert** [comment]
@hnyman this pull request from weblate looks really confused!
Is this a UTF8 problem with the boxes?
Or is it OK?

**Comment by hnyman** [comment]
> this pull request from weblate looks really confused!
> Is this a UTF8 problem with the boxes?
> Or is it OK?

????

Looks quite ok on Firefox on my desktop PC. Similar lettering as in the previous Marathi translations...

kuva

Firefox 68 on Windows 10: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by feckert** [comment]
@hnyman thanks for your comment.
On my system it looks like this.
Screenshot_2020-07-27 Translations update from Weblate by weblate · Pull Request #4292 · openwrt luci

**Comment by jow-** [comment]
@feckert - you lack extended unicode fonts to render indian scripts. On my Debian system, the marathi glyphs are rendered by `fonts-noto-mono` (Noto Sans Devanagari)

**Pull request merged**
