### PR TITLE
[RFC, WIP] luci-theme-bootstrap4: add new theme

### PR DESCRIPTION
**Pull request by ysc3839**
As discussed in #3644. I'm making a new Bootstrap 4 theme.
This theme contains two parts, one is in luci, another is in my [fork](https://github.com/ysc3839/bootstrap) of bootstrap.
The part in luci is based on current bootstrap theme. In order to show changes in git diff, I modify original code directly, and I will make a copy after it's done.
The part in my fork of bootstrap is based on bootstrap v4.4.1, you can see changes [here](https://github.com/twbs/bootstrap/compare/v4.4.1...ysc3839:luci).
I'm not familiar with Web front-end development. In order to simplify the work, I mainly use Sass' `@extend` to make it works with luci. However this will increase the size of final css. If you have any idea please tell me.

Currently it looks like this:
image

Ping @jow- and @aparcar

### CODE REVIEW

**Comment by aparcar** [comment]
Hi, thank you very much for looking into this! I think even the early stage looks already pretty good!

From my understanding Bootstrap changed the names of various `classes` which you *map* with the scss files, right? Wouldn't a treewide replace of such classes also do the trick?

I think part of the legacy nature of the current cascade.css its differ so much from upstream....

**Comment by jow-** [comment]
> Wouldn't a treewide replace of such classes also do the trick?

Not really, it would just push the burden of matching the markup to other themes. Keep in mind that there is not only bootstrap based themes.

**Comment by ysc3839** [comment]
> Wouldn't a treewide replace of such classes also do the trick?
No, for example, `cbi-tabmenu` class maps to navs with tab `nav nav-tabs` in bootstrap.

**Comment by aparcar** [comment]
> Not really, it would just push the burden of matching the markup to other themes. Keep in mind that there is not only bootstrap based themes.

Right, but if we also change their CSS files? I understand this is a bit of a mess once done future migration should be much simpler. I'd even claim that much more themes appear because boostrap CSS is so much more common.

>  No, for example, cbi-tabmenu class maps to navs with tab nav nav-tabs in bootstrap.

If you provide a map of such replacements I'll do the boring work of replace it within the code :)

**Comment by ysc3839** [comment]
@aparcar I think you are talking about replace in bootstrap source.

**Comment by aparcar** [comment]
> @aparcar I think you are talking about replace in bootstrap source.

No, replacing the LuCI bootstrap theme CSS and the other 3s. Keep the `boostrap.min.css` untouched.

**Comment by jow-** [comment]
I don't want to peg LuCI markup to bootstrap though, it should remain agnostic. Besides bootstrap lacks a lot of component markup which we need so custom CSS is required anyway.

**Comment by ysc3839** [comment]
> No, replacing the LuCI bootstrap theme CSS and the other 3s. Keep the `boostrap.min.css` untouched.

But other theme may use a different class name, this will result in modifying

**Comment by aparcar** [comment]
> But other theme may use a different class name, this will result in modifying

Yes, so edit these other themes but not the original bootstrap file.

> Besides bootstrap lacks a lot of component markup which we need so custom CSS is required anyway.

Can you please elaborate a bit on this. What [compontents](https://getbootstrap.com/docs/4.4/components/alerts/) are missing in bootstrap?

**Comment by ysc3839** [comment]
> Yes, so edit these other themes but not the original bootstrap file.

It's unfair to maintainers of other theme.

**Comment by jow-** [comment]
> Can you please elaborate a bit on this. What compontents are missing in bootstrap?

- Comboboxes
- Rich dropdowns
- Combo buttons
- Rich tooltips

Another problem is bootstrap's reliance on JavaScript to implement more complex controls.

**Comment by jow-** [comment]
One further thought about unmodified bootstrap: it contains extreme amounts of whitespace, we would need to modify that as well.

**Comment by aparcar** [comment]
> It's unfair to maintainers of other theme.

I think this is an misunderstanding, I would replace things like `cbi-button` treewide to `btn` so no extra workload appear for the maintainers. As the class would be changed in their CSS files too, it'd still work.

> Another problem is bootstrap's reliance on JavaScript to implement more complex controls.

Thanks for the quick response. I wonder if these elements are trivial to implement in JavaScript and could be an additional layer of CSS/JS on top of Bootstrap. Also if using Bootstrap JavaScript code would safe LuCis JS at other points.

Please don't misunderstand my comments as Bootstrap fandom, I barely used it before. I'm just fan of lowering the obstacles for new people to join in. Maybe it's a dead end. 

After all Bootstrap seems to break compatibility between versions anyway [3](https://getbootstrap.com/docs/3.4/migration/) & [4](https://getbootstrap.com/docs/4.4/migration/) 

> One further thought about unmodified bootstrap: it contains extreme amounts of whitespace, we would need to modify that as well.

The `bootstrap.min.css` file is *minimized*

**Comment by ysc3839** [comment]
> I would replace things like cbi-button treewide to btn so no extra workload appear for the maintainers.

But maybe there are some complex components.

**Comment by jow-** [comment]
> Also if using Bootstrap JavaScript code would safe LuCis JS at other points.

From a quick glance, there is little overlap.

> The bootstrap.min.css file is minimized

I am talking about visual space as in margins and paddings, not white space in the CSS file.

**Comment by ysc3839** [comment]
@jow- We need a luci app which contains all luci components. It can be used for theme development and testing, and demonstrate what components are available and how to use them.

**Comment by ysc3839** [comment]
It's difficult for me to make the "Save & Apply" behave normal, maybe I have to change it's structure to make it work.
Current screenshot:
image

**Comment by ysc3839** [comment]
Moved `#tabmenu` to top and use a new style:
image

Added border shadow to `.cbi-section`:
image

**Comment by ysc3839** [comment]
Finished `#topmenu` and cbi section.
image
image

**Comment by ysc3839** [comment]
@jow- Can we use standard table tags instead of div with .table class? Because doing this I don't need to write css for table classes.
image
image

**Comment by messismore** [comment]
> One further thought about unmodified bootstrap: it contains extreme amounts of whitespace, we would need to modify that as well.

Just to chime in on this. I just updated 17.x → 20.x and find the denser UI harder to parse and navigate. The more generous amounts of white space in previous releases helped to easily discern visual elements and aided intelligibility and navigation.

Busy Luci

17.x on the left, 20.x on the right.  While the individual differences seem negligible, they do add up. Thus white space can be considered an accessibility feature, especially for users that do not know every nook and cranny of the UI.

**Comment by aparcar** [comment]
@messismore This should be possible later on. I think for now it is mostly about making the current JavaScript framework work together with Bootstrap 4.

@ysc3839 Can you please share your modified bootstrap.css and add it to the current PR?

**Comment by jow-** [comment]
> @jow- Can we use standard table tags instead of div with .table class? 

That is not doable and would require tree-wide changes to a lot of components. For now just add the following lines to your CSS:

```
.table { display: table; }
.tr { display: table-row; }
.th, .td { display: table-cell; }
```

**Comment by ysc3839** [comment]
@aparcar Updated.

**Comment by ysc3839** [comment]
Close this pr since it requires a lot of work, and I have no time doing this.
I'm looking for a CSS utility framework to build our own theme, instead of out-of-box CSS framework like bootstrap.
Recently I found [Tailwind CSS](https://tailwindcss.com/) which may suit for making a theme.

**Pull request closed without merging**
