### PR TITLE
[19.07] luci-app-https_dns_proxy: better handling of ports, update dhcp config

### PR DESCRIPTION
**Pull request by stangri**
Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by feckert** [comment]
I think we should add https://github.com/openwrt/luci/pull/2890 into master first and then cherry-pick this with the option -x for reverence into to this stable branch -> openwrt-19.07

**Comment by stangri** [comment]
@feckert I was previously advised to submit 3 different PRs (master, 18.06, 19.07) for the bugfix for a different package. I would appreciate some guidance in this regard for the future PRs.

**Comment by feckert** [comment]
I think there is no guidance for this. There are advantage and disadvantage.

**Comment by hnyman** [comment]
I feel that having a separate PR for each branch from the package maintainer makes it easier for commit access holders.

The PR might contain a simple cherry-pick commit, but in some cases there may be branch-specific modifications, so that a straight cherry-pick does not work.

**Comment by feckert** [comment]
> I feel that having a separate PR for each branch from the package maintainer makes it easier for commit access holders.

Agree

> The PR might contain a simple cherry-pick commit,

Exactly so we could track the change if this is possible master -> stable

**Comment by jow-** [comment]
Cherry-picked from 85989079f instead. Thanks!

**Pull request closed without merging**
