### PR TITLE
luci-proto-ipv6: fix aiccu requiretls

### PR DESCRIPTION
**Pull request by poranje**
The aiccu requiretls option's default value was incorrect

### CODE REVIEW

**Comment by jow-** [comment]
Hm, this change effectively changes the property to a nil value as the "enabled" variable is not defined.
So this option defaults to off in uci?

**Comment by hnyman** [comment]
To my knowledge the generic default for requiretls option is "false".
https://www.sixxs.net/wiki/Aiccu/Installation#Configuration

The Openwrt aiccu package does not supply a default config, so there is no separate Openwrt default.

After this pull request was written, there has been a commit on 2 March 15 that changed the option handling in the aiccu package: https://github.com/openwrt/packages/commit/5f1006cb205f37a2027cd23e297fe8b5c9843715

The current aiccu option parser seems to expect 0/1 from uci, and will write "true" into aiccu's config file if uci option is 1. There is no default value definition, so I think that "false" is still the implicated default.
https://github.com/openwrt/packages/blob/master/ipv6/aiccu/files/aiccu.sh#L39
	[ "$requiretls" == 1 ] && echo "requiretls true" >> "$CFGFILE"

Luci seems to think that true/enabled is the default and that creates a conflict:
If a new aiccu interface is created in Luci, the GUI shows requiretls enabled, but no such value is written to /etc/config/network or is generated to aiccu's own config file. Ao aiccu will still think that requiretls=false.

Based on jow's response I think that the proposed patch has faulty syntax, although it will probably "fix" things if default gets set to false due to it.

**Comment by poranje** [comment]
Thanks for your investigations.
I’ll will change the pull request accordingly.

s.y.
Paul

**Comment by hnyman** [comment]
I applied the patch manually to one of my routers, and now the options in Luci are correctly reflected in /etc/config/aiccu

**Comment by jow-** [comment]
thanks for testing.

**Pull request merged**
