### PR TITLE
luci-app-mwan3: Update default values for down, up, timeout and interval on interfaces

### PR DESCRIPTION
**Pull request by jamesmacwhite**
@feckert LuCI currently sets the following defaults if they are not directly set on interface configurations.

 Option | LuCI default  | mwan3track default  |
| :------------- |-------------| -----|
| `up`  | `3` | `5` |
| `down`  | `3` |  `5` |
| `interval` | `5` | `10` |
| `timeout` | `2` | `4` |

These are different to the defaults specified by mwan3track, so this updates them to match.

### CODE REVIEW

**Comment by jamesmacwhite** [comment]
@feckert Did you happen to see this one, fixes some defaults that are currently mismatched with mwan3track.

**Comment by feckert** [comment]
@jamesmacwhite We can merge this independently of the[ P/R](https://github.com/openwrt/packages/pull/13169).
Could you please update the header prefix of you commits? So we have `luci-app-mwan3: xxxx`?

**Comment by jamesmacwhite** [comment]
@feckert Thanks. I've amended the commits to have `luc-app-mwan3:` on each commit message.

**Comment by feckert** [comment]
:+1: thanks

**Pull request merged**
