### PR TITLE
luci-base: apply fix for admin.lua

### PR DESCRIPTION
**Pull request by dibdot**
* fix for #2048

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by dibdot** [comment]
@jow OK to merge?

**Comment by jow-** [comment]
Hm, no not sure. I think it will cause SSH server changes to bypass the rollback mechanism. Will close this for now and come up with an alternative solution later.

**Comment by jow-** [comment]
Seems it does the job indeed - will merge it.

**Comment by jow-** [comment]
Merged with 32ee1873a - thanks!

**Comment by dibdot** [comment]
Already forget about this one - thanks for merging!

**Pull request closed without merging**
