### PR TITLE
luci-app-openvpn : Updates "user", "group", "proto" and "mssfix" params conds and defaults

### PR DESCRIPTION
**Pull request by pduveau**
From Philippe Duveau

"proto" parameter is available in client or server mode in the network section.
"mssfix" default value is setted to openvpn.org default value
"user" and "group" are available in service section with secured default values (nobody, nogroup)

Signed-off-by: Philippe Duveau <pduvax@gmail.com>

---

The "proto" parameter is mandatory for other parameters of server or client modes (topology, mssfix...) but the condition was to restrict it to client mode only.

### CODE REVIEW

**Comment by feckert** [comment]
Please prefix your commit with `luci-app-openvpn:` and also add a `Signed-off-by:` to your commit

**Comment by Neustradamus** [comment]
@pduveau: Have you seen @feckert comment?

**Comment by Neustradamus** [comment]
@pduveau: Why have you closed it?

**Comment by pduveau** [comment]
Hello,
As requested, I prefixed the commit and added the Signed-off-by (or so I thought). As I didn't see any progress, I closed the request.

**Comment by Neustradamus** [comment]
@feckert: Can you look the last @pduveau comment?

**Comment by feckert** [comment]
@pduveau It was not the commit that was prefixed but the pullrequest! That is a difference. The commit gets merged into to repository not the pullrequest . So could you please change the commit to:
```
luci-app-openvpn : Updates user, group, proto and mssfix params and defaults

- proto parameter is available in client or server mode in the network section.
- mssfix default value is setted to openvpn.org default value
- user/group are available in service section with secured default values (nobody, nogroup)
```

**Pull request closed without merging**
