### PR TITLE
Fix and update italian translation

### PR DESCRIPTION
**Pull request by Ansuel**
I have fixed some capital letter and add some translation

### CODE REVIEW

**Comment by jow-** [comment]
LGTM, merged. Thanks @Ansuel !

**Comment by hnyman** [comment]
I wonder about the correctness of this PR. 

It seems to me that some additions add duplicates to existing strings. E.g. "Global network options" is a new duplicate item for the same item earlier in the file.

Some of the strings seem to be related to firewall instead of luci-base, so they are in the wrong file. E.g. "Forward to":
```
perus@ub16041:/Openwrt/github/luci$ grep -r "Forward to" .
./modules/luci-base/po/it/base.po:msgid "Forward to"
./applications/luci-app-firewall/luasrc/model/cbi/firewall/forwards.lua:dest = s:option(DummyValue, "dest", translate("Forward to"))
./applications/luci-app-firewall/po/de/firewall.po:msgid "Forward to"
./applications/luci-app-firewall/po/sk/firewall.po:msgid "Forward to"
./applications/luci-app-firewall/po/sk/firewall.po~:msgid "Forward to"
./applications/luci-app-firewall/po/ms/firewall.po:msgid "Forward to"
...
./applications/luci-app-firewall/po/templates/firewall.pot:msgid "Forward to"
...
./applications/luci-app-firewall/po/it/firewall.po:msgid "Forward to"
```

Additionally, after applying this commit, the script ./build/i18n-sync.sh seems to jump over luci-base/po/it/base.po and leaves that un-updated and produces this error:
```
Updating ./modules/luci-base/po/it/base.po       ./modules/luci-base/po/it/base.po:2135: duplicate message definition...
./modules/luci-base/po/it/base.po:1486: ...this is the location of the first definition
./modules/luci-base/po/it/base.po:3656: duplicate message definition...
./modules/luci-base/po/it/base.po:1237: ...this is the location of the first definition
msgmerge: found 2 fatal errors
```

**Comment by jow-** [comment]
Thanks, @hnyman -  reverted the change.

**Comment by hnyman** [comment]
Thanks jow.

@Ansuel 
Please re-do your additions, but to the correct files. You should not create new msgid items as all needed items are already in the files. Search for the existing items, probably mainly in luci-base, luci-mod-admin-full, luci-app-firewall etc.

**Pull request merged**
