### PR TITLE
luci-app-mwan3: refactoring continue 2

### PR DESCRIPTION
**Pull request by feckert**
This pull request continues refactoring of luci-app-mwan3:
See commit description.
@hnyman I am not sure if you like this lot commits and changes.
I also could stash the changes in one commit if you like.
I think i will need one additional pull request to finish the changes in the luci-app-mwan3 module.

### CODE REVIEW

**Comment by feckert** [comment]
@hnyman i want to add a license info on every source file. But i am not sure which license should i use? In the makefile we have "PKG_LICENSE:=GPLv2". But in the sources there are no license informations!
I could use

> -- Copyright 2014 Aedan Renner <chipdankly@gmail.com>
> -- Copyright 2018 Florian Eckert <fe@dev.tdt.de>
> -- Licensed to the public under the Apache License 2.0.

or ( because the make file mention GPLv2 i would prefer this one)

> -- Copyright 2014 Aedan Renner <chipdankly@gmail.com>
> -- Copyright 2018 Florian Eckert <fe@dev.tdt.de>
> -- Licensed to the public under the GNU General Public License v2.

What do you think?

**Comment by user7887** [comment]
Great app, great job, thank you! :)
Small detail, extra quote
bag

**Comment by hnyman** [comment]
> What do you think?

You should probably keep the license type that there already is in the Makefile.

**Comment by feckert** [comment]
@user7887 thanks
follow up pullrequest will come next week with some additional changes as you mention and the following fix.
If route is nil in ubus then luci assert is throwing.
https://github.com/openwrt/luci/blob/cf1af792d6ca285fed757fa21904f635bdbfffce/applications/luci-app-mwan3/luasrc/controller/mwan3.lua#L110-L120
same there
https://github.com/openwrt/luci/blob/cf1af792d6ca285fed757fa21904f635bdbfffce/applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua#L78-L90

**Pull request merged**
