### PR TITLE
i18n: complete pt-br translation

### PR DESCRIPTION
**Pull request by luizluca**
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

### CODE REVIEW

**Comment by luizluca** [comment]
Is this too late for lede-17.01 backport?

**Comment by chris5560** [comment]
For 17.01 you need to send your commit to "lede-17.01" branch.

**Comment by luizluca** [comment]
OK, I guess, then, translation update are OK for backport. I'll create a new PR for it.
However, this PR is for master.

**Comment by chris5560** [comment]
Thanks

**Pull request merged**
