### PR TITLE
luci-network-interfaces: Add IPv6 lifetime options

### PR DESCRIPTION
**Pull request by systemcrash**
to the bottom of interface IPv6 settings tab

### CODE REVIEW

**Comment by systemcrash** [comment]
ping @jow- @hnyman 

See [forum topic](https://forum.openwrt.org/t/ipv6-lease-time-only-work-with-12h/170085)

**Comment by hnyman** [comment]
With the experience from 504bdb2 (from you), that was fixed with b7dd10d,  I don't like the "optional" settings to have numeric default values. They may get accidentally written to the config file even if the user has not modified them (as LuCI finds a value there).  Discussion in https://forum.openwrt.org/t/ipv6-works-on-clients-with-default-config-not-with-default-config/94460

You might define "placeholder" value instead.

And you did not define "optional" for ra_useleasetime ?
Based on odhcpd sources, the default is actually "disabled", unlike this PR claims?
https://github.com/openwrt/odhcpd/blob/master/README#L135-L137

**Comment by systemcrash** [comment]
> You might define "placeholder" value instead.
> 
> And you did not define "optional" for ra_useleasetime ? Based on odhcpd sources, the default is actually "disabled", unlike this PR claims? https://github.com/openwrt/odhcpd/blob/master/README#L135-L137

Good catches - I recall the instance. I've instead added some suggestions to choose. 

Fixed.

**Comment by timur-davletshin** [comment]
Shouldn't this be backported to current 23.05 and 22.03 branches too? I see this question about DHCPv6 lease time asked several times.

**Comment by Neustradamus** [comment]
@systemcrash, @hnyman: Have you seen the @timur-davletshin comment?

**Comment by feckert** [comment]
Backported to openwrt-23.05 via https://github.com/openwrt/luci/commit/257f54cb8bcd493d9be0a45a3c316668b793e8ae

**Comment by Neustradamus** [comment]
@feckert: Thanks for 23.05! :)
About 22.03 branch, it is possible to add too?

**Comment by feckert** [comment]
@hnyman @Neustradamus With backporting this change to openwrt-22.03, I have now read through the thread in the forum again. If I have understood correctly, the option `ra_useleasetime `must be set, so that `preferred_lifetime` works. This means we need a dependency for `preferred_lifetime` to` ra_useleasetime`?
But that is not the case! Please clarify.

**Comment by systemcrash** [comment]
> Please clarify.

I thought through this carefully when I made the PR:

`ra_useleasetime` =  When set, the configured *DHCPv4* leasetime is used *both as limit* for the *preferred* and *valid lifetime* of an IPv6 prefix. 

BUT

`preferred_lifetime` = Value for the preferred lifetime for a prefix. i.e. IPv6 Prefix preferred lifetime. 

Summary: Check `ra_useleasetime` to use the DHCPv4 field `leasetime` - UNCHECK it to use the DHCPv6 `preferred_lifetime`.


In this case, this PR has revealed two mutually exclusive options.

**Comment by systemcrash** [comment]
See also [this odhcpd commit](https://git.openwrt.org/?p=project/odhcpd.git;a=commitdiff;h=3bda90079ec5574ef469e2a7804808302f17769d;hp=b75bcad7bd5fd03f64011a532b9960d78e4aac22).

**Pull request merged**
