### PR TITLE
Updated Ukrainian translation with the latest resync translation

### PR DESCRIPTION
**Pull request by YuriPet**
Signed-off-by: Yurii <yuripet@gmail.com>

### CODE REVIEW

**Comment by feckert** [comment]
Please sign your work with your real name.

**Comment by feckert** [comment]
You do not have to close this pr just update your commits and then make a git push force :-)

**Comment by YuriPet** [comment]
I work exclusively through a browser and have already deleted that online repository.
How do I change my commits?

**Comment by feckert** [comment]
> I work exclusively through a browser and have already deleted that online repository

This will not work. You should use the shell

>Why so far only the first name was enough?

I do not think so sorry. Please add your real name in the future

**Comment by YuriPet** [comment]
If I add the second name, this signature does not pass DCO verification!

Commit sha: 18ff58f, Author: Yurii, Committer: GitHub; Expected "Yurii yuripet@gmail.com", but got "Yurii Petrashko yuripet@gmail.com".

I haven't found an opportunity to change my name in my account.

**Comment by feckert** [comment]
Ok i will cherry-pick this tomorrow.
If you do not please pink me.

**Pull request closed without merging**
