### PR TITLE
luci-app-https_dns_proxy:add rubyfish.cn DOH servise in china

### PR DESCRIPTION
**Pull request by kkjoy**
luci-app-https_dns_proxy:add rubyfish.cn DOH servise in china

### CODE REVIEW

**Comment by hnyman** [comment]
@stangri

**Comment by stangri** [comment]
I don't get it, I thought I deleted the old Luci app in the last pr.

**Comment by stangri** [comment]
This should be closed, I'm not sure how this even made it thru, as the `luci-app-https_dns_proxy` package was removed when I replaced it with `luci-app-https-dns-proxy` which uses RFC8484 instead of the JSON API (like in the old package with underscores).

**Comment by kkjoy** [comment]
OK got it

**Pull request closed without merging**
