### PR TITLE
luci-proto-bonding: add protohandler configuration for channel bonding

### PR DESCRIPTION
**Pull request by he-ma**
This is a luci implementation to configure Link Aggregation (Channel Bonding) through the netifd proto handler.

The netifd proto handler is already integrated in the OpenWrt packages.

This PR is related with #3712, #3713. 
@jow-  This is a follow-up to https://github.com/openwrt/luci/pull/3720

### CODE REVIEW

**Comment by jow-** [comment]
Okay, this looks fine to me now. One final question... is the 2017 copyright intended?

**Comment by he-ma** [comment]
@jow- At first thank you very much for code reviewing.
Regarding your question for the 2017's copyright:
Well, indeed I started this module in 2017 back then done in LUA.
(https://github.com/openwrt/luci/pull/1910)

If you think this is a problem we can change it to 2020, of course.

**Comment by hamadgin2** [comment]
TDT-AG:pr/20200422-add-proto-bonding

**Comment by feckert** [comment]
@jow- I took the liberty of adjusting the copyright date of my colleague and merged this request, since everything has been reviewed by you and was pending.

**Pull request merged**
