### PR TITLE
luci-mod-status: minor fix to channel_analysis

### PR DESCRIPTION
**Pull request by Ansuel**
2 minor fixup for channel_analysis status page.
- Handle HE channel width
- Fix undefined diff in ap sort function

Fixes: #6167
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@znevna @hnyman @dhewg can you guys test this?

**Comment by hnyman** [comment]
Sorry, I can test only after some 4-5 days.

**Comment by castillofrancodamian** [comment]
@Ansuel How can it be tested?

**Comment by Ansuel** [comment]
@castillofrancodamian if you are affected... just apply the change locally on your image and clear luci cache in /tmp and your cache browser and you should be good.

**Comment by dhewg** [comment]
Thanks, confirming that both patches work!

**Comment by Ansuel** [comment]
Can you check if all the different ap are sorted?

Il Sab 24 Dic 2022, 08:20 dhewg ***@***.***> ha scritto:

**Comment by dhewg** [comment]
They're sorted by channel descending first, then by name it seems

**Comment by Ansuel** [comment]
Ok yes it's correct

Il Sab 24 Dic 2022, 10:54 dhewg ***@***.***> ha scritto:

**Pull request merged**
