### PR TITLE
luci-mod-network: Use validators from validator module

### PR DESCRIPTION
**Pull request by wt**
The current code has custom implementations of a couple validators
that are already available from the validator module in luci-base.

Signed-off-by: Wren Turkal <wt@penguintechs.org>

### CODE REVIEW

**Comment by wt** [comment]
BTW, this has been tested via a qemu build.

**Comment by jow-** [comment]
NAK, there's not the same. The address validator from the validation module does not support dnsmasq' forward slash notation (`/hostname/ipaddr`)

**Comment by wt** [comment]
Oh, the rebind one is also fqdn as opposed to a hostname, so that makes sense. Would it be interesting if I added an fqdn validator and use that for the rebind domain if I could find a way to allow it to be surrounded with the /'s?

Is the hostname allowed in the static lease also an fqdn? That kinda doesn't make sense since the host wouldn't be able to use that name? But I guess is also kinda does make sense since it could simply be a dns name?

@jow-, It seems like having an fqdn validator would be useful. What do you think?

**Comment by jow-** [comment]
Closing this as it won't be merged.

**Pull request closed without merging**
