### PR TITLE
luci-proto-ncm: add dialnum option

### PR DESCRIPTION
**Pull request by geekinaboxx**
This option is useful for setting the dial number used for data service connection

Signed-off-by: geekinaboxx <aleem@tectonic.it>

### CODE REVIEW

**Comment by feckert** [comment]
Please stash the two commits to one and also add a `Signed-off-by:` to your commit

**Comment by geekinaboxx** [comment]
Thanks. Done.

**Comment by feckert** [comment]
Sorry I have missed that we should also change the translation from `translate("Modem dial string")` to `translate("Dial number")` so we could reuse the translation from https://github.com/openwrt/luci/blob/master/protocols/luci-proto-3g/luasrc/model/cbi/admin_network/proto_3g.lua#L45 and do not have to introduce a new one to the po files.

**Comment by geekinaboxx** [comment]
no problem; nice catch. Done.

**Comment by feckert** [comment]
Thanks merged!

**Pull request merged**
