### PR TITLE
Fix #1609: luci-proto-wireguard placeholder wrongfully suggests default port

### LINKED ISSUE #1609: UX: luci-proto-wireguard UI suggests default listening port where there is none
This should be quite straightforward: luci-proto-wireguard, when editing the interface details, has "51820" as placeholder in the "listen port" input field:

image

This suggests that the default listen port is 51820. In fact, there is no default port, when undefined WireGuard uses a random ephemeral port.

I suggest changing the placeholder string to either something like "random", or maybe even better, remove the placeholder entirely and add a notice about random ports to the remark below.

### PR DESCRIPTION
**Pull request by squarewf**

### CODE REVIEW

**Comment by hnyman** [comment]
cc also @danrl 

Have you checked that it works as expected? I am not quite sure if the placeholder itself should be translated and if that works.

**Comment by squarewf** [comment]
There's plenty of translated placeholders, and "random" is not numeric and should be translate(d/able). CMIIW.

**Comment by jow-** [comment]
LGTM

**Comment by danrl** [comment]
LGTM

**Pull request merged**
