### PR TITLE
luci-app-unbound: added DNS64 support

### PR DESCRIPTION
**Pull request by danrl**
Signed-off-by: Dan Luedtke <mail@danrl.com>

### CODE REVIEW

**Comment by danrl** [comment]
Depends on https://github.com/openwrt/packages/pull/3642

**Comment by danrl** [comment]
Maintainer @EricLuehrsen

**Comment by EricLuehrsen** [comment]
Thoughts to consider, not sure but...
- maybe the prefix shouldnt be in LuCI
- maybe RFC6052 deviations should only be CLI UCI

**Comment by EricLuehrsen** [comment]
Okay. Pending primary package.

**Comment by danrl** [comment]
PR now reflects the latest changes in `packages/unbound` which this application depends on.

**Comment by EricLuehrsen** [comment]
Ready to merge.

**Pull request merged**
