### PR TITLE
luci-app-adblock: put backup options to global section

### PR DESCRIPTION
**Pull request by dibdot**
this PR reflect the changes made in adblock 2.3.0

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by thess** [comment]
Could someone cherry-pick this to 17.01 to match 2.3.0 there. I don't have merge privs here

**Comment by hnyman** [comment]
Thanks. I cherry-picked it. 

I had not noticed that 2.3.0 itself had been backported.
Then maybe also adblock: 2.3.0 (package release 2)" should be backported ?

**Comment by thess** [comment]
Yup - jow merged 2.3.0 a couple of days ago. Just noticed it this morning.

**Comment by hnyman** [comment]
I cherry.picked "adblock: 2.3.0 (package release 2)" to the packages repo, too.

**Pull request merged**
