### PR TITLE
luci-base: vi/base.po: translate to vietnamese almost done.

### PR DESCRIPTION
**Pull request by tuanti1997qn**
Translate luci-base into vietnamese almost done.

### CODE REVIEW

**Comment by feckert** [comment]
Thanks for your contribution but
* Please sign off your work
* Also please rebase your changed against the current master there are some conflicts
* Please use also in the future https://hosted.weblate.org/projects/openwrt/ for translation.

**Comment by tuanti1997qn** [comment]
I resolved the conflict, Is there anything that I must do?

**Comment by yousong** [comment]
Hi @tuanti1997qn 

You will need to sign-off your work by adding `Signed-off-by: NAME <EMAIL>` in the commit message.  E.g. https://github.com/openwrt/luci/commit/0731f7e5e43f490c39e364e43988a59ee2be9576

The subject title had better be prefixed with the name of the component you worked on.  In this case, it should be `luci-base: xxx`.  Existing commits are generally also good examples to follow.

When doing rebase, you will need to drop those unrelated commits.  At the moment, there are 114 commits in this pull request.  Only one of them is needed.  `git rebase -i origin/master` and remove those unrelated lines should generally do.

**Comment by yousong** [comment]
Here is a wiki page describing the convention of "Submitting patches" to OpenWrt repos: https://openwrt.org/submitting-patches

**Comment by tuanti1997qn** [comment]
Sorry about my lack of skill in Git. I just learned git seriously about 2 mount ago.
This time, do I make it correctly?

**Comment by yousong** [comment]
Just one minor details to check.  The abbreviation is "vi" for the name of folder, but it's "vn" in the commit message title.

**Comment by tuanti1997qn** [comment]
ops, it's my mistake, I will fix it.

**Comment by yousong** [comment]
Thank you!

**Pull request merged**
