### PR TITLE
Add initial luci-app-fwknopd - a way to control the firewall knock da…

### PR DESCRIPTION
**Pull request by oneru**
…emon from luci

Signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>

### CODE REVIEW

**Comment by oneru** [comment]
@chris5560 Should I use Apache-2.0 for the license, or can I use GPLv2

**Comment by oneru** [comment]
@chris5560 @jow- I've updated the pull request to deal with the notes from Chris. Let me know if any further changes are needed.

~Jonathan Bennett

**Comment by oneru** [comment]
Adding the translation stuff has broken the package. I'll reopen once I figure out what all broke.

**Comment by oneru** [comment]
@chris5560 @jow- Working now. As far as I can tell, it's ready.

**Comment by chris5560** [comment]
Thanks

**Pull request merged**
