### PR TITLE
luci-proto-ipv6: Add support for IPIP6(RFC2473) tunnel 

### PR DESCRIPTION
**Pull request by missing233**
Add Generic Packet Tunneling in IPv6 Specification (RFC 2473) support.
(For NTT Broadband V6Plus/transix/Xpass Fixed IP)

[depends on other PRs: openwrt/openwrt](https://github.com/openwrt/openwrt/pull/14516)

### CODE REVIEW

**Comment by systemcrash** [comment]
OK @missing233 go ahead and resolve those conflicts and force push. When the parent PR https://github.com/openwrt/openwrt/pull/14516 lands in master, go ahead and set this to ready.

**Comment by systemcrash** [comment]
Rebase on current master to resolve conflicts

**Comment by missing233** [comment]
> Rebase on current master to resolve conflicts



> Rebase on current master to resolve conflicts

Done.
Thanks :)

**Comment by systemcrash** [comment]
> > Rebase on current master to resolve conflicts
> 
> > Rebase on current master to resolve conflicts
> 
> Done. Thanks :)

Were that so, github would not say: "This branch is out-of-date with the base branch" :)

**Comment by systemcrash** [comment]
So you need to at least: change to master, git pull, check out ipip6, rebase, ...

**Comment by missing233** [comment]
> Were that so, github would not say: "This branch is out-of-date with the base branch" :)

Well, I've never contributed to a large project before, so I'm a bit unfamiliar with this.
Thank you for your help! :D

**Comment by missing233** [comment]
> OK @missing233 go ahead and resolve those conflicts and force push. When the parent PR [openwrt/openwrt#14516](https://github.com/openwrt/openwrt/pull/14516) lands in master, go ahead and set this to ready.

Ok it's now ready.

**Comment by systemcrash** [comment]
OK. In she goes. Thanks @missing233

**Comment by systemcrash** [comment]
This is in tandem with https://github.com/openwrt/openwrt/commit/21eeb45420cf12c6df9b39b619f6579b3ec32bb4

**Pull request merged**
