### PR TITLE
luci-app-openvpn: sort basic and advanced options

### PR DESCRIPTION
**Pull request by mwarning**
Options sorted by name will make it easier to navigate the option lists
and selection boxes.

Signed-off-by: Moritz Warning <moritzwarning@web.de>

### CODE REVIEW

**Comment by mwarning** [comment]
I cannot verify the syntax right now, since luci-openvpn seems to be broken in nightly (`/usr/lib/lua/luci/model/cbi/openvpn.lua:76: attempt to index field 'extedit' (a nil value)`).

**Comment by mwarning** [comment]
A different approach would be to sort at runtime:
```
-- sort params by name
for i, val in pairs(knownParams) do
  table.sort(val[2], function(a, b) return a[2] < b[2] end)
end
```

**Comment by mwarning** [comment]
Anyway, the current order looks random to me. Finding a specific option is a bit of a hassle.

**Comment by dibdot** [comment]
@mwarning to be honest, I don't see any benefit in an alphabetical order - I would close this PR.

**Comment by mwarning** [comment]
Right now I find myself to have to parse the dropdown list twice, once quickly and once slowly, because I had overlooked the setting I was looking for. From my own experience it makes it easier.

Feel free to close the PR if you feel unconvinced.

**Pull request closed without merging**
