### PR TITLE
luci-mod-network: DHCP tab IPsets ( add NFTsets properties )

### PR DESCRIPTION
**Pull request by systemcrash**
See also:

https://github.com/openwrt/openwrt/commit/d7f378796f985c902ff7906767c275c40a15347f

@jow- Is a straight rename safe? Since fw4 is default now.

### CODE REVIEW

**Comment by dave14305** [comment]
Why not just call them “Sets” since the same config can be used to populate fw3 ipsets or fw4 nftables sets, depending how dnsmasq is compiled.

Nftset isn’t really a term except within dnsmasq’s configuration.

**Comment by rpigott** [comment]
fwiw systemd uses the term NFTSet as well: https://github.com/search?q=repo%3Asystemd%2Fsystemd%20NFTSet&type=code

**Comment by jow-** [comment]
This will break compatibility with firewall3, which still can be installed.

**Comment by jow-** [comment]
I think fw3/fw4 actually is unrelated here. The code you're about to touch relates to dhcp (dnsmasq) uci configuration and upstream dnsmasq.init currently only supports `config ipset` sections (which are transparently translated to --nftset settings if nftset is compiled in). I think this change (changing the `ipset` section type to `nftset`) will render the functionality broken.

**Comment by systemcrash** [comment]
> what about "Address set"?

Could work. I suspect it would take a bit for those users who need it to figure this out. 
"Remotely plausible menu here called 'sets' exists, but ipsets/nftsets is gone... hmm, click here."

How about handling ipsets and nftsets with two tables both under the same tab (I generally dislike conflating similar concepts), until dnsmasq.init has caught up?

**Comment by jow-** [comment]
Why not just leave it as-is? Maybe call the labels `nftset/ipset`. Right now dnsmasq init accepts "ipset", translates it to both `--ipset` and `--nftset` simultaneously and then throws away what is not supported. So in essence it is agnostic and should be imho.

Having a configuration abstraction in the form of uci makes little sense if every little implementation detail and native config idiosyncrasy is exposed as-is to uci. The uci configuration should be intent-driven, means "please build a set of resolved IPs for domain X" and not concern itself with details such as "is ipset compiled in or nftset? is it firewall3 or firewall4? do domain names need to be separated with slash, or comma, or space?"

Unfortunately the existing dnsmasq (dhcp) uci support is quite bad in this regard, organically grown over years and exposing weird dnsmasq design choices such as the slash separated address format as-is instead of doing proper structured lists. But that does not mean that we should needlessly continue this approach. When some hypothetical kind of eBPF based filtering comes along in a few years we'll be dealing with ipsets, nftsets and bpfsets.

The term "ipset" predates "nftsets" but is imho still a valid generic term for "set of IPs". Apart from these points, a `config ipset` is backwards compatible to old systems and upwards compatible to new, nft based ones while a `config nftset` will only work on new ones. We'd also need to duplicate the ui code and support both ipsets and nftsets with mostly overlapping functionality, leading to even further bloat.

**Comment by systemcrash** [comment]
> Having a configuration abstraction in the form of uci makes little sense if every little implementation detail and native config idiosyncrasy is exposed as-is to uci. The uci configuration should be intent-driven, means "please build a set of resolved IPs for domain X" and not concern itself with details such as "is ipset compiled in or nftset? is it firewall3 or firewall4? do domain names need to be separated with slash, or comma, or space?"
> 
You've said something very important here. 

> Unfortunately the existing dnsmasq (dhcp) uci support is quite bad in this regard, organically grown over years and exposing weird dnsmasq design choices such as the slash separated address format as-is instead of doing proper structured lists. But that does not mean that we should needlessly continue this approach. When some hypothetical kind of eBPF based filtering comes along in a few years we'll be dealing with ipsets, nftsets and bpfsets.

Ideally bpfsets (should such a thing come into existence) get their own proper handling. 

I'll rework the text on the page and just add the nftsets bits, marked appropriately as so.

**Comment by systemcrash** [comment]
OK, that's roughly done.

**Pull request merged**
