### PR TITLE
luci-app-nft-qos: add new application

### PR DESCRIPTION
**Pull request by rosysong**
This is the nftables implementation for qos limit rate.

Signed-off-by: Rosy Song <rosysong@rosinson.com>

Screenshot also shown at https://github.com/openwrt/packages/pull/6193

### CODE REVIEW

**Comment by rosysong** [comment]
Static QoS
static-qos

Traffic Control
traffic-control

Realtime Rate
realtime-rate

Dynamic/Auto QoS
dynamic-qos

**Comment by rosysong** [comment]
@hnyman  Thanks, and please don't forget to check this. :-)

**Comment by hnyman** [comment]
Hi, I just noticed, a bit too late as I merged it already, that there was also an extra binary file templates/zh_CN.mo and also templates/zh_CN.po file.

I removed those.

**Comment by rosysong** [comment]
@NeMeFuUuRyyyyY  1 is the highest.

**Pull request merged**
