### PR TITLE
luci-app-uhttpd German translation

### PR DESCRIPTION
**Pull request by Matthias84**
German translation by Matthias Meißer

### CODE REVIEW

**Comment by hnyman** [comment]
It should not be a .pot (template) file, but a normal .po

**Comment by aparcar** [comment]
@hnyman so we only need to move the file from `.pot` to `.po`?

**Comment by hnyman** [comment]
Basically so, and of course the commit should also be signed off.

**Comment by feckert** [comment]
Please merge the two commits. So we have only the first one
Smal howto:
`git checkout <your pr branch>`
`git rebase -i HEAD~2`
in the vi replace the last commit `pick` with `fixup` and save the change
`git push --force`

Also add add a  `Signed-off-by: xxx xxx <xxx@xxx>` to the first commit

After this change we are ready to merge.

**Comment by Matthias84** [comment]
Thanks for pointing me to the instructions! Usually I just use github to do some translations, but I wasn't clever enough to do it via frontend.

**Pull request merged**
