### PR TITLE
Add some Simplified Chinese translations

### PR DESCRIPTION
**Pull request by 981213**
This pull request adds some Simplified Chinese translation for luci-base.

Signed-off-by: 郭传鈜<gch981213@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Please sign off the commit, otherwise it looks fine to me.

**Comment by 981213** [comment]
Sorry,I don't understand what you mean...
Do you mean I need to sign off the commit instead of this pull request?

**Comment by hnyman** [comment]
> Do you mean I need to sign off the commit instead of this pull request?
Yes.
You can use ```git commit --amend``` to edit the commit message of the last commit.
(And please write your name with normal letters instead of Chinese letters.)

See https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md#advice-on-pull-requests for more advice.

**Comment by jow-** [comment]
A shortcut for adding a S-o-b line to the topmost commit is: `git commit --signoff --amend`, then quit & save the editor and upload the updated commit using `git push --force`

**Pull request closed without merging**
