### PR TITLE
luci-base: add freq to channel calculation to tools

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Translate iw function ieee80211_frequency_to_channel to lua
and add it to the tools section.

Signed-off-by: Nick Hainke <vincent@systemli.org>

### CODE REVIEW

**Comment by dibdot** [comment]
@PolynomialDivision just a short formal feedback:

- Semi-colons in Lua are generally only required when writing multiple statements on a line
- I would suggest to define a local variable "channel" with default 0, change that variable in the function and finally return "channel" once at the end

**Comment by PolynomialDivision** [comment]
@dibdot Thanks for your review! :)

If I add this function directly in my .../tools/status.lua script, it doesn't work.
I tested as local function in one of my lua scripts.
I think the dispatcher has to recognize this function somehow?

**Comment by dibdot** [comment]
Just a rough guess: did you reset your luci caches (rm -rf /tmp/luci*)?

**Comment by PolynomialDivision** [comment]
rm -rf /tmp/luci-*

is the solution. :)

Now you only have to accept my pull request. ^^

**Comment by dibdot** [comment]
@PolynomialDivision regarding merging: I'm still a LuCI rookie and I'm not sure if we need such function at all. There is already a generic "getiwinfo" function available, therefore it might be better to re-use this one in your app to get the channel information!?

**Comment by PolynomialDivision** [comment]
Ok.
I added this to my own app as tools. ;)
So I will close. :)

**Comment by dibdot** [comment]
Fair enough - thanks for the info.

**Pull request closed without merging**
