### PR TITLE
luci-base/luci-compat: Replace legend element with h3.

### LINKED ISSUE #3149: luci-theme-material: missing panel title in with client-side view
When using client-side view, panel title is missing:
image
Server-side view is normal:
image

I think it's because the code that creates it excutes on load, but the view is not loaded at that time.
https://github.com/openwrt/luci/blob/e459683822925bcdeb552673a4811aa3b4322640/themes/luci-theme-material/htdocs/luci-static/material/js/script.js#L174-L180

### PR DESCRIPTION
**Pull request by oldium**
The `legend` HTML element is allowed only as first element in `fieldset`, so use `h3` instead, which is rendered the same within themes.

Fixes #3149.

### CODE REVIEW

**Comment by oldium** [comment]
CC @jow-

**Comment by oldium** [comment]
I will also have a look at the possibility to clean-up legend handling in themes.

**Comment by oldium** [comment]
Fixed material handling of new H3 theme, all others look fine.

**Comment by jow-** [comment]
Awesome! Merged, thanks :+1:

**Pull request merged**
