### PR TITLE
luci-app-travelmate[18.06]: "final" fixes

### PR DESCRIPTION
**Pull request by dibdot**
cherry picked from commit af25cf4

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by hnyman** [comment]
You can continue to keep your 18.06 packages updated. Just merge the PR if the fix/enhancement works.

Like I said yesterday, 18.06 user-space packages are constantly built from the newest sources, so you can rather freely implement fixes even after a release deadline.

Note that
* normal users who install the forthcoming official release image, will get newest 18.06 buildbot packages with opkg (including this fix)
* if somebody checks out the 18.06.0 tag sources, he will build exactly from commits included in that tag and will get the fixed old version of the packages he includes in his build. But even he will get newest versions with opkg from the buildbot repo if he later installs packages with opkg.

**Comment by dibdot** [comment]
Thanks, this was my first attempt to send in a "cherrypick PR" (as requested by jow), therefore I've asked if it's OK. Currently I don't want to try out to directly commit in openwrt repo ... ;-)

**Comment by hnyman** [comment]
You could do actual cherry-picking, though, if that was jow's point. 
(that works if you can merge identical commit as in master)

checkout 18.06 branch
checkout new PR-branch
git cherry-pick -x master-commit
git push -u origin PR-branch  (to create PR)

That way you get the original commit message plus cherry-pick text.

**Comment by hnyman** [comment]
example of cherry-pick PR from me (in main repo): https://github.com/openwrt/openwrt/pull/1120/commits

**Comment by jow-** [comment]
I was actually hinting at the possibility for @dibdot to cherry-pick and push to LuCI's openwrt-18.06 without opening another PR. If the PR against master was reviewed / accepted and when a clean cherry pick works without the need to rebase, I see no need to have another PR.

**Comment by dibdot** [comment]
@hnyman @jow- 
Hopefully the latest cherry-pick commit was OK!? ;-)

**Comment by hnyman** [comment]
Looks ok to me at the first glance.

**Comment by dibdot** [comment]
Great - thanks for your patience!

**Pull request closed without merging**
