### PR TITLE
luci-mod-network: enable configuring wifi ax networks on the 6G band

### PR DESCRIPTION
**Pull request by dhewg**
That seems too easy? But it works for me (tm)

Depends on https://github.com/openwrt/openwrt/pull/11280

ax

### CODE REVIEW

**Comment by backslashxx** [comment]
image
works!

but as a nitpick, 6GHz only allows WPA3-SAE and OWE, basically it is sae-only so that should be handled too!

**Comment by dhewg** [comment]
> 6GHz only allows WPA3-SAE and OWE, basically it is sae-only so that should be handled too!

Indeed, maybe @jow can help how to filter that out properly? I see some `add_dependency_permutations()` calls with which this may be solved, but my js experiency is seriously lacking...

**Comment by dhewg** [comment]
What a rabbit hole, iwinfo usage is duplicated and inconsistent over the tree :\

The depending iwinfo PR now has some additions, and I added the usage of "hwmodes_text" (which does what suggested on irc) and "band" here, but please review carefully because of omg javascript.

**Comment by dhewg** [comment]
The PR this depends on has been merged, this can be considered now.

**Comment by dhewg** [comment]
Added a missing bump for rpcd-mod-luci. The others seem to use git infos for that, so don't require manual bumps

**Comment by dhewg** [comment]
The boards where this is relevant grows steadily, with ath11k in-tree there's even a new ax-capable driver, affecting more users.

So is there anything I can do to get this further?
Testers are always welcome, please leave some feedback!

For reviewers:
The first two patches are the bigger ones, but they're basically the equivalent of the already merged rpcd patches, see
https://git.openwrt.org/?p=project/rpcd.git;a=commitdiff;h=c46ad61d49de411fc5bc64dd0bdd48518601487b
https://git.openwrt.org/?p=project/rpcd.git;a=commitdiff;h=7de4820c87437033f6b7716018f3bfa60a3f7b12

The remainder isn't really much

**Comment by trippleflux** [comment]
@dhewg 

I have AsiaRF 7916, I need to switch and reboot between 5G and 6G, somehow after switching into 6G, luci cannot activate or found the 6G, only displayed as 160Mhz Freq, here is iw phy : 
```
# iw phy
Wiphy phy1
        wiphy index: 1
        max # scan SSIDs: 4
        max scan IEs length: 2232 bytes
        max # sched scan SSIDs: 0
        max # match sets: 0
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Device supports AP-side u-APSD.
        Device supports T-DLS.
        Available Antennas: TX 0x3 RX 0x3
        Configured Antennas: TX 0x3 RX 0x3
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
        Band 4:
                HE Iftypes: managed
                        HE MAC Capabilities (0x08011a000040):
                                +HTC HE Supported
                                Trigger Frame MAC Padding Duration: 2
                                OM Control
                                Maximum A-MPDU Length Exponent: 3
                                A-MSDU in A-MPDU
                        HE PHY Capabilities: (0x4c70ce126d00f3164e3f00):
                                HE40/HE80/5GHz
                                HE160/5GHz
                                242 tone RUs/5GHz
                                Device Class: 1
                                LDPC Coding in Payload
                                HE SU PPDU with 1x HE-LTF and 0.8us GI
                                NDP with 4x HE-LTF and 3.2us GI
                                STBC Tx <= 80MHz
                                STBC Rx <= 80MHz
                                Full Bandwidth UL MU-MIMO
                                Partial Bandwidth UL MU-MIMO
                                DCM Max Constellation: 2
                                DCM Max Constellation Rx: 2
                                SU Beamformee
                                Beamformee STS <= 80Mhz: 3
                                Beamformee STS > 80Mhz: 3
                                Codebook Size SU Feedback
                                Codebook Size MU Feedback
                                Triggered CQI Feedback
                                Partial Bandwidth Extended Range
                                Partial Bandwidth DL MU-MIMO
                                PPE Threshold Present
                                Power Boost Factor ar
                                HE SU PPDU & HE PPDU 4x HE-LTF 0.8us GI
                                Max NC: 2
                                20MHz in 40MHz HE PPDU 2.4GHz
                                20MHz in 160/80+80MHz HE PPDU
                                80MHz in 160/80+80MHz HE PPDU
                                DCM Max BW: 1
                                Longer Than 16HE SIG-B OFDM Symbols
                                Non-Triggered CQI Feedback
                                TX 1024-QAM
                                RX 1024-QAM
                                RX Full BW SU Using HE MU PPDU with Compression SIGB
                                RX Full BW SU Using HE MU PPDU with Non-Compression SIGB
                        HE RX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE TX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE RX MCS and NSS set 160 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE TX MCS and NSS set 160 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        PPE Threshold 0x39 0x1c 0xc7 0x71 0x1c 0x07
                EHT Iftypes: managed
                        EHT MAC Capabilities (0x0000):
                        EHT PHY Capabilities: (0x0000000000000000):
                        EHT MCS/NSS: (0x):
                        EHT bw <= 80 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
                        EHT bw=160 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
                        EHT bw=160 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
                        EHT bw=160 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
                HE Iftypes: AP
                        HE MAC Capabilities (0x00051a081044):
                                +HTC HE Supported
                                TWT Responder
                                BSR
                                OM Control
                                Maximum A-MPDU Length Exponent: 3
                                BQR
                                A-MSDU in A-MPDU
                                OM Control UL MU Data Disable RX
                        HE PHY Capabilities: (0x0c20ce926f12afd0000c00):
                                HE40/HE80/5GHz
                                HE160/5GHz
                                LDPC Coding in Payload
                                NDP with 4x HE-LTF and 3.2us GI
                                STBC Tx <= 80MHz
                                STBC Rx <= 80MHz
                                Full Bandwidth UL MU-MIMO
                                Partial Bandwidth UL MU-MIMO
                                DCM Max Constellation: 2
                                DCM Max Constellation Rx: 2
                                SU Beamformer
                                SU Beamformee
                                MU Beamformer
                                Beamformee STS <= 80Mhz: 3
                                Beamformee STS > 80Mhz: 3
                                Sounding Dimensions <= 80Mhz: 2
                                Sounding Dimensions > 80Mhz: 2
                                Codebook Size SU Feedback
                                Codebook Size MU Feedback
                                Triggered SU Beamforming Feedback
                                Triggered MU Beamforming Feedback
                                Partial Bandwidth Extended Range
                                PPE Threshold Present
                                Max NC: 2
                                STBC Tx > 80MHz
                                STBC Rx > 80MHz
                                TX 1024-QAM
                                RX 1024-QAM
                        HE RX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE TX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE RX MCS and NSS set 160 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE TX MCS and NSS set 160 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        PPE Threshold 0x39 0x1c 0xc7 0x71 0x1c 0x07
                EHT Iftypes: AP
                        EHT MAC Capabilities (0x0000):
                        EHT PHY Capabilities: (0x0000000000000000):
                        EHT MCS/NSS: (0x):
                        EHT bw <= 80 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
                        EHT bw=160 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
                        EHT bw=160 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
                        EHT bw=160 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
                HE Iftypes: mesh point
                        HE MAC Capabilities (0x00011a000040):
                                +HTC HE Supported
                                OM Control
                                Maximum A-MPDU Length Exponent: 3
                                A-MSDU in A-MPDU
                        HE PHY Capabilities: (0x0c200c0000000000008000):
                                HE40/HE80/5GHz
                                HE160/5GHz
                                LDPC Coding in Payload
                                STBC Tx <= 80MHz
                                STBC Rx <= 80MHz
                        HE RX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE TX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE RX MCS and NSS set 160 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE TX MCS and NSS set 160 MHz
                                1 streams: MCS 0-11
                                2 streams: MCS 0-11
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                EHT Iftypes: mesh point
                        EHT MAC Capabilities (0x0000):
                        EHT PHY Capabilities: (0x0000000000000000):
                        EHT MCS/NSS: (0x):
                        EHT bw <= 80 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
                        EHT bw=160 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
                        EHT bw=160 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
                        EHT bw=160 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
                Frequencies:
                        * 5955 MHz [1] (12.0 dBm) (no IR)
                        * 5975 MHz [5] (12.0 dBm) (no IR)
                        * 5995 MHz [9] (12.0 dBm) (no IR)
                        * 6015 MHz [13] (12.0 dBm) (no IR)
                        * 6035 MHz [17] (12.0 dBm) (no IR)
                        * 6055 MHz [21] (12.0 dBm) (no IR)
                        * 6075 MHz [25] (12.0 dBm) (no IR)
                        * 6095 MHz [29] (12.0 dBm) (no IR)
                        * 6115 MHz [33] (12.0 dBm) (no IR)
                        * 6135 MHz [37] (12.0 dBm) (no IR)
                        * 6155 MHz [41] (12.0 dBm) (no IR)
                        * 6175 MHz [45] (12.0 dBm) (no IR)
                        * 6195 MHz [49] (12.0 dBm) (no IR)
                        * 6215 MHz [53] (12.0 dBm) (no IR)
                        * 6235 MHz [57] (12.0 dBm) (no IR)
                        * 6255 MHz [61] (12.0 dBm) (no IR)
                        * 6275 MHz [65] (12.0 dBm) (no IR)
                        * 6295 MHz [69] (12.0 dBm) (no IR)
                        * 6315 MHz [73] (12.0 dBm) (no IR)
                        * 6335 MHz [77] (12.0 dBm) (no IR)
                        * 6355 MHz [81] (12.0 dBm) (no IR)
                        * 6375 MHz [85] (12.0 dBm) (no IR)
                        * 6395 MHz [89] (12.0 dBm) (no IR)
                        * 6415 MHz [93] (12.0 dBm) (no IR)
                        * 6435 MHz [97] (12.0 dBm) (no IR)
                        * 6455 MHz [101] (12.0 dBm) (no IR)
                        * 6475 MHz [105] (12.0 dBm) (no IR)
                        * 6495 MHz [109] (12.0 dBm) (no IR)
                        * 6515 MHz [113] (12.0 dBm) (no IR)
                        * 6535 MHz [117] (12.0 dBm) (no IR)
                        * 6555 MHz [121] (12.0 dBm) (no IR)
                        * 6575 MHz [125] (12.0 dBm) (no IR)
                        * 6595 MHz [129] (12.0 dBm) (no IR)
                        * 6615 MHz [133] (12.0 dBm) (no IR)
                        * 6635 MHz [137] (12.0 dBm) (no IR)
                        * 6655 MHz [141] (12.0 dBm) (no IR)
                        * 6675 MHz [145] (12.0 dBm) (no IR)
                        * 6695 MHz [149] (12.0 dBm) (no IR)
                        * 6715 MHz [153] (12.0 dBm) (no IR)
                        * 6735 MHz [157] (12.0 dBm) (no IR)
                        * 6755 MHz [161] (12.0 dBm) (no IR)
                        * 6775 MHz [165] (12.0 dBm) (no IR)
                        * 6795 MHz [169] (12.0 dBm) (no IR)
                        * 6815 MHz [173] (12.0 dBm) (no IR)
                        * 6835 MHz [177] (12.0 dBm) (no IR)
                        * 6855 MHz [181] (12.0 dBm) (no IR)
                        * 6875 MHz [185] (12.0 dBm) (no IR)
                        * 6895 MHz [189] (12.0 dBm) (no IR)
                        * 6915 MHz [193] (12.0 dBm) (no IR)
                        * 6935 MHz [197] (12.0 dBm) (no IR)
                        * 6955 MHz [201] (12.0 dBm) (no IR)
                        * 6975 MHz [205] (12.0 dBm) (no IR)
                        * 6995 MHz [209] (12.0 dBm) (no IR)
                        * 7015 MHz [213] (12.0 dBm) (no IR)
                        * 7035 MHz [217] (12.0 dBm) (no IR)
                        * 7055 MHz [221] (12.0 dBm) (no IR)
                        * 7075 MHz [225] (12.0 dBm) (no IR)
                        * 7095 MHz [229] (12.0 dBm) (no IR)
                        * 7115 MHz [233] (12.0 dBm) (no IR)
        valid interface combinations:
                 * #{ IBSS } <= 1, #{ AP, mesh point } <= 16, #{ managed } <= 19,
                   total <= 19, #channels <= 1, STA/AP BI must match, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz, 80 MHz, 160 MHz }

        HT Capability overrides:
                 * MCS: ff ff ff ff ff ff ff ff ff ff
                 * maximum A-MSDU length
                 * supported channel width
                 * short GI for 40 MHz
                 * max A-MPDU length exponent
                 * min MPDU start spacing
        max # scan plans: 1
        max scan plan interval: -1
        max scan plan iterations: 0
        Supported extended features:
                * [ VHT_IBSS ]: VHT-IBSS
                * [ RRM ]: RRM
                * [ BEACON_RATE_LEGACY ]: legacy beacon rate setting
                * [ BEACON_RATE_HT ]: HT beacon rate setting
                * [ BEACON_RATE_VHT ]: VHT beacon rate setting
                * [ FILS_STA ]: STA FILS (Fast Initial Link Setup)
                * [ CQM_RSSI_LIST ]: multiple CQM_RSSI_THOLD records
                * [ CONTROL_PORT_OVER_NL80211 ]: control port over nl80211
                * [ ACK_SIGNAL_SUPPORT ]: ack signal level support
                * [ TXQS ]: FQ-CoDel-enabled intermediate TXQs
                * [ SCAN_RANDOM_SN ]: use random sequence numbers in scans
                * [ SCAN_MIN_PREQ_CONTENT ]: use probe request with only rate IEs in scans
                * [ AIRTIME_FAIRNESS ]: airtime fairness scheduling
                * [ STA_TX_PWR ]: TX power control per station
                * [ AQL ]: Airtime Queue Limits (AQL)
                * [ CONTROL_PORT_NO_PREAUTH ]: disable pre-auth over nl80211 control port support
                * [ DEL_IBSS_STA ]: deletion of IBSS station support
                * [ SCAN_FREQ_KHZ ]: scan on kHz frequency support
                * [ CONTROL_PORT_OVER_NL80211_TX_STATUS ]: tx status for nl80211 control port support
                * [ FILS_DISCOVERY ]: FILS discovery frame transmission support
                * [ UNSOL_BCAST_PROBE_RESP ]: unsolicated broadcast probe response transmission support
                * [ BEACON_RATE_HE ]: HE beacon rate support (AP/mesh)
                * [ BSS_COLOR ]: BSS coloring support
                * [ RADAR_BACKGROUND ]: Radar background support
```

**Comment by dhewg** [comment]
My ax card only does 80mhz, that works just fine here.
160 may be restricted with the regdb for your country code. We already added new flags for this to iwinfo, see https://github.com/openwrt/openwrt/pull/11280#issuecomment-1378539552

But luci doesn't check those yet, so if you configure a channel where 160 isn't allowed I guess it can error out, but channel "auto" should work I guess

**Comment by trippleflux** [comment]
Hmm, I am quite new in OpenWrt wifi, what I've meant is here : 
6G

Selecting country code or Operating Freq doesn't make any differences. Also any ideas why Max Transmit Power being 255 dBm?.

Before [this ](https://github.com/openwrt/mt76/files/10530503/0001-wifi-mt76-mt7916-Support-per-radio-configuration-firmware-file.patch)code changes, I am able to select and use 6G at 160 MHz.

At overview the device shown as not active : 
6G2

**Comment by dhewg** [comment]
Sounds like 160mhz isn't support for that card: https://github.com/openwrt/mt76/commit/98aa346042bd21fe8c0b1594736edca16be436db
TX power looks wrong obviously, there's an issue about it here https://github.com/openwrt/openwrt/issues/11902

**Comment by trippleflux** [comment]
@dhewg 
I have tried 80 MHz and 40 MHz @ 6GHz but still wireless device cannot bring it up.

**Comment by dhewg** [comment]
I'm not sure, it shouldn't matter for this, but you may be running into the same bug as described here:
https://github.com/openwrt/openwrt/issues/11902

Fix: http://patchwork.ozlabs.org/project/openwrt/patch/20230130185757.9512-1-a.heider@gmail.com/
Alternatively a patch for the OpenWrt tree it is in that PR.

Or just wait until it's merged to get a libiwinfo package update

**Pull request merged**
