### PR TITLE
fixed and updated russian translation

### PR DESCRIPTION
**Pull request by user7887**
Signed-off-by: Vladimir <picfun@ya.ru>

### CODE REVIEW

**Comment by user7887** [comment]
The script was executed as you requested.

**Comment by hnyman** [comment]
Good.
But you should run the script after editing the file, but before creating a commit here, so that there would be no extra commits.

**Comment by user7887** [comment]
hnyman
Of course, next time I'll do it.
I was surprised when I saw 2 additional files, because I sent them this morning, sorry :)

**Comment by hnyman** [comment]
> I was surprised when I saw 2 additional files, because I sent them this morning, sorry :)

One basic fault in you git work is doing everything on the master branch. That can make it hard to separate things to different PRs.

The proper way is to create a feature branch for the changes, do the current changes there and finally create the pull request out of it. Then for the next changes you create a new branch from master.

See advice: https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md#advice-on-pull-requests

**Comment by user7887** [comment]
Well, thank you Sensei :)
I was in a hurry to do as much as possible, while in Russia holidays and have a lot of free time..
I'll do as you need.

**Comment by user7887** [comment]
Well, thank you Sensei :)
I was in a hurry to do as much as possible, while in Russia holidays and have a lot of free time..
I'll do as you need.
I created branch luci-ru.

**Pull request merged**
