### PR TITLE
luci-app-advanced-reboot: Advanced Reboot support for Linksys EA7300 v2

### PR DESCRIPTION
**Pull request by arrmo**
Add support for new (recently supported) hardware. Image with this change in place,

image

Thanks!

### CODE REVIEW

**Comment by stangri** [comment]
Great, thank you for the contribution! If it's a newly supported device, it will probably need just one of the "linksys-ea7300-v2" or "linksys,ea7300-v2", but not both. What does OpenWrt report for the board name?

Also, do you mind updating the README as well and then squashing two commits into one?

**Comment by arrmo** [comment]
You're right, thanks! I checked, and `ubus call system board` results in,
```
        "board_name": "linksys,ea7300-v2",
```
So updated to only use this name. Also added this device to the README, like you said. Single commit, just amended.

Thanks again.

**Comment by stangri** [comment]
Outstanding job, thanks!

**Comment by arrmo** [comment]
NP, glad to help. Thanks for the awesome app!

**Comment by varGeneric** [comment]
The EA7300 v1 uses the same partition layout and uboot variables as the EA7300 v2 and should have no problem using the same script. What's the best way to get the script expanded to support both devices? Should I open a separate PR?

```
root@OpenWrt:~# (dmesg | grep machine)
[    0.000000] MIPS: machine is Linksys EA7300 v1
root@OpenWrt:~# (ubus call system board | grep board)
        "board_name": "linksys,ea7300-v1",
root@OpenWrt:~# fw_printenv
bootargs=console=ttyS1,115200n8 root=/dev/mtdblock6 ro rootfstype=jffs2 init=/sbin/init
bootcmd=tftp
auto_recovery=yes
bootdelay=5
baudrate=115200
ethaddr="00:AA:BB:CC:DD:10"
ipaddr=192.168.1.1
serverip=192.168.1.180
bootfile=atlanta.img
Image1Stable=0
Image1Try=0
stdin=serial
stdout=serial
stderr=serial
boot_part_ready=3
boot_part=1
root@OpenWrt:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00080000 00020000 "boot"
mtd1: 00040000 00020000 "u_env"
mtd2: 00040000 00020000 "factory"
mtd3: 00040000 00020000 "s_env"
mtd4: 00040000 00020000 "devinfo"
mtd5: 00400000 00020000 "kernel"
mtd6: 02400000 00020000 "ubi"
mtd7: 00400000 00020000 "alt_kernel"
mtd8: 02400000 00020000 "alt_rootfs"
mtd9: 00100000 00020000 "sysdiag"
mtd10: 02d00000 00020000 "syscfg"
```

**Comment by stangri** [comment]
@varGeneric yes, definitely a separate PR. You may want to wait a few days as [there's an effort](https://github.com/openwrt/luci/pull/4489) by @Ansuel to convert client-side to JS (and it's pretty much done) and it involved converting the device-specific files from lua to json.

**Comment by varGeneric** [comment]
Thanks. I'll be sure to watch that then.

**Comment by arrmo** [comment]
Seems this device got broken with the json update 😞

**Comment by Ansuel** [comment]
Well the problem is that while I converted all the device this new device has been added... and I didn't refresh my repo to include this...

**Comment by arrmo** [comment]
Done! #4502 😄

**Pull request merged**
