### PR TITLE
luci-base: add tblsection sorting by column

### PR DESCRIPTION
**Pull request by kctani**
adding 'sortable=true' to a tblsection column presents
an up/down arrow to the respective field. clicking the
arrow sorts the rows accordingly. tblsection.htm adds
arrows and onclick functions; cbi.js sorts the rows
and updates the order element; cbi.lua detects a
sortable column and actions the order element.
updated dhcp.lua to sort on columns.

Signed-off-by: Ken Clough <git.tani@tani.ch>

### CODE REVIEW

**Comment by hnyman** [comment]
Why do you change file access modes?
 100644 → 100755 
Intentionally?

**Comment by jow-** [comment]
Thanks for doing this PR. I cannot merge it as is since it has various formal and style issues. I'll do a more thorough review later on.

**Comment by kctani** [comment]
> Why do you change file access modes?
> 100644 → 100755
> Intentionally?

Not intentional, file handling error on my part.

**Comment by kctani** [comment]
I have updated the request what I think are the formal and perhaps style issues noted by jow. The update now refers only to luci-base.

**Comment by kctani** [comment]
Jo, Thanks for the feedback. I will address all the points you made and update. Just one question: I updated the title to correct the package name and dropped dhcp.lua since it is not in luci-base. Was that correct and I should make a second PR for dhcp.lua or is it preferable to put both changes in the same PR?

Cheers, Ken

**Comment by jow-** [comment]
Hi,

thanks fpr looking nto it. I'd prefer separate subsequent PRs which then extend the sorting mechanism to other modules.

**Comment by kctani** [comment]
Jo, I have (hopefully) addressed all your concerns. I have tested with chrome 72 and IE 11. 
Do I need to test other browsers/versions?

**Comment by kctani** [comment]
I know it is usually the person who asks, but I wanted to know if there is anything more I need to do to have this pull request merged? 

Cheers, Ken

**Comment by jow-** [comment]
Didn‘t yet fine to thoroughly review it, hopefully tonight.

**Comment by kctani** [comment]
Thanks Jo.

**Comment by kctani** [comment]
Been two months now. Any chance you could look at this Jo?

**Comment by feckert** [comment]
This is the related feature request from the issue page.
https://github.com/openwrt/luci/issues/1491

**Comment by johny-mnemonic** [comment]
Thanks for all your effort so far @kctani !
Could you please resolve those conflicts so it is mergeable again?
Maybe we will be able to ask @jow- or other maintainers to check and merge it then.

**Comment by kctani** [comment]
Tomas,

I am guessing that this pull request has been abandoned. The user interface
design has moved on and the update I did is no longer appropriate.

Cheers,

Ken

**Comment by johny-mnemonic** [comment]
So if I understand it well, this would need completely new PR to the new UI code?

**Comment by kctani** [comment]
Yes, the changes are much simpler but entirely new.

**Comment by ristomatti** [comment]
> Yes, the changes are much simpler but entirely new.

@kctani If someone would like to attempt to redo the changes, do you happen to have any pointers where to look for? It appears the conflicting files don't even exist anymore... 

I can understand though if you're reluctant to put any more time into this.

**Pull request closed without merging**
