### PR TITLE
luci-app-privoxy: Added Hindi translation

### PR DESCRIPTION
**Pull request by gyr0tron**
Signed-off-by: Simmar Kalsi simmarkalsi@gmail.com

### CODE REVIEW

**Comment by feckert** [comment]
Please merge this two commits into only one commit.

**Comment by gyr0tron** [comment]
> Please merge this two commits into only one commit.

Done!

**Comment by feckert** [comment]
@hnyman we have no Hindi translation!
https://github.com/openwrt/luci/blob/0de1dcbf4a04940abf0e67d0f5f9e40523167cb1/luci.mk
What can we do to add this additional language?

**Comment by hnyman** [comment]
I don't think that it requires anything more than adding the language code and explanation to luci.mk.

Example from Korean, which seems to be the only language added in the past 5 year.s
https://github.com/openwrt/luci/commit/9d640e4c4ccd02ddb6234102724c34fe016aa5e8

**Comment by feckert** [comment]
@gyr0tron could you please update also luci.mk and add your language as mention in https://github.com/openwrt/luci/pull/2394#issuecomment-494062211

**Comment by gyr0tron** [comment]
> @gyr0tron could you please update also luci.mk and add your language as mention in [#2394 (comment)](https://github.com/openwrt/luci/pull/2394#issuecomment-494062211)

@feckert Done!

**Comment by feckert** [comment]
Sorry I know I'm annoying.
But could you please remove the double lines:

> Added privoxy Hindi translations
> 
> Signed-off-by: Simmar Kalsi <simmarkalsi@gmail.com>
> 
> Added privoxy Hindi translations
> 
> Signed-off-by: Simmar Kalsi <simmarkalsi@gmail.com>

In your commit!

**Comment by gyr0tron** [comment]
Haha! No worries! I think this should fix it!

**Pull request merged**
