### PR TITLE
 luci-mod-system: Fix broken JSON in ACL

### LINKED ISSUE #7126: luci-mod-system: Broken JSON for ACL
## Steps to reproduce:

1. Try to parse `/usr/share/rpcd/acl.d/luci-mod-system.json` e.g. using `jq`

## Actual behavior:

1. Get `jq: parse error: Expected another key-value pair at line 16, column 4`

## Expected behavior:

JSON is parsed correctly

## Additional Information:

This was seemingly broken by https://github.com/openwrt/luci/commit/2e4900eb43fe0687fb116e7defea4055b9c9b8a2

### PR DESCRIPTION
**Pull request by bluecmd**
- [x] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [x] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [x] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [ ] Tested on: (architecture, openwrt version, browser) :white_check_mark:
- [x] \( Preferred ) Mention: @ the original code author for feedback
- [x] \( Optional ) Closes: #7126
- [ ] Description: (describe the changes proposed in this PR)

Ping @systemcrash

### CODE REVIEW

**Comment by systemcrash** [comment]
Good! Thanks @bluecmd

**Comment by systemcrash** [comment]
Could you remove your double SOB line?

**Comment by bluecmd** [comment]
@systemcrash Woops, done

**Comment by systemcrash** [comment]
Excellent. Thanks @bluecmd

**Pull request merged**
