### PR TITLE
luci-app-nlbwmon: new package

### PR DESCRIPTION
**Pull request by jow-**
This commit introduces luci-app-nlbwmon, a frontend for nlbwmon, the
lightweight NetLink BandWidth Montor.

The nlbwmon daemon gathers per-host traffic statistics by querying netlink
accounting data. Due to this approach, the executable is very small and does
not rely on libpcap and CPU intensive raw sockets to monitor traffic.

Depends on PR https://github.com/openwrt/packages/pull/4646

Signed-off-by: Jo-Philipp Wich <jo@mein.io>

### CODE REVIEW

**Comment by jow-** [comment]
Screenshots:
1-host-display
2-protocol-display
3-family-display
4-data-export
5-config-advanced
6-config-general
7-config-protocols

**Comment by kuoruan** [comment]
Move to submenu of ```Status```?

**Comment by jow-** [comment]
I will consider moving it below status but I need to figure out how to best do it since it requires multiple items (Display, Config, Import/Export)

**Comment by hnyman** [comment]
@jow- 

Minor error:
if "Display" page is visited before the first database entry has been written to the database, stats are not displayed (which is natural), but uhttpd writes an error to the system log:

     Mon Jul 31 17:05:56 2017 daemon.err uhttpd[1889]: Unrecognized date 'undefined'

Apparently querying an empty database provides a result that does not suit the chart library well.

Additionally, installing the app with default settings can cause questions from users, as it may seem that the app does not work at all.  There was no data available for LuCI after running 10+ minutes. If I get the default config right, it takes 24h before the database file is first populated, right?  I got the app to display something only by restarting it, which forced a database write to  /var/lib/nlbwmon/

I fear that the initially empty database and getting first stats only after a day (?) will lead to unnecessary questions  as users do not get any visible output/stats for a rather long time. Or did I get the timing angle wrong?

But nice app in any case. Thanks. 👍

**Comment by hnyman** [comment]
Thanks, the change helps a lot.

You might also consider changing the default commit period from 24h to something much shorter as the default data location is on /var/lib that is ramdisk for most users. The 24h period may be useful for long-term monitoring, but I assume that many users will want to test the app right after installation, and the long default database update cycle makes data collection really slow.

Or alternatively, you might keep the "reload data" link/button visible all the time.

Additionally, the commit interval explanation in LuCI might be beefed up / clarified, as the the link between persistent database and LuCI reporting is not clear for casual users. Something like:

> Interval at which the temporary in-memory database is committed to the persistent database directory, which is also the source of data displayed in LuCI.

**Comment by jow-** [comment]
Will rework it tomorrow, actually there is an up-to-date in-memory database which is updated every 30s but it is only dumped when the data request is made without a timestamp argument.

Basically we just need to skip the most current accounting period in the select box and replace it with an empty value, then the dashboard should display the most current data in its default state.

**Comment by jow-** [comment]
Fixed with e276df205163425d43f7be04bd513569b26ad5b9

**Comment by hnyman** [comment]
Thanks jow, 
now it seems to work out of box pretty easily.

**Comment by hnyman** [comment]
@jow- 
Any objections against backporting this to 17.01? 
It should run pretty ok unmodified, right?

(the underlying kernel module depenency will make this hard to install into snapshots, and the interested novice users are on 17.01 in any case)

**Comment by hub2git** [comment]
Hi @jow and @hnyman  and everyone else.

Thank you for this program.

I'm a novice user running Luci 17.01. I just installed luci-app-nlbwmon and nlbwmon.

In the config section (http://i.imgur.com/RbYqHX1.png)
 I do see configuration for "Commit Interval". Some preset options are

24 h -- least flash wear at the expense of data loss risk
12 h -- compromise between risk of data loss and flash wear
10 m -- frequent commits at the expense of flash wear
60 s -- commit every minute, useful for non-flash storage

My WD MyNet 750 router comes with only flash storage. 
I want the best of both words (frequent backups without flash wear, so is there a way we can get luci-app-nlbwmon to save online (to the cloud)?

**Comment by halucigenia** [comment]
Wow,
Looks good. I have been struggling to get YAMon running on a router running LEDE without USB by trying to install to an NFS share.
I guess that I would only have to use an NFS share for the database directory to store one file per accounting period for luci-app-nlbwmon. However, would it be possible to configure it to store the real-time database on an NFS share and set "Commit Interval" to "60 s -- commit every minute, useful for non-flash storage" like hub2git's suggestion, but instead of using cloud storage using local NFS storage?

Would this also allow continuous monitoring for many accounting periods in a single file database?

This would be handy for anyone running NAS too.

**Comment by FangsMcWolf** [comment]
At the risk of sounding like a complete idiot, HOW do I get this?!  I need it!

**Comment by hnyman** [comment]
> HOW do I get this?! I need it!

Just install it via opkg. It is available just like all other packages both in LEDE master and in 17.01

**Comment by FangsMcWolf** [comment]
I have a Linksys WRT1200AC, running Chaos Calmer 15.05.1.  Is it unavailable to me on that version?  If so, how reliable is v17.01 (USS Enterprise) and where's a link on how to flash it?

**Comment by cabsandy** [comment]
Just found this, and seems a lot better than vnstat :-) Problem is, I have installed it via opkg install luci-app-nlbwmon nlbwmon -and it looks like it refuses to start (running LEDE Reboot 17.01.2 r3435-65eec8bd5f / LuCI lede-17.01 branch (git-17.152.82987-7f6fc16) on TP-Link TL-WDR3600 v1
On another LEDE install I can see the process running:
root@OpenWrt:~# top | grep nlbwmon
 2161     1 root     S     1576   3%   0% /usr/sbin/nlbwmon -o /var/lib/nlbwmon
 2161     1 root     S     1576   3%   0% /usr/sbin/nlbwmon -o /var/lib/nlbwmon
 2161     1 root     S     1576   3%   0% /usr/sbin/nlbwmon -o /var/lib/nlbwmon

but on the offending machine, I dont see this-which is probably why the circles are all grey :-)

Any idea? I have tried re-installing, stopping and starting the service but no joy-even stopped vnstat, in case that was causing the issue-but nope. I can only assume something is conflicting with it somewhere....

cheers
cabs

**Comment by rajil** [comment]
is it possible to differentiate bandwidth per WAN connection? I am using mwan3 with a dual WAN setup. This package does not take into account which WAN connection is used.

**Comment by mrobo11** [comment]
can someone post how to generate backup trough cli?

**Comment by AsianDesignMajor** [comment]
@jow- ,

I'm just this week getting into the world of OpenWRT 22.03.2, and this is EXACTLY what I was looking for to monitor WAN traffic (my ISP has a 1.2TB data cap every month, so it's helpful to see how close I get to it, and how).

I notice that this code hasn't been modified much since 2017, do I see that correctly?  Everything looks good, except the column sort function - so 900 KB is listed above 1.46 GB because 900 > 1.46, for example.  Easy fix?

I see your DB is written to /var/lib/nlbwmon, but if I change the location to /overlay/nlbwmon (where my USB drive, /dev/sda1, is mounted) will it move all files automatically, or "start over" and require me to do a "cp [old files] [new files]" kind of thing in SSH?

Again, thanks!

**Pull request merged**
