### PR TITLE
luci-theme-material: add missing css cbi-section-error definitions

### PR DESCRIPTION
**Pull request by feckert**
Add the missing error css class definitions.
Highlights the wrong inputs detected by the cbi validation function.

### CODE REVIEW

**Comment by dibdot** [comment]
@feckert could you please add the new ".cbi-progressbar" stuff as well? Currently the overview page is a bit empty with material theme ... ;-)

**Comment by feckert** [comment]
@dibdot I'll take care of it next week.

**Comment by jow-** [comment]
I think the material and rosy themes need way more changes. Off the top of my head they need CSS for the progress bars, the modal overlays and not sure if the tooltip bubbles need fixing too.

**Comment by jow-** [comment]
Merged, thanks!

**Pull request merged**
