### PR TITLE
use translatef instead of translate

### PR DESCRIPTION
**Pull request by ce-4**
This hopefully fixes translation strings to allow different word order due to other foreign grammar rules (e.g. German).

### CODE REVIEW

**Comment by jow-** [comment]
Syntactically it looks fine. Could you runtime test it?

**Comment by ce-4** [comment]
Yes, but that would have to wait til tomorrow, i have a box with 19.07.2 at hand.

**Comment by stangri** [comment]
Runtime tested on 18.06.8/theme-OpenWrt and it runs just fine.

Since the signoff is missing, should we wait for @ce-4 to push the updated commit or should I create separate PRs for master/19.07/18.06 branches now?

**Comment by ce-4** [comment]
Sorry for creating additional work - I have not uploaded a signing key yet, will do that now. If you don't mind you can create the PRs or wait a bit and i will sign it.

I have also checked it on a 19.07.2, looks good to me. I noticed that the value in the brackets of the tmpfsVersion value is empty with both versions of simple-adblock.lua on my box (but i just started using simple-adblock):
"Simple AdBlock Settings
Service Status []"

**Comment by hnyman** [comment]
> I have not uploaded a signing key yet

No need for that.
Just add the required "Signed-off-by:" line to your commit message.
Amend the commit, and force push the PR branch.

**Comment by hnyman** [comment]
Note that the commit title is also wrong. It should atrat with the app name:

`luci-app-simple-adblock: use translatef instead of translate`

**Comment by stangri** [comment]
@hnyman should I submit the patches for 19.07 and 18.06 branches?

**Pull request merged**
