### PR TITLE
luci-app-advanced-reboot: drop luci-compat dependency

### PR DESCRIPTION
**Pull request by brvphoenix**
This package has converted to client side and doesn't need `luci-compat` any more.

### CODE REVIEW

**Comment by stangri** [comment]
Hello Van,

I don't have access to a dual-boot router at the moment, which model/OpenWrt version have you tested the updated IPK on? Was the `luci-compat` manually removed prior to testing?

Thanks!

**Comment by brvphoenix** [comment]
> Hello Van,
> 
> I don't have access to a dual-boot router at the moment, which model/OpenWrt version have you tested the updated IPK on? Was the `luci-compat` manually removed prior to testing?
> 
> Thanks!

I run the updated IPK on platform x86_64 but have not tested on dual-boot router.

I have checked the codes and doesn't find they use the `luci-compat`. Maybe I'm wrong.

Ping @Ansuel

**Comment by hnyman** [comment]
> have not tested on dual-boot router.

So this is completely untested on the main target, dual partition routers ?????
You really should have mentioned that in the PR description.

(testing needs a build for dual-partition routers, made so that other packages do not pull luci-compat into build. I will see if I can made a really-stripped-down test build for my wrt3200acm)

**Comment by hnyman** [comment]
I tested with a stripped-down build with this change for WRT3200ACM.
Both "reboot to current" and "reboot to alternative" work ok.

(As the automatic main LuCI version changes with the git commit, I do not see an immediate need for PKG_RELEASE bump)

**Comment by Ansuel** [comment]
Any dependency with Luci compat is not needed. The PKG is full js. LGTM

Il Ven 18 Dic 2020, 10:00 Hannu Nyman <notifications@github.com> ha scritto:

**Comment by stangri** [comment]
The package still depends on lua being present in the system. @Ansuel -- I can take a crack at re-writing luci.advanced_reboot in shell script, but I have a few questions, do you mind if I email you directly? 

For now tho, I think it would be wise to add dependency on lua to the Makefile. Would it be the principal lua package then, not `liblua` nor `libubus-lua`, right?

**Comment by Ansuel** [comment]
Sure feel free to email me

Il Sab 26 Dic 2020, 21:36 Stan <notifications@github.com> ha scritto:

**Comment by hnyman** [comment]
> For now tho, I think it would be wise to add dependency on lua to the Makefile. 

There is already an indirect dependency to lua via luci-mod-admin-full. 
Not sure why this app would require more.

(Typically extra dependencies to low-level libraries already referenced in the dependency chain, tend to cause more trouble than benefits.)

**Comment by stangri** [comment]
> There is already an indirect dependency to lua via luci-mod-admin-full.

Oh, didn't realize it has dependency on lua. I was reading that lua is to be dropped from default packages eventually and was thinking of that eventuality.

**Pull request merged**
