### PR TITLE
luci-app-aria2: fix typos

### PR DESCRIPTION
**Pull request by urbalazs**

### CODE REVIEW

**Comment by feckert** [comment]
Please update the commit header with
luci-app-aria2: \<your message\>

**Comment by urbalazs** [comment]
@feckert commit message updated

**Comment by feckert** [comment]
@aparcar  this change by @urbalazs will change the translation. 
Is that compatible with weblate? I am not familar with this.
I think add new translation is no problem but a change of a translation?

**Comment by aparcar** [comment]
@feckert I thikn you have to run `./build/i18n-sync.sh` and add the changed POT files.

**Comment by hnyman** [comment]
From the perspective of preserving the already existing translations, it would be best to use sed to edit those changed "msgid" English lines in all *.po files (at least those that actually have translations). Then the existing translations would live on as they translation key matches the new .pot 

Otherwise the i18n-sync.sh will mark those existing translation as unknown. 

There are some translations (at least de, es, fr,  pt, zh-cn):
```
perus@ub1910:/Openwrt/github/luci/applications/luci-app-aria2/po$ grep -r -C 1 "Sava metadata" */*.po
bg/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
bg/aria2.po:msgid "Sava metadata"
bg/aria2.po-msgstr ""
--
ca/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
ca/aria2.po:msgid "Sava metadata"
ca/aria2.po-msgstr ""
--
cs/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
cs/aria2.po:msgid "Sava metadata"
cs/aria2.po-msgstr ""
--
de/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
de/aria2.po:msgid "Sava metadata"
de/aria2.po-msgstr "Speichere Metadaten"
--
el/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
el/aria2.po:msgid "Sava metadata"
el/aria2.po-msgstr ""
--
en/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
en/aria2.po:msgid "Sava metadata"
en/aria2.po-msgstr ""
--
es/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
es/aria2.po:msgid "Sava metadata"
es/aria2.po-msgstr "Guardar metadatos"
--
fr/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
fr/aria2.po:msgid "Sava metadata"
fr/aria2.po-msgstr "Enregistrer les métadonnées"
--
he/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
he/aria2.po:msgid "Sava metadata"
he/aria2.po-msgstr ""
--
hi/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
hi/aria2.po:msgid "Sava metadata"
hi/aria2.po-msgstr ""
--
hu/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
hu/aria2.po:msgid "Sava metadata"
hu/aria2.po-msgstr ""
--
it/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
it/aria2.po:msgid "Sava metadata"
it/aria2.po-msgstr ""
--
ja/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
ja/aria2.po:msgid "Sava metadata"
ja/aria2.po-msgstr ""
--
ko/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
ko/aria2.po:msgid "Sava metadata"
ko/aria2.po-msgstr ""
--
ms/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
ms/aria2.po:msgid "Sava metadata"
ms/aria2.po-msgstr ""
--
nb_NO/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
nb_NO/aria2.po:msgid "Sava metadata"
nb_NO/aria2.po-msgstr ""
--
pl/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
pl/aria2.po:msgid "Sava metadata"
pl/aria2.po-msgstr ""
--
pt/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
pt/aria2.po:msgid "Sava metadata"
pt/aria2.po-msgstr "Gravar metadados"
--
pt-br/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
pt-br/aria2.po:msgid "Sava metadata"
pt-br/aria2.po-msgstr ""
--
ro/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
ro/aria2.po:msgid "Sava metadata"
ro/aria2.po-msgstr ""
--
ru/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
ru/aria2.po:msgid "Sava metadata"
ru/aria2.po-msgstr ""
--
sk/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
sk/aria2.po:msgid "Sava metadata"
sk/aria2.po-msgstr ""
--
sv/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
sv/aria2.po:msgid "Sava metadata"
sv/aria2.po-msgstr ""
--
tr/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
tr/aria2.po:msgid "Sava metadata"
tr/aria2.po-msgstr ""
--
uk/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
uk/aria2.po:msgid "Sava metadata"
uk/aria2.po-msgstr ""
--
vi/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
vi/aria2.po:msgid "Sava metadata"
vi/aria2.po-msgstr ""
--
zh-cn/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
zh-cn/aria2.po:msgid "Sava metadata"
zh-cn/aria2.po-msgstr "保存元数据"
--
zh-tw/aria2.po-#: applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua:315
zh-tw/aria2.po:msgid "Sava metadata"
zh-tw/aria2.po-msgstr ""

```

**Comment by urbalazs** [comment]
@feckert Translations are managed on Weblate. Please let Weblate to do this stuff. You only have to provide an up-to-date POT file for Weblate, and Weblate will inform the translators about the changes and it wil provide the translated PO files for this project.

Is it still expected from me to sync translations manually?

**Comment by hnyman** [comment]
> Is it still expected from me to sync translations manually?

It would at least be preferrable, when you aim to invalidate existing translations due to (mainly) cosmetic changes.

**Comment by urbalazs** [comment]
To preserve existing translations:

1. Please merge my pull request.
2. Run the following commands:

```
for lang in `ls applications/luci-app-aria2/po/`; do sed -i 's/Sava metadata/Save metadata/g' applications/luci-app-aria2/po/$lang/aria2.po; done
```

Can you please do this? Or should I modify the existing PO files via a new commit for this PR?

**Comment by feckert** [comment]
Please open an new pull request.
As done with
https://github.com/openwrt/luci/pull/3417
and
https://github.com/openwrt/luci/pull/3416
I am not able to resolve the conflicts

Also execute this.
 ```
for lang in `ls applications/luci-app-aria2/po/`; do sed -i 's/Sava metadata/Save metadata/g' applications/luci-app-aria2/po/$lang/aria2.po; done
```

**Comment by urbalazs** [comment]
@feckert conflicts solved, please merge this PR with ``--squash``. The diff against master is correct now.

**Comment by feckert** [comment]
Thanks merged

**Pull request merged**
