### PR TITLE
package/community-profiles: add freifunk cottbus profile

### PR DESCRIPTION
**Pull request by marcel-sch**
new community cottbus, config based on profile_berlin at kathleen

### CODE REVIEW

**Comment by hnyman** [comment]
You should sign you commits.

**Comment by marcel-sch** [comment]
hello, i am new at git(hub) and at the moment i use the webinterface of github only
sorry, but i am learning

**Comment by FreifunkUFO** [comment]
did you check you settings before so they work properly? would be nice if they could working also with  meshkit imagebuilder http://meshkit.freifunk.net and normal (non-specially-berlin) openwrt-luci meshwizard 

you was deleting "mesh_network", it think you may need that!?
please be careful with copying berlin settings:
channel within freifunk wifi networks for bssid "02:ca:ff:ee:ba:be" is normally 01!  berlin has special historically settings to be on ch10.

**Comment by FreifunkUFO** [comment]
please change title of your pull request to
package/community-profiles: add freifunk cottbus profile

**Comment by marcel-sch** [comment]
we want to use the firmware kathleen in our community and it will be the best to have our own community-profile. do you think that is ok? i took over your suggestions:

config community 'profile'
	option ssid_scheme 'addchannelbefore'
	option splash_prefix '27'
	option name 'Freifunk Cottbus'
	option homepage 'http://cottbus.freifunk.net'
	option splash_network '10.35.0.0/16'
	option mesh_network '10.35.255.0/24'
	option latitude '51.757689'
	option longitude '14.328879'
	option ssid 'cottbus.freifunk.net'

config defaults 'wifi_device'
	option channel '13'

config defaults 'wifi_device_5'
	option channel '36'

config defaults 'wifi_iface'
	option mcast_rate '6000'

config defaults 'wifi_iface_5'
	option mcast_rate '12000'

config defaults 'bssidscheme'
	option 1 '02:CA:FF:EE:BA:BE'
	option 13 'D2:CA:FF:EE:BA:BE'
	option 36 '02:36:CA:FF:EE:EE'

config defaults 'ssidscheme'
	option 13 'intern-ch13.freifunk.net'
	option 36 'intern-ch36.freifunk.net'

config defaults 'interface'
	option netmask '255.255.255.255'
	option dns '85.214.20.141 213.73.91.35 194.150.168.168 2001:4ce8::53 2001:910:800::12'

config dhcp 'dhcp'
	option leasetime '5m'

**Comment by FreifunkUFO** [comment]
if you want to use it with berlin-kathleen openwrt firmware you will need almost ALL that berlin settings, including that olsr-RT-tables settings..?

where does that dhcp-lease time setting: 5minutes come from? 
splash-network and mesh-network cant be at the same subnet, or did you checked that behaviour already?

about firmware: berlin-katleen wizard is a fork from luci/meshwizard (freifunk).. 
the meshkit is a webfrontend for meshwizard. so it would be nice that your setting would also fit with meshwizard. 

please dont post changes via comment, better change these directly in your file within this pull-request :-o

**Comment by marcel-sch** [comment]
i have found http://doc.meshkit.freifunk.net/daily/html/communities/profiles.html and used it to create a "new" profile with basic information

**Comment by FreifunkUFO** [comment]
please have a look into other profiles again. mcast-rate should be set, for berlin katleen you may need some berlin specific settings.
do you have contact to berlin to ask for proper settings?

**Comment by marcel-sch** [comment]
i have looked at the profiles of Potsdam and Berlin, which are using kathleen and so i created that profile

**Comment by jow-** [comment]
So is this profile good for merging?

**Comment by FreifunkUFO** [comment]
i dont know..
f.i. now that "config defaults interface option netmask 255.255.255.255" is missing in files, but its only in the comments here.
unfortunately the berlin profile also isnt up-to-date here. they decided to patch that within kathleen-firmware-build to proper values at https://github.com/freifunk-berlin/firmware/blob/master/patches/015-profile_berlin.patch

**Comment by marcel-sch** [comment]
i hope it is ok now
that version is related to:
http://wiki.freifunk.net/Freifunk-Firmware/Community-Profile with looking at severals profiles of https://github.com/marcel-sch/luci/blob/patch-1/contrib/package/community-profiles/files/etc/config/

**Comment by FreifunkUFO** [comment]
yes, @jow- please merge it..
dhcp-lease time is very short, but should be ok for starting this profile..

**Comment by marcel-sch** [comment]
in our opinion it is ok, so please merge it

**Comment by jow-** [comment]
Merged, thanks!

**Pull request merged**
