### PR TITLE
luci-theme-material: Use description field as page title if set

### PR DESCRIPTION
**Pull request by majik-sheff**
The page title defaults to the hostname.  If the "description" option is set in the system config, use it instead.

Signed-off-by: Tim Thorpe <timfthorpe@gmail.com>

### CODE REVIEW

**Comment by feckert** [comment]
I am not entirely convinced. The description can be quite long and consist of several words.

**Comment by feckert** [comment]
Then why isn't the hostname enough for you?

**Comment by majik-sheff** [comment]
I have a bunch of devices that get moved around to different sites/jobs.  It's nice to be able to change the displayed title without changing the hostname.

**Comment by feckert** [comment]
I just see the problem that the option description can be quite long.
And your change always adds this to the title when the description option is set.

Maybe we should add a config option to also show this in the title?

**Pull request closed without merging**
