### PR TITLE
luci-app-setup-wizard: add new application

### PR DESCRIPTION
**Pull request by rosysong**
This application is design for the users who are new to OpenWrt or the people want to use OpenWrt but do not have professional background.

Setting parameters of OpenWrt devices has never been so easy as it is now, this app can guide users to initialize their device within 2 steps, including Internet Access, WiFi. That's most family users need (gain pppoe account from isp and use it connect to internet).

## Notes
notes

## Internet Access
internet

## WiFi
wifi

## Done
done

Enjoy it!!!

Signed-off-by: Rosy Song <rosysong@rosinson.com>

### CODE REVIEW

**Comment by rosysong** [comment]
@hnyman @jow-

**Comment by hnyman** [comment]
The app seems to take for granted that there is pppoe and a single radio.

pppoe is not used that often, so the first step will be confusing for many users. 
Similarly, there is no info about which radio is being setup. It varies by the router, if 2.4GHZ or 5GHz is radio0

I feel that this app tries to oversimplify things.

**Comment by aparcar** [comment]
I think this is generally a great idea!

Please add a dialog for default password.

Regarding 2.4 and 5GHz, I'd suggest to offer a single ESSID/Password form for both with an additional checkbox a la "Enable 5GHz" - if actually supported by hardware. Different names for 2.4/5GHz make no real sense for non-techies, huh?

Also it would be interesting to have this pop up instead of the default Luci Login page, giving whoever the possibility to hand a freshly flashed router to non-technical-users.

**Comment by rosysong** [comment]
@aparcar  Thanks, and I agree with your advice that replacing the LuCI login page when the firmaware is freshly flashed or return to firstboot status. This really can issue users, especially non-technical-users, to setup their unconfigured router.

**Comment by feckert** [comment]
I think this is a very good proposal.
We can't cover all the possibilities.
I think we should start with the standard scenario and if something is missing we could add the missing config options.

**Comment by aparcar** [comment]
I'd be very much in favor to have a feature like that! However the current approach relies on Lua whereas ubus call would be a cleaner and more generic solution. @rosysong could you refactor your code to use ubus?

**Comment by rosysong** [comment]
It's been a long time since I push this PR, well, I will refactor the code.

And, would you please comment in the code view or tell me where should I replace the approach with ubus call?

**Comment by aparcar** [comment]
Dear @rosysong , sorry for the long delay! Some time ago [I posted in the forum](https://forum.openwrt.org/t/common-use-case-for-simplified-web-interface/38866) for ideas of a simplified web interface. The idea is basically a LCi web interface doing multiple steps at once, instead of 1 by 1 configuring of options. Therefore, pretty much what your wizard does.

Regarding refactoring, I'd be happy to see some rpcd shell scripts (or later even C) modifying UCI values to the desired state. The web interface could then call those scripts with parameters (like WiFi name or password).

I'd be in favor to avoid Lua scripts at this state, if that would work for you. If not I'm sure those backend scripts are easily portable to other languages in the later run.

**Comment by rosysong** [comment]
@aparcar  Glad to see that you noticed this.
1. Both of them can works fine whether use rpcd Shell scripts or Lua scripts. For the As the first version, making it work is the first priority.

2. I agree with you opinion that to refactor this PR, and to have this pop up instead of the default Luci Login page. I'll update my commit once I done.

**Comment by aparcar** [comment]
> Both of them can works fine whether use rpcd Shell scripts or Lua scripts. For the first version, making it work is the first priority. On the other hand, as @feckert said, we can't cover all the possibilities, just for the most common scenario.

Other router vendors already created (from my point of view) [very good](https://docs.gl-inet.com/en/3/setup/mini_router/first-time_setup/) interfaces with a focus on use cases rather than fine granular configuration. Maybe this could be used as an inspiration. 

> I agree with you opinion that to refactor this PR. The "simple" interface you described looks better than the wizard I pushed. Do you mean to have this pop up instead of the default Luci Login page ? I'll update my commit once I done.

Again, my personal view, having two tabs like "simple" and "advanced" allowing to switch between the two modes. Therefore yes, after a login it could pop up per default.

**Pull request closed without merging**
