### PR TITLE
i18n-ru: fixed russian translation

### PR DESCRIPTION
**Pull request by user7887**
Signed-off-by: Vladimir <picfun@ya.ru>
http://cyber-place.ru/showpost.php?p=39011&postcount=66
http://cyber-place.ru/showpost.php?p=38478&postcount=23
http://cyber-place.ru/showpost.php?p=38252&postcount=16
http://cyber-place.ru/showpost.php?p=38527&postcount=31
http://cyber-place.ru/showpost.php?p=38480&postcount=25

### CODE REVIEW

**Comment by user7887** [comment]
@hnyman
I'm too old for this :)
And the young man doesn't know what he's doing....

**Comment by user7887** [comment]
@hnyman
I have everything ready, I insist on taking this option. This is my last big edit. Thank You!

**Comment by hnyman** [comment]
I will merge your changes, but please keep a bit pause and let's see, if there is more feedback from other Russian speaking users.

**Comment by user7887** [comment]
@hnyman 
Yes of course thank you!
Major changes have been made.

**Pull request merged**
