### PR TITLE
luci-mod-admin-full: add dependency for channel auto

### PR DESCRIPTION
**Pull request by HenryGiraldo**
Do not show 'auto' channel option if hostapd is not compiled with CONFIG_ACS

Signed-off-by: Enrique Giraldo <enrique.giraldo@galgus.net>

### CODE REVIEW

**Comment by HenryGiraldo** [comment]
It is also necessary to apply this patch to the hostapd.

[0001-hostapd-add-acs-feature-indication.txt](https://github.com/openwrt/luci/files/2392534/0001-hostapd-add-acs-feature-indication.txt)

This new feature is very interesting because if you set the channel to auto and the hostapd hasn't been compiled with ACS, the radios don't work.

**Comment by feckert** [comment]
Please remove the last commit
https://github.com/openwrt/luci/pull/2158/commits/adbb096e857896b6af547f4fd413d82f2331c10b
This doesn't look okay so we could not merge this.

**Comment by HenryGiraldo** [comment]
I just did, but there seems to be some conflict left. I can't see them, I pulled the upstream/master and it doesn't give me any problem cherrypicking the commit.

**Comment by feckert** [comment]
Maybe you could close this pullrequest and open a new one.

**Pull request closed without merging**
