### PR TITLE
luci-app-example: Update with more documentation, more examples

### PR DESCRIPTION
**Pull request by cricalix**
Summary
=======

The existing luci-app-example is very basic, and provides very little context to someone just getting started with LuCI development.

The changes in this PR are basically "I wish I'd had this information and context available to me", as I've recently worked on a PR to provide a UI for AdGuard Home, and it took me several days of hunting around in the wiki, other LuCI apps, and general 'net searches.

Documentation changes:

* add a structure.md file to explain the structure of a LuCI app
* add a BUILDING.md file to provide a quick overview of how to build the .ipk file for the app
* add a YAML.md to detail working with YAML files
* update README.md with some details about the Javascript files in the example
* update README.md with a note about ACLs
* update README.md with a note about translations

ACL changes:

* update the ACL file based on testing, removing unused grants

Code changes:

* update the menu file with links to the new Javascript UI files
* add RPC examples for a dedicated ubus RPC endpoint that's not UCI
* add a Lua script to answer RPC requests via rpcd

The Lua script demonstrates a few techniques, such as

* converting Lua tables to JSON
* argument parsing, with explanation about why it's done this way (luci.ddns did not explain the logic, nor did the wiki)
* how to test the Lua script without ubus
* how to test the Lua script with ubus

Three variants of the rpc.js file are provided. The first one is just calling RPC endpoints and rendering what could be equated to a status page; editing is turned off. The second and third call the same RPC endpoint, and demonstrate two different layout approaches - TableSection vs TypedSection.

Notes
=====

This is a re-spin of https://github.com/openwrt/luci/pull/5857, due to a ton of conflicts when trying to rebase my original PR via git commands. @jow- 's feedback about the YAML code has been taken on board, and split out to documentation that someone has to manually apply.

Testing
=======

All testing has been manual.

ACLs were refined by moving acl.d/luci-compat.json out of the way to see what broke in the UI, and then tweaking the ACLs until the UI worked again.

Arg parsing for the Lua script is based on the luci.ddns script, and it feels like the parseInput and validateArgs functions should be a core library so that Lua scripts for rpcd have a unified way of working.

Signed-off-by: Duncan Hill <github.com@cricalix.net>

### CODE REVIEW

**Comment by openwrtdiy** [comment]
Thanks for the update submission! My feedback is coming!
Hostname OpenWrt
Model D-Team Newifi D2
Architecture MediaTek MT7621 ver:1 eco:3
Target Platform ramips/mt7621
Firmware Version OpenWrt 23.05-SNAPSHOT r23334-f60829f5ac / LuCI pppoe-23.05 branch git-23.205.71256-0395ac5
Kernel Version 5.15.123

When I click the drop-down menu RPC Array Example of Example, I get an error message!

**ReferenceError
load_sample_yaml is not defined**

**Comment by openwrtdiy** [comment]
The screenshot of the compiled effect is as follows:

**Form View**


**HTML Page**


**RPC JSONMap Table Example**


**RPC JSONMap Typed Example**

**Comment by cricalix** [comment]
Ta for the check, fixed and tested properly on my Pi.

**Comment by openwrtdiy** [comment]
> Ta for the check, fixed and tested properly on my Pi.

OK,to confirm the fix display issue

**RPC Array Example**

**Review by stokito — APPROVED** [review]

**Comment by feckert** [comment]
This is to be a starting point for future developers, then we should also use tabs and not spaces. This is not mandatory, but tabs are used for indentation in all LuCI and not spaces.

**Comment by feckert** [comment]
Looks good.
* Could you then remove the merge commit.
* Please remove @feckert from the commit header I will always get a highlighted when this commit is used on Github.

**Comment by stokito** [comment]
Can we just merge it as is? This is example app that is not affects anyone on production.
But it will significantly help to new contributions.

Contributing to the Luci is too viscous. If you have a commit access then you can merge and just fix minor problems yourself. Contributiors work on their own job and sending PRs in a limited spare time.

**Comment by systemcrash** [comment]
Merged, thank you @cricalix

**Comment by zerounu** [comment]
The rpc examples are based on LUA which is not installed by default and i believed that i read somewhere that OpenWRT programmers are dropping support for it. Is LUA the only way to make RPC examples work ?

**Comment by jow-** [comment]
> Is LUA the only way to make RPC examples work ?

The examples in this example app are outdated. You can write rpcd plugins in any language (Shell scripts, Lua scripts even compiled C programs or Python scripts) as the interface is STDIO based. The rpcd daemon will invoke the plugin executable and send the received request parameters as JSON to stdin and read the intended reply as json from the plugin programs stdout.

Additionally, rpcd supports ucode scripts natively which simplifies plugin creation.

See ucode examples here:
- https://github.com/openwrt/luci/blob/master/applications/luci-app-upnp/root/usr/share/rpcd/ucode/luci.upnp
- https://github.com/openwrt/luci/blob/master/protocols/luci-proto-wireguard/root/usr/share/rpcd/ucode/luci.wireguard

STDIO based shell script example here:
- https://github.com/openwrt/luci/blob/master/applications/luci-app-olsr/root/usr/libexec/rpcd/olsrinfo
- https://github.com/openwrt/luci/blob/master/applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

Lua based example is contained in luci-app-example.

**Pull request merged**
