### PR TITLE
luci-mod-network: typo-fix: APR -> ARP

### PR DESCRIPTION
**Pull request by 532910**
- [x] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [x] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [x] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages

### CODE REVIEW

**Comment by systemcrash** [comment]
Good! This change alienates its corresponding translations. Can you update the 'eng' versions for all translation strings in master too?

**Comment by 532910** [comment]
Updated!

**Comment by systemcrash** [comment]
Fix subject line of last commit

**Comment by 532910** [comment]
fixed

**Comment by systemcrash** [comment]
Merged. Good work. Thanks!

**Pull request merged**
