### PR TITLE
luci-mod-system: update LED i18N trigger translation

### PR DESCRIPTION
**Pull request by feckert**
@hnyman Is this OK from you?
With this pullrequest I18N translation should be adapted, so it is clear what this trigger does.

### CODE REVIEW

**Comment by hnyman** [comment]
If that is just text, looks ok to me.

**Comment by feckert** [comment]
@hnyman yes that are only translation changes.
thanks for watching

**Comment by hnyman** [comment]
Please also run i18n-sync and then commit the necessary changes, so that the change actually gets propagated to the luci-base .pot file

**Comment by feckert** [comment]
Sorry I am not on my workstation. My first point tomorrow is to update
this. Thanks for the hint.

Hannu Nyman <notifications@github.com> schrieb am Mo., 4. Mai 2020, 17:12:

**Comment by hnyman** [comment]
PS. one practical advice:  to avoid merge errors in weblate, or at least decreae their probability, please merge the possible weblate PR first.

**Pull request merged**
