### PR TITLE
luci-proto-modemmanager: add support to manage ModemManager interfaces…

### PR DESCRIPTION
**Pull request by nickberry17**
luci-proto-modemmanager: add support to manage ModemManager interfaces in LuCI

Signed-off-by: Nicholas Smith <mips171@icloud.com>

### CODE REVIEW

**Comment by feckert** [comment]
I do not find any modemmanager application **mmcli** in any core package or packages feed.
So if we add this proto we should also add first mmcli.

**Comment by nickberry17** [comment]
Check with Aleksander Morgato over at freedesktop.org.  He has a feed for ModemManager and mentioned a couple of times that he mentioned he wanted to merge.  https://gitlab.freedesktop.org/mobile-broadband/mobile-broadband-openwrt

**Comment by feckert** [comment]
Sorry I do not that someone already wants to merge the modemmanger package.
So if we want  the luci-proto-modemmanger included into to luci we have to merge the modemmanger first. Feel free to open a pullrequest for this package in the OpenWrt package feed.

**Comment by nickberry17** [comment]
Thanks for your review.  Work has already started on getting MM into the OpenWrt package feed, hopefully you will see some activity soon.  I have also added the Apache 2 license with SPDX identifiers and moved the files out of a nested directory.

**Comment by nickberry17** [comment]
Working on it
https://github.com/openwrt/packages/pull/9137

**Comment by hnyman** [comment]
Several conflicts and over 300 commits. 

> @nickberry17 pushed 250 commits.

Looks like you have tried to refresh the branch from master, but you have not used "git rebase master" properly.

**Comment by nickberry17** [comment]
Oops, sorry

**Pull request closed without merging**
