### PR TITLE
luci-mod-system: zram fixes

### PR DESCRIPTION
**Pull request by rsalvaterra**
Update luci-mod-system/zram to reflect the lastest zram-swap changes.

**NOTE**: This is **completely untested**. My motivation to test LuCI is zero, as I personally don't use it at all.

### CODE REVIEW

**Comment by hnyman** [comment]
Note that your cosmetic spelling changes with 291a61fb invalidate all translations.

**Comment by rsalvaterra** [comment]
> Note that your cosmetic spelling changes with [291a61f](https://github.com/openwrt/luci/commit/291a61fb36e2837c5eb3ad328961dacc1b9b9455) invalidate all translations.

Ugh… Fine, I can drop that, for the time being. 😕

**Comment by hnyman** [comment]
Please do that.
The other two commits seem to be in line with OpenWrt itself

**Comment by rsalvaterra** [comment]
> Please do that.

Alright, done.

**Comment by rsalvaterra** [comment]
That was fast, thanks! 🙂

**Pull request merged**
