### PR TITLE
applications: add luci-app-pptpd

### PR DESCRIPTION
**Pull request by mumuqz**
Signed-off-by: Jing Lin mumuqz@163.com

### CODE REVIEW

**Comment by build000** [comment]
Very practical (... and how to show guides on many forums - much awaited) plug luci - provided that the i18n be for all supported languages

**Comment by mumuqz** [comment]
@build000 Add en and zh_tw language support.

**Comment by hnyman** [comment]
Adding the translation looks nice. Could you please run ``` ./build/i18n-sync.pl ``` in the Luci root directory (and then git add the re-sorted .po / .pot files of this  app). That command would sort the language files.

**Comment by hnyman** [comment]
After your language changes, I would have merged this LuCI app, but then I noticed that you have included files that belong to the actual pptpd package (in the packages repo: https://github.com/openwrt/packages/tree/master/net/pptpd/files ) and your changs would partially conflict with files in the main package. 

You should remove the /etc/init.d/pptpd , /etc/config/pptpd and /etc/ppp/options.pptpd files, and get the possibly needed changes added to the main package instead.  https://github.com/openwrt/packages/tree/master/net/pptpd  . (And it looks to me that you have converted the init script to an older version instead of the more modern procd version. That will likely not fly.)

**Comment by jow-** [comment]
This package also injects iptables rules using sed and firewall.user, this looks rather unclean to me (it also unconditionally allows traffic from `ppp+` which would also open `pppoe-wan` which is likely *not* intended).

This PR should either leave the firewall management aside for now - or - convert it to use uci & /etc/config/firewall - this way it also plays nice with the generic firewall ui.

**Pull request closed without merging**
