### PR TITLE
luci-app-minidlna: Colons removed

### PR DESCRIPTION
**Pull request by ameer1234567890**
Colons have been removed as asked in #1566

### CODE REVIEW

**Comment by namedun** [comment]
You could squash the 3 commits into a single one

**Comment by dibdot** [comment]
Please sign off your commit, everything else looks good to me.

**Comment by ameer1234567890** [comment]
Done

**Comment by dibdot** [comment]
@ameer1234567890 Still, I don't see your sign-off, please check https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md for details. Aside from that there are now two conflicting files in your commit , please clean up your commit and amend your changes (incl. your sign-off) - thanks.

**Comment by ameer1234567890** [comment]
I could not fix it, so opened a new PR #2068

**Pull request closed without merging**
