### PR TITLE
luci-app-nft-qos: Remove the redundant MAC address of the static IP speed limit

### PR DESCRIPTION
**Pull request by openwrtdiy**
The following development versions of OpenWrt can remove the old IP address static redundant MAC form option:
	OpenWrt 23.05
	OpenWrt 22.03
	OpenWrt 21.02

### CODE REVIEW

**Comment by hnyman** [comment]
Those are not "development versions" but stable releases.
Is there a reason why you are doing this change to the old stable branch 23.05 and not first to the development master?

Your commit is missing the signed-off-by line.

I am trying to understand the actual issue:

Is this a correction to https://github.com/openwrt/luci/commit/1166050fd34619b6cd9248c19ef40d11585c8d1e by @lzto that removed the macaddr option from download (lines 135-138) but left it for upload (lines 170-172) ?

**Comment by openwrtdiy** [comment]
> Is this a correction to [1166050](https://github.com/openwrt/luci/commit/1166050fd34619b6cd9248c19ef40d11585c8d1e) by @lzto that removed the macaddr option from download (lines 135-138) but left it for upload (lines 170-172) ?

Yes! This fix fixes the display issue!

**Comment by openwrtdiy** [comment]
Fix previous display
下载

Vs

Display after repair
下载 (1)

**Comment by openwrtdiy** [comment]
I accidentally synced the official openwrt source code!  You can continue
to fix! I want to upgrade nft-qos to version 2.0, merged into one column:
host, upload rate, download rate, rate unit!  I have tested three speed
limit schemes: single ip address, ip network segment, and mac address all
take effect!  But the code changes a lot!

Hannu Nyman ***@***.***> 于 2023年7月27日周四 23:04写道：

**Comment by hnyman** [comment]
I applied your original small fix to master and 23.05

**Comment by openwrtdiy** [comment]
thank you for your help!  I will provide a new version later for everyone
to discuss!  power outage at home

Hannu Nyman ***@***.***> 于 2023年7月28日周五 01:20写道：

**Pull request closed without merging**
