### PR TITLE
Update href for Bootstrap "brand"

### PR DESCRIPTION
**Pull request by arrmo**
In the Material theme, clicking on the logo takes you to the status page.
This seems logical, and is very helpful. But in Bootstrap, it doesn't
do anything, so just pulling the same href from Material to Bootstrap,
so the link works in Bootstrap as well.

### CODE REVIEW

**Comment by arrmo** [comment]
BTW, should this same "feature" be applied to the new openwrt-2020 theme? Thinking it would be nice to have this work (i.e. clicking on upper left corner, name or "icon" ... to the status page).

Thanks!

**Comment by jow-** [comment]
This will not work for installations that don't use `luci-mod-status`. Can't we simply link to `/` unconditonally without checking the auth state?

**Comment by arrmo** [comment]
Yep! Changed it on the router here, to check it out ... and yes, can just `href` to `/`. Want me to change it to that? I thought you wanted the rest of the `href`, but no issue here!

And do a similar thing (separately) in openwrt-2020?

Thanks!

**Comment by jow-** [comment]
Yep, it would be good if you could change it to href `/`. Feel free to do the change to OpenWrt 2020 in this PR too, using a separate commit.

**Comment by arrmo** [comment]
Hopefully all done right, and as you're wanting (2 separate commits). FYI, I did build each of these, tested them - and working 😄.

Thanks!

**Comment by arrmo** [comment]
Hi,

Just did an update here, realized this is still pending ... 😆. Is something missing, that I need to take care of?

Thanks!

**Comment by jow-** [comment]
Merged via 400ecb08f08be9045d83ce74534401a4ccae3aee and 27fc7a8b4e30d96228fe169e0266bd43564d5eb3 - thanks!

**Pull request closed without merging**
