### PR TITLE
important fixes incorrect Russian translation

### PR DESCRIPTION
**Pull request by user7887**
Signed-off-by: Vladimir <picfun@ya.ru>

### CODE REVIEW

**Comment by user7887** [comment]
Finishing correction of the quality of Russian translation, after careful visual proofreading of the interface text. 
======
I ask your advice, I use the program Poedit 1.8.7.1(ubuntu lts), the program incorrectly configured to extract the text of the translation from LUA scripts, there is a command "xgettext --language=Lua --add-comments=TRANSLATORS: --force-po -o %o %C %K %F"
Could you please advise the correct working of the team. Thank you!
======
Luci-app-firewall has one untranslated phrase - "Rule is enabled"
I wanted to add it to the template.

**Comment by jow-** [comment]
You can use `./build/i18n-sync.sh` to update the '*.pot` template files

**Comment by user7887** [comment]
jow-
I do it every time :)
I want to try to extract the translation from the original lua scripts in the program to which translation I use.

**Comment by jow-** [comment]
The script does exactly that, by invoking `./build/i18n-scan.pl`

**Comment by user7887** [comment]
Well, thank you, I use it !
Nevertheless I ask to accept these corrections, Russian user needs qualitative translation, thank you!

**Comment by jow-** [comment]
I figured out what the problem is. The `applications/luci-app-firewall/luasrc/tools/firewall.lua` script uses the `tr()` function to wrap translations which is not recognized by `i18n-scan-pl`. I changed it to `_()` and the strings are found now.

**Comment by user7887** [comment]
Okay, thanks, I'll check :)

**Comment by jow-** [comment]
e79a0ded7

**Comment by user7887** [comment]
I have change, now give to you, thank you ! This request I will close.

**Pull request closed without merging**
