### PR TITLE
luci: broadcom - add n-mode support

### PR DESCRIPTION
**Pull request by nlhintz**
Signed-off-by: Nathan Hintz nlhintz@hotmail.com

### CODE REVIEW

**Comment by cshoredaniel** [comment]
@nlhintz Please add a more complete commit message.  Also please indicate for which archs / device models you have compiled and run tested this PR.  To see how to update your PR without closing and resubmitting, see https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md

**Comment by cshoredaniel** [comment]
@jow- Thoughts on general guides to priorities?  There are five levels of labels, and this seems more important than a lot of the other ones, but I'm not sure about starting most things in the trivial category, so most would be minor and something like this that is of quite a bit of importance to people with the relevant hardware, seems to be major (level 3).  critical and blockers are self explanatory and rarely needed.

**Comment by jow-** [comment]
@cshoredaniel - these labels are artifacts from the import of the old Trac issues, so take them with a grain of salt. 

This PR can be merged as is.

**Comment by cshoredaniel** [comment]
Pull into my test tree.

**Comment by cshoredaniel** [comment]
Doesn't seem to break anything in my build although it's different hardware, but it also looks good and @jow- is happy with it, so merging

**Pull request merged**
