### PR TITLE
luci-app-olsr: fix null pointer exception

### PR DESCRIPTION
**Pull request by andibraeu**
please cherry pick that to 23.05, too

Thank you!

### CODE REVIEW

**Comment by systemcrash** [comment]
Sure, can you fix your signed off by? Should be a real email to get merged.

**Comment by andibraeu** [comment]
done

**Comment by systemcrash** [comment]
Could the np check be improved to simply eg
```
if (!interface...)
```
?

**Comment by systemcrash** [comment]
Merged, thanks :)

**Pull request merged**
