### PR TITLE
luci-theme-material: Synchronized to the LUCI version f9e590a

### PR DESCRIPTION
**Pull request by LuttyYang**
Signed-off-by: Lutty Yang <lutty@wcan.in>

### CODE REVIEW

**Comment by hnyman** [comment]
Your changes conflict with the ones that Jow made yesterday, as you implement a somewhat different detection function than f9e590a did. So this pull request does not merge cleanly, about which problem Github complains pretty clearly. 
conflict

To avoid unnecessary conflicts, you should always update your local copy of Luci sources before authoring new commits for new pull requests. Or even better is to start a new feature branch at the tip of the current Luci repo.

I tested reverting Jow's changeset f9e590a from the Luci repo and then applying this PR. Then it applies. So that might be a bit quick and dirty solution.

@jow- 
Is it ok to revert your change from yesterday to get this PR applied?

**Comment by LuttyYang** [comment]
@hnyman  Jow's changeset f9e590a have some small problem, so I implement a new detection function..

**Comment by jow-** [comment]
@LuttyYang - you should not rely on the layout of the url to find out what the current location is.

For example if LuCI runs via the Lua handler, its url will be `/luci/...` without any cgi-bin, also there might be protected pages that are not containing `admin/` in the url.

**Comment by LuttyYang** [comment]
@jow- I am not very clear how to find out the current position by the ```lua code```. Can you tell me how to do it.

thanks.

**Comment by jow-** [comment]
Add something like that to your header.html:

	<script type="text/javascript">
		window.luciLocation = <%= luci.http.write_json(luci.dispatcher.context.path) %>;
	</script>

Instead of making a global `window` property you could also store it as attribute, e.g. on the `<body>` element.

The above code will make the canonical resolved internal url available as JavaScript array, e.g. if you're on `http://192.168.1.1/cgi-bin/luci/admin` then the above code would result in 

    window.luciLocation = ["admin","status","overview"];

**Comment by LuttyYang** [comment]
@jow- thanks

**Comment by LuttyYang** [comment]
@hnyman @jow- 

I'm modified it.

**Comment by hnyman** [comment]
I compiled a version after I locally reverted Jow's fix and then applied the two commits in this PR. The menu's seems to work ok.
(One minor thing: on the login screen there is an empty space for the menu on the left.)

I still feel that the cleanest way to merge this would be to revert Jow's commit, after which this PR can be cleanly applied. That would enable a rather clean git commit history.

Does that process sound ok to you, @jow-  ?

**Comment by jow-** [comment]
@hnyman - sure, go ahead!

**Comment by hnyman** [comment]
Merged.

**Pull request merged**
