### PR TITLE
luci-app-noddos: backport from master

### PR DESCRIPTION
**Pull request by StevenHessing**
Noddos is a cloud-powered & device-aware firewall: https://github.com/noddos/noddos. This PR covers the original [PR](https://github.com/openwrt/luci/pull/1375) of noddos to openwrt/luci master branch plus the two commits for Japanese translations.

Signed-off-by: Steven Hessing <steven.hessing@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
Did you really mean to backport this for 17.01? 
To my knowledge the noddos package itself is not yet in 17.01 so this would not work, and I have seen no PR to backport it. (And usually new stuff does not get introduced to the stable branch, unless there is obvious wide interest for the functionality.)

**Comment by StevenHessing** [comment]
Thanks for reviewing the PR! 
Noddos has been merged to openwrt/packages branch lede-17.01: [PR #4916](https://github.com/openwrt/packages/pull/4916/commits)
Is there a description of the merge strategy for stable branch available on a Wiki? Waiting for the next major release is challenging if there is no date communicated for the next major release (or if such a date has a tendency to be pushed out frequently.)
Right now, Noddos is in sustaining phase for the current functionality. New functionality would not be merged to stable branches until that new functionality stabilizes.

**Comment by hnyman** [comment]
sorry, I somehow missed that the noddos package itself had really been backported to 17.01.
We can accept this LuCI GUI.

But you should change the commit title. It should just be something like "luci-app-noddos: backport from master" instead of referring to some PR1375

**Comment by StevenHessing** [comment]
Thanks for the feedback.  I have updated the title of this PR and the message of the commit.

**Pull request merged**
