### PR TITLE
luci-app-adblock: sync with adblock 3.5.0

### PR DESCRIPTION
**Pull request by dibdot**
* Support new 'Download Queue'
* Support new 'Jail' Blocklist Creation
  (replace former 'Whitelist Mode')
* Fix field width in "Runtime Information" section

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by hnyman** [comment]
no need for PRs any more. just commit directly

**Comment by dibdot** [comment]
Ah, OK forgot the new role ... ;-) Should I merge my own PRs for this time?

**Comment by hnyman** [comment]
Yes.
And in future, you can just push the commits related to your own packages to the upstream master branch (once you are ready), if you want.

My own workflow for packages that I maintain: 
* I first commit locally in a feature branch of my fork,
* then I push to my fork's master (origin/master) or to fork's feature branch, and verify/look at the commit output via Github GUI
    * do possible corrections locally, if e.g. some commit message looks funny in Github 
    * possibly force push the my fork to update the commit
* finally push to remote upstream/master (where you can't force-push)

You can of course keep doing PRs, as a PR also provides the preview possibility. Others could also then comment the proposed changes. But to be honest, I do not believe anybody to really look at your commits at that phase. If no comments to the PR for a few hours, just merge it by yourself.

**Comment by thess** [comment]
Yup - However, nothing wrong with PR if you are looking for comments/review. Either way, it's your choice now.

**Comment by dibdot** [comment]
@hnyman @thess 
OK, understood - many thanks!

**Pull request merged**
