### PR TITLE
luci-mod-wireguard: fix h/m/s ago display

### PR DESCRIPTION
**Pull request by systemcrash**
luci-i18n-wireguard-*: fix h/m/s ago display

translator note: remember: %d in the output string

### CODE REVIEW

**Comment by jow-** [comment]
The missing translations should be empty, and not `%d` otherwise "12s ago" would be simply translated as "12". Also `over a day ago` must be written as `_('over a day ago')` otherwise it will not get translated.

**Comment by systemcrash** [comment]
That's the idea: that translators will understand that `%d` is needed in the translated string. Anyway, this is already an improvement. 

Fixed the `_('over a day ago')`

**Comment by jow-** [comment]
But it will render untranslated strings broken. Either leave the msgstr empty or provide a complete translation string, not just `%d`

**Comment by systemcrash** [comment]
Ah, sucks. Fixed.

**Pull request closed without merging**
