### PR TITLE
luci-theme-boostrap: add javascript warning if disabled

### PR DESCRIPTION
**Pull request by feckert**
Signed-off-by: Florian Eckert <Eckert.Florian@googlemail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
Looks otherwise good (and I tested it), but JavaScript should be written together.

**Comment by feckert** [comment]
I am using the already introduced translation from the "luci-theme-openwrt"

https://github.com/openwrt/luci/blob/master/themes/luci-theme-openwrt/luasrc/view/themes/openwrt.org/header.htm#L182

**Comment by hnyman** [comment]
Well, it is wrong there too. 
You might fix that at the same time.

**Comment by feckert** [comment]
ok i will fix it

**Comment by feckert** [comment]
@hnyman fixed

**Pull request merged**
