### PR TITLE
rpc-mod-luci: Add support for ccmp-256/gcmp/gcmp-256 ciphers

### PR DESCRIPTION
**Pull request by schreibubi**
WPA3 added new ciphers, add support for displaying these in the wireless overview page

Signed-off-by: Joerg Werner <schreibubi@gmail.com>

### CODE REVIEW

**Comment by schreibubi** [comment]
This merge needs to wait until the corresponding patch to iwinfo got merged.

**Comment by schreibubi** [comment]
The required iwinfo changes have been merged to master. Any chance someone can retrigger the checks? Thanks!

**Comment by hnyman** [comment]
I guess this is now ready for merge, right?

(I triggered the checks. No surprises from there, although I am not sure if the CI really had the new iwinfo components, yet.)

**Comment by schreibubi** [comment]
This is ready for merging now. Thanks for retriggering the build!

**Pull request merged**
