### PR TITLE
[19.07] luci-app-ksmbd: support new UCI option, update for 3.2.1 version

### PR DESCRIPTION
**Pull request by Andy2244**
* support new UCI option "allow_legacy_protocols"
* update for 3.2.1 version (usmbd -> ksmbd.mountd)

Depends on: openwrt/packages#11297

### CODE REVIEW

**Comment by feckert** [comment]
Please rebase your changes

**Comment by Andy2244** [comment]
> Please rebase your changes

done... i really suck at those rebases lol

**Comment by feckert** [comment]
@Andy2244 sorry but that is because of the translations.
Could you also please do a separate commit for uci option add and api change?

**Comment by Andy2244** [comment]
> Could you also please do a separate commit for uci option add and api change?

done

**Pull request merged**
