### PR TITLE
translation: wifi -> WiFi

### PR DESCRIPTION
**Pull request by roger-**
Signed-off-by: Roger D <rogerdammit@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
The commit message title does not match the contents... WiFi vs. Wi-Fi

I don't like the "Wi-Fi". I know that it is the "official" trademark, but it is used more rarely than "Wifi" or "WiFi".

"WiFi" like in the commit message title, the title of this PR and in the title of #694 would be better, IMHO.
(In all config files etc. in Openwrt, it has been just "wifi".)

**Comment by roger-** [comment]
>  I know that it is the "official" trademark, but it is used more rarely than "Wifi" or "WiFi".

I agree that's the case in informal settings, but iOS, Android, OSX, Windows, etc. seem to use "Wi-Fi". 

I did however notice that network appliances tend to go for simply "wireless" or "WLAN" so maybe that's a better option?

**Comment by hnyman** [comment]
Well, in the Luci front page (Overview), network/wifi page and Luci statistics wireless page the headings are "Wireless" or "Wireless Network:" etc.  Always "Wireless"+something

I guess this menu item network/Wifi is actually the only place with Wifi.

I preferred "Wireless" in the discussion in #494  (from whre the Wifi change was dropped before merge with only the UPnP change)

**Comment by roger-** [comment]
I'm okay with "wireless" too, for consistency.

**Comment by roger-** [comment]
@jow: what are your thought? "WiFi" or "Wireless"?

**Comment by hnyman** [comment]
@jow- 
Please voice your opinion, is Wireless better than WiFi  ?

**Comment by jow-** [comment]
Sorry, did miss that one - "Wireless" is fine for me, more generic .

**Comment by hnyman** [comment]
Thanks jow,
let's change it to "Wireless" then.

I looked into the change and started to wonder if the correct place to change it would be the controller file, not the translation template as in this PR.

https://github.com/openwrt/luci/blob/master/modules/luci-mod-admin-full/luasrc/controller/admin/network.lua#L64

    page = entry({"admin", "network", "wireless"}, arcombine(template("admin_network/wifi_overview"), cbi("admin_network/wifi")), _("Wifi"), 15)

"Wifi" there is the original label that the .po picks up.

**Comment by jow-** [comment]
Yes, we need to change the label within the `_(...)` call.

**Comment by hnyman** [comment]
@jow- 
I am reusing this PR for discussion as my topic is related to translations:
i18n-sync script leaves the discarded old msgid/msgstr lines to the end of the .po file as comments. Especially in luci-base there are several .po files with upto 800-1000 lines of old strings. Example here, lines 3583-4436 are comments:
https://github.com/openwrt/luci/blob/f4a446ce727bc4347aa48b7ea3425c6199cfef94/modules/luci-base/po/ca/base.po#L3580

Should those files be cleaned at some point?  I guess the comments don't end up in the final packages, so they are harmless, but I still wonder.

**Comment by jow-** [comment]
Yes we can discard them. The gettext-tools idea behind that is such statel translations can be used for future reference when translating other things but one can as well grab that info from the Git history if it is of any interest.

**Comment by hnyman** [comment]
I pushed a commit cleaning 15,329 lines from the .po files in luci-base.

**Pull request closed without merging**
