### PR TITLE
luci-mod-system: improve sysupgrade page

### PR DESCRIPTION
**Pull request by Ansuel**
- Add missing -k and -u option from sysupgrade page.
- Fix missing check for image verification exit code
- Provide the actual reason of the image verification

Fixes: #4160

@jow- 

Here the screen of the fixes for the theme and the new option. (in the current state, with the material theme, the long text are never wrapped and goes outside the modal...)

Immagine 2021-01-29 190242

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by tapper82** [comment]
Can you make the modle grab focus for screenreaders. As it is now there is know way to know if the upgrade page has poped up with out arrowing all the way down to the botem of the page to see if a mesage has popped up.

**Comment by Ansuel** [comment]
> Can you make the modle grab focus for screenreaders. As it is now there is know way to know if the upgrade page has poped up with out arrowing all the way down to the botem of the page to see if a mesage has popped up.

Can you better explain what you are saying ?

**Comment by tapper82** [comment]
Hi yeah I will try and explain what I am on about. When using a screen reader and you are on the sysupgrade page in luci. After clicking on Flash image there is no way to know that the modle is asking for a response from the user. To the screen reader it seems like the button for Flash image does nothing. To find a way of interacting with the modle you have to jump all the way to the bottom of the page were you will here your screen reader say dialogue. When you here that you have to press the enter key and it will let the screen reader get focus on the actions for flashing your device. After clicking on the browse button to find the file to flash and then clicking on the upload button it then jumps you back up the page and you have to jump back down to the bottom of the page find where it says dialogue.  press enter. Then you can see the file name, size and things like that. After clicking on continue It then jumps you back on the page and there is no way for a screen reader to know that the router is flashing.

**Comment by Ansuel** [comment]
Can you post some screen of the problem?

Il Sab 30 Gen 2021, 19:42 tapper82 <notifications@github.com> ha scritto:

**Comment by tapper82** [comment]
The modle  thing can be fixt at a later date.

**Comment by feckert** [comment]
What about the other themes? Don't they have to be adapted the css as well?

**Comment by Ansuel** [comment]
Honestly I didn't check but they should be good... Will check

Il Gio 11 Feb 2021, 08:22 Florian Eckert <notifications@github.com> ha
scritto:

**Comment by nickberry17** [comment]
I hope this gets merged soon

**Comment by wulfy23** [comment]
did you test '-u' handling on ext4 systems?

**Comment by Ansuel** [comment]
@feckert i finally had time to test this on every supported theme. I fixed all the minor problem

**Comment by hnyman** [comment]
At the first glance it looks ok to me. 
I tested sysupgrading an invalid image for E8450 and after your changes it fails nicely and visibly.
Also the compat-version error is well visible.

image


Ps.
At that time I noticed that there is no line break between two lines of error messages, which makes the dialog a bit unclear, as the second timestamp starts right after the previous word without any punctuation. But looking at the source code (lines 240-244 that you did not touch), I think that it may come directly from stderr, so that a line break can't be easily inserted.

image

**Comment by Ansuel** [comment]
Now that I notice I think it's redundant to have 2 times the same error?

Il Mer 4 Ago 2021, 21:16 Hannu Nyman ***@***.***> ha scritto:

**Comment by hnyman** [comment]
hmmm.
some more testing with E8450 makes me to think that something is somehow broken.

* Normal sysupgrading of  r17254-edb6bc1990 with settings seems to cause the browser to hang with the spinning wheel, so that the new firmware does not load after the sysupgrdae. (Sysupgrade is still performed ok)
* If the option to "write installed packages" is selected, the sysupgrade does not even start. Not even the SSH console session is broken. (LuCI just remains with the spinning wheel)

**Comment by Ansuel** [comment]
Could be that something is messed up? I refreshed and fixed the theme
issue. Will check what is wrong.
Anyway did you notice any missing feature? Or improvement?

Il Mer 4 Ago 2021, 21:41 Hannu Nyman ***@***.***> ha scritto:

**Comment by hnyman** [comment]
I liked the new features in principle.

And the error condition checking seemed more complete than in the current LuCI.
 (I think that the compat-version handling at least may currently fail invisibly, so your changes are toward a better direction.)

**Comment by Ansuel** [comment]
Anyway the not reloading bug was simple... investigating the problem you reported about sysupgrade not working with the '-k' option

**Comment by Ansuel** [comment]
@hnyman there was a permission problem and i also disabled the button since it doesn't make sense to use the advanced backup config when is asked to reset the router on upgrade.

**Comment by hnyman** [comment]
Thanks, tested with R7800 and now also the -k seems to work (after you fixed the ACL permission definitions).

**Comment by hnyman** [comment]
Seems to work also in E8450
No comments from others in the meanwhile, so lets merge this and then see if there is any fallout.

**Pull request merged**
