### PR TITLE
luci-app-vpnbypass: directly enable service from Web UI.

### PR DESCRIPTION
**Pull request by stangri**
Allows to enable/start and stop/disable service from Web UI.
Minor fix: show all fields.
Minor fix: readme URL is in variable allowing more compact lua code.
Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by hnyman** [comment]
Merging this, but I am curious why do you want to manually disable/enable the package on system service level ( in /etc/rc.d) , when you already have the package-specific config switch "enabled" that your startup script and hotplug scripts probably evaluate correctly.

Personally I find that a bit cumbersome old practice that some apps still do.

**Comment by stangri** [comment]
Oh, I didn't realize that disabling/enabling on system service level was an older practice. I actually find it preferable to a package-specific config switch, because without the package-specific config switch luci's system/startup page would accurately reflect wherever service is enabled/disabled.

**Comment by hnyman** [comment]
If you have a package-specifc uci config option that you evaluate in startup script and hotplug scripts, you can leave the system-level service always on. (as your startup and hotplug scripts should first check that option and quit if disabled).

If somebody includes your package in a build, the system-level service enabling symlink gets always installed in the firmware image and service enabled, so the package is always on right after the flash in e.g. any private build (like community build). That is the major negative drawback on relying on system-level symlink. 

But a package-specific uci config option can have a default value 0 in the included config, and thus the included package does not actually do anything before the user has configured it.

**Comment by stangri** [comment]
Hannu, could you please provide feedback on [this](https://github.com/stangri/openwrt-luci/blob/luci-app-vpnbypass/applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua#L7-L26)?

The checkbox is enabled if the init script is enabled on system-level and config option set to 1, otherwise it's disabled. Enabling checkbox should set the config option to 1 and enable/start init script, while disabling checkbox should set config option to 0 and stop the service.

The init script checks for the config option and the default config has that option set to 0.

**Pull request merged**
