### PR TITLE
luci-app-ipvs: add Virtual Server Load Balancer configuration

### PR DESCRIPTION
**Pull request by ezplanet**
Linux Virtual Server (ipvs) is used to set up and manage virtual server load balancers
This adds load balancer capabilities to LEDE/OpenWrt de-facto turning a small router into a powerful hardware load balancer

This change adds Luci configuration and monitoring pages for lede ipvsadm package

Signed-off-by: Mauro Mozzarelli <mauro@ezplanet.org>

### CODE REVIEW

**Comment by ezplanet** [comment]
This packages depends on LEDE ipvsadm package added with the following PR:
https://github.com/lede-project/source/pull/936

**Comment by ezplanet** [comment]
Hannu which repo do I need for the PR?

**Comment by hnyman** [comment]
> Hannu, which repo do I need for the PR?

It is just a flag that the feature depends on a PR in another repo, so this can't be merged earlier. 
This time LEDE 936 needs to be accepted and merged first, right?

**Comment by ezplanet** [comment]
That is fine then, I confirm it depends on LEDE PR 936 as indicated above.

**Comment by feckert** [comment]
@ezplanet what about this PR will this get merged?

**Comment by hnyman** [comment]
> what about this PR will this get merged?

The underlying ipvsadm commit (from LEDE PR 936) itself is still in @jow-  staging queue, and has not yet been committed to the main source:
https://git.openwrt.org/?p=openwrt/staging/jow.git;a=commit;h=1bb590addc294a6716ac4a56a1d18e4220de2a4f

So this PR can't be merged, yet.

**Comment by feckert** [comment]
@hnyman thanks for clarify this.
I thought the depended PR was already merged upstream.

**Comment by feckert** [comment]
@hnyman ipvsadm is now merged https://github.com/openwrt/packages/commit/79c5c78115443df7c26b643aca38e4679950a6ab into the package feed. But only the tool. No init script so I think we could close this. Because this does not work.

**Pull request closed without merging**
