### PR TITLE
Corrected existing and added missing Russian translations LuCI

### PR DESCRIPTION
**Pull request by user7887**
I translated 16 luci-apps, and corrected and completed the translation 7 luci-apps had a Russian translation, including luci-base.
The theme with the translation on the forum cyber-place.ru:
http://cyber-place.ru/showthread.php?t=2620
I corrected according to your recommendations:
https://github.com/openwrt/luci/pull/1492#issuecomment-354656437
dnscrypt-proxy & adblock I will fix and post later along with other translations on which I'm working now.
Please do not judge strictly, I'm new :)
Merry Christmas and Happy New Year, thank you for your work !!!

### CODE REVIEW

**Comment by user7887** [comment]
I see you have updated some of the templates 5 days ago :). 
I'll check my translations in compliance to your templates...
Translation luci-app-adblock I did today, and corrected the pattern was missing a space after one single sentence. 
Thank you !

**Comment by user7887** [comment]
Now all ready, there have been several applications of the template, which was fixed after the transfer is made. 
I brought Russian translation in accordance with the templates. 
And all again rechecked. 
We value your business, you have many users in Russia, thank you!

**Comment by user7887** [comment]
You may be more comfortable if I will add the translation files a little

**Comment by jow-** [comment]
Hi @user7887 - any reason why you closed this PR? I've been looking at the delta and it looks mostly sane to me. I can squash your 33 commits into one and add a Signoff on your behalf if you're okay with that.

**Comment by user7887** [comment]
jow-
Excuse me please :)
I thought you would be easier if I present the material in small portions, at the same time doing additional testing. 
Sorry if I caused you any inconvenience. We value your work. 
The first time I work with github

**Comment by user7887** [comment]
Hi jow-
Excuse me please :)
I thought you would be easier if I present the material in small portions, at the same time doing additional testing. 
https://github.com/openwrt/luci/pull/1497
Sorry if I caused you any inconvenience. We value your work. 
The first time I work with github :)
===
"I can squash your 33 commits into one and add a Signoff on your behalf if you're okay with that."
 Yeah, I don't mind of course :)

**Comment by user7887** [comment]
Hi jow-
Excuse me please :)
I thought you would be easier if I present the material in small portions, at the same time doing additional testing. 
https://github.com/openwrt/luci/pull/1497
Sorry if I caused you any inconvenience. We value your work. 
The first time I work with github :)
===

> I can squash your 33 commits into one and add a Signoff on your behalf if you're okay with that.

 Yeah, I don't mind of course :)

**Comment by jow-** [comment]
Ok - I will do that then and you can base your further changes on top of that. Thank you for your contribution!

**Comment by user7887** [comment]
Thank you!

**Pull request closed without merging**
