### PR TITLE
luci-mod-status: auto-refresh system log and kernel log

### PR DESCRIPTION
**Pull request by dannil**
Implements #5568. See attached video. I have by design not implemented any "follow tail" logic for the log as I was unsure how it should interact with the "Scroll to tail" and "Scroll to head" buttons that are already there (should it follow the tail even if the user hasn't clicked "Scroll to tail" yet?), but any suggestion how and if we should handle that is welcome.

I was a bit unsure if PKG_RELEASE should be incremented for modules; luci-mod-status hasn't received any since 938e54df17d6a48fc8d84fe5893ff67ffe4a3e6e even though the diff since that commit is quite big.

https://github.com/openwrt/luci/assets/7290072/815a0dea-fa35-4146-bba0-b0cfa2fdb87b

- [X] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [X] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [X] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [X] Tested on: (x86/64, 23.05.3, Firefox) :white_check_mark:
- [ ] \( Preferred ) Mention: @ the original code author for feedback
- [X] \( Preferred ) Screenshot or mp4 of changes:
- [X] \( Optional ) Closes: e.g. openwrt/luci#5568
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [X] Description: (describe the changes proposed in this PR)

### CODE REVIEW

**Comment by systemcrash** [comment]
While I like this concept, something like this should be configurable, since everyone is used to today's behaviour: you load the page and you can stare at those logs for hours and nothing changes. Both behaviours are valuable: seeing live action, and freezing a log to understand something better.

I feel a log config tab coming on. Where one can have `tail logs` which chases output, perhaps among other configurables. 

Doable?

**Comment by feckert** [comment]
@systemcrash In my opinion, a configuration option is not necessary. We'll see if it bothers users. There is already a "Refresh" button in the view. If someone does not like this new feature, it can be disabled by pressing this button.

I think this could be merged.

**Comment by systemcrash** [comment]
@feckert there is no refresh button here...? So I would prefer not to introduce a behaviour change without an option to control it.

**Comment by dannil** [comment]
> @feckert there is no refresh button here...? So I would prefer not to introduce a behaviour change without an option to control it.

I think @feckert means the blue "Refreshing" text in the upper rightcorner  of LuCI, if you click that you disable the system-wide polling (technically everything that hasn't overriden the default timeout of the `poll` library), which includes the system log, that's why I didn't take into consideration of adding that as an option.

Screenshot_29
Screenshot_30

**Comment by feckert** [comment]
> > @feckert there is no refresh button here...? So I would prefer not to introduce a behaviour change without an option to control it.
> 
> I think @feckert means the blue "Refreshing" text in the upper rightcorner of LuCI, if you click that you disable the system-wide polling (technically everything that hasn't overriden the default timeout of the `poll` library if I remember correctly), which includes the system log in this diff, that's why I didn't at first think of taking that into consideration.
> 

@dannil  yes this is exactly what i mean. Thanks for the clarification.
@systemcrash I think that fulfills the requirement.
The behavior can be set as before when the logs were not refreshed.
I think this could be merged?

**Comment by dannil** [comment]
> > > 
> > 
> > 
> > I think @feckert means the blue "Refreshing" text in the upper rightcorner of LuCI, if you click that you disable the system-wide polling (technically everything that hasn't overriden the default timeout of the `poll` library if I remember correctly), which includes the system log in this diff, that's why I didn't at first think of taking that into consideration.
> 
> This simply does not exist on the log pages today, at least not for me, OpenWrt 23.05.3 r23809-234f1a2efa. In fact, none of the status pages except for real+time graphs show this bad boy:
> 
> > Screenshot_29 Screenshot_30
> 
> So if at least that can be added for those pages, then this is good to go.

It will be added with this PR. How the flow works is that the [start method of the poll class](https://github.com/openwrt/luci/blob/eee323cb6683e6f1f1da7059e49eb8f4498bedf6/modules/luci-base/htdocs/luci-static/resources/luci.js#L410-L423) dispatches the `poll-start` event. The [setupDOM function](https://github.com/openwrt/luci/blob/68b2ce84ece62e3aec98b9be31e61ec5f6cdba2d/modules/luci-base/htdocs/luci-static/resources/luci.js#L2618-L2626) listens to this event dynamically, and if it discovers there's such an event dispatched, it dynamically adds the "Refreshing" button/indicator (whatever you wanna call it), enabling users to stop the polling themselves. 

This is why some pages (such as Status -> Overview and System -> System) gets a refreshing indicator dynamically and others don't, even though those pages themselves doesn't have code to add the indicator. I verified this by swapping between this branch and `openwrt-23.05`, deploying `luci-mod-status` in between; the indicator disappeared in `openwrt-23.05` but showed up on this branch (due to the usage of the `poll` class).

**Comment by systemcrash** [comment]
Ah good! I learned something new :)

**Comment by feckert** [comment]
@dannil Thanks merged!

**Comment by systemcrash** [comment]
Thanks @dannil

**Pull request merged**
