### PR TITLE
luci-mod-admin-full: fix wrong dsl stats visualization

### PR DESCRIPTION
**Pull request by t0t3m1n**
This patch fixes the wrong visualization of Noise Margin (SNR) and Signal Attenuation (SATN) stats

Signed-off-by: Luca Debernardi <luca.debernardi@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
@hauke 
This touches the new stats introduced by you in https://github.com/openwrt/luci/commit/bedac198e5fb63da37ebaf5d9b49c215d18e010d

Does the change look ok?

**Comment by kdarbyshirebryant** [comment]
On a DGN3500 a number of stats look swapped and the above mentioned patch would help address some of those:  (Data rate vs Max attainable look swapped, as do SNR and noise margin)

Data Rate: 2.432 Mb/s / 608 Kb/s
Max. Attainable Data Rate (ATTNDR): 2.088 Mb/s / 616 Kb/s
Latency: 8.0 ms / 8.0 ms
Line Attenuation (LATN): 58.3 dB / 31.5 dB
Signal Attenuation (SATN): 6.8 dB / 11 dB
Noise Margin (SNR): 54.6 dB / 31.5 dB
Aggregate Transmit Power(ACTATP): 17.3 dB / 12.6 dB
Forward Error Correction Seconds (FECS): 9290206 / 661

**Comment by t0t3m1n** [comment]
Data Rate and Max. Attainable Data Rate look fine to me, i have a 5 Mb/s line (capped by ISP at my request to avoid disconnections) and Data Rate is 4.999 Mb/s. Signal Attenuation and Noise Margin are certainly swapped

**Comment by kdarbyshirebryant** [comment]
I'm happy to be wrong :-)

**Pull request merged**
