### PR TITLE
luci-app-adblock: Update Japanese translation

### PR DESCRIPTION
**Pull request by musashino205**
- Fixed LuCI i18n-tools detection issues
    - LuCI i18n-tools cannot interpret variables, so translations on that are not applied in po/pot by i18n-tools. 
- Synchronized translations
- Updated Japanese translations

### CODE REVIEW

**Comment by hnyman** [comment]
cc @dibdot

**Comment by dibdot** [comment]
@musashino205 I'm not aware of these translation limitations - hopefully the now 'hardcoded' status do not change frequently ... ;-))

Thanks for the fix!

**Comment by hnyman** [comment]
@dibdot 
please try to avoid unnecessary cosmetic changes to the strings. E.g. "Adblock version" vs. "Adblock Version" and "Runtime information" vs. "Runtime Information" break existing translations like musashino's sync commit shows: https://github.com/openwrt/luci/pull/1361/commits/8be0c7e7b26ff25ebc1e0cc8f92dfc7e71fb60de

Or please also fix the translations with sed or by running i18n-sync.pl and then fixing the changes.

Musashino fixed Japan, but other languages are still broken.

**Comment by musashino205** [comment]
Oops, sorry. I should also be careful about cosmetic changes in synchronization...

**Comment by dibdot** [comment]
@hnyman 
So a search & replace within the *.po files is enough?

**Comment by hnyman** [comment]
Basically yes.

Easy way check & propagate the changes is to run ./build/i18n-sync.pl in LuCI root after changes to the package itself, and check which strings break.

E.g. "Resume adblock" got replaced by "Resume" so a new empty translation was created for that
https://github.com/openwrt/luci/commit/8be0c7e7b26ff25ebc1e0cc8f92dfc7e71fb60de#diff-cc72579de5eaaf1d7526295ddfbc7f77L158
and the old translation got pushed down into archive of old unused strings
https://github.com/openwrt/luci/commit/8be0c7e7b26ff25ebc1e0cc8f92dfc7e71fb60de#diff-cc72579de5eaaf1d7526295ddfbc7f77R328

Afterwards it is a bit harder to properly fix things, as e.g. the old strings get pushed to end to the archive, but when the original changes have been done to the package, it is easier find&replace stuff.

**Comment by musashino205** [comment]
I tried to fix it only for letter-case.

- Unified to upper-case letters:
[Comparing openwrt:master...musashino205:adblk-fix-trans_upper](https://github.com/openwrt/luci/compare/master...musashino205:adblk-fix-trans_upper)

- Unified to lower-case letters:
[Comparing openwrt:master...musashino205:adblk-fix-trans](https://github.com/openwrt/luci/compare/master...musashino205:adblk-fix-trans)

After this I will sleep, so the response will be somewhat late...

**Comment by dibdot** [comment]
@musashino205 The first one (Upper-/Camel-Case-Fix) looks good to me.
@hnyman thanks for the information!

**Pull request merged**
