### PR TITLE
luci-app-travelmate fixed

### PR DESCRIPTION
**Pull request by user7887**
Signed-off-by: Vladimir <picfun@ya.ru>
There was no space:
default
Corrected, clarified the Russian text:

### CODE REVIEW

**Comment by dibdot** [comment]
@user7887 which PR is the relevant one, #1608 or #1607? You've changed (partly) the same files in different PRs.
Thanks!

**Comment by user7887** [comment]
dibdot
They are the same :)
One for "master", another for "luci 17"..
I mixed up 2 phrases in the Russian translation in some places , they have similar value. Correct to take both, as proposed. Thank You! :)

**Comment by dibdot** [comment]
Sorry I didn't see that your PRs are going to different branches. Next time please introduce your stable tree PRs with [17.01]. And just another nitpick: in future please sign off your commits with your name plus last name.

**Comment by user7887** [comment]
Ok:) Thanks...

**Pull request merged**
