### PR TITLE
luci-app-ddns: Fix time error

### PR DESCRIPTION
**Pull request by small-5**
Fix https://github.com/openwrt/luci/issues/4506

### CODE REVIEW

**Comment by small-5** [comment]
Check the dynamic_dns_updater.sh file and find that FORCE_SECONDS did not update the IP after the next update time, so line 114 should be retained.

**Comment by small-5** [comment]
Check the dynamic_dns_updater.sh and find that FORCE_SECONDS did not update the IP after the next update time, so line 114 should be retained.

**Comment by small-5** [comment]
Line 114 should be retained.

**Comment by feckert** [comment]
Can your please sign your commit with sign-off-by?
And in the commit message explain in more detail why we don't need this.
My problem is that I didn't write the code and don't know what the original developer was thinking.
If we change it now, then later you wonder why you changed it.

Lets ping @Ansuel maybe he could give us more info

**Comment by small-5** [comment]
I can't with sign-off-by now, because fork has been deleted. The removal of "+ force_seconds" is to compare the 18.06 version of ddns.lua (https://github.com/openwrt/luci/blob/openwrt-18.06/applications/luci-app-ddns/luasrc/tools/ddns.lua), this can be fixed The bug of the last time overflow. The 114 line is removed because this will cause the bug that the next update time is wrong when it is just started. You can try to modify this file in my way, and then service rpcd restart to verify.

**Pull request closed without merging**
