### PR TITLE
luci-mod-system: Add field to allow user-customizable branding

### PR DESCRIPTION
**Pull request by majik-sheff**
Add a field in the "Language and Style" tab of System to allow users to override
the title/branding of Luci (even emoji).  If left empty, behavior reverts to using the hostname.

Signed-off-by: Tim Thorpe <tim@tfthorpe.net>

### CODE REVIEW

**Comment by hnyman** [comment]
I don't like hiding the hostname.  That can easily create confusion if there are multiple routers and a customized "branded" build is used.

I would prefer adding an optional branding but keeping the hostname always visible.

**Comment by majik-sheff** [comment]
> I don't like hiding the hostname. That can easily create confusion if there are multiple routers and a customized "branded" build is used.
> 
> I would prefer adding an optional branding but keeping the hostname always visible.

The idea behind making it optional was to give the end-user a choice.  Until they change it, it defaults to using the hostname.

**Comment by stokito** [comment]
As a regular user I'm not sure why would I need this

**Comment by feckert** [comment]
This pull request has been lying around for a while now. It can also no longer be used, since the LuCI is using ucode. If this is of further interest, please rebase and open it again.

**Pull request closed without merging**
