### PR TITLE
luci-mod-status: Mobile styling for progressbar

### PR DESCRIPTION
**Pull request by camarel**
On a small screen the progressbar is too big to show all three values (value /
max value / percentage). This will put the label on one line and below
the progressbar.

Signed-off-by: Claudio Marelli <camarelli@gmx.net>

### CODE REVIEW

**Comment by camarel** [comment]
**Currently:**
image


**With the changes in the pull request**
image

**Comment by feckert** [comment]
Could we also add the missing css class to the other themes?

**Comment by camarel** [comment]
@feckert: Good input; I now updates the other themes too.

**Comment by feckert** [comment]
please rebase this branch and also split your commits into separate commits with logical changes or 
stash/fixup the commits into one. Its up to you If done I think we could merge this

**Comment by feckert** [comment]
@camarel Could you please rebase your changes. So I could merge your pull request

**Comment by feckert** [comment]
@camarel ping?

**Comment by feckert** [comment]
I have checked this with my browser firefox 60.7.0 and I could nor reproduce your issue. On my setup everything is working as expected? What browser do you use.

Screenshot-2019-9-23 G3000-LWV - Overview - LuCI

**Comment by feckert** [comment]
No reaction from pullrequest creator.
Feel free to reopen if you think we should merge this after changing.

**Pull request closed without merging**
