### PR TITLE
openwrt-dark theme

### PR DESCRIPTION
**Pull request by selanf**
2b2d805f9f themes: add openwrt-dark
14b0fc5292 network: use ifacebox-headlight
a350890c3a all themes: add ifacebox-headlight class

### CODE REVIEW

**Comment by Ansuel** [comment]
Any screen of the changes?

**Comment by jow-** [comment]
I do not really want to merge another theme due to the associated maintenance burden.

Is there any chance to fold your dark theme changes into the existing openwrt-2020 one using the `prefers-color-scheme` media query?

I'd be fine with changing openwrt-2020 as needed (e.g. to introduce new CSS variables) to support dark mode.

**Comment by jow-** [comment]
Sorry, did not meant to close the PR, accidentally hit the wrong button on my phone.

**Comment by selanf** [comment]
Screenshots:
aa
bb
image

**Comment by selanf** [comment]
Dont know if its better to add a subitem for current theme.
I chosed this way, as openwrt has an option to install additional packages to test during runtime and remove if someone does not like it. So also the existing option to switch theme could be used.
The Logo was also changed, as the dark part was only bare visible,

**Comment by selanf** [comment]
In https://github.com/openwrt/luci/pull/5246 was a related commit

**Comment by selanf** [comment]
This sould better be fold int openwrt20?? theme, buz i dont know how

**Comment by teohhanhui** [comment]
@jow- Is the `openwrt-2020` theme going to become the new default? If so, I'd like to work on creating a dark version using `prefers-color-scheme`.

Separately, is there any chance of such a PR being accepted for the `bootstrap` theme? https://github.com/openwrt/luci/issues/4578#issuecomment-919350088

**Pull request closed without merging**
