### PR TITLE
luci-mod-network: Expose multicast_to_unicast setting

### PR DESCRIPTION
**Pull request by systemcrash**
Tested on: 21.02.1

Signed-off-by: Paul Dee <itsascambutmailmeanyway@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@systemcrash can you improve the commit description ? also remove the (wireless) tag?

**Comment by systemcrash** [comment]
What would constitute an "improvement"? The commit itself is only 4 lines.

**Comment by Ansuel** [comment]
A commit description is mandatory in 99% of the commits... 
Something like

```
luci-mod-network: expose multicast_to_unicast wireless setting

From https://w1.fi/cgit/hostap/commit/?id=34f7c699a6bcb5c45f82ceb6743354ad79296078
add support for multicast_to_unicast conversion in the wireless settings. 
```

**Comment by systemcrash** [comment]
> A commit description is mandatory in 99% of the commits... Something like

OK thanks - I just didn't want it to stray too far from being short and concise.

**Comment by systemcrash** [comment]
Ready for merge.

**Pull request merged**
