### PR TITLE
luci-base: drop unused icons

### PR DESCRIPTION
**Pull request by jow-**
Remove icons which aren't used by the Bootstrap or OpenWrt themes anymore,
which saves about 4.1KB in the luci-base package.

Signed-off-by: Jo-Philipp Wich <jo@mein.io>

### CODE REVIEW

**Comment by jow-** [comment]
@dibdot @hnyman - pinging you because I am not sure if any of the extra LuCI apps still rely on one of the removed icons.

**Comment by dibdot** [comment]
@jow-  that's what I have found so far ...
```
- applications/luci-app-asterisk/luasrc/view/asterisk/dialplans.htm still reference remove.gif and edit.gif
- applications/luci-app-asterisk/luasrc/view/asterisk/dialzones.htm still reference remove.gif and edit.gif
- modules/luci-base/luasrc/view/cbi/upload.htm still reference reload.gif
- modules/luci-base/luasrc/view/sysauth.htm still reference up.gif
- themes/luci-theme-freifunk-generic/htdocs/luci-static/freifunk-generic/cascade.css still reference link.gif
- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js still reference save.gif
- themes/luci-theme-openwrt/htdocs/luci-static/openwrt.org/cascade.css still reference reset.gif
```

**Comment by dibdot** [comment]
@jow- 
Just to note that even cbi.js still reference add.gif and remove.gif:
`b.src = cbi_strings.path.resource + ((i+1) < values.length ? '/cbi/remove.gif' : '/cbi/add.gif');`

**Comment by jow-** [comment]
The `cbi.js? depends should be gone with https://github.com/openwrt/luci/commit/875b561875cb4eca4c913c69ce2dfd21265b6ac6

**Comment by dibdot** [comment]
Ah, I see. Sorry, my test checkout was just too old ... ;-)

**Comment by hnyman** [comment]
@jow- 
Is this PR still relevant?
It uses your master and has quite a variety of commits unrelated to the original purpose of the PR.

**Comment by jow-** [comment]
Yeah I heavily reworked my master clone, will reopen a similar icon removal PR in the future when things settled.

**Pull request closed without merging**
