### PR TITLE
Update openvpn.po

### PR DESCRIPTION
**Pull request by artioni81**

### CODE REVIEW

**Comment by hnyman** [comment]
Lookok, but you need to amend the commit itself:
* commit title should be  "luci-app-openvpn: update Italian translation"  or something like that
* you need to add a signed-off-by line with your real name and email to the commit message itself

https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md

**Comment by artioni81** [comment]
Thank you.

**Comment by hnyman** [comment]
Thanks.
you should have squashed the commits together (with "git rebase -i"), or just amended the original commit. Advice in the Contributing guide...

But I will merge this, as it is just translations and your second commit looks ok.

**Comment by artioni81** [comment]
Thanks...I'm a newbie...but I'll pay attention next time.

**Pull request merged**
