### PR TITLE
Datatype "pattern"

### PR DESCRIPTION
**Pull request by yousong**

### CODE REVIEW

**Comment by yousong** [comment]
How do you like a conversion from lua string pattern to js regexp without support for '%bxy' and empty capture '()'?  Indeed, '%bxy' alone cannot be expressed with regular expression and I am only aware of its existence when drafting the conversion function.

**Comment by yousong** [comment]
v2 changes

- A fix for converting lua string to js repr, specifically the backslash in lua string to js repr
- A new js function for converting lua string pattern to js regex syntax that will throw exception when encountering lua match feature `%bxy` and `()`
- Now with that conversion func we can do the validity check in browser!

**Comment by yousong** [comment]
v3 change

 - Fixup the range for `%p`, before `'\x00-\x2f\x3a-\x40\x5b-\x60\x7b-\x7e'`, after `'\x21-\x2f\x3a-\x40\x5b-\x60\x7b-\x7e'`, also change `%P` accordingly

**Comment by jow-** [comment]
I'm still not sure whether I like it. I mean the idea is neat and the implementation is good but it adds a huge amount of code.

**Comment by jow-** [comment]
As for the l2tp requirement, I added two new types in 9b30357454ea53a9f1d7e82d8f894db5f409de98 which you can use to validate the remote option for now.

**Comment by yousong** [comment]
ok.  I will close this, then rebase, test and open a new request.  Thank you.

**Pull request closed without merging**
