### PR TITLE
luci-mod-admin-full: bugfix ntp config reload on change

### PR DESCRIPTION
**Pull request by feckert**
- A call to "/sbin/reload_config" is solving this issue

Signed-off-by: Florian Eckert Eckert.Florian@googlemail.com

### CODE REVIEW

**Comment by jow-** [comment]
We should implement this in a more generic way. The best way would be adding this to servicectl.lua.

**Comment by feckert** [comment]
I thought this would be the best way to fix this.
All other changes would add a "feature" to the branch for-15.05.
I am not sure if the call to "/sbin/reload_config" is already added to all modules in master?

**Comment by cshoredaniel** [comment]
@jow- What is the policy for 15.05 branch regarding what should get fixed and what left?

**Comment by jow-** [comment]
@cshoredaniel - in general bug fixes are okay, but the fix proposed in this PR has quite a number of potential side effects. The `reload_config` command will reload *any* service that has pending runtime changes and not just ntp. There is also no support for the modern `reload_config` approach in LuCI at all yet so for the stable branch I'd prefer a solution using the legacy `luci-reload` mechanism.

**Comment by feckert** [comment]
@jow will luci ucitrack be replaced with "/sbin/reload_config" in the near feature? If so what is best place in source to replace it?

**Comment by jow-** [comment]
@feckert - it will get replaced but I'm not yet sure whether this will happens in LuCI or LuCI-NG.

**Pull request closed without merging**
