### PR TITLE
Add validation to APN and PIN fields in luci-proto-3g, luci-proto-qmi, luci-proto-ncm and luci-proto-modemmanager

### PR DESCRIPTION
**Pull request by nickberry17**
Validates APN fields in luci-proto-modemmanager, luci-proto-3g and luci-proto-qmi.  The APN is validated with a custom validator function instead of adding support to LuCI validation.js, as suggested.  While I'm at it I validated the PIN to a max of 4 digits for luci-proto-modemmanager.

The validation regex is based on [Chapter 9.1](https://www.etsi.org/deliver/etsi_ts/123000_123099/123003/08.08.00_60/ts_123003v080800p.pdf) of the 3GPP Spec, "Structure of APN" and the PIN length is based on [Chapter 5.2](https://www.etsi.org/deliver/etsi_ts/121100_121199/121111/08.00.01_60/ts_121111v080001p.pdf) "User Authentication".

### CODE REVIEW

**Comment by feckert** [comment]
We have also the ncm proto for wwan handling https://github.com/openwrt/luci/blob/master/protocols/luci-proto-ncm/htdocs/luci-static/resources/protocol/ncm.js#L87 so I think we should also add pin and apn validation to this as well.

**Comment by nickberry17** [comment]
> We have also the ncm proto for wwan handling https://github.com/openwrt/luci/blob/master/protocols/luci-proto-ncm/htdocs/luci-static/resources/protocol/ncm.js#L87 so I think we should also add pin and apn validation to this as well.

Hey, that's been done now

**Comment by feckert** [comment]
Where are the APN checks?

**Comment by jow-** [comment]
Squashed and merged with whitespace fixes via 1661ac6bf8, 114dc38dc2, 6a8ad40b05 and ebb676ef7b

**Comment by suyuan168** [comment]
Not all operators need to fill in the APN.
Cannot be empty now.

**Comment by suyuan168** [comment]
> Validates APN fields in luci-proto-modemmanager, luci-proto-3g and luci-proto-qmi. The APN is validated with a custom validator function instead of adding support to LuCI validation.js, as suggested. While I'm at it I validated the PIN to a max of 4 digits for luci-proto-modemmanager.
> 
> The validation regex is based on [Chapter 9.1](https://www.etsi.org/deliver/etsi_ts/123000_123099/123003/08.08.00_60/ts_123003v080800p.pdf) of the 3GPP Spec, "Structure of APN" and the PIN length is based on [Chapter 5.2](https://www.etsi.org/deliver/etsi_ts/121100_121199/121111/08.00.01_60/ts_121111v080001p.pdf) "User Authentication".

Not all operators need to fill in the APN.
Cannot be empty now.

**Pull request closed without merging**
