### PR TITLE
 luci-app-upnp: fix name of access-control-list

### PR DESCRIPTION
**Pull request by reidar-cederqvist**
give upnp a unique acl name that does not conflict with the one of ddns.

### CODE REVIEW

**Comment by reidar-cederqvist** [comment]
@systemcrash sorry I am unfamiliar with SOB, I tried to match the commit message from other PRs, please advice if there is anything else you would like me to change

**Comment by reidar-cederqvist** [comment]
I have pushed the change to a work-branch in my fork, but unfortunately it is not possible to change the source branch in an open PR, I can open a new PR if it is preferred that the source branch is other than master

**Comment by systemcrash** [comment]
You've done everything almost correctly. The commit has:

luci-app-ddns: fix

But this regards (I assume)

luci-app-upnp: fix

**Comment by reidar-cederqvist** [comment]
Yes, thanks for noticing, it is fixed now

**Pull request merged**
