### PR TITLE
luci-mod-status: fix bugs in channel analysis

### PR DESCRIPTION
**Pull request by Ansuel**
- Add check for missing ht_operation data
- Add support for radio that both support 5 and 2.4 band
- Hide wireless station that doesn't belong to the graph band

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
I copied it to a live router, and it seemed to work ok.

Do you want to wait for additional feedback? (or just merge this?)

**Comment by Ansuel** [comment]
I would wait for additional feedback

**Comment by gw826943555** [comment]
radio0
radio1
good job! 
But the channel width of GFW(5GHz) and nicaicai_5G(5GHz) are both 80MHz.

**Comment by hnyman** [comment]
I have noticed that some radios (at least 5GHz) are first displayed as 20 GHz but if the scan page remains open, they may widen on further scans.  That happened already with the December version of code.

**Comment by Ansuel** [comment]
@hnyman the current code by default set 20mhz wide if the ht or vht info are not received. Could be that this is the problem. Could be that our wifi while scanning sometimes doesn't receive the vht info. In theory the graph should fix itself and make the wifi wider. Does this feature works?

**Comment by hnyman** [comment]
> In theory the graph should fix itself and make the wifi wider. 

Yeah, it does. I have noticed especially mwlwifi in WRT3200ACM to first show up ar 20 MHz, and then later correct itself to wider.

**Comment by hnyman** [comment]
I will merge it, so that possible feedback targets the new code.

**Pull request merged**
