### PR TITLE
luci-app-firewall: allow redirects using ip family any

### PR DESCRIPTION
**Pull request by vgaetera**
Allow creating redirects using IP family `any`.
This helps redirect both IPv4 and IPv6 traffic.
It is used to intercept traffic on the router.

### CODE REVIEW

**Comment by systemcrash** [comment]
Isn't `any` just a synonym for automatic? The wiki says:

"Protocol family (ipv4, ipv6 or any) to generate iptables rules for. "

( OK the wiki needs updating since fw4 does not use iptables any longer )

But the point is still valid - `any` just means automatic. Wouldn't it be better simply to Rename all automatic to e.g. `Either` or `Both`?

**Comment by vgaetera** [comment]
An unspecified address family makes fw4 create an IPv4-only redirect.
This was also mentioned by @jow- here:
https://forum.openwrt.org/t/current-state-of-nftables-end-of-2020/80056/16

**Comment by systemcrash** [comment]
Unspecified is the empty value, yes? Didn't know that.

So both the wiki need updating and this merging then.

**Comment by vgaetera** [comment]
> Unspecified is the empty value, yes?

To be clear, an empty `family` option works like this for redirects:
* It generates an IPv6 redirect when an IPv6 source or destination address is specified.
* It generates an IPv4 redirect when an IPv4 source or destination address is specified.
* It generates an IPv4 redirect when no source or destination address is specified.

So, a dual-stack redirect requires to specify the `family=any` which is the goal of this PR.

> the wiki need updating

Done.

**Comment by jow-** [comment]
Hmm, I think there's further changes required. We probably should disable the source and destination address fields if "any" is selected.

Can you provide an example uci rule requiring family any? Is this for port redirection?

**Comment by vgaetera** [comment]
> Can you provide an example uci rule requiring family any?

https://openwrt.org/docs/guide-user/firewall/fw3_configurations/intercept_dns

**Comment by systemcrash** [comment]
> We probably should disable the source and destination address fields if "any" is selected.

@vgaetera is that something you'd be comfortable doing also in this PR?

**Comment by vgaetera** [comment]
The current validation blocks the user from saving the rule if the combination of the IP family and address do not match.
I tested the patched web interface and this already works well, so adding more restrictions would be overkill.

**Pull request merged**
