### PR TITLE
luci-app-mwan3: bugfix

### PR DESCRIPTION
**Pull request by dibdot**
* two more luci.model.uci fixes for #1743

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by dibdot** [comment]
@hnyman @feckert

**Comment by hnyman** [comment]
> I have no LuCI from the master on my devices. I have to install a openwrt master if this is not fixed.

When you are authoring and maintaining LuCI packages, it is really advisable that you have master installed at least in one device for testing, as all stuff gets first to the master, and the main LuCI in master is evolving and deviating from the old 17.01.

**Comment by dibdot** [comment]
@feckert: sorry I don't use mwan package itself, therefore I've only fixed the obvious error.

**Comment by dibdot** [comment]
@feckert I've quickly installed a clean mwan3 package: 

- I can add new members (screenshot 1)
- The interface section looks OK to me as well, please doublecheck (screenshot 2)


mwan3_1

mwan3_2

**Comment by feckert** [comment]
@hnyman 
> When you are authoring and maintaining LuCI packages, it is really advisable that you have master installed at least in one device for testing, as all stuff gets first to the master, and the main LuCI in master is evolving and deviating from the old 17.01.

sorry for the misunderstanding!
I am testing my changes and developing against the openwrt/LuCI master, but i do not update the master periodical and to test if i have nothing on my todo list.
The errors pop up after my last change because of changes in LuCI core.

@dibdot thanks for your test.

@dibdot @hnyman If will flash a box with the newest master openwrt/Luci and do some testings.
thanks

**Comment by autoexec-bob** [comment]
As a user of mwan3, I would like to give thanks for fixing these bugs and committing them to master.

However, the status bug still remains.  Your screenshot shows the MWAN interfaces from:
Network -> Load Balancing -> Interface

The bug affects Status -> Load Balancing -> Interface
MWAN Interfaces
No MWAN interfaces found

I have traced this to a problem with the status function inside mwan3.lua

function mwan_Status()
        local status = ut.ubus("mwan3", "status", {})

The ut.ubus call is not returning what is is supposed to.
You can verify this by trying the ubus call at the command line:

root@OpenWrt-Q:~# ubus -v list mwan3
'mwan3' @680b92ff
        "status":{"section":"String","interface":"String"}

root@OpenWrt-Q:~# ubus -v call mwan3 status
Command failed: No response

The ubus interface is provided by the mwan3 shell script located here:  /usr/libexec/rpcd/mwan3

I am looking into the shell script now; but; this is as far as I have gotten.
I don't have experience with the OpenWRT ubus system.

I hope this helps.

**Comment by autoexec-bob** [comment]
I just fixed the bug with Status -> Load Balancing -> Interface
MWAN Interfaces
No MWAN interfaces found

It was an error in the  /usr/libexec/rpcd/mwan3 shell script.
A local variable was defined outside of a function which is illegal in sh (or ash, in this case).

Line 89 had the following:

                        local section iface

The solution is to change these 2 variables to global by defining them up top.

Delete line 89                            local section iface

Define the variables as globals at the top of the script:

#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh
. /usr/share/libubox/jshn.sh
. /lib/mwan3/common.sh

MWAN3TRACK_STATUS_DIR="/var/run/mwan3track"

IPS="ipset"
IPT4="iptables -t mangle -w"
IPT6="ip6tables -t mangle -w"

section=""
iface=""


Please test the solution and commit.

Thanks.

- Bob

**Comment by dibdot** [comment]
@autoexec-bob good catch! I would simply remove this bogus local statement ... but as I said before, I don't use mwan3 package and this bug is located in the core package - @feckert will take care for sure! ;-)

**Comment by feckert** [comment]
@dibdot @autoexec-bob thanks for your work and bug hunting.
I will make a PR today to remove this `local` statements.

**Comment by feckert** [comment]
@autoexec-bob i have added a PR to https://github.com/openwrt/packages/pull/5904 to fix your issue
I have moved the hole code block into a main function (its like c).

**Comment by autoexec-bob** [comment]
Thank you @feckert and @dibdot for your work on this.

**Pull request merged**
