### PR TITLE
fix string "UPNP" -> "UPnP"

### PR DESCRIPTION
**Pull request by ollie27**

### CODE REVIEW

**Comment by hnyman** [comment]
The UPnP change looks good, but I don't especially like the Wi-Fi change.

Wifi or wifi is used so much in Openwrt (e.g. "wifi up" command etc.) that using Wi-Fi looks a bit strange. I know that Wi-Fi is the "official" term defined by Wi-Fi Alliance, but in everyday use "wifi" is currently more common.

**Comment by ollie27** [comment]
Maybe we could compromise and use WiFi as that also seems to an acceptable way of writing it. Although it looks like LuCI just uses the term Wireless everywhere else so we could switch to that instead.

**Comment by hnyman** [comment]
I would maybe prefer "Wireless" as the item in the Network menu, as the settings page itself is.titled "Wireless Overview"

@jow- 
Any comments on changing Wifi to WiFi, Wi-Fi or Wireless ???

**Comment by hnyman** [comment]
Could you drop the Wi-Fi change from the pull request and leave just the UPnP changes?
I could then merge the UPnP part, which makes sense.

**Pull request merged**
