### PR TITLE
init Material Design theme

### PR DESCRIPTION
**Pull request by LuttyYang**
I created a Material Design theme today, I want to add it into LUCI.

This theme is more suitable for the modern computer screen, and it improved support for mobile phones.

some screenshots:

Material for LuCI - Computer screenshot 1
Material for LuCI - Computer screenshot 2
Material for LuCI - Computer screenshot 3

Material for LuCI - Mobile screenshot 1
Material for LuCI - Mobile screenshot 2
Material for LuCI - Mobile screenshot 3

### CODE REVIEW

**Comment by hnyman** [comment]
I actually built your theme based on the previous pull request and tried it. (see below)

Looks like you have the paths wrong below 'htdocs'
There should be htdocs/luci-static/material directory and all htdocs stuff should then below it, because that is defined as the theme's root dir in uci-defaults. (and as there may be several themes installed, it is a good practice not to pollute /www with several subdirs specific to one theme only)

I manually created /www/luci-static/material/ and moved the subdirectories css fonts and js from /www to it, and things started to work.

    root@OpenWrt:/www# ls luci-static/material/
    css    fonts  js


But logo got lost somewhere. You might test with compiling the package to an *.ipk and installing it manually with opkg to check that it installs cleanly. (install to a clean router, naturally)

(Ps. You can update the commits in your local branch and "push -f" them to github to update this PR. Or you can push additional commits to this PR. There is no need to create a new PR after every small change. That works at least if you have a feature branch locally.)

Screenshot:
luci_material

**Comment by hnyman** [comment]
Another comment: the uci-defaults file seems to have DOS/windows line endings "0d 0a", unlike the other files. That causes trouble when running "opkg install". You should verify that line endings are normal unix-like "0a".

**Comment by LuttyYang** [comment]
Oh... uci-defaults file is write by Windows editor, I am fix the path error and uci-defaults file, but I do not know how to compiling the package to an *.ipk, can you tell me?

**Comment by LuttyYang** [comment]
I can using SDK to  compiling the package to an ipk file ,this is my dir tree:

```
(PC)[dlll luci-theme-material]$ ls -R .
.:
files  Makefile  README.md

./files:
htdocs  templates

./files/htdocs:
css  favicon.ico  fonts  js  logo.png

./files/htdocs/css:
style.css

./files/htdocs/fonts:
font.eot  font.svg  font.ttf  font.woff

./files/htdocs/js:
jquery.min.js  script.js

./files/templates:
footer.htm  header.htm

```

**Comment by hnyman** [comment]
1)
I have not used the SDK ever, so no help for that. I have always used the full buildroot. With the full buildroot, "make package/luci/compile" at your Openwrt buildroot should create the .ipk package at bin/<platform>/packages/luci directory. (or a general "make" will generate the package there along all other packages )

2)
I think that you have still got the directories wrong. You skipped the /luci-static/ part, while still saying /luci-static/material in the uci-defaults script

When I compiled it for myself, this directory structure worked:
```
	new file:   themes/luci-theme-material/Makefile
	new file:   themes/luci-theme-material/htdocs/luci-static/material/css/style.css
	new file:   themes/luci-theme-material/htdocs/luci-static/material/favicon.ico
	new file:   themes/luci-theme-material/htdocs/luci-static/material/fonts/font.eot
	new file:   themes/luci-theme-material/htdocs/luci-static/material/fonts/font.svg
	new file:   themes/luci-theme-material/htdocs/luci-static/material/fonts/font.ttf
	new file:   themes/luci-theme-material/htdocs/luci-static/material/fonts/font.woff
	new file:   themes/luci-theme-material/htdocs/luci-static/material/js/jquery.min.js
	new file:   themes/luci-theme-material/htdocs/luci-static/material/js/script.js
	new file:   themes/luci-theme-material/htdocs/luci-static/material/logo.png
	new file:   themes/luci-theme-material/luasrc/view/themes/material/footer.htm
	new file:   themes/luci-theme-material/luasrc/view/themes/material/header.htm
	new file:   themes/luci-theme-material/root/etc/uci-defaults/luci-theme-material
```

**Comment by LuttyYang** [comment]
I am added /luci-static/ part, I am try using the full buildroot to compiling the package.

Another words: My English is very bad, apologize for any inconvenience caused.

**Comment by LuttyYang** [comment]
I am used the full buildroot to compiled the package.
image
and find luci-theme-material_git-15.259.53707-f3f0de3-1_all.ipk in /bin/ar71xx/packages/base
then I installing it manually with opkg in a clean router, it worked.

so commit version cdf3122 is worked

**Comment by hnyman** [comment]
Good to hear that it works.

Currently none of your 3 commits has any commit message and none them is "signed off" by you.
You should probably squash the commits into one single commit for clarity, as two of them are mainly just renames. Then edit its commit message to be a short introduction to the theme and make sure that the commit message contains the signed-off-by line with your name & email.
See https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md and https://dev.openwrt.org/wiki/SubmittingPatches#a10.Signyourwork

@jow- 
Your comment to adding a new alternative theme to Luci?

**Comment by jow-** [comment]
I like the theme, fine with me if the commits are corrected.

**Comment by LuttyYang** [comment]
@hnyman I push a new commit,  would it be all right?

**Comment by hnyman** [comment]
I merged it. The commit message could have been a bit longer and it would have better to have just one signed commit, but I think that was good enough.

**Comment by LuttyYang** [comment]
@ thank you, I'll try my best.

**Comment by hnyman** [comment]
If you want users & feedback, you might start a theme-specific discussion thread at the Openwrt forums:

https://forum.openwrt.org/viewforum.php?id=16
Community Releases / Announcements

**Comment by LuttyYang** [comment]
@hnyman OK, I started a thread at the Openwrt forums, welcome to use and feedback.

https://forum.openwrt.org/viewtopic.php?pid=292211

**Pull request merged**
