### PR TITLE
luci-mod-status: add support for the 6g band

### PR DESCRIPTION
**Pull request by dhewg**
Currently, results from the 2.4 and 6 ghz bands get mixed together, because internally the channel number is used for some checks.

This adds some checks to prevent that, and then adds a new 6g band tab.

This works on my end, but my AP is the only 6g one nearby, so I don't have others in my scan results. Can someone test that please?

### CODE REVIEW

**Comment by mj22226** [comment]
@dhewg I tested, scan works, 6 ghz band is less crowded.

Screenshot_20230805

**Comment by dhewg** [comment]
Nice, thanks!
The channel width looks wrong though, could you please run `ubus call iwinfo scan '{"device":"radioX"}'` (where X=your 6g radio), fish out the 6g nets and paste them here?

**Comment by dhewg** [comment]
Well, maybe those widths are okay. At least my local 80mhz wide network shows up correctly.
This is a nice improvement, so let's merge and fix anything up if issues pop up?

**Comment by Ansuel** [comment]
@dhewg we should think of a solution for those channel number... Any idea?

**Comment by dhewg** [comment]
The shot above may be an extreme example. It depends on the country code and the available channels. It looks like this for me:
6g

**Comment by Ansuel** [comment]
@dhewg mhhh ok but we also need to handle that case... I think a 2 line implementation is the simplest one and would solve the thing... and maybe guard it and enable this only when then chan number is > of a specific value?

I can do some test if you don't have time with handling this

**Comment by dhewg** [comment]
That would be nice, js isn't my strong suit...

**Comment by Ansuel** [comment]
@mj22226 can you create an issue about this adding your image and tagging me so we can track this and I won't forget to improve this?

**Comment by Ansuel** [comment]
@dhewg nit last commit can you improve the commit description? Something like "Enable support for 6GHz band now that code supports it"

**Pull request merged**
