### PR TITLE
luci-app-dynapoint: new package

### PR DESCRIPTION
**Pull request by ascob**
Maintainer: me
Compile tested: OpenWRT trunk
Run tested: OpenWRT trunk

Description:
LuCI Support for DynaPoint
Dynapoint allows dynamic access point creation
and deletion depending on changes of certain network conditions.
More information: https://github.com/thuehn/dynapoint
Dynapoint Pull request: https://github.com/openwrt/packages/pull/3304

### CODE REVIEW

**Comment by cshoredaniel** [comment]
What is dynapoint?  Please add this information to commit and PR.

**Comment by cshoredaniel** [comment]
@ascob Sorry the formatting threw me; can you add:

LuCI Support for DynaPoint
Dynapoint allows dynamic access point creation
and deletion depending on changes of certain network conditions.
More information: https://github.com/thuehn/dynapoint

To the commit message please?

**Comment by ascob** [comment]
@cshoredaniel I updated the commit message accordingly.

**Comment by cshoredaniel** [comment]
Pulled into my test tree

**Comment by cshoredaniel** [comment]
I get:
/usr/lib/lua/luci/dispatcher.lua:380: Failed to execute cbi dispatcher target for entry '/admin/services/dynapoint'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:38: Model 'dynapoint/dynapoint' not found!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:380: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:109: in function </usr/lib/lua/luci/dispatcher.lua:108>

**Comment by ascob** [comment]
Thanks. It's fixed now.

**Pull request merged**
