### PR TITLE
luci-app-advanced-reboot: show OpenWrt info on compatible NAND routers

### PR DESCRIPTION
**Pull request by stangri**
Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by hnyman** [comment]
@stangri 
I am now seeing this in system log in WRT3200ACM, when I navigate to AdvancedReboot page:

```
Sat Nov 16 20:24:08 2019 daemon.err uhttpd[4410]: umount: can't unmount /alt/firmware: No such file or directory
Sat Nov 16 20:24:08 2019 daemon.err uhttpd[4410]: umount: can't unmount /alt/overlay: No such file or directory
Sat Nov 16 20:24:08 2019 daemon.err uhttpd[4410]: umount: can't unmount /alt/rom: No such file or directory
Sat Nov 16 20:24:08 2019 daemon.err uhttpd[4410]: ubiblock: error!: cannot open UBI volume "/dev/ubi1_0"
Sat Nov 16 20:24:08 2019 daemon.err uhttpd[4410]:           error 16 (Resource busy)
Sat Nov 16 20:24:08 2019 daemon.err uhttpd[4410]: ubidetach: error!: cannot detach mtd8
Sat Nov 16 20:24:08 2019 daemon.err uhttpd[4410]:            error 19 (No such device)
Sat Nov 16 20:24:08 2019 kern.err kernel: [12241.616455] ubi1 error: ubi_open_volume: cannot open device 1, volume 0, error -16
Sat Nov 16 20:24:08 2019 daemon.err uhttpd[4410]: ubidetach: error!: cannot detach mtd8
Sat Nov 16 20:24:08 2019 daemon.err uhttpd[4410]:            error 19 (No such device)
Sat Nov 16 20:24:08 2019 kern.notice kernel: [12241.634746] ubi2: attaching mtd8
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.103562] ubi2: scanning is finished
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.111799] ubi2: attached mtd8 (name "rootfs2", size 74 MiB)
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.117569] ubi2: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.124487] ubi2: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.131314] ubi2: VID header offset: 2048 (aligned 2048), data offset: 4096
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.138310] ubi2: good PEBs: 592, bad PEBs: 0, corrupted PEBs: 0
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.144341] ubi2: user volume: 2, internal volumes: 1, max. volumes count: 128
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.151606] ubi2: max/mean erase counter: 6/3, WL threshold: 4096, image sequence number: 24238052
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.160603] ubi2: available PEBs: 0, total reserved PEBs: 592, PEBs reserved for bad PEB handling: 40
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.169873] ubi2: background thread "ubi_bgt2d" started, PID 7332
Sat Nov 16 20:24:09 2019 kern.info kernel: [12242.179194] block ubiblock2_0: created from ubi2:0(rootfs)
Sat Nov 16 20:24:09 2019 daemon.err uhttpd[4410]: mount: mounting /dev/ubi1_2 on /alt/overlay failed: Invalid argument
Sat Nov 16 20:24:09 2019 daemon.err uhttpd[4410]: mount: mounting overlay on /alt/firmware failed: No such file or directory
Sat Nov 16 20:24:09 2019 kern.err kernel: [12242.198244] overlayfs: failed to resolve '/alt/overlay/upper': -2
Sat Nov 16 20:24:09 2019 daemon.err uhttpd[4410]: umount: can't unmount /alt/firmware: Invalid argument
Sat Nov 16 20:24:09 2019 daemon.err uhttpd[4410]: umount: can't unmount /alt/overlay: Invalid argument
Sat Nov 16 20:24:09 2019 daemon.err uhttpd[4410]: ubiblock: error!: cannot open UBI volume "/dev/ubi1_0"
Sat Nov 16 20:24:09 2019 daemon.err uhttpd[4410]:           error 16 (Resource busy)
Sat Nov 16 20:24:09 2019 kern.err kernel: [12242.264269] ubi1 error: ubi_open_volume: cannot open device 1, volume 0, error -16
Sat Nov 16 20:24:09 2019 kern.info kernel: [12242.350881] block ubiblock2_0: released
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.354773] ubi2: detaching mtd8
Sat Nov 16 20:24:09 2019 kern.notice kernel: [12242.358502] ubi2: mtd8 is detached
```

LuCI Master (git-19.320.34348-1df1421) / OpenWrt SNAPSHOT r11526-f84d6d2f3a

**Comment by stangri** [comment]
@hnyman I'll work on the errors, but the kernel notices will still be present.

I've also discovered that the actual reboot doesn't work on 19.07 due to luci changes, I think I'll look into this first.

**Comment by hnyman** [comment]
> I'll work on the errors, but the kernel notices will still be present.

Sounds bad if such scary kernel UBI errors would be permanent. They will confuse users.
Maybe reverting back to the old version without the info would be better.

**Comment by hnyman** [comment]
@stangri 
With reference to you comment that the new code may not actually reboot on 19.07 (and 18.06???), should we revert the app version bump on those branches while you work on fixes?

**Comment by stangri** [comment]
> Sounds bad if such scary kernel UBI errors would be permanent.

No, I think I can get rid of the errors, the kernel notices will be permanent tho. Please clarify if you think that the kernel notices are too scary too.


> With reference to you comment that the new code may not actually reboot on 19.07 (and 18.06???), should we revert the app version bump on those branches while you work on fixes?

The old version wouldn't reboot either. I'm calling ```luci.template.render("admin_system/applyreboot")```  as the last step and this is broken on 19.07. @jow- if you can reply with what should I replace it with on 19.07 before I can look at the new code and figure it out I'd be much obliged.

**Pull request merged**
