### PR TITLE
luci-app-openvpn: Update Spanish translation

### PR DESCRIPTION
**Pull request by castillofrancodamian**
Update Spanish translation

Signed-off-by: Franco Castillo <castillofrancodamian@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
The same thing again. all 844 lines deleted and re-created.
You have edited the same file last time two weeks ago, and then there was no problem. What has happened in the meanwhile?

**Comment by castillofrancodamian** [comment]
> The same thing again. all 844 lines deleted and re-created.
> You have edited the same file last time two weeks ago, and then there was no problem. What has happened in the meanwhile?

I do not know what it could be. There must be a problem with the file. I will try another way.

**Comment by hnyman** [comment]
Typical reason might be DOS-Unix line-ednings difference (CRLF vs. LF)
But hard to figure out why that would manifest now.

**Comment by hnyman** [comment]
Please verify the file difference after committing to your own fork,  before publishing the actual PR.

**Pull request closed without merging**
