### PR TITLE
luci-app-wireguard: resolve meta package in depdencies

### PR DESCRIPTION
**Pull request by danrl**
Signed-off-by: Dan Luedtke <mail@danrl.com>

### CODE REVIEW

**Comment by danrl** [comment]
Possible solution for https://github.com/openwrt/luci/commit/0f5321d2ebe801fea77031fed221ae7b13636816#commitcomment-20966776

**Comment by lucize** [comment]
the build process is successful

regards !

**Comment by hnyman** [comment]
> the build process is successful

It has been successful all the time, but because "wireguard" is empty, just two dependencies, no installable .ipk package file is created. And thatswhy the "opkg install" will fail, because there is no wireguard.ipk. The user (or opkg) can't install "wireguard" and he needs to somehow know that he should install "kmod-wireguard" and "wireguard-tools" instead. 

The empty metapackage dependencies work only in the build system, and thatswhy the package authors probably never notice the problem (as they include the package in their build).

99% of similar packages have 
  luci-app --> userspace package --> kernel package

But for some reason, wireguard has an empty metapackage on depending on both the userspace package and the kernel package. I can't really see the reason to install only userspace but no kernel, so that makes no sense...  (or can the userspace package be used without the kernel support?)

@danrl @zx2c4 

The are two long-term solutions:
* create an almost empty "install" section (containing just "true" ) in Makefile for "wireguard", so that the .ipk gets created for the metapackage. That can be installed by opkg and it calls the dependencies. Similar solution has been done e.g. for open-plc-utils, xz, boost:
   https://github.com/ffainelli/packages/commit/dc368cbcd0930f122ba70656066113dbdb879d12
  https://github.com/openwrt/packages/pull/1272/files
  https://github.com/openwrt/packages/pull/1487/files

* delete metapackage, rename wireguard-tools to wireguard and have it depend on the kernel package. Then the app is "normal". (But if the userspace app can be used without kernel, then this is not optimal)

**Comment by danrl** [comment]
The wg utility from tools can be used without the kernel module, although it makes little sense. It can je used for key generation for example. The keys could be used on another system.

I am in favor of an empty meta package to not force someone installing the kernel module when only the utility is wanted for some reason.

**Comment by zx2c4** [comment]
Actually wg(8) will also speak to userspace (slow) wireguard
implementations, so it's got some utility beyond the kmod, in addition to
the key generation bits Dan mentioned.

**Comment by hnyman** [comment]
> The wg utility from tools can be used without the kernel module

Ok, then the metapackage has a role.
If somebody wants only "-tools", he can install only that.

> I am in favor of an empty meta package to not force someone installing the kernel module when only the utility is wanted for some reason.

But then the metapackage should not be quite as empty as now. Now it installs nothing with opkg, but in the build system it installs both wireguard-tools and kmod-wireguard. That is a discrepancy.

You should add the almost empty install section to the metapackage to force the creation of the .ipk file. After that opkg install would work the same way as currently menuconfig & defconfig:  you select wireguard that selects -tools and kmod- packages 
```
define Package/wireguard/install
  true
endef
```

**Comment by danrl** [comment]
"But then the metapackage should not be quite as empty as now. Now it installs nothing with opkg, but in the build system it installs both wireguard-tools and kmod-wireguard. That is a discrepancy."

Agreed! That empty ("true") install section was what I meant. Something that creates the package but not any other files on install. I can take care of this later today or this week, or maybe @zorun jumps in.

**Comment by zorun** [comment]
I didn't know there could be a discrepancy between the build system and the target.

I'm fine with an empty "wireguard" package that pulls both kmod-wireguard and wireguard-tools, so that users are not confused.  But packages like luci-app-wireguard should depend explicitly on kmod-wireguard and/or wireguard-tools (depending on the needs).

**Comment by zx2c4** [comment]
There is now the empty wireguard package in the latest package. Fixed!

**Pull request merged**
