### PR TITLE
luci-mod-status: highlight primary 20 MHz channel

### PR DESCRIPTION
**Pull request by knarrff**
before
after
(The reason the strongest station from image 1 is missing in image 2 is simple: it was one of mine, which simply is not there anymore.)

As of now, channel analysis highlights the complete frequency spectrum of a base station (all channels used by the station, which might be more or fewer depending on channel bonding). This means in particular, that in the plot, a station at one main channel might look identical to another station at a different channel, because both might use the same bonded channel spectrum.

One such example is two 80 MHz stations on channels 100 and 108 respectively: both will be plotted from channel 100 up to 115, as both will use those those 80 MHz. This is not incorrect, but it makes it more difficult to see which station is really where, as they might as well switch back to 20 or 40 MHz at times, or for different clients, and where they are then is currently not visible in the plot.

This patch adds another trapez to the plot at the main 20 MHz channel of a station, with width 20 MHz, in case the station uses a wider general width. This is visible, because those polygons are partially transparent. It also moves the x-position of the label to the main channel of the station (which now is marked: this would have looked odd before).

This does not highlight the primary 40 MHz channel for 80 MHz channels and wider. It should be possible be compute this from the knowledge in luci of the primary 20 MHz channel, the center channel and the bandwidth, assuming ac logic, but I decided against adding it, to keep the plot less cluttered.

### CODE REVIEW

**Comment by castillofrancodamian** [comment]
Could you review [this](https://github.com/openwrt/luci/issues/6419)?

**Comment by knarrff** [comment]
I did have a look and commented there. The PR here should be independent though, as #6419 is about a shifted 20 MHz station in the plot, and this PR here only adds something for channels wider than 20 MHz, so it leaves 20 MHz channels as before.

**Comment by systemcrash** [comment]
> This does not highlight the primary 40 MHz channel for 80 MHz channels and wider. It should be possible be compute this from the knowledge in luci of the primary 20 MHz channel, the center channel and the bandwidth, assuming ac logic, but I decided against adding it, to keep the plot less cluttered.

@knarrff Could you show us just how cluttered it looks for 40 and 80 MHz please? ("why treat only 20 when we can treat all of them...")

**Comment by knarrff** [comment]
@systemcrash: I can't show it at the moment, without implementing it in the first place. I do not think it would be particularly difficult to implement, just tedious.

Ideally, if you want to go that route, some more logic would be nice to easily get to all necessary values (like the center frequency of 40 MHz channels if the overall bandwidth is larger). This could come in handy also someplace else than channel_analysis.js, and as such should be provided to channel_analysis.js instead of living inside it. iwinfo comes to mind, but then this becomes an entirely different matter.

**Comment by systemcrash** [comment]
Is it possible to provide some extra hinting in the SVG which helps anchor the fact that this is a primary channel within this SSID, rather than how it looks now: possibly two overlapping SSIDs?

**Comment by systemcrash** [comment]
That looks pretty sweet.

Is that gradient or blur an expensive function?

**Comment by knarrff** [comment]
I have adapted to the gradient highlight. It is not expensive, as this is a very standard svg gradient and nothing that would be implemented in js. Also, because this way, the drawing of the main channel (20 MHz) does something different than the drawing of the complete channel (>20 MHz), I reworked the original patch to make it simpler in the end and also smaller compared with current master. The change to the svg only adds the definition of the gradient itself (thus, no visible change), which is then later referenced in the js code.

**Comment by systemcrash** [comment]
@knarrff Could you update the header graphics demonstrating the PR changes please?

**Comment by knarrff** [comment]
> @knarrff Could you update the header graphics demonstrating the PR changes please?

I updated the image in the main description with the one from https://github.com/openwrt/luci/pull/6723#issuecomment-1843815093

**Comment by systemcrash** [comment]
@knarrff OK, are you happy with how things are now?

@jow- any reservations on this cosmetic change?

**Comment by knarrff** [comment]
> @knarrff OK, are you happy with how things are now?

Yes.

**Pull request merged**
