### PR TITLE
Luci-app-fwknopd:add a couple config options to the interface

### PR DESCRIPTION
**Pull request by oneru**
Minor tweaks to uci-defaults
refresh translation files
Signed-off-by: Jonathan Bennett <JBennett@incomsystems.biz>

### CODE REVIEW

**Comment by chris5560** [comment]
@oneru 
Are the changes in sync with last changes to the fwknopd package at openwrt/packages ?
Or are there no dependencies ?

**Comment by oneru** [comment]
@chris5560 I believe there are no dependancies between the two changes. Also, I've tested them together without problems.

~Jonathan

**Comment by oneru** [comment]
@chris5560 also, I maintain both packages, so I generally will avoid breaking one from the other. ;)

**Comment by chris5560** [comment]
Thanks

**Pull request merged**
