### PR TITLE
luci-app-nft-qos: fix lua trace by moving limit_mac_enabled option.

### PR DESCRIPTION
**Pull request by qiuzi**
Signed-off-by: Lopot li <gxfclql@gmail.com>

### CODE REVIEW

**Comment by feckert** [comment]
In order for me to be able to merge this, you still have to write your real name in front of the email address for a correct Signed-off-by.

**Comment by qiuzi** [comment]
@feckert  Signed-off-by: <> gxfclql@gmail.com ？
 Is it the signature in <>?

**Comment by feckert** [comment]
Please update your commit with this Signed-off-by from your first comment in this Pullrequest.
So we have this also in your commit:
`Signed-off-by: Lopot li <gxfclql@gmail.com>`

**Comment by qiuzi** [comment]
@feckert  I have edited in the first comment

**Comment by feckert** [comment]
Yes, I know that, but it doesn't have to be in the pullrequest but in the commit!
https://github.com/openwrt/luci/pull/5660/commits/b9ad925a5e2a2406a58d99607c0d49008a972653
Replace `Signed-off-by: qiuzi <gxfclql@gmail.com>` with `Signed-off-by: Lopot li <gxfclql@gmail.com>`
It is the commit that goes into the repository and not the pullrequest.
The pullrequest only serves as a discussion platform.

**Comment by qiuzi** [comment]
Such a rule 狗屎

**Pull request closed without merging**
