### PR TITLE
luci-proto-ipv6: dhcpv6.js fix translation

### PR DESCRIPTION
**Pull request by try496**

### CODE REVIEW

**Comment by try496** [comment]
@systemcrash Tried creating a new commit

**Review by stokito — APPROVED** [review]

**Comment by try496** [comment]
@systemcrash Modification completed

**Comment by systemcrash** [comment]
Great, thanks!

**Comment by jow-** [comment]
That merge was a bit premature, I wanted to point out that the translations should contain a context, since `try`, `force` and `disabled` alone are very broad and fuzzy.

**Pull request merged**
