### PR TITLE
Correction by script i18n-sync.sh with editing of Russian translation

### PR DESCRIPTION
**Pull request by user7887**
Signed-off-by: Vladimir <picfun@ya.ru>

### CODE REVIEW

**Comment by hnyman** [comment]
You need to rebase your branch.
I already pushed those changes a few minutes ago.

Likely the pull request is unnecessary.

**Comment by user7887** [comment]
I see thanks, I'm doing it now, I have a variant with translation:)

**Comment by user7887** [comment]
Now everything is fine :)

**Comment by hnyman** [comment]
It would be easier for you if you would have committed the i18n-sync changes separately in one commit and then your Russian changes in a separate commit. You have also mixed things up, as your first commit includes both i18n-sync changes and your own Russian translations that are not mentioned in the title.

Right now only the Russian changes are needed.

> Now everything is fine :)

Not quite. Merge commits are not accepted. You need to squash them away before the PR will be accepted. Advice in https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md#advice-on-pull-requests (git pull and merge actually made things a bit more difficult)

In practice, "git rebase -i HEAD~3" and then interactive editing of the commit selection (which are to be picked in).

Alternatively, might be easier to reset HEAD to the previous commit 846be36cf in master, and re-commit your own translation after that in a new commits that you force push. 

(If it goes over your head, I can squash those myself, but it would be good for you to pactice getting it right with git)

Ps. I think that Github should have warned you about a possible conflict when you authored the PR.

**Comment by user7887** [comment]
Thank you very much, I try to be diligent :) 
Sorry for possible inconvenience. I carefully read it. 
Thank you!

**Comment by user7887** [comment]
"Alternatively, might be easier to reset HEAD to the previous commit 846be36 in master"
I will do so, nothing comes out :(

**Pull request closed without merging**
