### PR TITLE
luci-app-aria2: add button ariang-nginx

### PR DESCRIPTION
**Pull request by shenghuang147**
Fix `luci` not showing `AriaNg-Nginx` button
Because the `ariang-nginx` package name is `ariang-nginx`, but this file does not add this package, so it cannot be recognized.
But the web service path of this package is still `ariang`, so I added a judgment condition to the `openWebInterface` method

Signed-off-by: Sheng Huang [shenghuang147@gmail.com](mailto:shenghuang147@gmail.com)

### CODE REVIEW

**Comment by feckert** [comment]
Please add a valid SOB with your real name.
Also update your commit message `luci-app-aria2: add button ariang-nginx`

**Comment by shenghuang147** [comment]
> Please add a valid SOB with your real name. Also update your commit message `luci-app-aria2: add button ariang-nginx`

Modified, please check

**Comment by BKPepe** [comment]
You have changed the pull request but not the commit itself, where it is required. Could you please check it one more time?

**Comment by shenghuang147** [comment]
> You have changed the pull request but not the commit itself, where it is required. Could you please check it one more time?

Sorry, I'm a novice and I'm not familiar with Github, can you help me see if this works?

**Pull request closed without merging**
