### PR TITLE
luci-base: hosts.js: Update chinese translations

### PR DESCRIPTION
**Pull request by muink**

### CODE REVIEW

**Comment by feckert** [comment]
Please add a Signed-off-by to your commit with your real name and mail. See the other commits

**Comment by muink** [comment]
> Please add a Signed-off-by to your commit with your real name and mail. See the other commits

Means I need to close this PR and re-submit? 
and need sign the commit with a personal gpg key?

**Comment by nickberry17** [comment]
> > Please add a Signed-off-by to your commit with your real name and mail. See the other commits
> 
> Means I need to close this PR and re-submit?
> and need sign the commit with a personal gpg key?

No, you can just do something like `git commit --amend --signoff` then `git push --force-with-lease`

**Comment by feckert** [comment]
Please read https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md
You have also add your real name to the signoff.

**Comment by feckert** [comment]
Thanks merged

**Pull request merged**
