### PR TITLE
luci-mod-system: Update system.lua

### PR DESCRIPTION
**Pull request by angusding**
Fix for more accurate description.
Signed-off-by: Angus Ding <angus.ding@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Please amend this pull request to update all translation files as well.

**Comment by angusding** [comment]
> Please amend this pull request to update all translation files as well.

**Comment by angusding** [comment]
Update all base.po files as follows::

Templates: de1f01baf3db48cff1b12ab07c82f2f3997d7fde

ca(Catalan): cc24bfb392e10812e25e5ddd701406ac095db76a

cs(Czech): 84549ee441ffec3b7217bcf27c582cbdb7d7a410

de(German): dddfad311f76d2dcfe715b2bdd28b36ebb4b6cd1

el(Greek): ab3ccb0e3c6df7600f1590b077fad1397b05936e

en(English): 586436f22ef83fd25e80b54cc14bbcd3851bcdb6

es(Spanish): 8b055fc8abb252f98bc007ddbb91c75ab63d37af

fr(French): ad1556eeb04aa1584843bca79303063b32a52daa

he(Hebrew): 701bcd2a5b77568e45a4a7c75bb66d467e982113

hu(Hungarian): ef6a693733e4d00603da1474cfed04abd34400a3

it(Italian): b0deb6a49cbccb1b07bda99f23659aa53100f657

ja(Japanese): 82b4aae8b412f716e96a616aa62473963e197685

ko(Korean): 1c3241d173c9d143c28bc2bea0413f53e8ccead7

ms(Malay): 6e0b035e21076232d870b7412c9ae8962ba36b8a

no(Norwegian): 3205eaef3dcf85db532bde4c81672cb2a38436f2

pl(Polish): a7c209c53fed79b898baf5bc2baf427547b73b00

pt-br(Brazialian Portuguese): a577bbf7d49295e3bddb413dfad5bc76852f4353

pt(Portuguese): 80cda4cf9a46e4e93d5d16d5ef98b045a77c604f

ro(Romanian): 5c5d33479691f84492deb71d48262a45df469561

ru(Russian): 29e011a35fddb4afe693eb04e6d8fc5c4f7d2d7c

sk(Slovak): 26a2f0f6b8c4f74be34d9905f81d0c6c5e3c31d1

sv(Swedish): 2b94a8b12aa13c731974cc200f38c4a375a1f0e9

tr(Turkish): 614c3281b6b56ea8b40df7373844c4c74f70c49c

uk(Ukrainian): 230fd8c5a614507a771b7f6b330f4e5164684308

vi(Vietnamese): 0634aff24a17509f775e133a7552a6c6f6fccf74

zh-cn(Chinese): 6286289335a3202ae40697b15234caa4543ad320

zh-tw(Taiwanese): 3c4762bb37f956768de28c774b13e6a1aae74b7f

**Comment by angusding** [comment]
Update all base.po files as follows::

Templates: de1f01baf3db48cff1b12ab07c82f2f3997d7fde

ca(Catalan): cc24bfb392e10812e25e5ddd701406ac095db76a

cs(Czech): 84549ee441ffec3b7217bcf27c582cbdb7d7a410

de(German): dddfad311f76d2dcfe715b2bdd28b36ebb4b6cd1

el(Greek): ab3ccb0e3c6df7600f1590b077fad1397b05936e

en(English): 586436f22ef83fd25e80b54cc14bbcd3851bcdb6

es(Spanish): 8b055fc8abb252f98bc007ddbb91c75ab63d37af

fr(French): ad1556eeb04aa1584843bca79303063b32a52daa

he(Hebrew): 701bcd2a5b77568e45a4a7c75bb66d467e982113

hu(Hungarian): ef6a693733e4d00603da1474cfed04abd34400a3

it(Italian): b0deb6a49cbccb1b07bda99f23659aa53100f657

ja(Japanese): 82b4aae8b412f716e96a616aa62473963e197685

ko(Korean): 1c3241d173c9d143c28bc2bea0413f53e8ccead7

ms(Malay): 6e0b035e21076232d870b7412c9ae8962ba36b8a

no(Norwegian): 3205eaef3dcf85db532bde4c81672cb2a38436f2

pl(Polish): a7c209c53fed79b898baf5bc2baf427547b73b00

pt-br(Brazialian Portuguese): a577bbf7d49295e3bddb413dfad5bc76852f4353

pt(Portuguese): 80cda4cf9a46e4e93d5d16d5ef98b045a77c604f

ro(Romanian): 5c5d33479691f84492deb71d48262a45df469561

ru(Russian): 29e011a35fddb4afe693eb04e6d8fc5c4f7d2d7c

sk(Slovak): 26a2f0f6b8c4f74be34d9905f81d0c6c5e3c31d1

sv(Swedish): 2b94a8b12aa13c731974cc200f38c4a375a1f0e9

tr(Turkish): 614c3281b6b56ea8b40df7373844c4c74f70c49c

uk(Ukrainian): 230fd8c5a614507a771b7f6b330f4e5164684308

vi(Vietnamese): 0634aff24a17509f775e133a7552a6c6f6fccf74

zh-cn(Chinese): 6286289335a3202ae40697b15234caa4543ad320

zh-tw(Taiwanese): 3c4762bb37f956768de28c774b13e6a1aae74b7f

**Comment by angusding** [comment]
Update all base.po files as follows::

Templates: de1f01baf3db48cff1b12ab07c82f2f3997d7fde

ca(Catalan): cc24bfb392e10812e25e5ddd701406ac095db76a

cs(Czech): 84549ee441ffec3b7217bcf27c582cbdb7d7a410

de(German): dddfad311f76d2dcfe715b2bdd28b36ebb4b6cd1

el(Greek): ab3ccb0e3c6df7600f1590b077fad1397b05936e

en(English): 586436f22ef83fd25e80b54cc14bbcd3851bcdb6

es(Spanish): 8b055fc8abb252f98bc007ddbb91c75ab63d37af

fr(French): ad1556eeb04aa1584843bca79303063b32a52daa

he(Hebrew): 701bcd2a5b77568e45a4a7c75bb66d467e982113

hu(Hungarian): ef6a693733e4d00603da1474cfed04abd34400a3

it(Italian): b0deb6a49cbccb1b07bda99f23659aa53100f657

ja(Japanese): 82b4aae8b412f716e96a616aa62473963e197685

ko(Korean): 1c3241d173c9d143c28bc2bea0413f53e8ccead7

ms(Malay): 6e0b035e21076232d870b7412c9ae8962ba36b8a

no(Norwegian): 3205eaef3dcf85db532bde4c81672cb2a38436f2

pl(Polish): a7c209c53fed79b898baf5bc2baf427547b73b00

pt-br(Brazialian Portuguese): a577bbf7d49295e3bddb413dfad5bc76852f4353

pt(Portuguese): 80cda4cf9a46e4e93d5d16d5ef98b045a77c604f

ro(Romanian): 5c5d33479691f84492deb71d48262a45df469561

ru(Russian): 29e011a35fddb4afe693eb04e6d8fc5c4f7d2d7c

sk(Slovak): 26a2f0f6b8c4f74be34d9905f81d0c6c5e3c31d1

sv(Swedish): 2b94a8b12aa13c731974cc200f38c4a375a1f0e9

tr(Turkish): 614c3281b6b56ea8b40df7373844c4c74f70c49c

uk(Ukrainian): 230fd8c5a614507a771b7f6b330f4e5164684308

vi(Vietnamese): 0634aff24a17509f775e133a7552a6c6f6fccf74

zh-cn(Chinese): 6286289335a3202ae40697b15234caa4543ad320

zh-tw(Taiwanese): 3c4762bb37f956768de28c774b13e6a1aae74b7f

**Comment by angusding** [comment]
@jow- 
Update all base.po files as follows::

Templates: de1f01baf3db48cff1b12ab07c82f2f3997d7fde

**Comment by angusding** [comment]
[](url)
Update all base.po files as follows::

Templates: [de1f01baf3db48cff1b12ab07c82f2f3997d7fde](url)

ca(Catalan): [cc24bfb392e10812e25e5ddd701406ac095db76a](url)

cs(Czech): [84549ee441ffec3b7217bcf27c582cbdb7d7a410](url)

de(German): [dddfad311f76d2dcfe715b2bdd28b36ebb4b6cd1](url)

el(Greek): [ab3ccb0e3c6df7600f1590b077fad1397b05936e](url)

en(English): [586436f22ef83fd25e80b54cc14bbcd3851bcdb6](url)

es(Spanish): [8b055fc8abb252f98bc007ddbb91c75ab63d37af](url)

fr(French): [ad1556eeb04aa1584843bca79303063b32a52daa](url)

he(Hebrew): [701bcd2a5b77568e45a4a7c75bb66d467e982113](url)

hu(Hungarian): [ef6a693733e4d00603da1474cfed04abd34400a3](url)

it(Italian): [b0deb6a49cbccb1b07bda99f23659aa53100f657](url)

ja(Japanese): [82b4aae8b412f716e96a616aa62473963e197685](url)

ko(Korean): [1c3241d173c9d143c28bc2bea0413f53e8ccead7](url)

ms(Malay): [6e0b035e21076232d870b7412c9ae8962ba36b8a](url)

no(Norwegian): [3205eaef3dcf85db532bde4c81672cb2a38436f2](url)

pl(Polish): [a7c209c53fed79b898baf5bc2baf427547b73b00](url)

pt-br(Brazialian Portuguese): [a577bbf7d49295e3bddb413dfad5bc76852f4353](url)

pt(Portuguese): [80cda4cf9a46e4e93d5d16d5ef98b045a77c604f](url)

ro(Romanian): [5c5d33479691f84492deb71d48262a45df469561](url)

ru(Russian): [29e011a35fddb4afe693eb04e6d8fc5c4f7d2d7c](url)

sk(Slovak): [26a2f0f6b8c4f74be34d9905f81d0c6c5e3c31d1](url)

sv(Swedish): [2b94a8b12aa13c731974cc200f38c4a375a1f0e9](url)

tr(Turkish): [614c3281b6b56ea8b40df7373844c4c74f70c49c](url)

uk(Ukrainian): [230fd8c5a614507a771b7f6b330f4e5164684308](url)

vi(Vietnamese): [0634aff24a17509f775e133a7552a6c6f6fccf74](url)

zh-cn(Chinese): [6286289335a3202ae40697b15234caa4543ad320](url)

zh-tw(Taiwanese): [3c4762bb37f956768de28c774b13e6a1aae74b7f](url)

**Comment by angusding** [comment]
Update all base.po files as follows::

Templates: de1f01baf3db48cff1b12ab07c82f2f3997d7fde

ca(Catalan): cc24bfb392e10812e25e5ddd701406ac095db76a

cs(Czech): 84549ee441ffec3b7217bcf27c582cbdb7d7a410

de(German): dddfad311f76d2dcfe715b2bdd28b36ebb4b6cd1

el(Greek): ab3ccb0e3c6df7600f1590b077fad1397b05936e

en(English): 586436f22ef83fd25e80b54cc14bbcd3851bcdb6

es(Spanish): 8b055fc8abb252f98bc007ddbb91c75ab63d37af

fr(French): ad1556eeb04aa1584843bca79303063b32a52daa

he(Hebrew): 701bcd2a5b77568e45a4a7c75bb66d467e982113

hu(Hungarian): ef6a693733e4d00603da1474cfed04abd34400a3

it(Italian): b0deb6a49cbccb1b07bda99f23659aa53100f657

ja(Japanese): 82b4aae8b412f716e96a616aa62473963e197685

ko(Korean): 1c3241d173c9d143c28bc2bea0413f53e8ccead7

ms(Malay): 6e0b035e21076232d870b7412c9ae8962ba36b8a

no(Norwegian): 3205eaef3dcf85db532bde4c81672cb2a38436f2

pl(Polish): a7c209c53fed79b898baf5bc2baf427547b73b00

pt-br(Brazialian Portuguese): a577bbf7d49295e3bddb413dfad5bc76852f4353

pt(Portuguese): 80cda4cf9a46e4e93d5d16d5ef98b045a77c604f

ro(Romanian): 5c5d33479691f84492deb71d48262a45df469561

ru(Russian): 29e011a35fddb4afe693eb04e6d8fc5c4f7d2d7c

sk(Slovak): 26a2f0f6b8c4f74be34d9905f81d0c6c5e3c31d1

sv(Swedish): 2b94a8b12aa13c731974cc200f38c4a375a1f0e9

tr(Turkish): 614c3281b6b56ea8b40df7373844c4c74f70c49c

uk(Ukrainian): 230fd8c5a614507a771b7f6b330f4e5164684308

vi(Vietnamese): 0634aff24a17509f775e133a7552a6c6f6fccf74

zh-cn(Chinese): 6286289335a3202ae40697b15234caa4543ad320

zh-tw(Taiwanese): 3c4762bb37f956768de28c774b13e6a1aae74b7f

**Comment by angusding** [comment]
Update all base.po files as follows::

Templates: de1f01baf3db48cff1b12ab07c82f2f3997d7fde

**Comment by angusding** [comment]
> Please amend this pull request to update all translation files as well.

OK! Close this pull and use new one to do it.

**Pull request closed without merging**
