### PR TITLE
luci-app-package-manager: rename from luci-app-opkg and add APK support

### PR DESCRIPTION
**Pull request by Ansuel**
Rename luci-app-opkg to luci-app-ipkg and add APK support for it.

The idea is to adapt APK to mimic OPKG output to require minimal changes
to the luci app.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

---

@jow- @aparcar @hauke 

TODO:
- [x] Config handling
- [x] Test install/remove
- [ ] Test update scenario
- [x] Handle --autoremove 
- [x] Handle --force-overwrite 
- [x] Handle --force-removal-of-dependent-packages

What works:
- [x] List packages
- [x] Update package list

Depends on:
https://github.com/openwrt/openwrt/pull/16759

### CODE REVIEW

**Comment by systemcrash** [comment]
Does this mean all rpc calls or otherwise to `opkg` must be updated?

**Comment by stangri** [comment]
> Rename luci-app-opkg to luci-app-ipkg and add APK support for it.

Why `luci-app-ipkg`? Why not `luci-app-pkg-manager`/`luci-app-package-manager` for example?

**Comment by systemcrash** [comment]
@stangri 

> Why `luci-app-ipkg`? Why not `luci-app-pkg-manager`/`luci-app-package-manager` for example?

standard naming convention ig.

**Comment by Ansuel** [comment]
> Does this mean all rpc calls or otherwise to `opkg` must be updated?

all rpc calls -> none

OPKG is enough sensible to wrap it in helper script and we already minimize it to just opkg-call script hence it's all handled there, we don't call opkg directly.

**Comment by Ansuel** [comment]
> > Rename luci-app-opkg to luci-app-ipkg and add APK support for it.
> 
> Why `luci-app-ipkg`? Why not `luci-app-pkg-manager`/`luci-app-package-manager` for example?

yes can be an idea but for sure the name needs to be changed to something more generic.

**Comment by hnyman** [comment]
+1 for a clear name that is also understandable by newcomers.

`luci-app-packagemanager` would be my favorite

**Comment by lorand-horvath** [comment]
**`luci-app-opm`** - short for Openwrt Package Manager

**`luci-app-pm`** - even shorter

**Comment by castillofrancodamian** [comment]
> +1 for a clear name that is also understandable by newcomers.
> 
> `luci-app-packagemanager` would be my favorite

Or `luci-app-package-manager`. I like it better.

**Comment by systemcrash** [comment]
Full names tend to serve better than ambiguous acronyms and abbreviations for first-timers. 

I like luci-app-package-manager

**Comment by Ansuel** [comment]
Actually this went pretty fast... Should be finished... Maybe the po file needs some bit of touchup...

**Comment by systemcrash** [comment]
@Ansuel 
```sh
build/i18n-sync.sh modules/luci-app-package-manager
```

**Comment by systemcrash** [comment]
Closed by bcd13b918e2f30b8d19027a06e3d773a1b0ec4c0

**Comment by Ansuel** [comment]
@stokito thanks for the comments I will take care of fixing them

**Comment by systemcrash** [comment]
Yo @Ansuel can this get cherry-picked to 23 or is there stuff it requires from master?

**Comment by Ansuel** [comment]
not at all... 23 doesn't even have working apk. Why should we backport?

**Comment by systemcrash** [comment]
Ah, maybe I can just take the useful fix from #7340 to 23?

**Comment by Ansuel** [comment]
@systemcrash yep that was why it was in a dedicated commit :D

**Pull request closed without merging**
