### PR TITLE
luci-theme-nightstrap: add new theme

### PR DESCRIPTION
**Pull request by Aeneon**
I've created a real Nightmode for OpenWrt based on the Bootstrap-Theme. This Commit contains a tweaked "cascade.css" and "mobile.css" with the new Colorization and a few Fixes, so it looks much better than the original Bootstrap-Theme. The "header.htm" and "footer.htm" are unchanged …

Hopefully this Packages will be included in a further Release of OpenWrt.

### CODE REVIEW

**Comment by jow-** [comment]
I'm relucatant to merge yet another theme. Can you rework `Bootstrap` instead and factor out the color changes into a separate CSS file? Maybe take a look at https://github.com/openwrt/luci/pull/2159 to see how this can be achieved.

**Comment by Aeneon** [comment]
I'll do it hopefully this Week. Thanks for your Answer …

**Comment by feckert** [comment]
Any progress on this PR?

**Comment by Aeneon** [comment]
Not really. Currently it's not possible for me to "reduce" the Style to Custom Variables. There's to much I've done and there are also a few Fixes inside the Style. If you want to add it, have a Look at this [Repo](https://github.com/Aeneon/luci-theme-nightstrap) …

**Comment by feckert** [comment]
Nice view but as mention by @jow- we could not support another theme.

I think the only way to get more themes into LuCI is to support only two base themes
* Side menu (bootstrap)
* Drop down menu (material)

So we have only 2 header.htm and footer.htm.

All other changes should be done in CSS with **variables** which could be custemized or  **separate** CSS-files which could be replaced.

**Comment by jow-** [comment]
Closing this as this has seen no progress. It would also be incompatible with current master.

**Comment by rafay-ositech** [comment]
@Aeneon How did  you test your theme? I mean how to build and deploy the theme on my router's Luci? I'm new in LuCI and have tried editing in material theme, but can't find a way to run that theme on my router. any leads?

**Comment by Aeneon** [comment]
@rafay-ositech Have a Look at this [Project](https://github.com/Aeneon/luci-theme-nightstrap), here you can find all necessary Files and Edits …

**Pull request closed without merging**
