### PR TITLE
 luci-app-frpc: add uci file read permissions

### PR DESCRIPTION
**Pull request by zhanhb**
Add required permission

### CODE REVIEW

**Comment by feckert** [comment]
I could not see in the code that you need passwd or group permissions.
Can you show me this in frpc code?

**Comment by zhanhb** [comment]
image

https://github.com/openwrt/luci/blob/e05c219b24645f27e8d0adc2a523d610392246a3/applications/luci-app-frpc/htdocs/luci-static/resources/view/frpc.js#L11-L12

**Comment by brvphoenix** [comment]
@feckert 
https://github.com/openwrt/luci/pull/4026
This is caused by the loss of read permissions in the `luci-base`. All packages using `UserSelect` and `GroupSelect` widgets have this issue.

**Comment by feckert** [comment]
Got it
Thanks

**Pull request merged**
