### PR TITLE
luci-app-lxc: initial commit

### PR DESCRIPTION
**Pull request by danrl**
Moved over here from the packages repository.

Signed-off-by: Dan Luedtke <mail@danrl.com>

### CODE REVIEW

**Comment by hnyman** [comment]
What happened to lxc.config  file?

Have you compared the compiled results?

**Comment by danrl** [comment]
I kind of fixed it. I was thinking about using a uci-defaults script, but let's just stick with what the original authors had in mind.

**Comment by hnyman** [comment]
Well, the fix went partially wrong. Directory is "root" instead of "rootfs"

**Comment by danrl** [comment]
Renamed rootfs to root. Build not yet tested.

**Comment by hnyman** [comment]
I will merge this, as I tested it myself 2 days ago, and otherwise the build was ok except that root.

**Pull request merged**
