### PR TITLE
luci-app-usteer: Added 2 missing parameters, updated 2 defaults, updated help texts

### PR DESCRIPTION
**Pull request by Ramon00**
Added 2 missing parameters, updated 2 defaults, updated help texts

### CODE REVIEW

**Comment by Jonsonmon** [comment]
It is an Important update

**Comment by systemcrash** [comment]
Can you do the same for the last "empty means all"?

**Comment by Ramon00** [comment]
yes sorry, I was too hasty

**Comment by systemcrash** [comment]
Merged. Thanks!

**Comment by Ramon00** [comment]
@systemcrash thank you

**Pull request merged**
