### PR TITLE
build,travis: add script from openwrt/packages.git

### PR DESCRIPTION
**Pull request by aparcar**
add .travis.yml and a slightly modiefied .travis_do.sh to fit the
luci.git repository structure.

Builds all changed packages of the `applications/` folder.

Script is adapted from openwrt/packages.git based on @lynxis work.

Changes of script are mostly:

* 68: PKGS var is set differently due auto versioning of luci packages
* 88: use Githubs openwrt/packages.git as feed
* 101, 112: no need to parse pkg_name
* 186: use different first commit hash

Signed-off-by: Paul Spooren <paul@spooren.de>

### CODE REVIEW

**Comment by lynxis** [comment]
@aparcar:
- line 68: I don't like to filter only for applications
- line 88: ok.
- line 101/112: why do you removed it?
- linue 186: ok

**Comment by aparcar** [comment]
@lynxis 

- line 68: I don't like to filter only for applications
It's changed to applications/collections/contrib/libs/modules/protocols/themes
- line 88: ok.
- line 101/112: why do you removed it?
It's set via line 68, no need for any further modifications. 
- line 186: ok

**Comment by hnyman** [comment]
@jow- 
any thoughts on activating travis also here in LuCI, like on packages feed?

@lynxis @champtar
Any further comments from the travis specialists?

**Comment by lynxis** [comment]
@aparcar why do you want to filter the files? Do you have any example when the script would otherwise fail?

**Comment by aparcar** [comment]
@lynxis the other folders do not contain _Makefiles_ so I thought no packages can result -> nothing to build

**Comment by aparcar** [comment]
@lynxis please see line 188. It reads the first commit id so it could be used for packages.git as well.

**Comment by lynxis** [comment]
@aparcar LGTM. Do you tested it?

**Comment by aparcar** [comment]
@lynxis yes I created [this](https://github.com/aparcar/luci/pull/5/files) rather useless PR changing packages/files at different locations. The scripts [finds](https://travis-ci.org/aparcar/luci/builds/271508539#L685) all changes correctly.

**Comment by lynxis** [comment]
thanks for your work!

**Comment by champtar** [comment]
Hi @aparcar 
Just want to double check that the ```FIRST_COMMIT_ID``` works in all cases.
Also maybe we can make this script generic enough to share it between repos?

**Comment by aparcar** [comment]
@champtar what do you mean with all cases? I tried it and it works as (I) expected.

I started on a more generic approach but it got a bit messy as https://github.com/openwrt-routing/packages uses a different structure/depth of packages. 
There where some ideas about merging to openwrt/packages but stopped for a while https://github.com/openwrt-routing/packages/issues/184

**Comment by feckert** [comment]
I think this could be closed because of
https://github.com/openwrt/luci/commit/da35bfcf54246550bd00b1004f5ec2ca3764457b#diff-df4a0e327b62c8cc393e4f285d1d86e4

**Comment by aparcar** [comment]
@feckert thanks for reviewing, when I created the other PR I totally forgot about this one!

**Pull request closed without merging**
