### PR TITLE
add rubyfish.cn DOH servise in china

### PR DESCRIPTION
**Pull request by kkjoy**
add rubyfish.cn in china

### CODE REVIEW

**Comment by feckert** [comment]
@stangri ok from your side?
@kkjoy Please sign off you work with your real name and mail address
Please add a meaningful header for your commit header/message
*luci-app-https_dns_proxy: \<message\>*
and also fixup up your commits into one.

**Comment by feckert** [comment]
You do not have to delete your branch if you want to change your pullrequest.
Edit your commits rebase them and then do a force push.
Have a look at git workflow

**Comment by stangri** [comment]
@kkjoy, just a FYI, the principle package is moving away from JSON-based resolvers to the RFC8484 (binary) resolvers in the next version. I will add rubyfish then.

**Comment by kkjoy** [comment]
> You do not have to delete your branch if you want to change your pullrequest.
> Edit your commits rebase them and then do a force push.
> Have a look at git workflow

I am just a starter and this is my first commit at github,got it thanks a lot

**Comment by stangri** [comment]
BTW, looks like that resolver is using JSON API and not RFC8484, so it will not be supported from next release forward.

**Pull request closed without merging**
