### PR TITLE
luci-mod-admin-full: improve applyreboot page

### PR DESCRIPTION
**Pull request by Ansuel**
This improve applyreboot page and fix problem with luci-nginx that doesn't refresh the page when the router reboot.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Do we really need those inline styles? You could move them to the material theme CSS and I'll take care of adding appropriate styles to the other themes.

**Comment by Ansuel** [comment]
2 class with that styles should be good right? 
applyreboot-container
applyreboot-section

**Comment by Ansuel** [comment]
@jow- inline style removed... tested with all the other themes

**Comment by jow-** [comment]
Almost fine :) Can you please replace `fieldset` with `div` ?

**Comment by Ansuel** [comment]
done @jow-

**Comment by jow-** [comment]
merged, thanks!

**Pull request merged**
