### PR TITLE
luci-proto-3g: fix error on proto selection

### PR DESCRIPTION
**Pull request by feckert**
If you select the proto 3g you will see the following error

> Missing protocol extension for proto "3g"
cannot open /usr/lib/lua/luci/model/cbi/admin_network/proto_3g.lua: No such file or directory

To fix this move the 3g proto from `luci-proto-ppp` to `luci-proto-3g` and add the missing file `proto_3g.lua` under `/model/network/`.

### CODE REVIEW

**Comment by yousong** [comment]
Have you installed the `luci-proto-3g` package.  From the directory layout file `admin_network/proto_3g.lua` is supposed to be provided by it.  If that is the case, a routine fix should be moving the file into `luci-proto-ppp` like other ppp-related protocols.

Or if we care about space preservation, like `luci-proto-3g` we can move those protocols each into their own package and let `proto:opkg_package()` returning the package name.

**Comment by feckert** [comment]
@yousong  I would prefer your suggestion.

> Or if we care about space preservation, like luci-proto-3g we can move those protocols each into their own package and let proto:opkg_package() returning the package name.

 If some needs this package he could install this over **opkg** the following protocols  into separate packages

I have also staged (but not opened a PR) to move also
- pppossh https://github.com/openwrt/luci/blob/master/protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppossh.lua
- hnet https://github.com/openwrt/luci/blob/master/protocols/luci-proto-ipv6/luasrc/model/network/proto_hnet.lua
- aiccu https://github.com/openwrt/luci/blob/master/protocols/luci-proto-ipv6/luasrc/model/network/proto_aiccu.lua

I am not sure if l2tp should also go to a separate package.
https://github.com/openwrt/luci/blob/master/protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_l2tp.lua

**Comment by yousong** [comment]
Hi, @feckert , why `proto_l2tp` is special?

**Comment by feckert** [comment]
@yousong sorry my fault!

For protocol luci-proto-ppp:
You are right only the following protocols should be included into this packages all other should go into a separate package. They all depend onto the **ppp** package. So only the following protocols should got into luci-proto-ppp.

luci-proto-ppp:
- pppoe
- pppoa
- pptp
- ppp

The following package should go into separate packages
- luci-proto-3g
- luci-proto-l2tp
- luci-proto-pppossh

For protocol luci-proto-ipv6:
This was already split up into different files but this should also go into separate packages

The following package should go into separate packages and the **luci-proto-ipv6 could be deleted**.
- luci-proto-4to6
- luci-proto-6to4
- luci-proto-aiccu
- luci-proto-dhcpv6
- luci-proto-hnet

So we have after this changes the following protocols

- luci-proto-ppp
- luci-proto-3g
- luci-proto-l2tp
- luci-proto-pppossh
- luci-proto-4to6
- luci-proto-6to4
- luci-proto-aiccu
- luci-proto-dhcpv6
- luci-proto-hnet

From my point of view i think we should only install protocols which are really needed by the user. If the user has a special use case then the missing protocols could be installed by opkg.

If we use a wwan connection the protocols are already split up into separate packages
- luci-proto-qmi
- luci-proto-ncm

**Comment by yousong** [comment]
Hi @feckert , 

Personally, I got the impression pppoe, pptp, l2tp as a group is very common in the market.  It would be good to have them present (visible) in the default installation.

The same goes for those ipv6 protocols, but I only have limited experience with them in OpenWrt.  I think the main idea is that those commonly used native and transitional technologies by ISPs should be grouped together.

The change will be user-visible and as such it will be good to have some feedback from at least several other users.

Thank you.

**Comment by feckert** [comment]
@yousong 

> The same goes for those ipv6 protocols, but I only have limited experience with them in OpenWrt. I think the main idea is that those commonly used native and transitional technologies by ISPs should be grouped together.

I do not think so because we do not have a ipv4 proto either!
From the user point of view the user could install the protocols he like and do not get spawned with this lot of protocols which he normal not uses.
From my experience i was confused when i have seen this lot protocols. 

By the way. In then cellular (qmi/nbim) and vpn (wiregurad/openconnect) they have also separate protocol handlers and have not been include in a proto cellular or vpn.

So I think it is better to separate the protocols.

> The change will be user-visible and as such it will be good to have some feedback from at least several other users

what can we do to get a feedback?

Thanks for feedback

**Comment by yousong** [comment]
Hi, @feckert , the line on grouping common protocols together is more because of my perception of them being very popular and expected by a lot of users.  It may save people a few google searches and clicks in the ui to install them.  Splitting them each into its own tiny unit may seem uniform as a whole but probably not a most practical user-friendly way of doing it.  This is of course my personal view on this.

As for how to get some feedback, I think opening another issue/pull request will be enough.  If it's good or bad, the act to take is clear, otherwise the bits will rotten away ;)

**Comment by yousong** [comment]
Close this as the discussion has been mostly irrelevant to the original topic

**Comment by feckert** [comment]
@yousong you are right this was not the topic of the PR.
but the failure on selecting 3g proto is still there.
So why close this PR?
Should i reopen another with the same topic?

**Comment by yousong** [comment]
Please open another one.  As the new fix will be very different from the current one anyway.

**Pull request closed without merging**
