### PR TITLE
luci-app-shadowsocks-libev: fix cidr datatype

### PR DESCRIPTION
**Pull request by dibdot**
* fix unknown cidr datatype (#2671)

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by dibdot** [comment]
@yousong @jow-

**Comment by yousong** [comment]
Hi @dibdot , thanks for taking care of this.  The issue was caused by commit a86c068870dea59844a282ca43885ef4fcbfa07f .  "cidr" as a validator is part of ubox validate command.  Maybe we should add 'cidr' as a alias for cidr4 and cidr6 into LuCI

**Comment by jow-** [comment]
@dibdot - can you extend the client side JS validator in cbi.js as well?

**Comment by dibdot** [comment]
@jow- There's already a generic 'cidr' function in cbi.js or did you mean something different!?

**Comment by jow-** [comment]
@dibdot - ah nevermind then, sorry. I didn't bother to actually look due to spotty 3g connection.

**Pull request merged**
