### PR TITLE
luci-base: show manufacturer in leases overview page

### PR DESCRIPTION
**Pull request by feckert**
This pull-request will add the feature, which was requested in the issue #2065.

**This works for now only for ipv4.**

I have added a new package for luci (ouidb) to lookup the company name with the oui part of the mac. I have also added the possibily, that the ouidb is not required for small devices. So if ouidb file is not installed then it will not shown in then status page.

To minify the oui database, I have added a python convert script to remove the unneeded information.
Only the Company name and the oui are written to the ouidb.

Size difference

- With all information 6.3MB
- With oui and manufacture information  0.9MB

### CODE REVIEW

**Comment by jow-** [comment]
Please hold this request for now, the corresponding code will be soon converted to JavaScript.

**Comment by 49616e** [comment]
> Please hold this request for now, the corresponding code will be soon converted to JavaScript.

I'm not sure if this is 100% on-topic but OUI info would be a good thing to have on the the wireless page as well.

**Comment by lucize** [comment]
or in Routes section ?

**Comment by kayrus** [comment]
+1 for this feature. @feckert could you pleas rebase?

**Comment by tapper82** [comment]
+1 for this feature.

**Comment by 49616e** [comment]
> Please hold this request for now, the corresponding code will be soon converted to JavaScript

Since `modules/luci-base/luasrc/view/lease_status.htm` and `modules/luci-base/luasrc/tools/status.lua` are both gone, I assume the relevant lua code has already been converted to js now? If that's the case, please consider reworking on this PR now, thanks. @feckert

**Comment by feckert** [comment]
@jow- I just wanted to update the pullrequest.
Not sure where to put this right now.
I could add the need information to luci-rpc in this function.
https://github.com/openwrt/luci/blob/0412e85a57c2f271c24fe837e3a6adcf60bc63f1/libs/rpcd-mod-luci/src/luci.c#L1739
We could check if the oui db file is present and if so, add the needed information to the ubus object.
This could then be used in the status pagehttps://github.com/openwrt/luci/blob/master/modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/40_dhcp.js

**Comment by jow-** [comment]
That would be one approach, yes. Another one would be loading the OUI database on the client side and use it there.

**Comment by odkrys** [comment]
+1 It's closed, but I hope it gets added as a package.

**Pull request closed without merging**
