### PR TITLE
luci-app-dawn: Add configuration page

### PR DESCRIPTION
**Pull request by findlayfeng**
Add the configuration page under the network path
Move hearing_map and network_overview pages to status path

- [x] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [x] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [x] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [x] Incremented :up: any `PKG_VERSION` in the Makefile
- [x] Tested on: (architecture, openwrt version, browser) :white_check_mark:
- [ ] \( Preferred ) Mention: @ the original code author for feedback
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [ ] \( Optional ) Closes: e.g. openwrt/luci#issue-number
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [x] Description: (describe the changes proposed in this PR)

### CODE REVIEW

**Comment by systemcrash** [comment]
Could you provide a few overview screenshots please @findlayfeng ?

**Comment by systemcrash** [comment]
ping @findlayfeng

**Comment by findlayfeng** [comment]
dawn

**Comment by systemcrash** [comment]
We absolutely shall not use default values anywhere. Those first variables in the screen shot (thank you) don't have any placeholder values. What are the units for bandwidth? What is a collision domain? Is iv - init vector?

There's no value type or error checking for fields. Do the IP fields only take ipv4 and some random text appended to them? Or must they be strictly ipv4? ipv6?

**Comment by systemcrash** [comment]
ping @findlayfeng

**Comment by systemcrash** [comment]
ping @findlayfeng

**Comment by systemcrash** [comment]
Closed by df3a77e49cfd95247f9783e4321e9876d5c90ec1

**Pull request closed without merging**
