### PR TITLE
mod-admin-full: Allow odhcpd to be configured via LuCI

### PR DESCRIPTION
**Pull request by danrl**
This is what I have been running for a while now on one of my LEDE routers. I use odhcp and unbound to replace dnsmasq. I built custom images without dnsmasq for this.

* The test for `has_dnsmasq` was not sufficient and failed when odhcp was present but dnsmasq not.
* Some comments did not really represent what the code was doing (DNS, DHCP, etc.)
* I left the dnsmasq section mostly untouched, although I feel the urge to rename/rearrange a couple of things as they are not where they belong from a technical point of view.
* For odhcpd, I have arranged configuration items in a less confusing manner. IPv6 is not advanced, it is the new normal. We may reflect these changes in the networking world by naming things appropriately. However, I hesitate(d) from changing things for dnsmasq, as I like the user experience to be consistent from one release to the next whenever possible. But we should do new things right.
* We have sections for "General", "IPv4" and "IPv6" now. Protocol versions are clearly separated and users are able to understand what protocol is affected by which section. There are users that do not want to run one of the IP protocols, which is a legitimate use case, I think.
* With dnsmasq the M and O-Flag did depend on using dnsmasq for dhcpv6. I think this is a bug. As I said I left this untouched. For odhcpd I removed that dependency. I do not want to forbid users to run a dhcpv6 server from another machine. The LEDE router may be the one sending out RAs but may not be the dhcpv6 server in that network, and this is fine and a legitimate use case.

I would like to join these changes and the ones @cshoredaniel made in https://github.com/openwrt/luci/pull/964 as I think that they are even better together. Also, I would love to hear @EricLuehrsen's opinion, he has recently worked with odhcpd and maybe aware of caveats or mistakes in my code I have overlooked. There is also a multiple-instances of dnsmasq pull request from @cshoredaniel, which may or may not be affected by changes in this PR.

Let's discuss, guys! What is the best way to get odhcp and dnsmasq to coexist?

Signed-off-by: Dan Luedtke <mail@danrl.com>

PS: If you have not tried yet, build without dnsmasq and with unbound and odhcpd. It's wonderful to have a local resolving, validating nameserver on your router and the features of odhcpd.

### CODE REVIEW

**Comment by EricLuehrsen** [comment]
odhcpd is reasonably simple in that it doesn't have a lot of options which can be good or bad  depending on your goals. Its hard to do wrong here.

One caveat is that odhcpd and dnsmasq-UCI do not share option space. odhcpd uses `option dns` and `option domain` for each dhcp instance by design. These could be interpreted also by dnsmasq-UCI scripts for common interface. dnsmasq itself needs a different syntax and handles far more comprehensive options. dnsmasq handles auto-assignment like [fd00::] to mean the ULA of this interface. dnsmasq only assigns a domain per instance,and so, requires multiple dnsmasq instances (which then don't share cache memory or cpu processing of DNSSEC). When building LuCI you need to recognize these and display or hide them appropriately.

_off topic: Long term somebody should get odhcpd and dnsmasq-UCI to share option statements and deprecate the older way in either or both. The scripts would be easy to write. C-code option space parsing uses uci libraries, so no issue there in odhcpd. Organizing the community to accept the changes is not easy._

**Comment by EricLuehrsen** [comment]
As a matter of consistency, I would like the DNS/DHCP **global** settings that are not intrinsic to a networks configuration settings be moved to 'services' menu. Something like 'General DNS-DHCP'. The network tab is cluttered.

**Comment by danrl** [comment]
> As a matter of consistency, I would like the DNS/DHCP global settings that are not intrinsic to a networks configuration settings be moved to 'services' menu. Something like 'General DNS-DHCP'. The network tab is cluttered.

I would go even further: Split DNS and DHCP. They have nothing in common except that we use dnsmasq (not a big fan, just someone didn't notice) and therefore it made sense to configure these on the same page. It does make sense on low-end devices, but everything as "powerful" as a raspberryPI can run unbound or other DNS software alongside almost any other common dhcp server. Often, thanks to recent works, even with dhcp-clients showing up in the DNS.

**Comment by hnyman** [comment]
I would prefer to keep the basic network config, including DHCP and DNS, in the Network tab. It is easier to the casual users.

**Comment by danrl** [comment]
If we want to discuss this, we should probably do this in the mailing list and more publicly.

**Comment by cshoredaniel** [comment]
Marking this and #964 as 'needs update' to reflect desire to merge the two.

**Comment by danrl** [comment]
Working on it. Will post here once it is ready for review. WiP currently, don't merge or build this now :)

**Comment by danrl** [comment]
Still working in it. It became bigger than expected. I hope to finish this up by the end of the week. Thanks for everyones patience so far!

**Comment by cshoredaniel** [comment]
DUID are not necessary 16 hexdigits; there are different lengths of duid (I've seen mac-based ones in some cases with some additional stuff which are shorter and some longer ones which seem uuid-ish).  No details on the rules though, sorry.  In any event the duid validation just added will prevent entry of valid duid's

**Comment by EricLuehrsen** [comment]
Two common types you will see: rfc6355 defines a arbitrary UUID fro 144 bits (16 bit DUID type, 128 bit UUID). rfc3315 LLT defines 102 bits (16 bit DUID type, 16 bit hardware type, 32 bit time, 48 bit mac).

**Comment by hnyman** [comment]
@danrl 
Please leave here only your own commits.
Now there are about 48 extra commits. You likely tried to update this branch with new upstream commits, but it does not look good...

You should rebase the branch.
Probably this would work:
* first update your master with upstream commits
* then checkout this branch
* and "git rebase master". That should pick up new commits from master, and move the branching point upward towards HEAD and leave your own commits on top of them. (and eliminate the master commits from this branch.)

Then you can update this github PR with "git push -f"

**Comment by danrl** [comment]
Oh dear, this is still open :(
There is much more work to do regarding odhcpd than I anticipated. Let me close this and open a new PR once I finished work.
Sorry for the buzz!

**Pull request closed without merging**
