### PR TITLE
luci-app-openvpn-policy-routing: initial commit

### PR DESCRIPTION
**Pull request by stangri**
This is a companion package for openvpn-policy-routing allowing easy Web-based configuration.

Please provide feedback on the code.

Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by danrl** [comment]
Does this change support IPv6? From the source it looks like legacy IP only.

**Comment by stangri** [comment]
@ddanrl -- no, it doesn't yet. If the main app works well enough for IPv4 I can look into adding IPv6 support (or would welcome a PR) in it, along with the luci app, but I haven't dealt with IPv6 and not sure I understand enough about it to do it right away.

**Comment by danrl** [comment]
I am happy to help you understand it. I think we shouldn't merge new code that doesn't work with IPv6. In this case this should be a quick fix. I'll have a look at it soon.

**Comment by stangri** [comment]
@danrl, well, adding IPv6 support to luci app in my local repo is completed. It's ready to be merged! ;)

For the main package tho, what are the IPv6 substitutes for: ip, iphash, ipset? How do I obtain the IPv6 gateway (is there such a thing as IPv6 gateway or is it called an IPv6 server?) for the OpenVPN tunnel? 

Maybe we should take this conversation off the comments, can you please e-mail me at the address in the makefile?

**Comment by stangri** [comment]
@hnyman Hannu, I've asked on the forum -- what's the most reliable way to detect if dnsmasq is being used for name resolution? Presence of /var/run/dnsmasq/dnsmasq.cfg*? Or is parsing of either /var/etc/dnsmasq.conf* or /var/run/dnsmasq.cfg* required?

**Comment by danrl** [comment]
@stangri That is a tricky question and I think you are onto something here.
The most reliable way would be `netstat` but that's not what I suggest.

Working on a different part but having the same problem, I suggest we introduce a variable for that in the long term. For now I think any workaround is OK. Presence of `/var/run/dnsmasq.cfg` seems the best choice to me. Beware, I am not deep into dnsmasq. Not a big fan of dnsmasq at all /o\

**Comment by stangri** [comment]
@danrl, ```/var/run/dnsmasq.cfg*``` files have ```.dhcp``` extension so I suspect they may be present when dnsmasq is used for serving dhcp (I've read about people using unbound for name resolution and still keeping dnsmasq for dhcp). 

```/var/run/dnsmasq/dnsmasq.cfg*``` however doesn't have anything to do with dhcp in the name, so short of parsing ```/var/etc/dnsmasq.conf.*``` I'm guessing it's a best bet, unless I'm told otherwise.

**Comment by danrl** [comment]
You are right. I forgot about the `.dhcp` extension. That combination of DHCP and DNS in a single program is a mess*!

*On systems powerful enough to run unbound. Like, almost all systems.

**Comment by stangri** [comment]
@danrl, do you know if unboud on LEDE supports ipsets configuration via uci? Is the syntax same as dnsmasq ```/domain/domain/ipset```?

**Comment by danrl** [comment]
Not that I am aware of. unbound uses `forward` directives for that. @EricLuehrsen is the unbound guy around here I guess :)

**Comment by stangri** [comment]
@danrl, thank you, I've sent @EricLuehrsen an e-mail about it.

Why would you not advise using netstat (and how btw) to determine if dnsmasq is used for name resolution? Do you think parsing /var/etc/dnsmasq.conf* is a better option?

**Comment by danrl** [comment]
> Why would you not advise using netstat
Well, I think this is something that should not be done in Luci because it is too complex and still a dirty hack. As I said, I do not suggest it, but nothing is stopping you to do it. Maybe it turns out well? I doubt it, though.

**Comment by stangri** [comment]
The only solid information I found on disabling DNS functions of dnsmasq, while retaining DHCP functions pointed to specifying port 0 in the dnsmasq section of dhcp.

So if the /etc/config/dhcp is not present or if all dnsmasq sections of dhcp has port==0, I'm showing internal config for domain-based routing. Otherwise -- dnsmasq config.

Feedback?

**Comment by danrl** [comment]
FYI: `odhcpd` also uses `/etc/config/dhcp`

**Comment by stangri** [comment]
It's been a long day, so please review the logic of the code below. From what I see it would still work correctly of odhcpd is present:
```lua
if nixio.fs.access("/etc/config/dhcp") then
   uci.cursor():foreach("dhcp", "dnsmasq", function(s)
     if s.port ~= "0" then
       dnsserver = "dnsmasq"
     end
   end)
end

if dnsserver == "dnsmasq" then
  d = Map("dhcp")
  s4 = d:section(TypedSection, "dnsmasq", translate("Domain-based Policies"))
  s4.anonymous = true
  di = s4:option(DynamicList, "ipset", translate("Domain Policies"), translate("Domains routed via specific gateways, see ")
    .. [[<a href="]] .. readmeURL .. [[#domain-based-policies" target="_blank">]]
    .. translate("README") .. [[</a>]] .. translate(" for details"))
else
  d = Map("openvpn-policy-routing")
  s3 = d:section(TypedSection, "domain-policy", translate("Domains"))
  s3.anonymous = true
  s3.addremove = true
  dp = s3:option(DynamicList, "ipset", translate("Domain Policies"), translate("Domains routed via specific gateways, see ")
    .. [[<a href="]] .. readmeURL .. [[#domain-based-policies" target="_blank">]]
    .. translate("README") .. [[</a>]] .. translate(" for details"))
end
```

**Comment by EricLuehrsen** [comment]
This is not robust:
```
if nixio.fs.access("/etc/config/dhcp") then
   uci.cursor():foreach("dhcp", "dnsmasq", function(s)
     if s.port ~= "0" then
       dnsserver = "dnsmasq"
```
If you build your own images without dnsmasq and use Unbound or Bind instead, then the default dhcp configurations may be left behind for `config dnsmasq`. Yo

**Comment by EricLuehrsen** [comment]
This is not completely robust:
```
if nixio.fs.access("/etc/config/dhcp") then
   uci.cursor():foreach("dhcp", "dnsmasq", function(s)
     if s.port ~= "0" then
       dnsserver = "dnsmasq"
```
If you build your own images without dnsmasq and use Unbound or Bind instead, then the default DHCP configurations may be left behind for `config dnsmasq`. You need to check if the binary is present and the /etc/init.d/dnsmasq script is enabled using the /rc.d standard checks.

**Comment by EricLuehrsen** [comment]
> [S]: do you know if unboud on LEDE supports ipsets configuration via uci? 
> [S]: Is the syntax same as dnsmasq /domain/domain/ipset?
> [D]: Not that I am aware of. unbound uses forward directives for that.

Unbound is a recursive server intended to run in your edge appliance to resolve the world. Unbound is also intended to be compiled on any OS with as little dependency as practical. It doesn't have ipset support. It does use `local-zone: example.com transparent` in the `server:` clause with matching `forward:` clauses to act like a stub resolver. It needs the domain and arpa(s) separately and explicitly. This explicit arpa definition gets really tricky and tedious for IP6. Like RFC1918 IP4 addresses, the IP6 ULA is whatever your domain chooses. But the IP6 GA is changed at the whim of your ISP. Even if a large internal company like a fictitious "Multi National United" will not obtain their own IP6::/32. This would create concerns about writing UCI to read ipset and write the `forward:`. Not that the code is tricky, but making sure that it gets triggered when it should is. We don't want DNS queries enumerating the inside of the VPN by random and occasional leaks to the world.

Split horizon VPN is a security risk in general and requires detail oriented care. It is not clear if LuCI to help an amateur through it is a good idea. Obviously our fictitious company "MNU" would have split horizons on split horizons. They isolate research from general office. They isolate each government compliance office with respect to each government interfaced. Everyone needs to get to the same HR website to fill out medical forms. But they also have professional IT operating the system 24/7.

**Comment by EricLuehrsen** [comment]
> [S]: do you know if unboud on LEDE supports ipsets configuration via uci? 
> [S]: Is the syntax same as dnsmasq /domain/domain/ipset?
> [D]: Not that I am aware of. unbound uses forward directives for that.

Unbound is intended to be a recursive edge resolver and compiled for any OS. It doesn't have ipset support. It does use `local-zone: example.com transparent` in the `server:` clause with matching `forward:` clauses to act like a stub resolver. It needs the domain and arpa(s) separately and explicitly. This explicit arpa definition gets really tricky and tedious for IP6. IP6 addresses change at the whim of the ISP even for large international companies. This would create concerns about writing UCI to read ipset and write the `forward:`. Not that the code is tricky, but making sure that it gets triggered when it should is. We don't want DNS queries enumerating the inside of the VPN by random and occasional leaks to the world. Split horizon VPN should be handled with care, and it is not clear if elaborate support in LuCI is the best choice.

**Comment by stangri** [comment]
@EricLuehrsen -- great point, thank you. Would checking for dnsmasq's PID file like below replace the need to check for the binary and if the dnsmasq init script is enabled?
```lua
if nixio.fs.access("/var/run/dnsmasq/") and nixio.fs.access("/etc/config/dhcp") then
  for f in nixio.fs.dir("/var/run/dnsmasq/") do
    if string.match(f, "dnsmasq.cfg.*.pid") then
      uci.cursor():foreach("dhcp", "dnsmasq", function(s)
        if s.port ~= "0" then
          dnsserver = "dnsmasq"
        end
      end)
    end
  end
end
```

I also appreciate your feedback regarding unbound. If unbound doesn't support ipsets, there's nothing else for me to do in luci app once I fix the last remaining IPv6 issue.

**Pull request closed without merging**
