### PR TITLE
luci-app-ttyd-fix ttyd config innerHTML error

### PR DESCRIPTION
**Pull request by lingfeng0303**
luci-app-ttyd Under OpenWrt theme, luci-app-ttyd page cannot be displayed
image

### CODE REVIEW

**Comment by Ramon00** [comment]
Is this related to XML vs HTML? If so this was fixed already on master by converting that theme to HTML.

**Comment by systemcrash** [comment]
Not sure whether it was backported to that version, or if it's even possible.

**Comment by Ramon00** [comment]
doesnt appear that XML to HTML change was backported [23.05](https://github.com/openwrt/luci/tree/openwrt-23.05/themes/luci-theme-openwrt/ucode/template/themes/openwrt.org)  [master](https://github.com/openwrt/luci/tree/master/themes/luci-theme-openwrt/ucode/template/themes/openwrt.org)

I guess it should be possible...

**Comment by lingfeng0303** [comment]
Yes, 23.05 also has problems

**Comment by Ramon00** [comment]
if you take latest master is the issue still there?

**Comment by Ramon00** [comment]
So I guess the original "bug" (theme incompatibility) has been fixed, hence this additional error checking in this PR is not really needed, but cant hurt either. I guess one of the maintainers needs to decide if it makes sense to merge this.

**Comment by lingfeng0303** [comment]
Yeah, sure.

**Comment by systemcrash** [comment]
Works in at least master. The current commit does not pass formalities anyway. Closing.

**Pull request closed without merging**
