### PR TITLE
luci-proto-sstp: Add sstp protocol support for Luci

### PR DESCRIPTION
**Pull request by rkkoszewski**
This is a follow up PR of: https://github.com/openwrt/luci/pull/2768

This PR includes a single Commit based on the previous PR (https://github.com/openwrt/luci/pull/2768).

The content is based on the work of @harveyhu2012 (https://github.com/harveyhu2012/luci/commit/3854b5ac2647a90839f075b8c8af4a4ea33bdf89) and my own changes to adapt the scrips to the new changes in luci and other fix suggestions from previous PRs.

Signed-off-by: Robert Koszewski <rkkoszewski@gmail.com>

### CODE REVIEW

**Comment by rkkoszewski** [comment]
@feckert Here is the follow up PR from the previous PR https://github.com/openwrt/luci/pull/2768
I just copied over all changes from the previous PR into a single commit, and with that the commit (https://github.com/harveyhu2012/luci/commit/3854b5ac2647a90839f075b8c8af4a4ea33bdf89) from @harveyhu2012 is not showing up anymore. But the name of the author appears in the sources that were initially created by that author, which I hope is good enough credits.

**Comment by feckert** [comment]
As I can see in the current master your suggested feature will not work because the protocols are ported to javascript.

Have a look at

https://github.com/openwrt/luci/tree/master/modules/luci-mod-network/htdocs/luci-static/resources/view/network

and
 
https://github.com/openwrt/luci/tree/master/protocols

**Comment by feckert** [comment]
No reaction from pullrequest creator.
Feel free to reopen if you think we should merge this after changing.

**Comment by rkkoszewski** [comment]
Hi @feckert
I will come back to this PR, I am quite busy lately and porting this requires quite a bit of time to familiarise myself with the new JavaScript way and to setup a device to test the changes.

**Pull request closed without merging**
