### PR TITLE
luci-base: switch to ubus uci operations

### PR DESCRIPTION
**Pull request by jow-**
This is a rather invasive commit which turns the central `luci.model.uci` UCI binding class into a proxy translating former libuci api calls into equivalent ubus uci operations.

This change paves the way for a number of changes I like to add in the near future:
 - Switch to per-session uci changes, means uci changes are tied to the current login session and automatically vanish when the session expires or the user logs out
 - Deprecate `ucitrack` & `luci-reload` in favor to config change events
 - And, most importantly, implement the try-apply-rollback workflow which is already supported in rpcd since a long time

I ran some preliminary tests so far (mainly clicking around in LuCI, adding and removing CBI sections, applying changes etc.) and didn't notice any problems yet but I'd like to see some wider testing (especially on less capable devices) before I merge that into master.

Once this commit lands, the next steps will be:
 - start working on getting rid of `ucitrack`
 - remove `libuci-lua` dependencies from LuCI core, that would save approx. ~6KB after gzip on an ar71xx device
 - simplify `luci.model.uci.changes()`; its sole known user is the pending changes uci diff views in `luci-mod-admin-full`, so I'd like to adjust the view there to work with the orginal `ubus call uci changes` format rather than converting back and forth to the old libuci `uci.changes()` format

### CODE REVIEW

**Comment by hnyman** [comment]
I compiled a patched luci-base yesterday and did not notice anything strange in my brief testing.

**Comment by dibdot** [comment]
@jow- please wait with the merge. I've quickly tested adblock & travelmate ... and both are broken. 
The culprit is this in my overview_tab.lua:
`local adbinput = uci.get("adblock", "global", "adb_rtfile") or "/tmp/adb_runtime.json"`

I will fix it on the next weekend - thanks.

**Comment by dibdot** [comment]
BTW, 'wifitoggle' loops / dies silently - but I've not looked into this.

**Comment by jow-** [comment]
@dibdot - sure thing, will wait. Thats exactly the reason for this PR :) I totally missed that the old api was callable without implicit self (colon vs. dot notation). Allthough it was never documented I maybe should keep supporting this usage...

**Comment by jow-** [comment]
I pushed a change that should restore compatibility with unmodified uci api users.

**Comment by hnyman** [comment]
Looks like @dibdot found all occurrences of "uci.get", as adblock, travelmate and wifischedule are the only apps (in this repo) that use that notation.

**Comment by jow-** [comment]
Great. I'll probably leave out the compat commit then as it considerably complicates the code...

**Comment by dibdot** [comment]
Switched all relevant packages to the "new" API calls. Thanks for your patience.

**Pull request closed without merging**
