### PR TITLE
luci-app-https-dns-proxy: Add new and update adguard dns server

### PR DESCRIPTION
**Pull request by ProKn1fe**
Add adguard unsecured dns provider and update ip addresses on existent based on https://adguard-dns.io/en/public-dns.html info. Also add ipv6 bootstrap_dns ip addresses.

### CODE REVIEW

**Comment by stangri** [comment]
Thank you for your contribution. 

Please delete old "com.adguard.*" files in the PR and create new ones with the io.adguard-dns.* scheme instead.

Please use their "Non-filtering servers" as bootstrap servers for all 3 files.

**Comment by ProKn1fe** [comment]
Done.

**Comment by stangri** [comment]
Please amend commits:
```
: === Checking commit '41890c82a04e4895c5dd2bfdd39c7c9bc56cfd7e'
: Author name (Zuev Aleksandr) seems ok
: Commit subject line MUST start with '<package name>: ' (Change files names and replace bootstrap_dns)
: Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Zuev Aleksandr <A.Zuev@stdev.su>')
: === Checking commit '4e820a8a217164e17d0ead3e3d578ba4a717c179'
: Author name (Zuev Aleksandr) seems ok
: Commit subject line MUST start with '<package name>: ' (Add new and update adguard dns server)
: Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: Zuev Aleksandr <A.Zuev@stdev.su>')
Error: Process completed with exit code 1.
```

**Comment by ProKn1fe** [comment]
Now it should be normal. Oh my god how old was my luci repository.

**Comment by stangri** [comment]
> Now it should be normal. Oh my god how old was my luci repository.

Please amend signed-off-by to both commits.

**Comment by ProKn1fe** [comment]
@stangri anything else should i do?

**Comment by stangri** [comment]
> @stangri anything else should i do?

I didn't get notified of your commits, re-running the CI jobs now.

**Comment by stangri** [comment]
@jow- @aparcar @neheb (and anyone else with expertise in CI tasks), the builds are failing because:
```
checking whether the C compiler works... no
configure: error: in `/home/build/openwrt/build_dir/target-x86_64_musl/elfutils-0.188':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[2]: *** [Makefile:118: /home/build/openwrt/build_dir/target-x86_64_musl/elfutils-0.188/.configured_a17fb5ef857664f03cd0ce37cc5ea591] Error 77
make[2]: Leaving directory '/home/build/openwrt/feeds/base/package/libs/elfutils'
time: package/feeds/base/elfutils/compile#4.50#0.47#5.86
    ERROR: package/feeds/base/elfutils failed to build.
make[1]: *** [package/Makefile:116: package/feeds/base/elfutils/compile] Error 1
make[1]: Leaving directory '/home/build/openwrt'
make: *** [/home/build/openwrt/include/toplevel.mk:224: package/luci-app-pbr/compile] Error 2
Error: Process completed with exit code 2.
```

Please advise:
1. If it's still OK to merge as is.
2. Or if CI can be fixed promptly, should I rather wait until it is to merge with the green checkmark.

**Comment by stangri** [comment]
Thank you @ProKn1fe !

**Pull request merged**
