### PR TITLE
This addresses the issue of openconnect.sh from openconnect package expecting a vpn- suffix, while the frontend didn't.

### PR DESCRIPTION
**Pull request by DasTestament**

### CODE REVIEW

**Comment by nmav** [comment]
I think a better description is needed especially since this spans various projects. Something like:

This addresses the issue of openconnect.sh from openconnect package expecting a `-vpn` suffix, while the frontend didn't.

Addresses:
https://github.com/openwrt/packages/issues/11584

**Comment by nmav** [comment]
Other than the description LGTM

**Comment by DasTestament** [comment]
Well, I thought to make changes in openconnect.sh, but came to conclusion that fixing frontend will be much proper place rather than messing with a script. I've redacted the title.

**Comment by nmav** [comment]
@jow- any concern in merging?

**Comment by jow-** [comment]
Merged via adf0fb187 - thanks!

**Pull request closed without merging**
