### PR TITLE
Support for collectd-mod-contextswitch

### PR DESCRIPTION
**Pull request by fantom-x**
Adding support for a useful plug-in and would also like it to be backported to 17.01 branch.

### CODE REVIEW

**Comment by hnyman** [comment]
I haven't tested that, yet, but you need to have "signed-off-by" **in the commit message**, not PR discussion. (Commit message gets stored in git history, PR discussion does not).

And please squash the two commits into one.

**Comment by fantom-x** [comment]
Done, but now I have a merge commit as well...

**Comment by hnyman** [comment]
Read the advice in CONTRIBUTING.md that I already linked in forum thread.
https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md#advice-on-pull-requests

You can easily "squash" (= combine into one) those four commits into one (and remove the "collects" typo from the title).

> *    Checkout the feature branch by `git checkout luci-collectd-mod-contextswitch`
> *    If you added several new commits or made other changes that require cleaning up, you can use `git rebase -i HEAD~4` (4 = number of commits to edit) to possibly squash some commits.
> *    Push the changed commits to Github with `git push -f` to overwrite the original commits in the feature branch with the new ones. The pull request gets automatically updated

Some git exercise for you ;-)

**Comment by fantom-x** [comment]
I will eventually figure it out...

**Comment by hnyman** [comment]
It is pretty easy, once you have done it once (and have the commits in a branch instead of master). 
Github makes it rather convenient to makes polished changes to PRs.

I will test it.

**Comment by fantom-x** [comment]
Do I need to submit another request to get it into 17.01?

**Comment by hnyman** [comment]
No need. I can cherry-pick it in a few days, after first seeing that it has caused no hiccup in the buildbot.

(If I don't remember to do that. just remind me.)

**Comment by hnyman** [comment]
Just noticed that you had used spaces in the config file instead of a tab :-(
I will fix that myself.

**Comment by fantom-x** [comment]
If you have not done that yet, I do not mind cleaning than up.

**Comment by hnyman** [comment]
Already done. I also moved the item to alphabetically correct place. Nitpicking ;-)

https://github.com/openwrt/luci/commit/2bc2f935a0428b8d31a6ff2b967157b5ca02e06b

**Comment by fantom-x** [comment]
Ok, I will keep those things in mind next time.

**Comment by hnyman** [comment]
One other hint for you:
if you change translation items, please run in luci repo root this command before you commit: 
./build/i18n-sync.sh

It straightens up the translation files, sorts them properly, cuts too long lines etc.

Your samba, hd-idle, statistics and wifi changes were fixed / changes propagated by musashino with
https://github.com/openwrt/luci/commit/86a708b06b1284045c0216e35a2bf3f40411177e

**Comment by fantom-x** [comment]
I see that I also need to add the new strings to the translation files. Acknowledged.

**Comment by hnyman** [comment]
> I see that I also need to add the new strings to the translation files. Acknowledged.

./build/i18n-sync.sh  adds the new strings. Basically it searches for new/changed strings in the main lua code and updates .pot master accordingly, and then adjusts all .po files as necessary.

(Note that it may mishandle cases where you change an already translated string a major way. Translations may get lost (marked invalid, and new empty ones created on their place.  some manual editing may be needed. so look at "git diff" after running it... )

**Comment by fantom-x** [comment]
Got it, thx.

**Pull request merged**
