### PR TITLE
luci-app-advanced-reboot: add support for Linksys EA6350v3, fix kerne…

### PR DESCRIPTION
**Pull request by stangri**
…l version length issue

Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by hnyman** [comment]
Could you please slightly amend the commit:
* README.md: remove the reversal of the OpenWrt/LEDE forum address change etc. (i.e. do not undo the changes done in the OpenWrt repo by d99831e9d0
* advanced-reboot.pot: do not remove the location tags, as they will be added again in the next language sync (by ./build/i18n-sync.pl ). The .pot file has no actual changes, so there is actually no need to touch the file at all.

**Comment by stangri** [comment]
Hannu, is the updated i18n-sync.pl available somewhere on github?

**Comment by hnyman** [comment]
> is the updated i18n-sync.pl available somewhere on github?

Well, it is actually build/i18n-scan.pl that contains the modified logic (although it is usually run via i18n-sync):
https://github.com/openwrt/luci/blob/master/build/i18n-scan.pl

**Comment by stangri** [comment]
Thank you, got the new perl script, it's much easier for me to submit another PR than fix this one, I hope it's OK.

**Pull request closed without merging**
