### PR TITLE
luci-app-statistics: add snmp6 collector

### PR DESCRIPTION
**Pull request by PolynomialDivision**
Add IPv6 statistics.

Depends on:
https://github.com/openwrt/packages/pull/14205

### CODE REVIEW

**Comment by hnyman** [comment]
You are missing also for this plugin all the visible LuCI chart stuff, similarly as was for the dhcpleases plugin. 
I did merge your collectd part, but please create the proper charts also for this, so that there is a reason to include this in LuCI.
You can likely model it along the example set in f8552af for your #4654

**Comment by PolynomialDivision** [comment]
@hnyman Does the netlink plugin work for you? If I select more than 1 interface, it does not work in the luci_statistics.

**Comment by PolynomialDivision** [comment]
Seems to work, except that I get a warning
```
rrdtool plugin: rrd_update_r failed: /tmp/rrd/OpenWrt/snmp6-br-lan/if_octets.rrd: illegal attempt to update using time 1610203836 when last update time is 1610203836 (minimum one second step)
Sat Jan  9 14:50:36 2021 daemon.err collectd[8209]: rrdtool plugin: rrd_update_r failed: /tmp/rrd/OpenWrt/snmp6-br-lan/if_octets_mcast.rrd: illegal attempt to update using time 1610203836 when last update time is 1610203836 (minimum one second step)
Sat Jan  9 14:50:36 2021 daemon.err collectd[8209]: rrdtool plugin: rrd_update_r failed: /tmp/rrd/OpenWrt/snmp6-br-lan/if_octets_bcast.rrd: illegal attempt to update using time 1610203836 when last update time is 1610203836 (minimum one second step)
````

**Comment by hnyman** [comment]
That warning may come once at the collectd start (due to the absence of real-time clock and the adjustment of the time).

**Comment by hnyman** [comment]
Looks good enough (based on code).
I think that the number formats should be set, but that can be done afterward.

**Comment by hnyman** [comment]
Sadly it looks like that your own observations about "illegal attempt to update using time" is right. The plugin seems to cause those errors to the log.

```
 Sun Jan 10 11:12:31 2021 daemon.err collectd[13593]: rrdtool plugin: rrd_update_r failed: /tmp/rrd/router1/snmp6-eth0.2/if_octets_mcast.rrd: illegal attempt to update using time 1610269952 when last update time is 1610269952 (minimum one second step)
Sun Jan 10 11:12:31 2021 daemon.err collectd[13593]: rrdtool plugin: rrd_update_r failed: /tmp/rrd/router1/snmp6-eth0.2/if_octets_bcast.rrd: illegal attempt to update using time 1610269952 when last update time is 1610269952 (minimum one second step)
Sun Jan 10 11:12:31 2021 daemon.err collectd[13593]: rrdtool plugin: rrd_update_r failed: /tmp/rrd/router1/snmp6-eth0.2/if_octets.rrd: illegal attempt to update using time 1610269952 when last update time is 1610269952 (minimum one second step)
Sun Jan 10 11:12:31 2021 daemon.err collectd[13593]: rrdtool plugin: rrd_update_r failed: /tmp/rrd/router1/snmp6-eth0.2/if_octets.rrd: illegal attempt to update using time 1610269952 when last update time is 1610269952 (minimum one second step)
Sun Jan 10 11:12:31 2021 daemon.err collectd[13593]: rrdtool plugin: rrd_update_r failed: /tmp/rrd/router1/snmp6-eth0.2/if_octets_mcast.rrd: illegal attempt to update using time 1610269952 when last update time is 1610269952 (minimum one second step)
Sun Jan 10 11:12:31 2021 daemon.err collectd[13593]: rrdtool plugin: rrd_update_r failed: /tmp/rrd/router1/snmp6-eth0.2/if_octets_bcast.rrd: illegal attempt to update using time 1610269952 when last update time is 1610269952 (minimum one second step)
```

How did you originally overcome that? When did it start producing those (at which modification)? 
As I assume that your PR did not initially do that...

**Comment by PolynomialDivision** [comment]
> How did you originally overcome that? When did it start producing those (at which modification)?

I'm not sure. This plugin was on hold a long time since the snmp6 interface was not enabled in OpenWrt default.
I always tested with collectd and it looked okay. The graphs also look okay.

Actually, this is not so much code. ^^ I would guess that I can not call `snmp6_submit` to often, or that iterating through the list somehow scrapes the same interface twice.

Sry, for the circumstances. I will have a look.

**Comment by PolynomialDivision** [comment]
@hnyman I found the issue. I was missing `freeifaddrs(if_list);` So I copied not enough. xD

**Pull request merged**
