### PR TITLE
OpenVPN server options were hidden due to a dependency on an undefined va…

### PR DESCRIPTION
**Pull request by innovate-invent**
…riable "server_mode". This commit removes that dependency.

### CODE REVIEW

**Comment by hnyman** [comment]
I am not quite sure what has been the purpose of that server_mode dependency, as it as been there since the original commit by @jow- in 2008.
https://github.com/openwrt/luci/commit/7fe7d6d5e654d2092f89d81b0e1627fb99eb1a74

In any case, that openvpn Luci plugin should have a larger cleanup regarding its whitespace. It has not taken well the transitions, latest to github.

**Comment by hnyman** [comment]
This PR needs update as the file was beautified by another PR. (you seem to have edited your local master branch, so updating this might be a bit tricky.)

But do you @jow- have any recollection why the server options were originally hidden? Was the intention to divide the options into server/client and provide tabs or some toggle for configuration?

**Comment by jow-** [comment]
Yes, the intention was to shrink the form

**Comment by innovate-invent** [comment]
Did someone run an auto reformatter on this code? it took ~200 lines of code and scrambled it into ~800 lines of code. This has made it infinitely more difficult to read and parse through looking for a specific value. I recommend a roll back.

**Comment by hnyman** [comment]
Well, it is about personal opinion, I guess.
The previous code was really hard to read, as it contained lots of extra tabs on each line between items, and lines were very long, rolling quite far into right. And some items, e.g. that variable that you want eliminate, was practically hidden. Having source code that is readable in a normal way e.g. in Github, makes things easier.

**Comment by feckert** [comment]
@innovate-invent If you make changes on the file it was very hard to see at once what was changed. I thought split the table into lines will improve readability.

**Comment by feckert** [comment]
I think we can close this PR. It should be updated anyway

**Comment by hnyman** [comment]
I will close this, as it would require reformatting due to conflicts.
But you @feckert might look into the core issue. If the server options are currently hidden, they might be displayed properly at some point.

**Pull request closed without merging**
