### PR TITLE
Fix ATM HEC label on stats.js

### PR DESCRIPTION
**Pull request by innovara**
HEC stands for Header Error Control in the context of ATM, AFAIK

### CODE REVIEW

**Comment by systemcrash** [comment]
@innovara Can the corresponding i18n strings also be updated to keep the i18n strings synched?

**Comment by innovara** [comment]
@systemcrash Sure. See additional commit

**Comment by feckert** [comment]
- Please add the `luci-mod-dsl:` prefix to your commit messages.
- Also add the full name to the `Signed-off-by`

**Comment by systemcrash** [comment]
Can you sync the i18n fiels please? Then LGTM.

**Comment by innovara** [comment]
@systemcrash please see last commit. Is that what you wanted me to do?

**Comment by systemcrash** [comment]
Almost. Can you just rebase?

**Comment by innovara** [comment]
@systemcrash I think I finally got there. I'm not very well versed in the ins and outs of git tbh

**Comment by innovara** [comment]
Email mismatch. Fixed now

**Comment by systemcrash** [comment]
Thank you 😄

**Pull request merged**
