### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/openwrt/luci/) for OpenWrt/LuCI/modules/luci-base.

### CODE REVIEW

**Comment by hnyman** [comment]
@jow-  @aparcar 
Weblate again wants to initialize the wrong country codes for Chinese. Vnstat2 is a new app, and weblate has automatically generated all language files, and there are again these zh_Hant ones.

What is the preferred approach? Merge this and immediately fix the languages afterward with new commits?

**Comment by aparcar** [comment]
I hoped to fix it by setting this option, however it seems to fail. Maybe we should report that upstream?
image

**Comment by hnyman** [comment]
There are also the Norwegian and Portuguese codes that need to be checked.

Upstream should allow us to define the exact list of languages used in our context. Now it looks like it has a global list somewhere and new apps get languages from that list.

**Comment by hnyman** [comment]
@jow-  @aparcar 

I think that I will merge this and fix it manually, but we should think about future.

As we now seem to encourage weblate usage (and it seems to work nicely), would it be easier to switch to using weblate-compatible language codes in LuCI to enable automatic handling in future?

These would be the changes:
* zh-cn --> zh_Hans
* zh-tw --> zh_Hant
* no --> nb_NO
* pt-br --> pt_BR 

Those are the ones where we now have a difference compared with weblate defaults.

Ps. Right now we actually have discrepancies in the repo: new apps like advanced-reboot, nextdns, yggdrasil have "nb_NO" instead of "no" and "pt_BR" instead of "pt-br". Those were missed in the resync that jow did two weeks ago.

**Comment by hnyman** [comment]
@aparcar @jow- 

Situation is actually much worse than I thought.

Regarding Norwegian and Brazilian PÅortuguese, we already have an evenly split LuCI repo:

Half of app translations are with old locale codes "no" and "pt-br", while half are weblate originating new translation files:

```
perus@ub1910:/Openwrt/github/luci/applications$ ls -d1 */po/no*
luci-app-ahcp/po/no
luci-app-commands/po/no
luci-app-coovachilli/po/no
luci-app-ddns/po/no
luci-app-diag-core/po/no
luci-app-firewall/po/no
luci-app-hd-idle/po/no
luci-app-minidlna/po/no
luci-app-ntpc/po/no
luci-app-olsr/po/no
luci-app-openvpn/po/no
luci-app-opkg/po/no
luci-app-p910nd/po/no
luci-app-polipo/po/no
luci-app-qos/po/no
luci-app-samba4/po/no
luci-app-samba/po/no
luci-app-splash/po/no
luci-app-statistics/po/no
luci-app-tinyproxy/po/no
luci-app-transmission/po/no
luci-app-upnp/po/no
luci-app-vnstat/po/no
luci-app-watchcat/po/no
luci-app-wol/po/no

perus@ub1910:/Openwrt/github/luci/applications$ ls -d1 */po/nb*
luci-app-adblock/po/nb_NO
luci-app-advanced-reboot/po/nb_NO
luci-app-aria2/po/nb_NO
luci-app-attendedsysupgrade/po/nb_NO
luci-app-banip/po/nb_NO
luci-app-bcp38/po/nb_NO
luci-app-bmx7/po/nb_NO
luci-app-clamav/po/nb_NO
luci-app-cshark/po/nb_NO
luci-app-dcwapd/po/nb_NO
luci-app-dnscrypt-proxy/po/nb_NO
luci-app-dump1090/po/nb_NO
luci-app-dynapoint/po/nb_NO
luci-app-fwknopd/po/nb_NO
luci-app-https-dns-proxy/po/nb_NO
luci-app-ltqtapi/po/nb_NO
luci-app-lxc/po/nb_NO
luci-app-mjpg-streamer/po/nb_NO
luci-app-mwan3/po/nb_NO
luci-app-nextdns/po/nb_NO
luci-app-nft-qos/po/nb_NO
luci-app-nlbwmon/po/nb_NO
luci-app-noddos/po/nb_NO
luci-app-nut/po/nb_NO
luci-app-ocserv/po/nb_NO
luci-app-olsr-services/po/nb_NO
luci-app-olsr-viz/po/nb_NO
luci-app-omcproxy/po/nb_NO
luci-app-pagekitec/po/nb_NO
luci-app-privoxy/po/nb_NO
luci-app-radicale2/po/nb_NO
luci-app-radicale/po/nb_NO
luci-app-rp-pppoe-server/po/nb_NO
luci-app-shadowsocks-libev/po/nb_NO
luci-app-shairplay/po/nb_NO
luci-app-simple-adblock/po/nb_NO
luci-app-smbd/po/nb_NO
luci-app-squid/po/nb_NO
luci-app-travelmate/po/nb_NO
luci-app-ttyd/po/nb_NO
luci-app-udpxy/po/nb_NO
luci-app-uhttpd/po/nb_NO
luci-app-unbound/po/nb_NO
luci-app-vpnbypass/po/nb_NO
luci-app-vpn-policy-routing/po/nb_NO
luci-app-wifischedule/po/nb_NO
luci-app-wireguard/po/nb_NO
luci-app-yggdrasil/po/nb_NO


perus@ub1910:/Openwrt/github/luci/applications$ ls -d1 */po/pt-*
luci-app-adblock/po/pt-br
luci-app-ahcp/po/pt-br
luci-app-aria2/po/pt-br
luci-app-commands/po/pt-br
luci-app-coovachilli/po/pt-br
luci-app-ddns/po/pt-br
luci-app-diag-core/po/pt-br
luci-app-dynapoint/po/pt-br
luci-app-firewall/po/pt-br
luci-app-fwknopd/po/pt-br
luci-app-hd-idle/po/pt-br
luci-app-minidlna/po/pt-br
luci-app-mjpg-streamer/po/pt-br
luci-app-ntpc/po/pt-br
luci-app-olsr/po/pt-br
luci-app-openvpn/po/pt-br
luci-app-opkg/po/pt-br
luci-app-p910nd/po/pt-br
luci-app-polipo/po/pt-br
luci-app-privoxy/po/pt-br
luci-app-qos/po/pt-br
luci-app-radicale/po/pt-br
luci-app-samba4/po/pt-br
luci-app-samba/po/pt-br
luci-app-shairplay/po/pt-br
luci-app-simple-adblock/po/pt-br
luci-app-splash/po/pt-br
luci-app-statistics/po/pt-br
luci-app-tinyproxy/po/pt-br
luci-app-transmission/po/pt-br
luci-app-travelmate/po/pt-br
luci-app-uhttpd/po/pt-br
luci-app-upnp/po/pt-br
luci-app-vnstat/po/pt-br
luci-app-vpnbypass/po/pt-br
luci-app-watchcat/po/pt-br
luci-app-wifischedule/po/pt-br
luci-app-wireguard/po/pt-br
luci-app-wol/po/pt-br

perus@ub1910:/Openwrt/github/luci/applications$ ls -d1 */po/pt_*
luci-app-advanced-reboot/po/pt_BR
luci-app-attendedsysupgrade/po/pt_BR
luci-app-banip/po/pt_BR
luci-app-bcp38/po/pt_BR
luci-app-bmx7/po/pt_BR
luci-app-clamav/po/pt_BR
luci-app-cshark/po/pt_BR
luci-app-dcwapd/po/pt_BR
luci-app-dnscrypt-proxy/po/pt_BR
luci-app-dump1090/po/pt_BR
luci-app-https-dns-proxy/po/pt_BR
luci-app-ltqtapi/po/pt_BR
luci-app-lxc/po/pt_BR
luci-app-mwan3/po/pt_BR
luci-app-nextdns/po/pt_BR
luci-app-nft-qos/po/pt_BR
luci-app-nlbwmon/po/pt_BR
luci-app-noddos/po/pt_BR
luci-app-nut/po/pt_BR
luci-app-ocserv/po/pt_BR
luci-app-olsr-services/po/pt_BR
luci-app-olsr-viz/po/pt_BR
luci-app-omcproxy/po/pt_BR
luci-app-pagekitec/po/pt_BR
luci-app-radicale2/po/pt_BR
luci-app-rp-pppoe-server/po/pt_BR
luci-app-shadowsocks-libev/po/pt_BR
luci-app-smbd/po/pt_BR
luci-app-squid/po/pt_BR
luci-app-ttyd/po/pt_BR
luci-app-udpxy/po/pt_BR
luci-app-unbound/po/pt_BR
luci-app-vpn-policy-routing/po/pt_BR
luci-app-yggdrasil/po/pt_BR
```

**Comment by jow-** [comment]
Well LuCI maps browser language codes to language files and no browser I've seen in the wild actually sends `zh-Hant` in its HTTP `Accept-Language` header - so we'd need to maintain a mapping somewhere.

**Comment by hnyman** [comment]
If we want to stick to the current locale codes, then we should likely repair Norwegian and Portuguese.

And Just remember to fix weblate-generated codes for new apps in future.

**Pull request merged**
