### PR TITLE
[24.10] luci-app-advanced-reboot: Linksys MX5300 support

### PR DESCRIPTION
**Pull request by stangri**
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc2
Run tested: Linksys MX5300, OpenWrt 24.10.0-rc2

### CODE REVIEW

**Comment by systemcrash** [comment]
@stangri dont cherry pick to 24 yet. We're still just rebasing 24 on master.  If this is in master it'll show up in 24 immediately.

**Comment by stangri** [comment]
> @stangri dont cherry pick to 24 yet. We're still just rebasing 24 on master. If this is in master it'll show up in 24 immediately.

I didn't know, thanks. This is just for the luci repo, right, packages I have to do PR for 24.10, correct?

**Comment by systemcrash** [comment]
As far as I know it's unique to luci. Maybe one or two other repos. 

Is this in master already?

**Comment by stangri** [comment]
> Is this in master already?

Yes, I merged the master PR yesterday.

**Comment by systemcrash** [comment]
OK. Then this is in 24.10 also via 7baceb068d020df307eb2edb1e1b187b711ee02b :) 

Closing.

**Pull request closed without merging**
