### PR TITLE
initial commit of localization to cs(_CZ) locale

### PR DESCRIPTION
**Pull request by fra-iesus**
some hints remain unlocalized, but it's good enough to cover all the common needs.
I'll try to find a bit more time to translate it completely later.

### CODE REVIEW

**Comment by fra-iesus** [comment]
sorry, but I see no reason to create a local repo just for signing that commit just because github web UI doesn't allow that.

**Comment by feckert** [comment]
Please see https://github.com/openwrt/luci/commitb7ae1694f207f974fd8a55277bdc24d9771b01aa
You have to add the following lines to your commit


> luci-app-travelmate: update **language** translation
> 
> Update **language** translation.
> 
> Signed-off-by: **your fullname** <**your mail@mail.com**>


I think this could be done in the github webui as well.

**Comment by fra-iesus** [comment]
Thanks, but I'm afraid it's not possible to edit commit message through the web ui:
https://help.github.com/en/articles/changing-a-commit-message

**Comment by feckert** [comment]
> sorry, but I see no reason to create a local repo just for signing that commit just because github web UI doesn't allow that.

So its up to you to get this merged into LuCI master.
I think it's time to do the command line thing. :-)

**Comment by fra-iesus** [comment]
:-) I think, that I can live happily even without that translation being merged to master. Really I see no reason for this complication for anyone, who's trying to help. Commit verified by github itself is not enough? No problem, I don't want to waste my time and disk space for that.

**Comment by feckert** [comment]
Ok thanks for your time to update the translation.

But that are the guidelines see https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
