### PR TITLE
luci-mod-dsl: add pilot tones

### PR DESCRIPTION
**Pull request by janh**
This adds pilot tones to the bit allocation graph (the data is available via ubus since https://github.com/openwrt/openwrt/commit/b91d7d9d78ea12097de4c518c8cd2215ff286f7a).

### CODE REVIEW

**Comment by janh** [comment]
Here is what the updated graph looks like:
bit-allocation-pilot-tones

**Comment by jow-** [comment]
Did you test the behaviour after this change when the OpenWrt side `ltq-*-app` has not been updated yet? It's not uncommon for people to upgrade their LuCI packages

**Comment by janh** [comment]
Yes, it falls back gracefully if the data doesn't contain the pilot tones (`window.json` is the data returned from the ubus call):
https://github.com/openwrt/luci/blob/3ed20aac9d086be6cec6291d0e33f19ef2d58355/modules/luci-mod-dsl/htdocs/luci-static/resources/view/status/dsl/graph.js#L92

**Comment by dhewg** [comment]
LGTM, tested with luci updated but without ltq-app, which didn't break, and then a full sysupgrade, where the lines start to show up

**Comment by jow-** [comment]
Thanks for the clarification!

**Pull request merged**
