### PR TITLE
luci-app-pppoe-server: Add PPPoE server configuration

### PR DESCRIPTION
**Pull request by dfc-d**
Adds support for rp-pppoe-server configuration once pending
pull request for packages feed gets applied.

Signed-off-by: Daniel Dickinson <openwrt@daniel.thecshore.com>

### CODE REVIEW

**Comment by hnyman** [comment]
I think that this should be renamed to luci-app-rp-pppoe-server to be aligned with the underlying rp-pppoe-server

**Comment by dfc-d** [comment]
Ok.

**Comment by dfc-d** [comment]
Pending testing fixes to rp-pppoe package.

**Comment by dfc-d** [comment]
Ok, appears to be working for me in my current build.

**Comment by dfc-d** [comment]
Oopps sorry, I thought this was the packages feeds PR; this one needs an update pushed yet.

**Comment by dfc-d** [comment]
Tested and working with new push

**Comment by dfc-d** [comment]
Fixed to use ifacelist instead of netlist (phsyical interface not uci network name is needed).

**Pull request merged**
