### PR TITLE
luci-theme-bootstrap: Remove jql.min.js which does not exist

### PR DESCRIPTION
**Pull request by kuoruan**
Fix 404 error

Signed-off-by: Hsing-Wang Liao <kuoruan@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
@jow- 
That line with the reference to the non-existing jql.min.js is from your commit: 
https://github.com/openwrt/luci/commit/b3c69b123a698e596a5df4797378d976718247f0#diff-7fa9a24152eff24c800bf0579b65553eR175

Any idea what was the intention?

**Comment by kuoruan** [comment]
Maybe this script reference to https://github.com/Cerdic/jQl, I am not sure.

**Comment by jow-** [comment]
Sorry for the delay - the introduction of this script reference was unintentional. I was playing with some lightweight jquery implementations locally and probably forgot to nuke the script tag when copying the .htm file off my router.

**Comment by jow-** [comment]
@kuoruan - merged, thanks a lot!

**Pull request merged**
