### PR TITLE
luci.mk: allow more customization (for external feeds/packages)

### PR DESCRIPTION
**Pull request by SvenRoederer**
~~Split the current luci.mk file into two files, "luci-common.mk" with definitions that might be relevant for other feeds too and "luci.mk" to be included by our packages.~~

EDIT: After the NACK of my 1st version in https://github.com/openwrt/luci/pull/2637#issuecomment-753945049 I did a complete rework, which only adds / changes some macros. 
This new Version will not split the current ```luci.mk``` but allows nearly all defaults to be overwritten externally. This allows including the ```luci.mk``` in external Makefiles and allowing strong customization.

After the move of the freifunk-packages to it's own feed (https://github.com/openwrt/luci/commit/55cd0c4c6b572f5b35244927a738c46b7dd711b8) such "luci-common.mk" will make the freifunk-packages build again without recreating the Makefile or copying the common code over to this feed.
The luci-apps of the openwrt-routing feed might also  benefit from the common definition of the LuCI-menu and the srcdiet feature.

~~I send this PR in 2 individual commits for easy reviewing but finally all can be squashed into one single commit.~~

Further down @feckert suggested to just link to luci.mk from 3rd-party repos to benefit from the features of luci.mk, which I also did before creating this PR. Linking had several drawbacks:
* inclusion of unneeded definitions e.g. `LuciTranslation`, `luci-base` (V1 removed this unneeded code for external repos; V2 keeps itas it'S just conditional code that is not causing problems)
* some hardcoded defaults, that can't be changed, e.g. `CATEGORY:=LuCI` can't be changed (This has been made customizable in patch v2)
* no way to define the URL or MAINTAINER variable of a Package, which is not required for LuCI, but might be for 3rd-party (This has been made customizable in patch v2)

### CODE REVIEW

**Comment by jow-** [comment]
hat is preventing other packages from using `luci.mk` directly?

**Comment by SvenRoederer** [comment]
One fact of suggesting this is making the Makefile more readable. When working on fixing the freifunk-packages, recently split off the luci-feed, it was really handy to get not distracted by these luci-only definitions like:
* ifeq ($(PKG_NAME),luci-base)
* define LuciTranslation
Having this separate luci-common.mk might help also others to reuse this definitions in other feeds.

**Comment by SvenRoederer** [comment]
@jow- using the unmodified luci.mk causes a lot of warnings:
> make[2]: Entering directory '/mnt/hosts/build/src/openwrt/packages_sven/freifunk/modules/luci-mod-freifunk'
../../freifunk.mk:48: warning: overriding recipe for target '/mnt/hosts/build/src/openwrt/freifunk/lede/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/pkginfo/luci-mod-freifunk.default.install.luci-mod-freifunk'

I guess this is caused by calling the "Buildpackage" macro by the feeds Makefile and a 2nd time by luci.mk

**Comment by feckert** [comment]
I have also luci packages in my own feed.
To use luci.mk from my own feed directly I added a symlink to the main luci.mk file in the luci feed
An `ls` in your own feed in the toplevel directory would show` luci.mk -> ../luci/luci.mk`.
With this I could call luci.mk in my makefiles.

**Comment by feckert** [comment]
@SvenRoederer Does my last message solve your issue with luci.mk?

**Comment by SvenRoederer** [comment]
@feckert  linking / including the original luci.mk was also done by me. But as this file defines many things that are not needed in other feeds (e.g. ```LuciTranslation```, package ```luci-base```) I liked the idea of splitting this file. This also improves the readability when using in other feeds, as of less uninteresting definitions and receipts.

**Comment by SvenRoederer** [comment]
@feckert by just linking / including the original luci.mk I found no way to make a package appear outside of the LuCI-menu of menuconfig (caused by hardcoded ```CATEGORY:=LuCI``` of Package/$(PKG_NAME) section).
For our freifunk-firmware, we like to keep most of our packages in a separate menu-section.

**Comment by feckert** [comment]
From my side, the explanation sounds conclusive. 
:+1: 
But the last word has @jow-

**Comment by SvenRoederer** [comment]
in our freifunk-firmware we use the following code to locate and include the luci-common.mk file

```
LUCIMKFILE:=$(wildcard $(TOPDIR)/feeds/*/luci-generic.mk)

# verify that there is only one single file returned
ifneq (1,$(words $(LUCIMKFILE)))
ifeq (0,$(words $(LUCIMKFILE)))
$(error did not find luci.mk in any feed)
else
$(error found multiple luci.mk files in the feeds)
endif
else
#$(info found luci.mk at $(LUCIMKFILE))
endif

...
# place Makefile here
...

include $(LUCIMKFILE)
```

**Comment by SvenRoederer** [comment]
PR https://github.com/openwrt/luci/pull/3986 just takes the 1 commit ("reordering") of this PR into a separate one.

**Comment by SvenRoederer** [comment]
@jow- @feckert just found the time to push a non-conflicting and rebased version.
Can you comment on this and probably it can be considered to be included to OpenWrt-20.x .

**Comment by SvenRoederer** [comment]
@jow- Can you have a look on this PR?

**Comment by SvenRoederer** [comment]
@jow- What do you think on this? Can this be merged?

**Comment by SvenRoederer** [comment]
@jow- Do you also follow my idea as feckert in comment https://github.com/openwrt/luci/pull/2637#issuecomment-569507199 ?

**Comment by SvenRoederer** [comment]
@jow- Just rebased to reapply onto master. What about merging, to ease using LuCI-features in other feeds.

**Comment by SvenRoederer** [comment]
@jow- pinging again, after another month has passed by...

Just had a short search on github and found the some repos (excluding obvious forks), that would benefit from this change:
* https://github.com/freifunk/openwrt-packages
* https://github.com/Freifunk-Spalter/packages
* https://github.com/kooiot/packages_ex
* https://github.com/freifunk-berlin/firmware-packages
* https://github.com/Freifunk-Potsdam/firmware-packages

**Comment by SvenRoederer** [comment]
based on @aparcar recent suggestion of moving "findrev" (http://lists.openwrt.org/pipermail/openwrt-devel/2021-January/033037.html) I pointed out this PR on the openwrt-devel ML (http://lists.openwrt.org/pipermail/openwrt-devel/2021-January/033040.html)

**Comment by jow-** [comment]
I would like to keep one file only to simplify maintenance. The readability argument is not convincing enough for me.
As for the warnings / menu placement etc. I am fine with changing the macros as needed to avoid redefinitions and to allow overrides where needed.

**Comment by SvenRoederer** [comment]
@jow- can you review again? just pushed a way only based on some changed macros.

On the external repo some additional changes are required, to archive the same result as in my previous version, but that's not relevant here.

**Comment by SvenRoederer** [comment]
@jow- Can you comment

**Comment by hnyman** [comment]
I haven't tested it. But at the first glance that looks ok to me.

The only thing that looks confusing to me is line 127 where you apparently introduce an external variable `LUCI_MENU` although we already have a bunch of `LUCI_MENU.xxx` variables.  

`LUCI_SUBMENU=$(if $(LUCI_MENU),$(LUCI_MENU),$(LUCI_SUBMENU_DEFAULT))`

It would clarify things if you rename that `LUCI_MENU` to something like `LUCI_NONSTANDARD_MENU` or `LUCI_EXTERNAL_MENU` or `LUCI_PRIVATE_MENU` or something that makes it more obvious that this is external to OpenWrt and LuCI.

**Comment by SvenRoederer** [comment]
According to @hnyman renamed the variable to ```LUCI_SUBMENU_FORCED``` and added some comments.

**Comment by SvenRoederer** [comment]
@jow- any feedback would be appreciated as at least 2 feeds hoping to use this reworked luci.mk or having to look for alternatives.

**Comment by behzaddana** [comment]
Hi, I am Iranian. I have a problem with the M3 confing. 

Sent from Yahoo Mail on Android 
 
  On چهارشنبه, می ۵, ۲۰۲۱ at ۲:۵۱, Sven ***@***.***> wrote:   


@jow- any feedback would be appreciated as at least 2 feeds hoping to use this reworked luci.mk or having to look for alternatives.

**Comment by SvenRoederer** [comment]
@behzaddana What do you mean by "M3 config"?

**Comment by SvenRoederer** [comment]
@jow- did you have time to review?

**Comment by SvenRoederer** [comment]
@feckert can you verify this change with your own feed? I'm currently using this change in my personal builds of our firmware for the Freifunk- and Freifunk-Berlin feeds (only)

**Comment by SvenRoederer** [comment]
@Freifunk-Potsdam  @Freifunk-Spalter as you are also using my old "LuCI-include" code, you might also benefit from the improvements of this PR (esp. placing the packages outside of the LuCI menu, embedding your own Repo-URL).

**Comment by SvenRoederer** [comment]
@jow- just seen that OpenWrt-21.02-rc2 has been tagged. How are the chances to get this merged to master and backported to 21.02 before official release?

**Comment by aparcar** [comment]
Looks pretty good to me, i don't see why this should be merged.

**Comment by SvenRoederer** [comment]
> Looks pretty good to me, i don't see why this should be merged.

@aparcar I'm confused now ... "looks pretty good" as ```luci.mk``` is now, that this change should not be needed?

**Comment by aparcar** [comment]
Oh snap I meant to say "shouldn't be merged"

**Comment by aparcar** [comment]
Thanks for your patience, i hope we didn't discourage your from further contributions!

**Comment by SvenRoederer** [comment]
@aparcar indeed took some time, but it's volunteer work for all of us.

AS it's a non-breaking change, can this be cherry-picked into openwrt-21.02 too?

**Comment by aparcar** [comment]
To github.com:openwrt/luci.git
   74e04dde74..51da4d1561  openwrt-21.02 -> openwrt-21.02

**Pull request merged**
