### PR TITLE
[luci-app-openvpn] DynamicList issue fix.

### LINKED ISSUE #628: [luci-app-openvpn] (incl. fix) DynamicList options do not persist
**Steps to reproduce:**
* In the luci GUI add a second value to any option that is declared as *Dynamic List* (e.g. *route*)
* Click *Save & Apply*

**Behavior:**
The first and second value are merged together into one line and the second line disappears. This is also reflected in the uci file */etc/config/openvpn*, where it still appears as *option route ...*

**Desired behavior:**
There should be multiple lines starting with *list route ...* in the uci file */etc/config/openvpn* and the GUI should keep the values in separate lines.

**Fix:**
Remove from *openvpn-basic.lua* line *65* and from *openvpn-advanced.lua* line *238* (both contain *o.cast = nil*). This fixed it for me.

### PR DESCRIPTION
**Pull request by Wedmer**
closes #628
Maybe it can fix https://dev.openwrt.org/ticket/21506

### CODE REVIEW

**Comment by Wedmer** [comment]
Any reasons why it's not merged?

**Comment by jow-** [comment]
Yeah, I wondered about the unrelated `o.cast` changes and forgot to write about it.

**Comment by Wedmer** [comment]
I've found  #628 just after I've opened pull request.  So I've added description in commit. Also there no any information why it should be nil. So if we comment these strings DynamicList will be interpreted as "table" else as "string".

**Comment by Wedmer** [comment]
So I should close this and open a new request?

**Pull request closed without merging**
