### PR TITLE
luci-base: simplify luci base link

### PR DESCRIPTION
**Pull request by Ansuel**
@jow- 
Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by cshoredaniel** [comment]
@Ansuel Have you verified this works on a 'normal' OpenWrt installation?  This looks to me like it could break if you aren't using the uhttpd lua plugin...

**Comment by Ansuel** [comment]
Lua plugin is installed and enabled by default in uhttpd configuration

**Comment by cshoredaniel** [comment]
Oh! I didn't realize that had changed (I've been away a *while*).  In any event have you verified on 'normal' OpenWrt?  (IIRC you're doing the nginx thing).

**Comment by Ansuel** [comment]
Actually on the wiki there is a guide to enable embedded lua... 

One part of it got merged (the uhttpd config) but the index changes never got merged... In the past I always used Luci with this configuration

**Comment by cshoredaniel** [comment]
@Ansuel I knew about the guide, I didn't know it was half-meged though.  Seems a good plan to fully merge.  Knowing you've actually used it this way (on stock OpenWrt except these changes) is helpful.

In that case LGTM.

**Comment by jow-** [comment]
NACK. Embedded Lua is *not* installed by default and your change would completely break normal LuCI for the majority of users.

**Comment by Ansuel** [comment]
@jow- can i provide a specific index file for just luci-nginx?

**Pull request closed without merging**
