### PR TITLE
luci-proto-xfrm: update description for now-optional tunlink parameter

### PR DESCRIPTION
**Pull request by divinehawk**
- [x] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch
- [x] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [x] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [x] Tested on: [LuCI openwrt-23.05 branch (git-24.086.45142-09d5a38)](https://github.com/openwrt/luci) / [OpenWrt 23.05.4 (r24012-d8dd03c46f)](https://openwrt.org/), with openwrt/openwrt#16046 backport
- [x] Depends on: openwrt/openwrt#16046
- [x] Description: Updates luci description for tunlink parameter which is now optional.

### CODE REVIEW

**Comment by systemcrash** [comment]
Can you handle the equivalent i18n strings also?

Does the field accept an empty value today?

**Comment by divinehawk** [comment]
> Can you handle the equivalent i18n strings also?

For the i18n, I believe I did that correctly.
 
> Does the field accept an empty value today?

Yes, "unspecified" is permitted in the dropdown.

**Comment by systemcrash** [comment]
Good. The i18n needs just the changes of the modified string (should be only 1-2 lines). You can exclude other updates eg pbr.

**Comment by feckert** [comment]
Can you please rebase!

**Comment by systemcrash** [comment]
ping @divinehawk

**Comment by systemcrash** [comment]
@divinehawk - please do not use merge branches - just rebase your changes against master

**Comment by divinehawk** [comment]
> @divinehawk - please do not use merge branches - just rebase your changes against master

Should be good now I think. Apologies for that.

**Comment by systemcrash** [comment]
Thanks @divinehawk!

**Pull request merged**
