### PR TITLE
luci-app-mwan3: initial commit

### PR DESCRIPTION
**Pull request by danrl**
Moved over here from the packages repository.

Signed-off-by: Dan Luedtke <mail@danrl.com>

### CODE REVIEW

**Comment by feckert** [comment]
@danrl How is the status for this PR?

You should also backup the conffiles
> /etc/hotplug.d/iface/16-mwancustom

Maybe also this file?

> /etc/hotplug.d/iface/16-mwancustombak

**Comment by hnyman** [comment]
> /etc/hotplug.d/iface/16-mwancustom 

The practice of hiding some settings into hotplug files themselves  in /etc/hotplug.d is rather strange. For that reason I have not accepted the PR https://github.com/openwrt/packages/pull/3693 from @feckert . In my mind a better solution would be to have a static hotplug that reads the settings from a more typical location.

The goal is to transition all Luci apps to the LuCI repo, and that is the reason behind this PR itself. This has not been committed yet, as I have been waiting if there is any sign of @arfett but I am not sure if he has been around since 2015. 

Care to list yourself as a maintainer also for this Luci app, @feckert  ?

**Comment by danrl** [comment]
@feckert As @hnyman said, this is just a transferring from one repo to another repo PR. I do not intend to make any substantial change with this PR.

**Comment by feckert** [comment]
@hnyman i will to a seperate script in /etc/hotplug.d/iface/ which calls a script for example /etc/mwan3.user. Is this what you mean? Should i also close the PR https://github.com/openwrt/packages/pull/3693 ?
@danrl ok no problem i did not know that this is only a init commit.

**Comment by hnyman** [comment]
> a seperate script in /etc/hotplug.d/iface/ which calls a script for example /etc/mwan3.user. Is this what you mean?  

Yes, I mean something like that. Users expect modified files in /etc and subdirs, but not in /etc/hotplug.d. I closed PR 3693

And it is a bit strange that the hotplug iface thing is introduce in LuCI. That kind of extension of functionality belongs more to the actual mwan3 package itself than the LuCI app, which should be about making config settings and monitoring situation. Introducing hotplug scripts here that extend the core functionality of the main app is rather unorthodox.  From that perspective it would be even better to have the whole hotplug thing in the main app in the packages repo.

**Comment by danrl** [comment]
> From that perspective it would be even better to have the whole hotplug thing in the main app in the packages repo.
Agreed.

@feckert, do you like to create a new PR based on this and we close this one here? Or shall we make the transition first so that we have a working version in LuCI for now. And then later move the hotplug things into the main package?

**Comment by feckert** [comment]
@danri i would suggest make transision first and add the feature `/etc/mwan3.user` skript into mwan3. In the next step then we should remove the `/etc/hotplug.d/iface/16-mwancustom` and /etc/hotplug.d/iface/16-mwancustombak from luci-app-mwan3

**Comment by feckert** [comment]
@danri @hnyman [RFC] for `/etc/mwan3.user`
https://github.com/TDT-GmbH/packages/commit/b5e3546a667cac6c04f0c2630b4d3eaea00c7b29

**Comment by hnyman** [comment]
That looks good in principle. But I am thinking if there should be some checking if e.g. mwan3 the enabled at all (before calling the user script). I haven't checked the main mwan3 itself for the behaviour on ifup/ifdown reaction, if it doen any enabled/disabled checking.)

**Comment by hnyman** [comment]
I will merge this Luci transition now.

**Comment by feckert** [comment]
@hnyman 
`Care to list yourself as a maintainer also for this Luci app, @feckert ?` I have no problem to get the maintainer of the luci-app-mwan3 as well. But I am not sure if @danrl wants to delegate the task to me.

**Comment by danrl** [comment]
No objections, @feckert. I have enough other packages to maintain :)

**Comment by feckert** [comment]
@danrl i will do a PR next week

**Comment by hnyman** [comment]
> But I am not sure if @danrl wants to delegate the task to me.

Well, the Makefile lists @arfett as the maintainer, not @danrl ...
(danrl just made the PR to transfer this to the Luci repo)

But @arfett has not been really active since 2015, so it is good to have additional maintainers.

**Comment by arfett** [comment]
Since the main mwan3 package stopped really being updated I haven't had much to do (or much that I cared to do). I can always help if needed or given a direction to go. Feel free to add anyone else as a maintainer.

**Pull request merged**
