### PR TITLE
fixed russian translation

### PR DESCRIPTION
**Pull request by user7887**
Signed-off-by: Vladimir <picfun@ya.ru>

### CODE REVIEW

**Comment by user7887** [comment]
Presents a translation option for these applications - proven (including in graphical mode):
luci-app-adblock
luci-app-advanced-reboot
luci-app-aria2
luci-app-clamav
luci-app-ddns
luci-app-dnscrypt-proxy
luci-app-dynapoint
luci-app-fwknopd
luci-app-mjpg-streamer
luci-app-privoxy
luci-app-samba
luci-app-shairplay
luci-app-simple-adblock
luci-app-statistics
Will be right if you make changes to the application and templates.
Checked everything to the point :)
Thank you!

**Comment by hnyman** [comment]
I will merge this.

One piece of advice for you:
After making the actual translation, please run ./build/i18n-sync.pl in the luci source repo's root dir in order to format the .po files correctly (e.g. adjusting long lines to the default length etc.)

I did that after your previous changes and some lines were changed. See e.g. https://github.com/openwrt/luci/commit/bd52bf4625c31c532f108c706165efa85cfca4ac#diff-cf696755e6ae6d75edd0a5f79a17c9f8

That i18n-sync.pl is run in any case every now and then, but it would be great if your input is correctly formatted already at your original commit.

**Comment by user7887** [comment]
hnyman
Ok
Thanks!

**Comment by user7887** [comment]
hnyman
Ok. Thanks!
I will do as you said :)

**Pull request merged**
