### PR TITLE
luci-mod-network: add master option

### PR DESCRIPTION
**Pull request by Ansuel**
This option is usefull if someone needs to route ipv6 dhcp from wan to lan.
@jow- 
Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
The description string has multiple typos, it also does not really explain what it does. Why is setting `master` "useful with multiple interfaces?

Also what are the possible values for the `master` option? Does a CBI `Value` really make sense? Shouldn't it be a checkbox?

**Comment by Ansuel** [comment]
@jow- actually the master option  is just a boolean.  Does luci have an option to check if master is not already checked on others section of should i create a function for it?

**Comment by LipkeGu** [comment]
@Ansuel Yes Luci has this option.
Master is not only neaded by WAN interfaces... you can say all upstream interfaces. Im using it on a vpn interface.

**Comment by feckert** [comment]
Please rebase your changes against the new javascript implementation.

**Comment by Ansuel** [comment]
@feckert done...

**Comment by jow-** [comment]
@Ansuel - it's almost golden, can you add semicolons to your .js lines? After that it can be merged.

**Comment by Ansuel** [comment]
@jow- my bad sorry.... anyway done...

**Comment by jow-** [comment]
Thanks!

**Pull request merged**
