### PR TITLE
luci-theme-material: add back removed color variables

### PR DESCRIPTION
**Pull request by dannil**
Spawned from https://github.com/openwrt/luci/pull/6936#issuecomment-2011632254. Everything should look as before.

Partially reverts 2bdabf14c30320ef0433828b1a080f6b8fe9c430 by adding back the deleted color variables as the custom.css was used by users to override the theme with their own colors. To maintain backwards compatibility with users we should not remove/rename these as it will result in colors being applied incorrectly.

Ping @feckert 

- [X] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [X] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [X] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [X] Incremented :up: any `PKG_VERSION` in the Makefile
- [X] Tested on: (x86/64, 23.05.2, Firefox) :white_check_mark:
- [ ] \( Preferred ) Mention: @ the original code author for feedback
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [ ] \( Optional ) Closes: e.g. openwrt/luci#issue-number
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [X] Description: (describe the changes proposed in this PR)

### CODE REVIEW

**Comment by systemcrash** [comment]
Ready @dannil ?

**Comment by dannil** [comment]
> Ready @dannil ?

Yes I would think so, I was waiting for feedback from @feckert tho.

**Comment by feckert** [comment]
@dannil Thanks for your work and the fix. Is working as expected :+1:

**Comment by feckert** [comment]
@dannil I've only just seen it.
Next time, please make sure that the length of the commit description does not exceed the 80 character limit per line!.

**Comment by systemcrash** [comment]
> @dannil I've only just seen it. Next time, please make sure that the length of the commit description does not exceed the 80 character limit per line!.

Is this just something we blindly repeat without understanding why? Torvalds removed this restriction a number of years back, since we have high-res desktops capable of more than 80 characters wide since forever, and editors that can horizontally scroll since even more forever.

**Comment by jow-** [comment]
I want to keep that limitation, makes it easier to work with git log in small terminal windows.

**Comment by systemcrash** [comment]
Solved problem apparently: https://stackoverflow.com/questions/2119942/how-to-wrap-git-commit-comments

**Comment by dannil** [comment]
Would it make sense to think about adding the 80 character limit to the [formal.yml](https://github.com/openwrt/actions-shared-workflows/blob/main/.github/workflows/formal.yml) task?

**Comment by feckert** [comment]
@systemcrash I have found an interesting article a bout this topic https://hackaday.com/2020/06/18/ask-hackaday-are-80-characters-per-line-still-reasonable-in-2020/

From my point of view, the following statement says it all. 

`In other words, requires us to move our eyes, or even the entire head, disrupting the reading flow and increasing the risk to overlook something important.`

**Comment by systemcrash** [comment]
Salient points. Consider this: the reason ebooks and HTML don't use 80 character limits anywhere (and why PDFs look and behave like dog-shit on portable readers) is...

RE-FLOW

If text is one contiguous block, you can reformat it at will (which is what github attempts to do) and set whatever width you want. 80 characters be damned. I'd be happy with 30 or 40 (for faster reading, as your point).

**Comment by dannil** [comment]
I've created https://forum.openwrt.org/t/enforcement-of-commit-subject-and-description-in-ci/193391 to follow up the discussion on the formal requirements for commits.

**Pull request merged**
