### PR TITLE
Fix app statistics postinst

### PR DESCRIPTION
**Pull request by cshoredaniel**
Should fix https://github.com/openwrt/luci/issues/722.  There were two errors:

1) Spurious uci warnings when installing app-statistics on a system with no existing app-statistics (due to deleting etc non-existent entries).  We simply drop the error; if debugging is need that can be removed and the uci-default run manually.
2) luci.mk had a postinst that automatically performed uci-defaults scriptlets on install but LEDE trunk also does this so the uci-defaults file was missing for the latter's execution.  We omit LuCI's 'live uci-defaults' on new enough LEDE.

### CODE REVIEW

**Comment by cshoredaniel** [comment]
@hnyman @jow- Could you review?

**Comment by hnyman** [comment]
I am offline for the next week or so.

**Comment by cshoredaniel** [comment]
Appears to work for me, but would appreciate other's input.

**Comment by hnyman** [comment]
I don't like the ` grep -q uci-defaults /lib/functions.sh ` part of the patch. That grep is non-conclusive as the functions.sh might include the word "uci-defaults" elsewhere than default-postinst, and then this scripts should be run here anyway. So, I would leave that part away.

But both 
* the quieting of uci commands with  `2>&1 || true ` and 
* the test for script existence before executing `[ -r /etc/uci-defaults/$(script) ] ` look good. (This is pretty much the same that @jow- implemented as the fix with https://git.lede-project.org/?p=source.git;a=commitdiff;h=7f6945829640e82dadf928c9e214470fa0c5a321 )

**Comment by cshoredaniel** [comment]
I see however LEDE has a core fix that eliminates the need for that.

**Comment by hnyman** [comment]
Yes I know that **currently** there is no other instance of that string there, but there may be in future.

But isn't that grep check unnecessary, as two lines later you added a check for the uci-defaults file' existence before running it. Or did I get that part wrong?

**Comment by cshoredaniel** [comment]
It's no longer necessary because Jo's core fix, but before that default_postinst would emit an error because default_postinst would try to execute the luci uci-defaults after luci's postinst had deleted it.

**Comment by cshoredaniel** [comment]
Closing as have taken a break from LEDE/OpenWrt development for various reasons, so will reopen when this is back on the radar.

**Pull request closed without merging**
