### PR TITLE
Pull request app firewall timedate

### PR DESCRIPTION
**Pull request by dfc-d**
This series of commits adds the UCI time and date restriction for firewall rules and redirects to LuCI.

### CODE REVIEW

**Comment by jow-** [comment]
Yay, had this on my to-do list for ages, good to see that you beat me to it.
A couple of things:
 * `translate()` should only be called with string literals, otherwise it is impossible to extract original strings from the source code, also it imho makes no sense to translate 1..31
 * We need a JavaScript counterpart for the new validation types (see `cbi.js`)
 * The time stuff adds a lot of new options to the rule details so maybe we should start using tabs, e.g. 
    * General: name, enabled, protocol, action
    * ICMP: icmp types [will be hidden if proto!=icmp]
    * Source: src, src_ip, src_port, src_mac
    * Destination: dest, dest_ip, dest_port
    * Timing: all the date and time options

What do you think? I can also merge the PR without the tabbing (but with JS validation added) and then take a stab at the tabs myself.

**Comment by dfc-d** [comment]
I will try to get to it this weekend but I've got a major cold that is making me miserable since Tuesday.

**Comment by dfc-d** [comment]
I haven't finished but I did notice that the commit seems to have missed the actual UI page.

**Comment by dfc-d** [comment]
nvm, it was when I went to fix it that I missed the second commit

**Comment by dfc-d** [comment]
Ok, I've update based on your comments;

I've also fixed a couple of bugs with the implementation and added the option of using and option using self.oneline = true with a multivalue checkbox which makes a checkbox be space-separated instead of each checkbox item being on a separate line.  This makes the days of week and days of month selection much more compact (and iMO usable).

I'm not sure the tabbing is actually necessay and might actually be more of a pain when it comes to actually creating firewall rules from an data-entry standpoint.

**Comment by dfc-d** [comment]
Sorry I'm review what actually got in the commit and it looks like I lost cbi.js.

Will fix.

**Comment by dfc-d** [comment]
Ok, the cbi.js is there but the datatypes.lua isn't but I have to play around with github to make sure that's not just an me misreading github's presentation of the branch.

**Comment by dfc-d** [comment]
Ok, it's actually correct, I was just misreading github.

**Comment by dfc-d** [comment]
I've reviewed this changeset because of the number dumb mistakes with changing the upload dir pull request - this changeset is correct.

**Comment by dfc-d** [comment]
Apparently I was wrong - I had managed to pull in my version of ipaddrport which isn't needed for this pull request and was better implemented in the l2tp pull request already merged.

That is fixed now.

**Comment by dfc-d** [comment]
I had forgotten to push a fix for a javascript syntax error that wasn't immediately obvious until I noticed that dynamic lists weren't working and pulled out the the debugger.  Apparently if there is a syntax error in cbi.js it's not as obvious as lua errors.

**Comment by jow-** [comment]
Merged, thanks!

**Pull request merged**
