### PR TITLE
luci-proto-openconnect: synchronize certificate pem files with openconnect package

### PR DESCRIPTION
**Pull request by nmav**
Signed-off-by: Nikos Mavrogiannopoulos <nmav@gnutls.org>

### CODE REVIEW

**Comment by nmav** [comment]
This change applies to both master of openwrt and luci-14.07 branch.

**Comment by jow-** [comment]
As I already commented on your other commit; I strongly urge you to not use /etc/config/ for non-uci files, whats the rationale for it?

**Comment by nmav** [comment]
Because otherwise the settings cannot be backed up and are lost on an upgrade.

**Comment by nmav** [comment]
The issue is that these files contain multi-line strings, and those cannot be stored with luci. dropbear does something similar, but is backed up explicitly.

**Comment by jow-** [comment]
Just define a conffiles sections in the openconnect Makefile.

    define Package/foo/conffiles
    /etc/openconnect/
    endef

**Comment by jow-** [comment]
Also I did not mean that you should convert those files to uci, just that non-uci files should not be in /etc/config/, the previous /etc/openconnect/ location seemed fine to me, in conjunction with the conffiles section mentioned above.

**Pull request closed without merging**
