### PR TITLE
Add basic danish translation

### PR DESCRIPTION
**Pull request by rubo77**
The translation in base.po is by @RegsaGC at https://github.com/RegsaGC/luci/commit/1df54e80d97359c2482d762d8284adcb1eee6e3c

I squashed it all into one commit

### CODE REVIEW

**Comment by rubo77** [comment]
The translation in base.po is by @RegsaGC at https://github.com/RegsaGC/luci/commit/1df54e80d97359c2482d762d8284adcb1eee6e3c

I squashed it all into one commit

**Comment by hnyman** [comment]
I don't think that it makes sense to merge empty translation files to Luci. Both firewall and meshwizard files are currently without any actual translation. 

And the main Luci of base.po is maybe 1/4 translated. That does not serve anybody, yet, as the translated strings will be shown on mixed with untranslated strings on pages.

Your editor probably does some line wrapping as Github gui shows at least one strange wrap ( https://github.com/rubo77/luci/blob/8e39e47ea7c1549fa18c1d866ea354fad4d48045/modules/luci-base/po/da/base.po#L888 ), and probably at least one " is missing (at https://github.com/rubo77/luci/blob/8e39e47ea7c1549fa18c1d866ea354fad4d48045/modules/luci-base/po/da/base.po#L111 ).

You have disregarded the advice in CONTRIBUTING.md (and my last message) to sign off the commit itself. (not the PR, but the commit message itself).

I think that you should complete the base.po translation and we can then merge that.

**Comment by rubo77** [comment]
The main issue here is, that we use luci in gluon and I think we don't need any of the translations in base.po but we have only our own da.po files that should be used in our config mode. So we just want that luci supports basic danish.

since I don't speak danish yet and there is no real need for the danish base.po file, it is hard to find anyone to finish the translation.

can't we just include the danish support and show english, where there is no translation yet?

(I will rebase the commit to include the signature)

**Comment by hnyman** [comment]
> The main issue here is, that we use luci in gluon and I think we don't need any of the translations in base.po but we have only our own da.po files that should be used in our config mode. So we just want that luci supports basic danish.

So, you might actually be happy with just the luci.mk change? Declaring Danish as a supported language in menuconfig, but not really providing translations for Luci modules. That would enable you to use Danish in the application specific things.

@jow- 
Any views to the question, if it is suitable to declare a language supported in luci.mk without having an actual translation ready for luci-base?

**Comment by rubo77** [comment]
If so, then this would be a PR: https://github.com/openwrt/luci/pull/792

**Comment by rubo77** [comment]
So what exactly do you mean here? https://github.com/openwrt/luci/pull/792#issuecomment-245241708

I thought about your comment above:

> just the luci.mk change

(maybe we can better discuss this issue in the `#openwrt` IRC channel at freenode)

**Comment by hnyman** [comment]
> So what exactly do you mean here? #792 (comment)

I meant with my comment here at #790 that adding the Danish definition by itself to the Luci master might be possible if that would help you, and I enquired opinion from Jow, the main developer of Luci.

Then I saw your new PR #792 to add definitions for several languages to Luci master (just the definitions, but without any translations done) and that made me to visit your Gluon repo. Based on the Gluon feed definition file ( https://github.com/freifunk-gluon/gluon/blob/master/modules ) it seems to me that Gluon is not using the Luci master branch, but instead you use the old stable for-15.05 branch. So adding Danish (or other languages) to Luci master with your PR would not make them visible in your Gluon build system that uses the older for-15.05 branch.

And from "Luci perspective" I see not much point in adding an empty language definitions to the historical for-15.05 stable branch.

In my comment in #792 I suggested that you look into possibilities of patching the Luci feed at Gluon to include the Danish language. You seem to be defining own patches for the feeds at https://github.com/freifunk-gluon/gluon/tree/master/patches/packages and that includes patches for Luci:  https://github.com/freifunk-gluon/gluon/tree/master/patches/packages/luci

You might be able to patch luci.mk there to insert the necessary language definitions into Luci, without any need to modify the original Luci repo here.

**Comment by hnyman** [comment]
I close this PR. Please file a new one if you complete the Danish translation for master. But like I said, Gluon seems to need the for-15.05 branch instead of master. And new languages will not be introduced here for the old for-15.05 branch. So you might be better off by crafting a patch in Gluon.

**Comment by rubo77** [comment]
Gluon  will switch to the luci master very soon.

**Comment by rubo77** [comment]
I added a patch to gluon now, so we can add our own danish language files there: https://github.com/freifunk-gluon/gluon/pull/996

I hope this is all we need to start translating gluon?

**Pull request closed without merging**
