### PR TITLE
luci-app-smartdns: Fix The list has multiple headers.

### PR DESCRIPTION
**Pull request by FanxJK**
Before the fix:
Before
After the fix:
image

@pymumu

### CODE REVIEW

**Comment by pymumu** [comment]
LGTM

**Comment by systemcrash** [comment]
Fix the checks please

**Comment by zxlhhyccc** [comment]
It's really much cleaner. Suggest merging.

**Comment by systemcrash** [comment]
> It's really much cleaner. Suggest merging.

Suggest to read the checks and fixing those first.

**Review by FanxJK — COMMENTED** [review]
Signed-off-by:  FanxJK <fanxjk@gmail.com>

**Comment by systemcrash** [comment]
Almost. Now fix the *commit*

**Comment by systemcrash** [comment]
Good. Merged. Thanks!

**Pull request merged**
