### PR TITLE
Added luci-app-wifischeduler 

### PR DESCRIPTION
**Pull request by newkit**
Turns WiFi on and off according to a schedule

Signed-off-by: Nils Koenig <mailUNDERSCOREopenwrt@newkDOTit>

### CODE REVIEW

**Comment by chris5560** [comment]
@newkit

good idea, but why do you not offer the functionality to OpenWrt/LEDE packages tree without the need of LuCI frontend ?
My idea is to split script and config into OpenWrt/LEDE package tree and LuCI frontend into LuCI tree.
There are a lot of routers with low flash memory and no LuCI installed.

**Comment by newkit** [comment]
@chris5560 

Yeah, good point, makes sense. I'll look into that.

**Comment by northbound1** [comment]
This is LEDE r2144
If it matters WRT1900AC V1 (mvebu)

This is something useful to me and it would be nice to see it work. And Thank you for your time.

I got https://github.com/openwrt/luci/pull/843/commits/72adb484e5b2c02171d0be3e04b8a8179e403d6d

I got it to compile and it shows in luci. View log file works. View cron jobs works but not schedule
the tab is there, but no options 

"Wifi Schedule

Defines a schedule when to turn on and off wifi." Is all that is on that tab.

When I manually try to start it does shows in log.
Tue Nov  8 21:18:27 EST 2016 ./wifi_schedule.sh
Tue Nov  8 21:19:04 EST 2016 ./wifi_schedule.sh
Tue Nov  8 21:29:00 EST 2016 /usr/bin/wifi_schedule.sh

I know I am missing something but can't put my finger on what it is.


below is the modified config file.


/etc/config/wifi_schedule.
config global
        option logging '1'
        option enabled '1'
        option recheck_interval '10'
        option modules_retries '10'

config entry 'Businesshours'
        option enabled '1'
        option daysofweek 'Monday Tuesday Wednesday Thursday Friday'
        option starttime '06:00'
        option stoptime '22:00'
        option forcewifidown '0'

config entry 'Weekend'
        option enabled '1'
        option daysofweek 'Saturday Sunday'
        option starttime '00:00'
        option stoptime '00:00'
        option forcewifidown '1'

All below "removed" were changed values. 

root@OpenWrt:~# strace -v /usr/bin/wifi_schedule.sh
execve("/usr/bin/wifi_schedule.sh", ["/usr/bin/wifi_schedule.sh"], ["SSH_CLIENT=                                                                                        192.168.1.183 5570 42"..., "USER=root", "SHLVL=1", "HOME=/root", "SSH_TTY=/dev/p                                                                                        ts/0", "PS1=\\u@\\h:\\w\\$ ", "LOGNAME=root", "TERM=xterm", "PATH=/usr/bin:/usr/                                                                                        sbin:/bin:/sb"..., "SHELL=/bin/ash", "PWD=/root", "SSH_CONNECTION=192.168.1.183                                                                                         557"...]) = 0
set_tls(removed, removed, removed, 0, removed) = 0
set_tid_address(removed)             = 3625
open("/etc/ld-musl-armhf.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No                                                                                         such file or directory)
open("/lib/libgcc_s.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0
fstat64(3, {st_dev=makedev(254, 0), st_ino=244, st_mode=S_IFREG|0644, st_nlink=1                                                                                        , st_uid=0, st_gid=0, st_blksize=1024, st_blocks=75, st_size=38211, st_atime=201                                                                                        6/11/08-14:00:42, st_mtime=2016/11/08-14:00:42, st_ctime=2016/11/08-14:00:42}) =                                                                                         0
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\240;\0\0004\0\0\0"..., 9                                                                                        36) = 936
mmap2(NULL, 106496, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0xb6e94000
mmap2(0xb6ead000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x9000)                                                                                         = 0xb6ead000
close(3)                                = 0
mprotect(0xb6f20000, 4096, PROT_READ)   = 0
getuid32()                              = 0
getpid()                                = 3625
rt_sigaction(SIGCHLD, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0xb6eef9b8}, {SIG_DF                                                                                        L, [], 0}, 8) = 0
rt_sigaction(SIGHUP, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0xb6eef9b8}, {SIG_DFL                                                                                        , [], 0}, 8) = 0
getppid()                               = 3622
uname({sysname="Linux", nodename="OpenWrt", release="4.4.30", version="#0 SMP Tu                                                                                        e Nov 8 18:15:14 2016", machine="armv7l", domainname="(none)"}) = 0
stat64("/root", {st_dev=makedev(0, 15), st_ino=5415, st_mode=S_IFDIR|0755, st_nl                                                                                        ink=2, st_uid=0, st_gid=0, st_blksize=1024, st_blocks=0, st_size=3, st_atime=201                                                                                        6/11/08-14:00:42, st_mtime=2016/11/08-14:00:42, st_ctime=2016/11/08-14:00:42}) =                                                                                         0
stat64(".", {st_dev=makedev(0, 15), st_ino=5415, st_mode=S_IFDIR|0755, st_nlink=                                                                                        2, st_uid=0, st_gid=0, st_blksize=1024, st_blocks=0, st_size=3, st_atime=2016/11                                                                                        /08-14:00:42, st_mtime=2016/11/08-14:00:42, st_ctime=2016/11/08-14:00:42}) = 0
open("/usr/bin/wifi_schedule.sh", O_RDONLY|O_LARGEFILE) = 3
fcntl64(3, F_DUPFD, 10)                 = 10
close(3)                                = 0
fcntl64(10, F_SETFD, FD_CLOEXEC)        = 0
rt_sigaction(SIGINT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
rt_sigaction(SIGINT, {0x2d2e0, ~[RTMIN RT_1 RT_2], SA_RESTORER, 0xb6eef9b8}, NUL                                                                                        L, 8) = 0
rt_sigaction(SIGQUIT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, {SIG_IGN, ~[RTMIN RT_1 RT_2], SA_RESTORER, 0xb6eef9b8}, NU                                                                                        LL, 8) = 0
rt_sigaction(SIGTERM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTERM, {SIG_DFL, ~[RTMIN RT_1 RT_2], SA_RESTORER, 0xb6eef9b8}, NU                                                                                        LL, 8) = 0
read(10, "#!/bin/sh\n\n# Copyright (c) 2016,"..., 511) = 511
read(10, "RECT, OR CONSEQUENTIAL DAMAGES O"..., 511) = 511
wait4(-1, 0xbeb956d4, WNOHANG, NULL)    = -1 ECHILD (No child process)
wait4(-1, 0xbeb956d4, WNOHANG, NULL)    = -1 ECHILD (No child process)
wait4(-1, 0xbeb956d4, WNOHANG, NULL)    = -1 ECHILD (No child process)
wait4(-1, 0xbeb956d4, WNOHANG, NULL)    = -1 ECHILD (No child process)
wait4(-1, 0xbeb956d4, WNOHANG, NULL)    = -1 ECHILD (No child process)
wait4(-1, 0xbeb956d4, WNOHANG, NULL)    = -1 ECHILD (No child process)
read(10, "n\n        local ts=$(date)\n     "..., 511) = 511
read(10, " return ${rc}\n}\n\n_get_uci_value("..., 511) = 511
brk(NULL)                               = 0x67a000
brk(0x67b000)                           = 0x67b000
read(10, "\n    local starttime\n    local s"..., 511) = 511
read(10, "i\n\n\n    local stop_cron_entry=\"$"..., 511) = 511
brk(0x67c000)                           = 0x67c000
read(10, "nterfaces()\n{\n    local n=$(cat "..., 511) = 511
read(10, "_list | tr ',' ' '\n}\n\n_save_modu"..., 511) = 511
read(10, " for mod in ${list}\n        do\n "..., 511) = 511
brk(0x67d000)                           = 0x67d000
read(10, "ile [[ ${i} -lt ${retries}  &&  "..., 511) = 511
read(10, " | awk -F'.' '{print $2}' | grep"..., 511) = 511
brk(0x67e000)                           = 0x67e000
read(10, " 1 ]; then\n        _create_cron_"..., 511) = 511
read(10, " if no stations are associated\n "..., 511) = 511
read(10, "sable wifi.\"\n        disable_wif"..., 511) = 511
brk(0x67f000)                           = 0x67f000
read(10, " fi\n    /sbin/wifi\n}\n\nusage()\n{\n"..., 511) = 511
read(10, "ho \"    help: This description.\""..., 511) = 511
pipe([3, 4])                            = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
fork()                                  = 3626
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(4)                                = 0
read(3, "1\n", 128)                     = 2
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3626, si_uid=0, si_sta                                                                                        tus=0, si_utime=0, si_stime=0} ---
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 3626
wait4(-1, 0xbeb95514, WNOHANG, NULL)    = -1 ECHILD (No child process)
wait4(-1, 0xbeb956d4, WNOHANG, NULL)    = -1 ECHILD (No child process)
brk(0x680000)                           = 0x680000
wait4(-1, 0xbeb9511c, WNOHANG, NULL)    = -1 ECHILD (No child process)
pipe([3, 4])                            = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
fork()                                  = 3629
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(4)                                = 0
read(3, "Tue Nov  8 21:29:00 EST 2016\n", 128) = 29
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3629, si_uid=0, si_sta                                                                                        tus=0, si_utime=0, si_stime=1} ---
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 3629
wait4(-1, 0xbeb94f5c, WNOHANG, NULL)    = -1 ECHILD (No child process)
open("/tmp/log/wifi_schedule.log", O_WRONLY|O_CREAT|O_APPEND|O_LARGEFILE, 0666)                                                                                         = 3
fcntl64(1, F_DUPFD, 10)                 = 11
dup2(3, 1)                              = 1
close(3)                                = 0
wait4(-1, 0xbeb94f5c, WNOHANG, NULL)    = -1 ECHILD (No child process)
write(1, "Tue Nov  8 21:29:00 EST 2016 /us"..., 55) = 55
dup2(11, 1)                             = 1
close(11)                               = 0
stat64("/usr/bin/lock", 0xbeb956a0)     = -1 ENOENT (No such file or directory)
stat64("/usr/sbin/lock", 0xbeb956a0)    = -1 ENOENT (No such file or directory)
stat64("/bin/lock", {st_dev=makedev(254, 0), st_ino=1385, st_mode=S_IFREG|0755,                                                                                         st_nlink=1, st_uid=0, st_gid=0, st_blksize=1024, st_blocks=731, st_size=374209,                                                                                         st_atime=2016/11/08-14:00:42, st_mtime=2016/11/08-14:00:42, st_ctime=2016/11/08-                                                                                        14:00:42}) = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
fork()                                  = 3630
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 3630
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3630, si_uid=0, si_sta                                                                                        tus=0, si_utime=0, si_stime=0} ---
read(10, "   help|--help|-h) usage ;;\nesac"..., 511) = 42
wait4(-1, 0xbeb956d4, WNOHANG, NULL)    = -1 ECHILD (No child process)
wait4(-1, 0xbeb94f5c, WNOHANG, NULL)    = -1 ECHILD (No child process)
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
fork()                                  = 3632
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 3632
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3632, si_uid=0, si_sta                                                                                        tus=0, si_utime=0, si_stime=0} ---
wait4(-1, 0xbeb9511c, WNOHANG, NULL)    = -1 ECHILD (No child process)
exit_group(0)                           = ?
+++ exited with 0 +++
root@OpenWrt:~#

**Comment by newkit** [comment]
@northbound1 

Can you please call

`/usr/bin/wifi_schedule.sh cron`

and see if that creates the cron jobs?
Did you use the GUI to enable? Because I am missing the 

`/usr/bin/wifi_schedule.sh cron`

entry in the log file.

**Comment by northbound1** [comment]
Under view cron jobs I now see this.
00 00 * * Sat,Sun /usr/bin/wifi_schedule.sh forcestop
00 06 * * Mon,Tue,Wed,Thu,Fri /usr/bin/wifi_schedule.sh start
00 22 * * Mon,Tue,Wed,Thu,Fri /usr/bin/wifi_schedule.sh stop

There are still no options under the schedule tab in luci.
I won't have much time to play with this until I get home from work.
The cron jobs were created so it may work now.
Thank you for your time.

**Comment by newkit** [comment]
@northbound1 
Regarding the GUI issue, this is me just guessing, but could it be that the inline "<br>" tags in 
`luasrc/model/cbi/wifischedule/wifi_schedule.lua`
stop you luci version from parsing? I know it's hackish to put those inline line breaks, just had no other quick clue by the time doing it. So my suggestion would be to remove those and give it a try, if you find time. 

I'll look into building and integrating the package with LEDE.

**Comment by northbound1** [comment]
It may go deeper than just the gui. Which I still don't have working yet.
If I do either a
"/usr/bin/wifi_schedule.sh forcestop" 
or a 
"/usr/bin/wifi_schedule.sh stop" 
The 
"/usr/bin/wifi_schedule.sh start" 
does not start wifi.
I disable wifi in luci and re-enable but it will not come back up.
The only thing I have found so far is a reboot and wifi is back up.
Using strace I get the below.
open("/etc/ld-musl-armhf.path", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No                                                                                         such file or directory)
open("/lib/libgcc_s.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_SETFD, FD_CLOEXEC)         = 0

Am I maybe missing a dependency?
Just a note... I am still learning and the more I learn the less I know. :-)

**Comment by newkit** [comment]
@northbound1 

Two things:

1. Could you please check if you use commit https://github.com/newkit/luci/commit/6e39a39507b6b2b3ad7b0bf154c58de9051a724e you still have the GUI issue?

2. Does `/sbin/wifi down` and  `/sbin/wifi` the job of disabling/enabling WiFi)

I built against LEDE r2145 and could use the code without modifications, so I am not sure what causes the issues you report.

**Comment by northbound1** [comment]
@newkit 
Seems good now (I fumble fingered the edit)
And I was doing the config wrong The working GUI solved it all..
Thanks again for your patience and time. And a great scheduler.

**Comment by newkit** [comment]
@northbound1

Glad to hear! Thanks for you beta testing and your time!

**Pull request closed without merging**
