### PR TITLE
 luci-base: fix syntax error in hostapd features

### PR DESCRIPTION
**Pull request by MartB**
Signed-off-by: Martin Böh <mart.b@outlook.de>

### CODE REVIEW

**Comment by MartB** [comment]
Sorry for the DCO spam but it didnt like that i tried to use github directly for this minor edit and then it didnt like the mismatch between my realname (which is required for signing off) and my github username.

**Comment by jow-** [comment]
Merged, thanks!

**Comment by lynxthecat** [comment]
Error is back. 

https://github.com/openwrt/luci/issues/4555#issuecomment-927104087

**Comment by clonin216** [comment]
I have the same error message, but I can't find what's the problem?
image
This is our "luci" file
[luci.txt](https://github.com/openwrt/luci/files/8813244/luci.txt)

**Comment by lynxthecat** [comment]
@clonin216 can you try hard reset of browser cache?

**Comment by clonin216** [comment]
@lynxthecat Yes, I did, but the problem persists

**Comment by clonin216** [comment]
@jow- 
I am using the latest version of luci
image
I use the same source code, one computer compiles without this error, but another computer compiles with the error.
When we add these codes, there will be errors, please help me to confirm if there is a problem.
image
image
image
image

**Comment by clonin216** [comment]
I use the same source code to compile on two different computers, one succeeds and the other fails, what's the difference before?

image
image

**Pull request merged**
