### PR TITLE
luci-app-ddns: improve performance

### PR DESCRIPTION
**Pull request by Ansuel**
Every request directed to the ddns app call ddns tools module.
Ddns tools module have lots of global variable that call slow os.execute function. This adds 10 second to every ddns request even if the function that is requested doesn't need that global variable. This commit introduce env_info function that execute os.execute command by executing what is actually requested and not process all the variables. Also remove 2 unecessary module that are not used. More researh find that major slowdown was caused by the calling of ddns script for the version check. Now we check if opkg is present and use it to check ddns-scripts version.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
Great that you have found some optimisations for LuCI DDNS app.

I evaluated three years ago the front page refreshing load, and noticed already then that DDNS status info refresh was a major load generator, but did not actually look for improvements: https://github.com/openwrt/luci/issues/459

I haven't tested the proposed fixes, but the goal of optimising DDNS LuCI app is great.

**Comment by Ansuel** [comment]
Also now we can put Xhr request for no IP back to 5 second (or increase it to 30-60, as it doesn't change so much) 
Anyway now it does load in 300 ms like others Xhr request

**Comment by Ansuel** [comment]
https://github.com/openwrt/packages/pull/6103

This pr is also very important.

**Comment by hnyman** [comment]
@chris5560 
any comments to the proposed changes?

**Comment by chris5560** [comment]
I did not check the patches but if it works it's fine for me.
I'm currently a little bit short on time. Sorry.
Please increase PKG_RELEASE inside Makefile to reflect changes.
Many thanks

**Comment by Ansuel** [comment]
@chris5560 what about this #1835 
PKG_RELEASE increased

**Comment by hnyman** [comment]
Let's merge this first, then you consider the other optimisations in the other PRs.

**Comment by silence48** [comment]
thanks for this. i couldn't figure out why it was sooo SLOWWWW

**Pull request merged**
