### PR TITLE
luci-theme-rosy: Fix bug in the login interface and header style 

### PR DESCRIPTION
**Pull request by yglb**
luci-theme-rosy: Fix the display bug in the mobile login interface
luci-theme-rosy: Modification of header style of Web pages.

Signed-off-by: YanlanShen <yanlan.Shen@rosinson.com>

### CODE REVIEW

**Comment by yglb** [comment]
@jow-

**Comment by yglb** [comment]
sorry, my carelessness led to the second and third submissions.

**Comment by rosysong** [comment]
ACK!

**Comment by rosysong** [comment]
Any problem on this PR?

**Pull request merged**
