### PR TITLE
luci-app-https_dns_proxy: bugfix: subnet address datatype, add DNS.SB provider

### PR DESCRIPTION
**Pull request by stangri**
This addresses the issue mentioned in #3148.

Signed-off-by: Stan Grishin <stangri@melmac.net>

### CODE REVIEW

**Comment by feckert** [comment]
Could we split the commit into smaller peaces?
Also is it necessary that we check in code comments?

**Comment by feckert** [comment]
> You want me to separate commits for bugfix and adding new DoH providers?

See it as a suggestion and improvement from my side. It is easier for the reviewer to have small commits. Your change makes a fix and a improvement in one commit. So if we move this in the future to a stable branch it es easier to have small commits because we only want to cherrry-pick the bugfix and not a new feature.

> It would make it easier for those willing to experiment with other DoH servers to do so. I'm waiting for feedback from @aarond10 on support on the main package.

A normal user without coding experience will not edit this file. So maybe we should read the values from a json file. So we do not have to edit the source file in the future. See https://github.com/openwrt/luci/tree/master/applications/luci-app-statistics/luasrc/statistics/plugins

```
return {
	value = "https://dns.adguard.com/dns-query?",
	i18n = _(AdGuard (Standard))
}
```
But this is only a suggestion from my side. How I would make this.

**Comment by hnyman** [comment]
> Your change makes a fix and a improvement in one commit. So if we move this in the future to a stable branch it es easier to have small commits because we only want to cherrry-pick the bugfix and not a new feature.

I agree with the advice about separate commits. But I feel that on non-core apps it makes sense to pick up also the (small) improvements to stable branches. We do not need to be quite that strict there.  (Especially 19.07 has not yet seen any rc builds, so there is no locked-down feature set or anything like that)

For package maintainers it makes sense to keep branches in sync if possible, of course without breaking things in release branches.

**Comment by feckert** [comment]
> > Your change makes a fix and a improvement in one commit. So if we move this in the future to a stable branch it es easier to have small commits because we only want to cherrry-pick the bugfix and not a new feature.
> 
> I agree with the advice about separate commits. But I feel that on non-core apps it makes sense to pick up also the (small) improvements to stable branches. We do not need to be quite that strict there. (Especially 19.07 has not yet seen any rc builds, so there is no locked-down feature set or anything like that)
> 

This was only an advice from my side.
So please go ahead

@hnyman @stangri if this is ok for you I will merge this and close https://github.com/openwrt/luci/pull/3148 because this fixes the same issue.

**Comment by stangri** [comment]
> But this is only a suggestion from my side. How I would make this.

Thanks, I'll look into this for the future updates.

**Pull request merged**
