### PR TITLE
Fix a style issue on the dashboard page

### PR DESCRIPTION
**Pull request by HouCoder**
I just found a style issue on the dashboard pages, it happens in multiple themes, here is the PR to fix it.

image
image

### CODE REVIEW

**Comment by feckert** [comment]
I can not reproduce your issue on 18.06.
Does this only happen on master?

**Comment by HouCoder** [comment]
I didn't test other branches, here is my build: 

```
Powered by LuCI openwrt-18.06 branch (git-19.079.57770-b99e77d)
```

**Comment by Ansuel** [comment]
Can confirm this... could be chrome dev?

**Comment by feckert** [comment]
Please add a `Signed-off-by` to your commit

**Comment by HouCoder** [comment]
> Can confirm this... could be chrome dev?

yep, I'm using Chrome canary

**Comment by Ansuel** [comment]
the changes should be test to firefox to make sure it doesn't brake on other browser

**Comment by jow-** [comment]
This change breaks Firefox and older Chrome for me.

**Comment by jow-** [comment]
Superseded by #2804

**Pull request closed without merging**
