### PR TITLE
luci-app-unbound: add statistics and manual edit configuration panels

### PR DESCRIPTION
**Pull request by EricLuehrsen**
A new option has been added for LuCI to expand the access to statistics and raw editing of configuration files. This includes switching to /etc/unbound/unbound.conf in manual override UCI mode. On the basics tab, check the box for *LuCI Expanded*. This will also add the option `luci_expanded` to the UCI file. If you have unbound-control installed, then some pre-configured commands are available.

Tested: LEDE trunk / TL-Archer-C7v2
rtm: @hnyman 
cc: @dibdot @poranje @vollkommenheit @chemicalstorm @RalfJung @danrl  @Borromini

### CODE REVIEW

**Comment by dibdot** [comment]
@EricLuehrsen Should I do some sort of review?

**Comment by EricLuehrsen** [comment]
@dibdot, this has no direct effect on adblock or Unbound. However it does provide for debug of adblock+unbound. The CC list includes those that have expressed an interest in the UCI/LuCI improvements for Unbound this last year. This is a significant expansion to LuCI for Unbound and comments are welcome.

**Comment by dibdot** [comment]
@EricLuehrsen Sorry for coming back so late. Now I've tested your new enhanced GUI ... just a few remarks:

- small typo in unbound_srv.conf "cluase".
- The wording of the help text for "LuCI Expanded" should be changed in something like "advanced configuration", it's not only relevant for debugging,
- both edit tabs (for undbound_srv & unound_ext) should use a monospaced font and filter out windows line encodings like "^M", as an example check my blacklist editing page in adblock
- you should consider a size limit for displaying the adblock include, there are some guys out there using lists with > 200 k entries which will lead to timeouts etc., as an example check my blacklist editing page in adblock.

Overall I've configured my unbound instance with DNS over TLS within a few minutes - very impressive!

br
dirk

**Comment by EricLuehrsen** [comment]
@dibdot Good points. Thanks. I will roll these in with the next round of updates.

**Pull request merged**
