### PR TITLE
luci-mod-admin-full: improve applyreboot page

### PR DESCRIPTION
**Pull request by Ansuel**
Currently applyreboot page lost the style and result in an empty page with some text. With this the page renders correctly. Also we fix problems when server address is broken by taking the ipaddr from the browser directly and we make the flash message more readable.

@jow-  think the only problem is the css part... didn't find a better way to hide it in a general way... 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
This page is supposed to be empty with just some text. Since the underlying ui is unavailable during this time it makes no sense to render the entire menu to let the user browse around.

What exactly do you try to fix here?

**Comment by Ansuel** [comment]
this is way better

cattura

**Comment by jow-** [comment]
Ah, the material theme again. This issue only affects material due to the nonstandard CSS location. A simpler fix would be renaming `css/style.css` to `cascade.css` like in the other themes.

**Comment by Ansuel** [comment]
ok i reworked this change a bit... @jow- 

cattura
cattura2

**Comment by Ansuel** [comment]
@jow- i'm stupid... use line-height was sufficent to make the text more readable. 

anything to change?

**Comment by Ansuel** [comment]
@jow- can you check this and other pr?

**Comment by Ansuel** [comment]
rebased

**Comment by Ansuel** [comment]
rebased @jow-

**Comment by Ansuel** [comment]
Can you check this? @jow-

**Comment by Ansuel** [comment]
@jow- sorry for so much stress but currently luci on nginx have the autorefresh broken... (problem with url generation) can this be merged?

**Pull request closed without merging**
