### PR TITLE
Update EA7300, v1 and v2, for new json based approach

### PR DESCRIPTION
**Pull request by arrmo**
Checked on EA7300, V2 (and copied to V1)

### CODE REVIEW

**Comment by Ansuel** [comment]
Thx a lot and sorry for the regression. @hnyman

**Comment by arrmo** [comment]
No worries - it happens!

**Comment by varGeneric** [comment]
Should also update README.md to indicate support for the EA7300 v1.

**Comment by stangri** [comment]
> Should also update README.md to indicate support for the EA7300 v1.

Good comment! But because the screenshots can't be included in the official repo, I'm thinking of moving the READMEs away from the OpenWrt repo as well, so I wouldn't bother with the README for now.

**Comment by stangri** [comment]
Uh oh, didn't notice no package name in the commit message and already merged.
@hnyman should this be fixed somehow?

**Pull request merged**
