### PR TITLE
luci-mod-network: wifi_join.js: Add WPA3 support

### PR DESCRIPTION
**Pull request by antoinedeschenes**
`iwinfo` now supports wpa=4 for WPA3

Signed-off-by: Antoine Deschênes <antoine@antoinedeschenes.com>

### CODE REVIEW

**Comment by jow-** [comment]
Where is the `case 6` coming from?

**Comment by antoinedeschenes** [comment]
The bitwise OR for `2|4` (WPA2 & WPA3). This would definitely be clearer with constants.

**Comment by antoinedeschenes** [comment]
@jow- Now replaced with constants. WPA2|WPA3 returns a bitwise OR of 2 and 4.

**Comment by jow-** [comment]
@antoinedeschenes - thank you! Your original PR was superseded by a complete rework of the wireless configuration pages in master but I squashed and picked your commits into the `openwrt-19.07` branch.

**Pull request closed without merging**
