### PR TITLE
luci-mod-system: remove bogus btn class in flash.js

### LINKED ISSUE #4970: force upgrade markup (sysupgrade/luci-21.02 - luci-theme-bootstrap)
The option "Force upgrade" is outside the container (Bootstrap theme). Tested Firefox/Chrome browsers with reset caches. 
Снимок экрана от 2021-04-09 12-05-14
LuCI openwrt-21.02 branch (git-21.088.35541-d627abe) / OpenWrt 21.02-SNAPSHOT r15952+1-6090337

### PR DESCRIPTION
**Pull request by dibdot**
* fixes #4970

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by dibdot** [comment]
after the change the modal window looks like that ...

flash

**Review by BKPepe — APPROVED** [review]

**Comment by dibdot** [comment]
Thanks, I've rebased this PR and synced translations

**Comment by jow-** [comment]
This change breaks alignment, the text next to the checkbox is not vertically centered. Also the checkbox cannot be selected anymore by clicking anywhere into the red area.

**Comment by dibdot** [comment]
The latter point was really meant as a "feature"? I thought it was a bug, for me it's at least unexpected.

**Pull request merged**
