### PR TITLE
luci-app-watchcat: Typo in watchcat.js

### PR DESCRIPTION
**Pull request by kumy**
- [x] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [x] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [x] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [ ] Tested on: (architecture, openwrt version, browser) :white_check_mark:
- [x] \( Preferred ) Mention: @ the original code author for feedback
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [ ] \( Optional ) Closes: e.g. openwrt/luci#issue-number
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [x] Description: (describe the changes proposed in this PR)

A small PR to fix a typo.

image

### CODE REVIEW

**Comment by systemcrash** [comment]
A simple search and replace for `ModemManger` should do it.

**Comment by kumy** [comment]
@systemcrash done :heavy_check_mark:

**Comment by systemcrash** [comment]
I don't really understand that stray `</i>` in there. But that's a problem for another day, unless you want to prune it out.

**Comment by kumy** [comment]
That's more than what I was going to fix first :)

I've added 2 missing `<i>`, as it was present on line 104 and missing on 94 / 111 and updated all existing translations.


https://github.com/openwrt/luci/blob/82e5c888408a9728576f584088432289809fa293/applications/luci-app-watchcat/htdocs/luci-static/resources/view/watchcat.js#L92-L112

**Comment by systemcrash** [comment]
You'll need to update your sign-off email for the checks to pass.

**Comment by kumy** [comment]
@systemcrash done

**Comment by systemcrash** [comment]
Great, thanks @kumy !

**Pull request merged**
