### PR TITLE
luci-mod-status: move svg to dedicated dir

### PR DESCRIPTION
**Pull request by Ansuel**
Move svgs from top dir to a dedicated svgs dir.

@jow- 
svgs or graph_svg ? 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Why do we need it?

**Comment by Ansuel** [comment]
Just to keep things organized. We have separation with cbi, icon and view page files. Looks wrong to have svg files (that are actually related to the mod-status module) in the top dir with the core files.

**Comment by jow-** [comment]
Okay, fine with me, but please use `svg` (singular) as folder name.

**Comment by Ansuel** [comment]
Done

**Comment by jow-** [comment]
Merged, thanks!

**Pull request merged**
