### PR TITLE
luci-app-openwisp: improved schema for usability

### PR DESCRIPTION
**Pull request by nemesisdesign**
Without these changes, saving the form of luci-app-openwisp without doing any change generates a configuration which will not work in most cases.

In this patch I took care of providing the right settings to show the default values, avoid saving default values and show the interface names properly. With these changes it will be possible for a user to edit just 1 field without introducing breaking changes.

### CODE REVIEW

**Comment by nemesisdesign** [comment]
@mips171 CC

**Comment by nemesisdesign** [comment]
@dibdot @jow- @hnyman could anyone take a look at this? :pray:

**Comment by jow-** [comment]
@nemesisdesign - merged, thanks!

**Comment by nemesisdesign** [comment]
> @nemesisdesign - merged, thanks!

No, thank you Jow!

**Pull request merged**
