### PR TITLE
luci-base: update Traditional Chinese translation

### PR DESCRIPTION
**Pull request by rypervenche**
Update "gateway" translation using standardized word used by both Google and Microsoft.

### CODE REVIEW

**Comment by yousong** [comment]
@a962702 please help review, thanks

@rypervenche the commit needs to be signed off with your real name.  Check existing commits in this repo to find out what's it like.

**Comment by yousong** [comment]
For ref, wikipedia says it should be ["閘道器"](https://zh.wikipedia.org/zh-tw/%E7%BD%91%E5%85%B3)

**Comment by a962702** [comment]
1. In wikipedia, it should be [閘道器](https://zh.wikipedia.org/zh-tw/%E7%BD%91%E5%85%B3), and the [wiktionary](https://zh.wiktionary.org/wiki/gateway) say it can be 閘道 or 閘道器.
2. According to the dictionary by National Academy for Educational Research in Taiwan, it can be [閘道](http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=Z00000114700) or [閘道器](http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=Z00000114701)

So use 閘道 or 閘道器 are the same, but the original word 匝道器 is not correct.

**Comment by rypervenche** [comment]
@yousong Sorry about that. I have signed off the commit. I chose the first version without 器 as both [Microsoft](https://www.microsoft.com/en-us/language/Search?searchTerm=gateway&langID=129&Source=true&productid=undefined) and [Google](https://support.google.com/a/answer/60730?hl=zh-Hant) seem to prefer the two-character version in most cases (see the two links).

**Comment by yousong** [comment]
Thanks!

**Pull request merged**
