### PR TITLE
luci-app-upnp: load data directly

### PR DESCRIPTION
**Pull request by Ansuel**
Rework upnp_status page to load data without first wait for the xhr request to load. Also rename variable to better understand what they are.

@hnyman another small improvement. I notice that upnp section hang the load of the value, this fix this problem. 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
The `XHR.get()` invocation here might cancel other pending requests.

**Comment by Ansuel** [comment]
then we should remove get invocation in the ddns script. as it use the same code

**Comment by hnyman** [comment]
@jow- 
any more comments here?

**Comment by Ansuel** [comment]
@jow- i reworked this. Now it doesn't cancel the xhr request as it start the XHR.get as soon as the other finish. (i assume that xhr request finish by checking if data in other section change)

**Pull request closed without merging**
