### PR TITLE
Add LuCI support for HSO protocol (Option 3G card)

### PR DESCRIPTION
**Pull request by Kyklas**
LuCI interface for HSO protocol to support Option 3G cards.
To use along with comgt + patch https://dev.openwrt.org/attachment/ticket/6995/comgt-hso_141012.patch
image

### CODE REVIEW

**Comment by jow-** [comment]
This looks good to me. Can you please change the copyright lines to the current year and your name/email? If you've taken care of that I'm going to merge it.

**Comment by Kyklas** [comment]
Depending on the file, should I add another line with my name or replace the line with my information ?
- hso/luasrc/model/cbi/admin_network/proto_hso.lua uses most of the code from 3g/luasrc/model/cbi/admin_network/proto_3g.lua
- hso/luasrc/model/network/proto_hso.lua comes from ppp/luasrc/model/network/proto_ppp.lua with a lot of code remove and some addition
When I commit again, should I create another pull request ?

**Comment by jow-** [comment]
You can replace it. No need to do another PR, you can simply update your branch.

**Comment by Kyklas** [comment]
I updated the copyright lines.
Thank you.

**Pull request merged**
