### PR TITLE
luci-app-https-dns-proxy: add cn.edu.tsinghua.tuna.dns.lua provider

### PR DESCRIPTION
**Pull request by autoexpect**
luci-app-https-dns-proxy: add cn.edu.tsinghua.tuna.dns.lua provider

Signed-off-by: Zhang Rui <rui.crater@gmail.com>

### CODE REVIEW

**Comment by stangri** [comment]
@autoexpect Thank you for this. Please add signed-off-by using the real email address and real name to both commit and PR description.

**Comment by autoexpect** [comment]
Thanks for the reminder, I have fixed it.

**Comment by stangri** [comment]
@autoexpect sorry, I'm not sure if non-english alphabet is accepted for the full name, could you please duplicate it with the english transliteration for the name? And could you please also update the PR description with the same?
Thanks!

**Comment by autoexpect** [comment]
Done.

Thanks!

**Pull request merged**
