### PR TITLE
Luci app wifischedule: minor changes

### PR DESCRIPTION
**Pull request by kuoruan**
* Formatting codes.
* Move to services sub menu.
* Update Simplified Chinese translation.
* And some other small changes.

Tested in luci trunk version.

### CODE REVIEW

**Comment by hnyman** [comment]
Ano comments, @newkit ?

**Comment by newkit** [comment]
@kuoruan @hnyman 
I like the restructuring underneath "Services" and putting the log file as tab there.

I do not like so much the removal of the cron page. I personally would like to see it as another tab next to the log file. I can see where you are coming from, that the information is already there and should not be implemented twice. But on the other hand it would be convenient for the user.
The following sentence from the README.md would need to be adjusted: 
> The cron jobs created can be reviewed through the "View Cron Jobs" tab.

The other changes are fine.

**Comment by kuoruan** [comment]
OK, added cron jobs back. Please check. @hnyman @newkit

**Comment by newkit** [comment]
@kuoruan 
Thanks for keeping the cron tab.

@hnyman 
Looks good to me, can be merged.

**Pull request merged**
