### PR TITLE
[RFC] luci-app-frp: add new packages

### PR DESCRIPTION
**Pull request by ysc3839**
[frp](https://github.com/fatedier/frp) is a reverse proxy which has a complicated config file. (Yes, like OpenVPN.)
Should I implement only a config file upload UI or all available options?

### CODE REVIEW

**Comment by ysc3839** [comment]
@jow- 
Since there's a lot of options, are you going to implement the "Add Additional Field" feature?
image
Can I help you anything?

**Comment by jow-** [comment]
@ysc3839 - hm, right now I have no plan to implement the additional fields capability. I never liked it because its UX is a bit weird and quirky imho.

I'd prefer to simply expose all options and move the less commonly needed ones into advanced tabs. You could also consider using modals to display more elaborate CBI maps on a button press or similar.

**Comment by ysc3839** [comment]
@jow- Finally I decided to remove some not commonly used options. For "pro users" who needs these options they should edit config file manually.

**Comment by ysc3839** [comment]
`luci-app-frpc` is ready for review.

**Comment by ysc3839** [comment]
Ping @jow-

**Comment by feckert** [comment]
Please add a package Makefile and also please add a acl file

**Comment by ysc3839** [comment]
@feckert Done.

**Comment by ysc3839** [comment]
@jow- Any updates?

**Comment by Retrochet** [comment]
@ysc3839 Seems it's missing some essecial parameter in luci like server_addr

**Comment by ysc3839** [comment]
@Retrochet It's in Common Settings, the top of page.

**Comment by ysc3839** [comment]
@Retrochet It works fine with latest OpenWrt snapshot and luci.
> Powered by LuCI Master (git-20.049.11521-bebfe20) / OpenWrt SNAPSHOT r12288-1173719817

image

**Comment by ysc3839** [comment]
@Retrochet I found it's because `/etc/config/frpc` missing required sections (or missing the whole file). Currently it doesn't check if these sections is absent.
A workaround is copy the default [config](https://github.com/openwrt/packages/blob/master/net/frp/files/frpc.config) to `/etc/config/frpc`.

**Comment by Retrochet** [comment]
@ysc3839 Cover the default config make luci works. Thank you

**Pull request merged**
