### PR TITLE
luci-base: Use sane tarball filename for luasrcdiet

### PR DESCRIPTION
**Pull request by diizzyy**
Switch to codeload and use a sane filename

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@Ansuel @jow-

**Comment by jow-** [comment]
After this PR, the tarball will be named `luci-base-1.0.0.tar.gz` which does not seem correct either.

**Comment by diizzyy** [comment]
Sorry, bad cut 'n paste on my behalf...

**Comment by diizzyy** [comment]
@jow- 
Fixed, sorry 'bout that

**Comment by jow-** [comment]
Superseded by faa5f0eacd2b2c90c33a75ee1e7fd3ec776601af.

**Pull request closed without merging**
