### PR TITLE
luci-app-ttyd: add option for UNIX socket and URL override

### PR DESCRIPTION
**Pull request by ysc3839**
- [x] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [x] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [x] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [x] Tested on: (armsr, snapshot, Edge) :white_check_mark:
- [ ] \( Preferred ) Mention: @ the original code author for feedback
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [ ] \( Optional ) Closes: e.g. openwrt/luci#issue-number
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [x] Description: Related issues: #5347 and #7022

### CODE REVIEW

**Comment by systemcrash** [comment]
Good. Thanks.  @ysc3839

**Comment by ZeaKyX** [comment]
Hi @ysc3839 @systemcrash
I noticed that in this change there’s a note: 

> Note that reverse proxied pages are NOT protected by password like LuCI.


However, in the [Unraid system](https://unraid.net/), the built-in ttyd supports being reverse proxied by Nginx to a custom URL, and it is also integrated with the system’s web management authentication. If the web management page is not logged in, opening the ttyd link will redirect to the login page.
image

May I ask if it’s possible for LuCI to implement a similar feature?

**Comment by ysc3839** [comment]
@ZeaKyX I guess it's using nginx's built-in authentication mechanism. In this case, ttyd is behind nginx, so it's protected.
However, by default LuCI uses uhttpd as reverse proxy server, but uhttpd doesn't have authentication mechanism. Client request goes directly to LuCI, and then LuCI checks token.

**Comment by ZeaKyX** [comment]
> @ZeaKyX I guess it's using nginx's built-in authentication mechanism. In this case, ttyd is behind nginx, so it's protected. However, by default LuCI uses uhttpd as reverse proxy server, but uhttpd doesn't have authentication mechanism. Client request goes directly to LuCI, and then LuCI checks token.

大佬好，本来这个url功能就是为nginx准备的吧，我看原issue里也是装的nginx替代uhttpd。
关于装了nginx-full后openwrt的登录保护，大佬有什么头绪吗？之前研究半天没找到是怎么实现的😂

**Pull request merged**
