### PR TITLE
luci-app-adblock: release 4.0.0

### PR DESCRIPTION
**Pull request by dibdot**
* complete rewrite, migrated to client side JS
* tested with mainline 19.07 and current master
* tested with latest Firefox & Chrome and all
  standard themes (not OpenWrt2020!)
  Pre-tested by many forum users, see here:
  https://forum.openwrt.org/t/adblock-4-pre-releases/57101
* sync translations
* 2nd try ... ;-)

Signed-off-by: Dirk Brenken <dev@brenken.org>

### CODE REVIEW

**Comment by finasfinas** [comment]
not appearing on the build I just compiled ( trunk ). theme material or bootstrap. command line says it is running and is version 4.0.0

**Comment by dibdot** [comment]
not reproducible here, maybe it's worth a try to reset you luci caches (`rm -rf /tmp/luci-*`) ... and restart your rpcd daemon as well (`/etc/init.d/rpcd restart`).

**Comment by finasfinas** [comment]
I don't have anything named /tmp/lu* and restarting rpcd didn't solve it.
A bit more information because with what I gave you it would be hard for you to give me any meaningful help. I am sorry.

So, this is a a fresh trunk build, like I just  pulled the code to a new dir, target is mvebu, I compile all the packages in, so I don't use opkg, and because of that I had to delete my previous adblock conf and get the new clean one from git ( because as I don't use packages I can't do that thing of upgrading the conf ). The conf overall conf is retained except for that adblock.conf file. 

adblock is running:

`root@gateway:/tmp# /etc/init.d/adblock status
::: adblock runtime information
  + adblock_status  : enabled
  + adblock_version : 4.0.0
  + blocked_domains : 35526
  + active_sources  : adaway adguard disconnect
  + dns_backend     : dnsmasq, /tmp/dnsmasq.d
  + run_utils       : /usr/bin/curl, /usr/bin/awk
  + run_ifaces      : trigger: -, report: -
  + run_directories : base: /tmp, backup: /tmp, report: /tmp, jail: /tmp
  + run_flags       : backup: 1, reset: 0, flush: 0, force: 0, search: 0, report: 0, mail: 0, jail: 0
  + last_run        : reload, 0m 11s, 1029/559/627, 29.03.2020 06:00:12
  + system          : Turris Omnia, OpenWrt SNAPSHOT r12755-19760563f7
`
if I try to go directly to what I believe is that http path of adblock "/cgi-bin/luci/admin/services/adblock" it displays this:

`404 Not Found

Sorry, the object you requested was not found.
Unable to dispatch: /cgi-bin/luci/admin/services/adblock`

**Comment by dibdot** [comment]
If you get a 404 with `https://<YOUR-IP>/cgi-bin/luci/admin/services/adblock` than your build is faulty for unknown reason. Just download the adblock-related luci package from an official build, e.g. `https://downloads.openwrt.org/snapshots/packages/x86_64/luci/` and install with opkg <PACKAGE>.ipk --force-reinstall

**Comment by finasfinas** [comment]
`root@gateway:/tmp# opkg install luci-app-adblock_git-20.088.63956-e22d832-1_all.ipk
Package luci-app-adblock (git-20.088.63956-e22d832-1) installed in root is up to date.
root@gateway:/tmp# opkg install --force-reinstall luci-app-adblock_git-20.088.63956-e22d832-1_all.ipk
Removing package luci-app-adblock from root...
Installing luci-app-adblock (git-20.088.63956-e22d832-1) to root...
Configuring luci-app-adblock.
root@gateway:/tmp# /etc/init.d/rpcd stop
root@gateway:/tmp# /etc/init.d/uhttpd stop
root@gateway:/tmp# /etc/init.d/rpcd start
root@gateway:/tmp# /etc/init.d/uhttpd start
root@gateway:/tmp#
`

still doesn't appear on luci and if I put the direct path same 404 error

**Comment by jospezial** [comment]
Looks as not related to adblock, but I'm not shure.
fresh build from openwrt git master:

https://192.168.1.1/cgi-bin/luci/admin/services
404 Nicht Gefunden

Entschuldigung, das anfgeforderte Objekt wurde nicht gefunden.
Kann Anfrage nicht zustellen: /cgi-bin/luci/admin/services

**Pull request merged**
