### PR TITLE
luci-app-wireguard: move to correct location

### PR DESCRIPTION
**Pull request by Borromini**
@hnyman Looks like I dumped it in the top directory instead of under applications/, this PR should correct that. My apologies.

Signed-off-by: Stijn Segers <foss@volatilesystems.org>

### CODE REVIEW

**Comment by hnyman** [comment]
Yeah, and I didn't notice that myself :-(

**Comment by manjuprajna** [comment]
@Borromini @hnyman but after I update, luci-app-wireguard does not show under menuconfig>luci>luci-application, why?
missed something?

**Comment by hnyman** [comment]
You update the feeds and install the feeds, and at that point the build system notices the new package:
```
perus@ub1710:/OwrtLEDE/r7800-1701$ ./scripts/feeds update
...
perus@ub1710:/OwrtLEDE/r7800-1701$ ./scripts/feeds install -a
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing package 'luci-app-wireguard' from luci
Installing all packages from feed routing.
Installing all packages from feed telephony.
```
After that the menuconfig shows it ok:

```
  │ │     < > luci-app-watchcat.............................. LuCI Support for Watchca│ │  
  │ │     < > luci-app-wifischedule...... Turns WiFi on and off according to a schedul│ │  
  │ │     <M> luci-app-wireguard...................................... WireGuard Statu│ │  
  │ │     <*> luci-app-wol................................ LuCI Support for Wake-on-LA│ │  

```

**Comment by manjuprajna** [comment]
@hnyman oh, I forgot to run ./scripts/feeds install -a, my mistake

**Pull request merged**
