### PR TITLE
luci-app-filemanager: fixed negative time zone parsing

### PR DESCRIPTION
**Pull request by rdmitry0911**
- [ ] This PR is not from my *main* or *master* branch :poop:, but a *separate* branch :white_check_mark:
- [ ] Each commit has a valid :black_nib: `Signed-off-by: <my@email.address>` row (via `git commit --signoff`)
- [ ] Each commit and PR title has a valid :memo: `<package name>: title` first line subject for packages
- [ ] Incremented :up: any `PKG_VERSION` in the Makefile
- [ ] Tested on: (architecture, openwrt version, browser) :white_check_mark:
- [ ] \( Preferred ) Mention: @ the original code author for feedback
- [ ] \( Preferred ) Screenshot or mp4 of changes:
- [ ] \( Optional ) Closes: e.g. openwrt/luci#issue-number
- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo
- [ ] Description: (describe the changes proposed in this PR)

### CODE REVIEW

**Comment by rdmitry0911** [comment]
Is there anything I can do to fix the falling check or to run it again?

**Comment by WhateverMO** [comment]
same issue again why?

**Comment by WhateverMO** [comment]
here is the web browser console error output

**Comment by WhateverMO** [comment]
Failed to parse line: drwxr-xr-x   2 root root  4096 2025-02-03 23:09:37.000000000 +0000 bin
```
zjj@a2d9a9d0ebfb ~/o/o/f/l/a/l/h/l/r/v/system (7b0663a5557118499dc3b3d44550efc1b6fa3feb)> sed -n '300,302p' filemanager.js 
			// Parse the output line from 'ls' command
			var parts = line.match(/^([\-dl])[rwx\-]{2}[rwx\-Ss]{1}[rwx\-]{2}[rwx\-Ss]{1}[rwx\-]{2}[rwx\-Tt]{1}\s+\d+\s+(\S+)\s+(\S+)\s+(\d+)\s+([\d\-]+\s+[\d\:\.]{8,12}\s+[+-]\d{4})\s+(.+)$/);
			if (!parts || parts.length < 7) {
```
it seems there is the bug

and i change the js code ：
```
var parts = line.match(/^([\-dl])[rwx\-]{2}[rwx\-Ss]{1}[rwx\-]{2}[rwx\-Ss]{1}[rwx\-]{2}[rwx\-Tt]{1}\s+\d+\s+(\S+)\s+(\S+)\s+(\d+)\s+([\d\-]+\s+\d{2}:\d{2}:\d{2}(?:\.\d+)?\s+[+-]\d{4})\s+(.+)$/);
```

it work well



and i will make a PR to solve this bug

**Pull request merged**
