### PR TITLE
luci-app-aria2: fix and update

### PR DESCRIPTION
**Pull request by kuoruan**
* Add maintainer info;
* Fix unable save authentication method;
* Use luci.dispatcher.build_url(...) to support Chaos Calmer;
* Add log file and log level options;
* Rename files.

Signed-off-by: Hsing-Wang Liao <kuoruan@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
Like I commented on your PR in packages, the move or aria2's config & init files from the core aria2 package to the Luci app looks strange.

**Comment by kuoruan** [comment]
@hnyman If you insist, I can rm the last commit.

**Comment by hnyman** [comment]
It would be better that way. please rm the commit that moved the config/init files. 

Conceptually the config and init script of a package belong to that package, not to the Luci app.  (Yes, you have introduced them at the same time as the Luci app, but still.)

**Comment by kuoruan** [comment]
@hnyman OK, pleace check it.

**Pull request merged**
