### PR TITLE
Update Simplified Chinese translation

### PR DESCRIPTION
**Pull request by sotux**
Update Simplified Chinese translation for
luci-base
luci-app-adblock
luci-app-mwan3

### CODE REVIEW

**Comment by hnyman** [comment]
Please rebase to remove the merge commit. (there should be no merge commits in the PR)

**Comment by sotux** [comment]
I've removed the merged commit. But how can I resolve the conflicts?

**Comment by hnyman** [comment]
Hmm, the conflict is likely just due to this:
https://github.com/openwrt/luci/commit/0e0ee2fed51f7108ee088e121ecbba479a5e88cc#diff-4095316bac2c702c18c6b3ca00b975c9

Several approaches:
1)
update your master from upstream (or you have already done that), then rebase your feature branch on top of that.
git checkout master
git pull upstream master
git checkout master-zh_CN
git rebase master

(I think that "git pull --rebase upstream master"  in the feature branch) should also work and do all those commands, but I haven't actually tried that.

then edit the conflict manually

2)
manually apply the changes from the patch I linked. Only a few lines in that file have actually changed.
combine that to your commit.

4)
Or if that sounds too complicated, I could pick those commit manually. It is a bit hard to explain the best ways to resolve this kind of conflicts.

**Comment by sotux** [comment]
Thanks hnyman, I've deleted conflicts lines and rebase my commit.

**Pull request merged**
