### PR TITLE
modules: use configurable poll interval

### PR DESCRIPTION
**Pull request by feckert**
If an interval configuration option is set under luci.main.interval,
then use this one.
If this is not specified then use the default specified in the source.

### CODE REVIEW

**Comment by jow-** [comment]
Hmm, instead of replicating this everywhere I feel that it should got into `XHR.poll()` directly. Means when a value like `-1` or `0` is passed, we use the default value.

We could use the newly introduced `luci.js` initialization (https://github.com/openwrt/luci/blob/master/modules/luci-base/luasrc/view/header.htm#L16) to store the default value in the client side JavaScript context, then retrieve it from there (using `L.env.pollinterval`)

**Comment by feckert** [comment]
@jow- I have update my PR with your suggestions.
The new poll interval will only be used if the first argument value of XHR.poll is lower or equal zero.
And if no poll interval option is set in uci the default value is set to 5 seconds which is the value most function uses.

Shouldn't I change the XHR.poll functions which use also 5 seconds?
They could be set to **-1** and then will also use the default value from L.env.pollinterval?

**Comment by jow-** [comment]
Yep, I suggest to also change all `XHR.poll(5, ...)` to `XHR.poll(-1, ...)` calls.

**Comment by feckert** [comment]
@jow- I have update the PR so that **all** XHR.poll functions who use the default value of 5 seconds using now the poll interval value from the config and if this is not set/found a default value of 5 seconds.

**Comment by jow-** [comment]
Merged, thanks @feckert

**Pull request merged**
