### PR TITLE
Update base.po

### PR DESCRIPTION
**Pull request by fabio70mi**
Corrected "Aggironamento Automatico" to "Aggiornamento Automatico"

### CODE REVIEW

**Comment by chris5560** [comment]
Please sign-off your commit and pull.

**Comment by fabio70mi** [comment]
Christian,
I'm not practiced with git.How could I do ?
Fabio
      Da: Christian Schoenebeck <notifications@github.com>
 A: openwrt/luci <luci@noreply.github.com> 
Cc: fabio70mi <fbettoni@yahoo.com> 
 Inviato: Domenica 12 Luglio 2015 18:52
 Oggetto: Re: [luci] Update base.po (#416)
   
Please sign-off your commit and pull.—

**Comment by hnyman** [comment]
@fabio70mi 

Your commit is the only commit in a not-yet-merged feature branch, so adding the signed-off-by line is rather easy:
* checkout the patch-1 branch
* Amend the last commit message with "git commit --amend". That should open the commit message in an editor. Add the line ``` "signed-off-by: Your Real Name <fbettoni@yahoo.com>" ``` (with your real name) to the existing commit message. That should take care of your local repo.
* When you then "git push -f", the old commit gets replaced with the modified one.  (If you would just add a second commit to the pull request, just "git push" would be enough. But editing the commit message in an already pushed commit requires "-f", which is allowed in pull request feature branches, but should not be used otherwise.

This pull request should then automatically update to reflect the new commit message.

**Comment by hnyman** [comment]
I merged it anyway, as similar #417 was merged to for-15.05 already in June

**Comment by fabio70mi** [comment]
Ok thank you,
I was not able to do it in these days as I was on vacation.

Fabio
      Da: Hannu Nyman <notifications@github.com>
 A: openwrt/luci <luci@noreply.github.com> 
Cc: fabio70mi <fbettoni@yahoo.com> 
 Inviato: Martedì 1 Settembre 2015 9:11
 Oggetto: Re: [luci] Update base.po (#416)
   
I merged it anyway, as similar #417 was merged to for-15.05 already in June—

**Pull request merged**
