### PR TITLE
luci-app-mjpg-streamer: add link option 

### PR DESCRIPTION
**Pull request by jose1711**
Signed-off-by: Jose Riha <jose1711@gmail.com>

### CODE REVIEW

**Comment by feckert** [comment]
Please update your commit message in the commit to

luci-app-mjpg-streamer: add link option

but I do net see the link option in the init script
https://github.com/openwrt/packages/blob/master/multimedia/mjpg-streamer/files/mjpg-streamer.init

**Comment by jose1711** [comment]
> but I do net see the link option in the init script
> https://github.com/openwrt/packages/blob/master/multimedia/mjpg-streamer/files/mjpg-streamer.init

it is a chicken-vs-egg problem. the `link` option will only appear in `mjpg-streamer.init` if https://github.com/openwrt/packages/pull/8658 gets merged

**Comment by feckert** [comment]
Thanks for the hint. And the other options?

**Comment by jose1711** [comment]
> Thanks for the hint. And the other options?

All the other options were already in sync with the init file

**Comment by feckert** [comment]
Related pullrequest https://github.com/openwrt/packages/pull/8658 was merged.

**Pull request merged**
