### PR TITLE
Add a new table option under "Resolv and Host Files", Advance DNSMa…

### PR DESCRIPTION
**Pull request by nivranaitsirhc**
…sq Configuration. (this will enable additional configuration of dnsmasq)

- Check if dnsmasq.conf exist in /etc/dnsmasq.conf, otherwise the section "Advance DNSMasq Configuration" will not appear.
- Directly modifies the dnsmasq.conf file.
- restart's the dnsmasq service

### CODE REVIEW

**Comment by chris5560** [comment]
@nivranaitsirhc Some Questions:
- Why did you not sign your work ?
- Why implement to "old" BB 14.07 branch and not to "master" branch ?
- Why not extending language template for creating translations ?
- Why not creating a totally separated tab like "System->Software->Configuration"

**Comment by nivranaitsirhc** [comment]
@chris5560 Good day sir.

- I forgot the signing part..

- I need to support this branch first because most of my stable builds are from this branch and the later if it gets accepted.

- I did not really considered the translation part, that was out of my attention. 

- For the purpose putting it at the best place possible for simplicity and and easy orientation.
I chose that tab because all of the DNSMasq and dhcp configuration is all there. although I think I should have put it in the "Advance Settings" taboption Under "DHCP and DNS" > Server Settings.

My intention is to implement an access to dnsmasq.conf file. for an optional advance full usage of the DNSMasq for the features that cannot be accessed by the web interface.

**Comment by chris5560** [comment]
@nivranaitsirhc

If updating old branches, it is not compiled into the builds on the download servers.
Old Branches are releases possibly with fixes but without extensions.
So best place is the master branch (trunk) to offer new extensions (because everybody knows it might have bugs).
I general I think it's a helpful extension.
If using a separate tab there is more space to edit and it's separate from UCI settings.
Language template updates are useful for everybody who want to help translating into other languages.

Christian

**Comment by nivranaitsirhc** [comment]
@chris5560 

I see. thank you for the tips and clarification.
I will work on your suggestion but I'm still not really familiar with the inner workings of LuCI. If someone can better implement than me. Then that would be much better i guess.
For the mean time guess I have to locally implement it in my local build.

Christian Arvin

**Pull request closed without merging**
