### PR TITLE
luci-app-dawn: Rewrite of Dawn Hearing Map in Table Form

### PR DESCRIPTION
**Pull request by JonnyTischbein**
Doing a rewrite of the luci dawn hearing map in fancy table form.

Screenshot_2020-04-18_10-12-22-2

Thanks to @PolynomialDivision for the work

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
Looks awesome! Thank you.

Please merge, since I do not have merge permissions.

**Comment by dibdot** [comment]
@JonnyTischbein 
Has this been tested with all LuCI standard themes? 
Why do we still use deprecated table-syntax with hardcoded styles? 
I would suggest to better use the common div-structure with a separate css file, e.g.
```
<div class="cbi-section-node">
	<div class="table" id="...">
		<div class="tr table-titles">
			<div class="th"><%:...%></div>
			<div class="th"><%:...%></div>
			<div class="th"><%:...%></div>
[...]
```

**Comment by JonnyTischbein** [comment]
Originally I wanted to use something like bootstrap grids but I didn't know that there are classes like that.

I'll to replace it

**Comment by JonnyTischbein** [comment]
Works good so far.

@dibdot Do you know if there is an equivalent to rowspan ? I didn't found something like that in the css file. 
Is there documentation for the div table ?

**Comment by JonnyTischbein** [comment]
Current changes with div tables
I don't know which other themes I should test. Where can I choose them ?

 Screenshot_2020-04-18_12-36-57-2

**Comment by dibdot** [comment]
@JonnyTischbein that looks much better - many thanks!
The theme selection is placed in the system menu, at least you should test Bootstrap (most probably already done), OpenWrt & OpenWrt2020.

Thanks again for your efforts!

**Comment by JonnyTischbein** [comment]
Thanks! In my build only bootstrap is availalble and was used for develpoping.

**Comment by dibdot** [comment]
Just install the other themes with opkg (luci-theme-*)

**Comment by PolynomialDivision** [comment]
looksawesome

Looks awesome! :)

**Comment by dibdot** [comment]
OK then, let's merge it.

**Comment by PolynomialDivision** [comment]
Let's see if I can convert the other page to "div-structure with a separate css file", too. ;)

**Pull request merged**
