### PR TITLE
luci-app-olsr: fix typos

### PR DESCRIPTION
**Pull request by urbalazs**
Fixed typos:

- linux -> Linux
- "approx" use the hopcount... -> "approx" uses the hopcount...
- ipv4 -> IPv4
- connecitivity -> connectivity
- infinate -> infinite

### CODE REVIEW

**Comment by hnyman** [comment]
Just a note that all these typo/style changes will apparently create a conflict in weblate if somebody is just translating one of these strings there.

**Comment by aparcar** [comment]
I think it is not possible to translate the "origin" strings weblate. I'd merge this PR and then fix the weblate branch manually.

**Comment by hnyman** [comment]
Lots of conflicts due to other merges and translations

**Comment by urbalazs** [comment]
> Lots of conflicts due to other merges and translations

@hnyman conflicts solved, ready to merge

**Pull request merged**
