### PR TITLE
theme: add initial commit for purple theme

### PR DESCRIPTION
**Pull request by yglb**
Signed-off-by: Yanlan Shen <yanlan.shen.@rosinson.com>

### CODE REVIEW

**Comment by yglb** [comment]
@jow-

**Comment by yglb** [comment]
## GIF map
<div align=center>login-pc</div>
<p align=center>A GIF chart that can preview the content of the topic</p>

## Previews on PC
<div align=center>login-pc</div>
<p align=center>Purple theme login interface</p>

<div align=center>navi-pc</div>
<p align=center>Purple theme navigation interface</p>

<div align=center>logged-pc</div>
<p align=center>Purple theme overview interface</p>


## Previews on mobile
<div align=center>login-pc</div>
<p align=center>Purple theme login interface</p>

<div align=center>navi-pc</div>
<p align=center>Purple theme navigation interface</p>

<div align=center>login-pc</div>
<p align=center>Purple theme overview interface</p>

**Comment by jow-** [comment]
Why is jQuery needed?

**Comment by shunjou** [comment]
This trend of forking the material theme into a "new" theme really needs to stop. Why not do what material originally did and fork bootstrap?
  
If you insist on it though, you should at least be retaining the relevant header comment bits as to not be rude about ripping it off.

**Pull request merged**
