### PR TITLE
build: add circleci

### PR DESCRIPTION
**Pull request by aparcar**
This automatically performs formal checks and also checks and compiles
the packages. The resulting packages are then stored as artifacts and
easily testable on running machines.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by BKPepe** [comment]
Is this used somehow in the LuCI repository? I am not able to see any check nor that it does compile anything. Anyway, it uses an old version of the docker image. The current is 1.0.5, but in LuCI, there is 1.0.2.

**Comment by BKPepe** [comment]
Ping @aparcar!

Let's notify also @jow- and @hnyman as well.

**Comment by hnyman** [comment]
I am not sure if @jow- or @aparcar ever actually activated the integration to circleci.

And in any case, if it is activated, the circleci recipe should be updated to the current one to handle 19.07 etc.

**Comment by aparcar** [comment]
Ugh this is badly out of date. Should we update or remove it? Compiling LuCI packages is somewhat unlikely to fail (usually no real compiling) and checking a SoB line can be done by a simple GitHub action, so no need of some complex external scripting.

**Comment by hnyman** [comment]
we could remove it.

Like you say, there is not much actual compiling involved in the LuCI repo itself.
I also feel that making circleci to compile the related dependency packages from the packages feed for e.g. a small change in statistics interface, is unnecessary.

**Comment by aparcar** [comment]
@hnyman please merge this https://github.com/openwrt/luci/pull/3776

**Pull request merged**
